#####                                                       #####
##### PRE-LIMINARY ANALYSIS                                 #####
#####                                                       #####

```{r}
##### LOAD PACKAGES
library("tidyverse")
library("modelsummary")
library("kableExtra")
library("gt")
library("shiny")

```

```{r}
##### LOAD DATASET
PFAS <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/PFAS_DEMO.csv")

```

```{r}
##### RUN UNADJUSTED LINEAR REGRESSION MODELS
# PFOS
unad.models.pfos <- list(
  "Weight Gain" = glm(WEIGHT_mdxa17 ~ LNPFOS, family = gaussian, data = PFAS),
  "Waist Circumference" = glm(LNWAIST ~ LNPFOS, family = gaussian, data = PFAS),
  "Total Body Fat %" = glm(LNWAIST ~ LNPFOS, family = gaussian, data = PFAS),
  "VAT Area" = glm(LNVAT_AREA ~ LNPFOS, family = gaussian, data = PFAS),
  "SAAT Area" = glm(LNSAT_AREA ~ LNPFOS, family = gaussian, data = PFAS),
  "TAAT Area" = glm(LNTAT_AREA ~ LNPFOS, family = gaussian, data = PFAS))

modelsummary(unad.models.pfos)

# PFOA
unad.models.pfoa <- list(
  "Weight Gain" = glm(WEIGHT_mdxa17 ~ LNPFOA, family = gaussian, data = PFAS),
  "Waist Circumference" = glm(LNWAIST ~ LNPFOA, family = gaussian, data = PFAS),
  "Total Body Fat %" = glm(LNWAIST ~ LNPFOA, family = gaussian, data = PFAS),
  "VAT Area" = glm(LNVAT_AREA ~ LNPFOA, family = gaussian, data = PFAS),
  "SAAT Area" = glm(LNSAT_AREA ~ LNPFOA, family = gaussian, data = PFAS),
  "TAAT Area" = glm(LNTAT_AREA ~ LNPFOA, family = gaussian, data = PFAS))

modelsummary(unad.models.pfoa)

# PFNA
unad.models.pfna <- list(
  "Weight Gain" = glm(WEIGHT_mdxa17 ~ LNPFNA2, family = gaussian, data = PFAS),
  "Waist Circumference" = glm(LNWAIST ~ LNPFNA2, family = gaussian, data = PFAS),
  "Total Body Fat %" = glm(LNWAIST ~ LNPFNA2, family = gaussian, data = PFAS),
  "VAT Area" = glm(LNVAT_AREA ~ LNPFNA2, family = gaussian, data = PFAS),
  "SAAT Area" = glm(LNSAT_AREA ~ LNPFNA2, family = gaussian, data = PFAS),
  "TAAT Area" = glm(LNTAT_AREA ~ LNPFNA2, family = gaussian, data = PFAS))

modelsummary(unad.models.pfna)

# PFHxS
unad.models.pfhxs <- list(
  "Weight Gain" = glm(WEIGHT_mdxa17 ~ LNPFHxS, family = gaussian, data = PFAS),
  "Waist Circumference" = glm(LNWAIST ~ LNPFHxS, family = gaussian, data = PFAS),
  "Total Body Fat %" = glm(LNWAIST ~ LNPFHxS, family = gaussian, data = PFAS),
  "VAT Area" = glm(LNVAT_AREA ~ LNPFHxS, family = gaussian, data = PFAS),
  "SAAT Area" = glm(LNSAT_AREA ~ LNPFHxS, family = gaussian, data = PFAS),
  "TAAT Area" = glm(LNTAT_AREA ~ LNPFHxS, family = gaussian, data = PFAS))

modelsummary(unad.models.pfhxs)

# Me_FOSSA
unad.models.mefos <- list(
  "Weight Gain" = glm(WEIGHT_mdxa17 ~ LNME_PFOSA, family = gaussian, data = PFAS),
  "Waist Circumference" = glm(LNWAIST ~ LNME_PFOSA, family = gaussian, data = PFAS),
  "Total Body Fat %" = glm(LNWAIST ~ LNME_PFOSA, family = gaussian, data = PFAS),
  "VAT Area" = glm(LNVAT_AREA ~ LNME_PFOSA, family = gaussian, data = PFAS),
  "SAAT Area" = glm(LNSAT_AREA ~ LNME_PFOSA, family = gaussian, data = PFAS),
  "TAAT Area" = glm(LNTAT_AREA ~ LNME_PFOSA, family = gaussian, data = PFAS))

modelsummary(unad.models.mefos)

# Et_FOSSA
unad.models.etfos <- list(
  "Weight Gain" = glm(WEIGHT_mdxa17 ~ LNET_PFOSA, family = gaussian, data = PFAS),
  "Waist Circumference" = glm(LNWAIST ~ LNET_PFOSA, family = gaussian, data = PFAS),
  "Total Body Fat %" = glm(LNWAIST ~ LNET_PFOSA, family = gaussian, data = PFAS),
  "VAT Area" = glm(LNVAT_AREA ~ LNET_PFOSA, family = gaussian, data = PFAS),
  "SAAT Area" = glm(LNSAT_AREA ~ LNET_PFOSA, family = gaussian, data = PFAS),
  "TAAT Area" = glm(LNTAT_AREA ~ LNET_PFOSA, family = gaussian, data = PFAS))

modelsummary(unad.models.etfos)

```

```{r}
##### RUN ADJUSTED LINEAR REGRESSION MODELS
# PFOS
ad.models.pfos <- list(
  "Weight Gain" = glm(WEIGHT_mdxa17 ~ LNPFOS + age_enroll + age_dxa + exer + race + 
                        bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Waist Circumference" = glm(LNWAIST ~ LNPFOS + age_enroll + age_dxa + exer + race + 
                                bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Total Body Fat %" = glm(LNWAIST ~ LNPFOS + age_enroll + age_dxa + exer + race + 
                             bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "VAT Area" = glm(LNVAT_AREA ~ LNPFOS + age_enroll + age_dxa + exer + race + 
                     bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "SAAT Area" = glm(LNSAT_AREA ~ LNPFOS + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "TAAT Area" = glm(LNTAT_AREA ~ LNPFOS + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS))

modelsummary(ad.models.pfos, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc")

# PFOA
ad.models.pfoa <- list(
  "Weight Gain" = glm(WEIGHT_mdxa17 ~ LNPFOA + age_enroll + age_dxa + exer + race + 
                        bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Waist Circumference" = glm(LNWAIST ~ LNPFOA + age_enroll + age_dxa + exer + race + 
                                bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Total Body Fat %" = glm(LNWAIST ~ LNPFOA + age_enroll + age_dxa + exer + race + 
                             bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "VAT Area" = glm(LNVAT_AREA ~ LNPFOA + age_enroll + age_dxa + exer + race + 
                     bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "SAAT Area" = glm(LNSAT_AREA ~ LNPFOA + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "TAAT Area" = glm(LNTAT_AREA ~ LNPFOA + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS))

modelsummary(ad.models.pfoa, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc")

# PFNA
ad.models.pfna <- list(
  "Weight Gain" = glm(WEIGHT_mdxa17 ~ LNPFNA2 + age_enroll + age_dxa + exer + race + 
                        bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Waist Circumference" = glm(LNWAIST ~ LNPFNA2 + age_enroll + age_dxa + exer + race + 
                                bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Total Body Fat %" = glm(LNWAIST ~ LNPFNA2 + age_enroll + age_dxa + exer + race + 
                             bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "VAT Area" = glm(LNVAT_AREA ~ LNPFNA2 + age_enroll + age_dxa + exer + race + 
                     bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "SAAT Area" = glm(LNSAT_AREA ~ LNPFNA2 + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "TAAT Area" = glm(LNTAT_AREA ~ LNPFNA2 + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS))

modelsummary(ad.models.pfna, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc")

# PFHxS
ad.models.pfhxs <- list(
  "Weight Gain" = glm(WEIGHT_mdxa17 ~ LNPFHxS + age_enroll + age_dxa + exer + race + 
                        bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Waist Circumference" = glm(LNWAIST ~ LNPFHxS + age_enroll + age_dxa + exer + race + 
                                bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Total Body Fat %" = glm(LNWAIST ~ LNPFHxS + age_enroll + age_dxa + exer + race + 
                             bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "VAT Area" = glm(LNVAT_AREA ~ LNPFHxS + age_enroll + age_dxa + exer + race + 
                     bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "SAAT Area" = glm(LNSAT_AREA ~ LNPFHxS + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "TAAT Area" = glm(LNTAT_AREA ~ LNPFHxS + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS))

modelsummary(ad.models.pfhxs, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc")

# Me_FOSSA
ad.models.mefos <- list(
  "Weight Gain" = glm(WEIGHT_mdxa17 ~ LNME_PFOSA + age_enroll + age_dxa + exer + race + 
                        bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Waist Circumference" = glm(LNWAIST ~ LNME_PFOSA + age_enroll + age_dxa + exer + race + 
                                bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Total Body Fat %" = glm(LNWAIST ~ LNME_PFOSA + age_enroll + age_dxa + exer + race + 
                             bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "VAT Area" = glm(LNVAT_AREA ~ LNME_PFOSA + age_enroll + age_dxa + exer + race + 
                     bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "SAAT Area" = glm(LNSAT_AREA ~ LNME_PFOSA + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "TAAT Area" = glm(LNTAT_AREA ~ LNME_PFOSA + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS))

modelsummary(ad.models.mefos, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc")

# Et_FOSSA
ad.models.etfos <- list(
  "Weight Gain" = glm(WEIGHT_mdxa17 ~ LNET_PFOSA + age_enroll + age_dxa + exer + race + 
                        bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Waist Circumference" = glm(LNWAIST ~ LNET_PFOSA + age_enroll + age_dxa + exer + race + 
                                bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Total Body Fat %" = glm(LNWAIST ~ LNET_PFOSA + age_enroll + age_dxa + exer + race + 
                             bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "VAT Area" = glm(LNVAT_AREA ~ LNET_PFOSA + age_enroll + age_dxa + exer + race + 
                     bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "SAAT Area" = glm(LNSAT_AREA ~ LNET_PFOSA + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "TAAT Area" = glm(LNTAT_AREA ~ LNET_PFOSA + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS))

modelsummary(ad.models.etfos, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc")

```

```{r}
##### PLOT THE ADJUSTED LINEAR MODEL COEFFICIENTS 
modelplot(ad.models.pfos, coef_omit = "Interc")
modelplot(ad.models.pfoa, coef_omit = "Interc")
modelplot(ad.models.pfna, coef_omit = "Interc")
modelplot(ad.models.pfhxs, coef_omit = "Interc")
modelplot(ad.models.mefos, coef_omit = "Interc")
modelplot(ad.models.etfos, coef_omit = "Interc")

```

