#####                                                       #####
##### PRE-LIMINARY ANALYSIS                                 #####
#####                                                       #####

```{r}
##### LOAD PACKAGES
library("tidyverse")
library("modelsummary")
library("kableExtra")
library("gt")
library("shiny")

```

```{r}
##### LOAD DATASET
PFAS_A <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/PFAS_A.csv")
PFAS_AD <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/PFAS_AD.csv")

```

```{r}
##### RUN UNADJUSTED LINEAR REGRESSION MODELS, ANTHRO DATASET

# BMI
a.unad.m.bmi <- list(
  "PFOS" = glm(BMI ~ LNPFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(BMI ~ LNPFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(BMI ~ LNPFNA2, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(BMI ~ LNPFHxS, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(BMI ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(BMI ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
modelsummary(a.unad.m.bmi)

a.unad.lnm.bmi <- list(
  "PFOS" = glm(LNBMI ~ LNPFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(LNBMI ~ LNPFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(LNBMI ~ LNPFNA2, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(LNBMI ~ LNPFHxS, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(LNBMI ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(LNBMI ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
modelsummary(a.unad.lnm.bmi)


# WEIGHT
a.unad.m.wt <- list(
  "PFOS" = glm(Weight ~ LNPFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(Weight ~ LNPFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(Weight ~ LNPFNA2, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(Weight ~ LNPFHxS, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(Weight ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(Weight ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
modelsummary(a.unad.m.wt)

a.unad.lnm.wt <- list(
  "PFOS" = glm(LNWT ~ LNPFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(LNWT ~ LNPFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(LNWT ~ LNPFNA2, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(LNWT ~ LNPFHxS, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(LNWT ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(LNWT ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
modelsummary(a.unad.lnm.wt)


# WAIST CIRCUMFERENCE
a.unad.m.waist <- list(
  "PFOS" = glm(Waist ~ LNPFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(Waist ~ LNPFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(Waist ~ LNPFNA2, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(Waist ~ LNPFHxS, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(Waist ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(Waist ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
modelsummary(a.unad.m.waist)

a.unad.lnm.waist <- list(
  "PFOS" = glm(LNWAIST ~ LNPFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(LNWAIST ~ LNPFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(LNWAIST ~ LNPFNA2, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(LNWAIST ~ LNPFHxS, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(LNWAIST ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(LNWAIST ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
modelsummary(a.unad.lnm.waist)


# HIP CIRCUMFERENCE
a.unad.m.hip <- list(
  "PFOS" = glm(Hip ~ LNPFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(Hip ~ LNPFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(Hip ~ LNPFNA2, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(Hip ~ LNPFHxS, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(Hip ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(Hip ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
modelsummary(a.unad.m.hip)

a.unad.lnm.hip <- list(
  "PFOS" = glm(LNHIP ~ LNPFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(LNHIP ~ LNPFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(LNHIP ~ LNPFNA2, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(LNHIP ~ LNPFHxS, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(LNHIP ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(LNHIP ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
modelsummary(a.unad.lnm.hip)


# BODY FAT %
a.unad.m.bfat <- list(
  "PFOS" = glm(FatPct ~ LNPFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(FatPct ~ LNPFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(FatPct ~ LNPFNA2, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(FatPct ~ LNPFHxS, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(FatPct ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(FatPct ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
modelsummary(a.unad.m.bfat)

a.unad.lnm.bfat <- list(
  "PFOS" = glm(LNBFAT ~ LNPFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(LNBFAT ~ LNPFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(LNBFAT ~ LNPFNA2, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(LNBFAT ~ LNPFHxS, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(LNBFAT ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(LNBFAT ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
modelsummary(a.unad.lnm.bfat)


# BODY FAT MASS
a.unad.m.fat <- list(
  "PFOS" = glm(FatMass ~ LNPFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(FatMass ~ LNPFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(FatMass ~ LNPFNA2, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(FatMass ~ LNPFHxS, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(FatMass ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(FatMass ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
modelsummary(a.unad.m.fat)

a.unad.lnm.fat <- list(
  "PFOS" = glm(LNFAT ~ LNPFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(LNFAT ~ LNPFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(LNFAT ~ LNPFNA2, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(LNFAT ~ LNPFHxS, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(LNFAT ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(LNFAT ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
modelsummary(a.unad.lnm.fat)

```

```{r}
##### RUN UNADJUSTED LINEAR REGRESSION MODELS, ANTHRO + DXA DATASET

# BMI
ad.unad.m.bmi <- list(
  "PFOS" = glm(BMI ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(BMI ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(BMI ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(BMI ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(BMI ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(BMI ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.m.bmi)

ad.unad.lnm.bmi <- list(
  "PFOS" = glm(LNBMI ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(LNBMI ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(LNBMI ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(LNBMI ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(LNBMI ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(LNBMI ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.lnm.bmi)


# WEIGHT
ad.unad.m.wt <- list(
  "PFOS" = glm(Weight ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(Weight ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(Weight ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(Weight ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(Weight ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(Weight ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.m.wt)

ad.unad.lnm.wt <- list(
  "PFOS" = glm(LNWT ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(LNWT ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(LNWT ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(LNWT ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(LNWT ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(LNWT ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.lnm.wt)


# WAIST CIRCUMFERENCE
ad.unad.m.waist <- list(
  "PFOS" = glm(Waist ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(Waist ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(Waist ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(Waist ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(Waist ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(Waist ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.m.waist)

ad.unad.lnm.waist <- list(
  "PFOS" = glm(LNWAIST ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(LNWAIST ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(LNWAIST ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(LNWAIST ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(LNWAIST ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(LNWAIST ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.lnm.waist)


# HIP CIRCUMFERENCE
ad.unad.m.hip <- list(
  "PFOS" = glm(Hip ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(Hip ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(Hip ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(Hip ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(Hip ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(Hip ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.m.hip)

ad.unad.lnm.hip <- list(
  "PFOS" = glm(LNHIP ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(LNHIP ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(LNHIP ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(LNHIP ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(LNHIP ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(LNHIP ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.lnm.hip)


# BODY FAT %
ad.unad.m.bfat <- list(
  "PFOS" = glm(FatPct ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(FatPct ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(FatPct ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(FatPct ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(FatPct ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(FatPct ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.m.bfat)

ad.unad.lnm.bfat <- list(
  "PFOS" = glm(LNBFAT ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(LNBFAT ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(LNBFAT ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(LNBFAT ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(LNBFAT ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(LNBFAT ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.lnm.bfat)


# BODY FAT MASS
ad.unad.m.fat <- list(
  "PFOS" = glm(FatMass ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(FatMass ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(FatMass ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(FatMass ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(FatMass ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(FatMass ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.m.fat)

ad.unad.lnm.fat <- list(
  "PFOS" = glm(LNFAT ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(LNFAT ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(LNFAT ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(LNFAT ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(LNFAT ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(LNFAT ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.lnm.fat)


# VAT AREA
ad.unad.lnm.vata <- list(
  "PFOS" = glm(LNVAT_AREA ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(LNVAT_AREA ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(LNVAT_AREA ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(LNVAT_AREA ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(LNVAT_AREA ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(LNVAT_AREA ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.lnm.vata)


# SAAT AREA
ad.unad.lnm.sata <- list(
  "PFOS" = glm(LNSAT_AREA ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(LNSAT_AREA ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(LNSAT_AREA ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(LNSAT_AREA ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(LNSAT_AREA ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(LNSAT_AREA ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.lnm.sata)


# TAAT AREA
ad.unad.lnm.tata <- list(
  "PFOS" = glm(LNTAT_AREA ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(LNTAT_AREA ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(LNTAT_AREA ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(LNTAT_AREA ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(LNTAT_AREA ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(LNTAT_AREA ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.lnm.tata)


# VAT MASS
ad.unad.lnm.vatm <- list(
  "PFOS" = glm(LNVAT_MASS ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(LNVAT_MASS ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(LNVAT_MASS ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(LNVAT_MASS ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(LNVAT_MASS ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(LNVAT_MASS ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.lnm.vatm)


# SAAT MASS
ad.unad.lnm.satm <- list(
  "PFOS" = glm(LNSAT_MASS ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(LNSAT_MASS ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(LNSAT_MASS ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(LNSAT_MASS ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(LNSAT_MASS ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(LNSAT_MASS ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.lnm.satm)


# TAAT MASS
ad.unad.lnm.tatm <- list(
  "PFOS" = glm(LNTAT_MASS ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(LNTAT_MASS ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(LNTAT_MASS ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(LNTAT_MASS ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(LNTAT_MASS ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(LNTAT_MASS ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.lnm.tatm)


# VAT VOLUME
ad.unad.lnm.vatv <- list(
  "PFOS" = glm(LNVAT_VOLUME ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(LNVAT_VOLUME ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(LNVAT_VOLUME ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(LNVAT_VOLUME ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(LNVAT_VOLUME ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(LNVAT_VOLUME ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.lnm.vatv)


# SAAT VOLUME
ad.unad.lnm.satv <- list(
  "PFOS" = glm(LNSAT_VOLUME ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(LNSAT_VOLUME ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(LNSAT_VOLUME ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(LNSAT_VOLUME ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(LNSAT_VOLUME ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(LNSAT_VOLUME ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.lnm.satv)


# TAAT VOLUME
ad.unad.lnm.tatv <- list(
  "PFOS" = glm(LNTAT_VOLUME ~ LNPFOS, family = gaussian, data = PFAS_AD),
  "PFOA" = glm(LNTAT_VOLUME ~ LNPFOA, family = gaussian, data = PFAS_AD),
  "PFNA" = glm(LNTAT_VOLUME ~ LNPFNA2, family = gaussian, data = PFAS_AD),
  "PFHxS" = glm(LNTAT_VOLUME ~ LNPFHxS, family = gaussian, data = PFAS_AD),
  "MeFOSSA" = glm(LNTAT_VOLUME ~ LNME_PFOSA, family = gaussian, data = PFAS_AD),
  "EtFOSSA" = glm(LNTAT_VOLUME ~ LNET_PFOSA, family = gaussian, data = PFAS_AD))
modelsummary(ad.unad.lnm.tatv)

```

```{r}
##### RUN ADJUSTED LINEAR REGRESSION MODELS
# PFOS
ad.models.pfos <- list(
  "Weight Gain" = glm(WEIGHT_mdxa17 ~ LNPFOS + age_enroll + age_dxa + exer + race + 
                        bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Waist Circumference" = glm(LNWAIST ~ LNPFOS + age_enroll + age_dxa + exer + race + 
                                bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Total Body Fat %" = glm(LNWAIST ~ LNPFOS + age_enroll + age_dxa + exer + race + 
                             bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "VAT Area" = glm(LNVAT_AREA ~ LNPFOS + age_enroll + age_dxa + exer + race + 
                     bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "SAAT Area" = glm(LNSAT_AREA ~ LNPFOS + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "TAAT Area" = glm(LNTAT_AREA ~ LNPFOS + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS))

modelsummary(ad.models.pfos, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc")

# PFOA
ad.models.pfoa <- list(
  "Weight Gain" = glm(WEIGHT_mdxa17 ~ LNPFOA + age_enroll + age_dxa + exer + race + 
                        bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Waist Circumference" = glm(LNWAIST ~ LNPFOA + age_enroll + age_dxa + exer + race + 
                                bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Total Body Fat %" = glm(LNWAIST ~ LNPFOA + age_enroll + age_dxa + exer + race + 
                             bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "VAT Area" = glm(LNVAT_AREA ~ LNPFOA + age_enroll + age_dxa + exer + race + 
                     bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "SAAT Area" = glm(LNSAT_AREA ~ LNPFOA + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "TAAT Area" = glm(LNTAT_AREA ~ LNPFOA + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS))

modelsummary(ad.models.pfoa, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc")

# PFNA
ad.models.pfna <- list(
  "Weight Gain" = glm(WEIGHT_mdxa17 ~ LNPFNA2 + age_enroll + age_dxa + exer + race + 
                        bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Waist Circumference" = glm(LNWAIST ~ LNPFNA2 + age_enroll + age_dxa + exer + race + 
                                bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Total Body Fat %" = glm(LNWAIST ~ LNPFNA2 + age_enroll + age_dxa + exer + race + 
                             bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "VAT Area" = glm(LNVAT_AREA ~ LNPFNA2 + age_enroll + age_dxa + exer + race + 
                     bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "SAAT Area" = glm(LNSAT_AREA ~ LNPFNA2 + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "TAAT Area" = glm(LNTAT_AREA ~ LNPFNA2 + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS))

modelsummary(ad.models.pfna, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc")

# PFHxS
ad.models.pfhxs <- list(
  "Weight Gain" = glm(WEIGHT_mdxa17 ~ LNPFHxS + age_enroll + age_dxa + exer + race + 
                        bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Waist Circumference" = glm(LNWAIST ~ LNPFHxS + age_enroll + age_dxa + exer + race + 
                                bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Total Body Fat %" = glm(LNWAIST ~ LNPFHxS + age_enroll + age_dxa + exer + race + 
                             bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "VAT Area" = glm(LNVAT_AREA ~ LNPFHxS + age_enroll + age_dxa + exer + race + 
                     bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "SAAT Area" = glm(LNSAT_AREA ~ LNPFHxS + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "TAAT Area" = glm(LNTAT_AREA ~ LNPFHxS + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS))

modelsummary(ad.models.pfhxs, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc")

# Me_FOSSA
ad.models.mefos <- list(
  "Weight Gain" = glm(WEIGHT_mdxa17 ~ LNME_PFOSA + age_enroll + age_dxa + exer + race + 
                        bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Waist Circumference" = glm(LNWAIST ~ LNME_PFOSA + age_enroll + age_dxa + exer + race + 
                                bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Total Body Fat %" = glm(LNWAIST ~ LNME_PFOSA + age_enroll + age_dxa + exer + race + 
                             bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "VAT Area" = glm(LNVAT_AREA ~ LNME_PFOSA + age_enroll + age_dxa + exer + race + 
                     bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "SAAT Area" = glm(LNSAT_AREA ~ LNME_PFOSA + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "TAAT Area" = glm(LNTAT_AREA ~ LNME_PFOSA + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS))

modelsummary(ad.models.mefos, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc")

# Et_FOSSA
ad.models.etfos <- list(
  "Weight Gain" = glm(WEIGHT_mdxa17 ~ LNET_PFOSA + age_enroll + age_dxa + exer + race + 
                        bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Waist Circumference" = glm(LNWAIST ~ LNET_PFOSA + age_enroll + age_dxa + exer + race + 
                                bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "Total Body Fat %" = glm(LNWAIST ~ LNET_PFOSA + age_enroll + age_dxa + exer + race + 
                             bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "VAT Area" = glm(LNVAT_AREA ~ LNET_PFOSA + age_enroll + age_dxa + exer + race + 
                     bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "SAAT Area" = glm(LNSAT_AREA ~ LNET_PFOSA + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS),
  "TAAT Area" = glm(LNTAT_AREA ~ LNET_PFOSA + age_enroll + age_dxa + exer + race + 
                      bmi_cat + edu + smoke + income_cat2 + parity, family = gaussian, data = PFAS))

modelsummary(ad.models.etfos, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc")

```

```{r}
##### PLOT THE ADJUSTED LINEAR MODEL COEFFICIENTS 
modelplot(ad.models.pfos, coef_omit = "Interc")
modelplot(ad.models.pfoa, coef_omit = "Interc")
modelplot(ad.models.pfna, coef_omit = "Interc")
modelplot(ad.models.pfhxs, coef_omit = "Interc")
modelplot(ad.models.mefos, coef_omit = "Interc")
modelplot(ad.models.etfos, coef_omit = "Interc")

```

