#####                                                       #####
##### PRE-LIMINARY ANALYSIS                                 #####
#####                                                       #####

```{r}
##### LOAD PACKAGES
library("tidyverse")
library("modelsummary")
library("kableExtra")
library("gt")
library("shiny")
library("olsrr")

```

```{r}
##### LOAD DATASET
PFAS_A <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/PFAS_A.csv")
PFAS_D <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/PFAS_D.csv")

```

```{r}
##### RUN UNADJUSTED LINEAR REGRESSION MODELS, ANTHRO DATASET (N = 549)

# BMI
#unad.m.bmi <- list(
#  "PFOS" = glm(BMI ~ LNPFOS, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(BMI ~ LNPFOA, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(BMI ~ LNPFNA2, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(BMI ~ LNPFHxS, family = gaussian, data = PFAS_A),
#  "MeFOSSA" = glm(BMI ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
#  "EtFOSSA" = glm(BMI ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
#modelsummary(unad.m.bmi, fmt = 2, title = "PFAS vs. BMI (Unadjusted)")

unad.lnm.bmi <- list(
  "PFOS" = glm(LNBMI ~ LNPFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(LNBMI ~ LNPFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(LNBMI ~ LNPFNA2, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(LNBMI ~ LNPFHxS, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(LNBMI ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(LNBMI ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
modelsummary(unad.lnm.bmi, fmt = 2, title = "PFAS vs. LN-BMI (Unadjusted)")


# WAIST CIRCUMFERENCE
unad.m.waist <- list(
  "PFOS" = glm(Waist ~ LNPFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(Waist ~ LNPFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(Waist ~ LNPFNA2, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(Waist ~ LNPFHxS, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(Waist ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(Waist ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
modelsummary(unad.m.waist, fmt = 2, title = "PFAS vs. WAIST CIRCUMFERENCE (Unadjusted)")

#unad.lnm.waist <- list(
#  "PFOS" = glm(LNWAIST ~ LNPFOS, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNWAIST ~ LNPFOA, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNWAIST ~ LNPFNA2, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNWAIST ~ LNPFHxS, family = gaussian, data = PFAS_A),
#  "MeFOSSA" = glm(LNWAIST ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
#  "EtFOSSA" = glm(LNWAIST ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
#modelsummary(unad.lnm.waist, fmt = 2, title = "PFAS vs. LN-WAIST CIRCUMFERENCE (Unadjusted)")


# WAIST-TO-HIP RATIO
unad.m.whr <- list(
  "PFOS" = glm(WHR ~ LNPFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(WHR ~ LNPFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(WHR ~ LNPFNA2, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(WHR ~ LNPFHxS, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(WHR ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(WHR ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
modelsummary(unad.m.whr, fmt = 2, title = "PFAS vs. WHR (Unadjusted)")

#unad.lnm.whr <- list(
#  "PFOS" = glm(LNWHR ~ LNPFOS, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNWHR ~ LNPFOA, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNWHR ~ LNPFNA2, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNWHR ~ LNPFHxS, family = gaussian, data = PFAS_A),
#  "MeFOSSA" = glm(LNWHR ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
#  "EtFOSSA" = glm(LNWHR ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
#modelsummary(unad.lnm.whr, fmt = 2, title = "PFAS vs. LN-WHR (Unadjusted)")


# MUAC
unad.m.muac <- list(
  "PFOS" = glm(MUAC ~ LNPFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(MUAC ~ LNPFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(MUAC ~ LNPFNA2, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(MUAC ~ LNPFHxS, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(MUAC ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(MUAC ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
modelsummary(unad.m.muac, fmt = 2, title = "PFAS vs. MUAC (Unadjusted)")

#unad.lnm.muac <- list(
#  "PFOS" = glm(LNMUAC ~ LNPFOS, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNMUAC ~ LNPFOA, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNMUAC ~ LNPFNA2, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNMUAC ~ LNPFHxS, family = gaussian, data = PFAS_A),
#  "MeFOSSA" = glm(LNMUAC ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
#  "EtFOSSA" = glm(LNMUAC ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
#modelsummary(unad.lnm.muac, fmt = 2, title = "PFAS vs. LN-MUAC (Unadjusted)")


# WEIGHT
#unad.m.wt <- list(
#  "PFOS" = glm(Weight ~ LNPFOS, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(Weight ~ LNPFOA, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(Weight ~ LNPFNA2, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(Weight ~ LNPFHxS, family = gaussian, data = PFAS_A),
#  "MeFOSSA" = glm(Weight ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
#  "EtFOSSA" = glm(Weight ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
#modelsummary(unad.m.wt, fmt = 2, title = "PFAS vs. WEIGHT (Unadjusted)")

#unad.lnm.wt <- list(
#  "PFOS" = glm(LNWT ~ LNPFOS, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNWT ~ LNPFOA, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNWT ~ LNPFNA2, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNWT ~ LNPFHxS, family = gaussian, data = PFAS_A),
#  "MeFOSSA" = glm(LNWT ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
#  "EtFOSSA" = glm(LNWT ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
#modelsummary(unad.lnm.wt, fmt = 2, title = "PFAS vs. LN-WEIGHT (Unadjusted)")


# BODY FAT MASS
#unad.m.fat <- list(
#  "PFOS" = glm(FatMass ~ LNPFOS, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(FatMass ~ LNPFOA, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(FatMass ~ LNPFNA2, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(FatMass ~ LNPFHxS, family = gaussian, data = PFAS_A),
#  "MeFOSSA" = glm(FatMass ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
#  "EtFOSSA" = glm(FatMass ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
#modelsummary(unad.m.fat, fmt = 2, title = "PFAS vs. BODY FAT MASS (Unadjusted)")

#unad.lnm.fat <- list(
#  "PFOS" = glm(LNFAT ~ LNPFOS, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNFAT ~ LNPFOA, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNFAT ~ LNPFNA2, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNFAT ~ LNPFHxS, family = gaussian, data = PFAS_A),
#  "MeFOSSA" = glm(LNFAT ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
#  "EtFOSSA" = glm(LNFAT ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
#modelsummary(unad.lnm.fat, fmt = 2, title = "PFAS vs. LN-BODY FAT MASS (Unadjusted)")


# BODY FAT %
#unad.m.bfat <- list(
#  "PFOS" = glm(FatPct ~ LNPFOS, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(FatPct ~ LNPFOA, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(FatPct ~ LNPFNA2, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(FatPct ~ LNPFHxS, family = gaussian, data = PFAS_A),
#  "MeFOSSA" = glm(FatPct ~ LNME_PFOSA, family = gaussian, data = PFAS_A),
#  "EtFOSSA" = glm(FatPct ~ LNET_PFOSA, family = gaussian, data = PFAS_A))
#modelsummary(unad.m.bfat, fmt = 2, title = "PFAS vs. BODY FAT % (Unadjusted)")


```

```{r}
##### RUN UNADJUSTED LINEAR REGRESSION MODELS, ANTHRO + DXA DATASET (N = 429)

# TRUNK FAT MASS
#unad.m.trnkfat <- list(
#  "PFOS" = glm(TrnkFat ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(TrnkFat ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(TrnkFat ~ LNPFNA2, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(TrnkFat ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSSA" = glm(TrnkFat ~ LNME_PFOSA, family = gaussian, data = PFAS_D),
#  "EtFOSSA" = glm(TrnkFat ~ LNET_PFOSA, family = gaussian, data = PFAS_D))
#modelsummary(unad.m.trnkfat, fmt = 2, title = "PFAS vs. TRUNK FAT MASS (Unadjusted)")

unad.lnm.trnkfat <- list(
  "PFOS" = glm(LNTKNFAT ~ LNPFOS, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTKNFAT ~ LNPFOA, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTKNFAT ~ LNPFNA2, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTKNFAT ~ LNPFHxS, family = gaussian, data = PFAS_D),
  "MeFOSSA" = glm(LNTKNFAT ~ LNME_PFOSA, family = gaussian, data = PFAS_D),
  "EtFOSSA" = glm(LNTKNFAT ~ LNET_PFOSA, family = gaussian, data = PFAS_D))
modelsummary(unad.lnm.trnkfat, fmt = 2, title = "PFAS vs. LN-TRUNK FAT MASS (Unadjusted)")


# TOTAL BODY FAT MASS
#unad.m.totfat <- list(
#  "PFOS" = glm(TotFat ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(TotFat ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(TotFat ~ LNPFNA2, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(TotFat ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSSA" = glm(TotFat ~ LNME_PFOSA, family = gaussian, data = PFAS_D),
#  "EtFOSSA" = glm(TotFat ~ LNET_PFOSA, family = gaussian, data = PFAS_D))
#modelsummary(unad.m.totfat, fmt = 2, title = "PFAS vs. TOTAL BODY FAT MASS (Unadjusted)")

unad.lnm.totfat <- list(
  "PFOS" = glm(LNTOTFAT ~ LNPFOS, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTOTFAT ~ LNPFOA, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTOTFAT ~ LNPFNA2, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTOTFAT ~ LNPFHxS, family = gaussian, data = PFAS_D),
  "MeFOSSA" = glm(LNTOTFAT ~ LNME_PFOSA, family = gaussian, data = PFAS_D),
  "EtFOSSA" = glm(LNTOTFAT ~ LNET_PFOSA, family = gaussian, data = PFAS_D))
modelsummary(unad.lnm.totfat, fmt = 2, title = "PFAS vs. LN-TOTAL BODY FAT MASS (Unadjusted)")


# TOTAL BODY FAT %
unad.m.totpfat <- list(
  "PFOS" = glm(TotFatPct ~ LNPFOS, family = gaussian, data = PFAS_D),
  "PFOA" = glm(TotFatPct ~ LNPFOA, family = gaussian, data = PFAS_D),
  "PFNA" = glm(TotFatPct ~ LNPFNA2, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(TotFatPct ~ LNPFHxS, family = gaussian, data = PFAS_D),
  "MeFOSSA" = glm(TotFatPct ~ LNME_PFOSA, family = gaussian, data = PFAS_D),
  "EtFOSSA" = glm(TotFatPct ~ LNET_PFOSA, family = gaussian, data = PFAS_D))
modelsummary(unad.m.totpfat, fmt = 2, title = "PFAS vs. TOTAL BODY FAT % (Unadjusted)")

#unad.lnm.totpfat <- list(
#  "PFOS" = glm(LNPFAT ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNPFAT ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNPFAT ~ LNPFNA2, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNPFAT ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSSA" = glm(LNPFAT ~ LNME_PFOSA, family = gaussian, data = PFAS_D),
#  "EtFOSSA" = glm(LNPFAT ~ LNET_PFOSA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.totpfat, fmt = 2, title = "PFAS vs. LN-TOTAL BODY FAT % (Unadjusted)")


# TOTAL BODY LEAN MASS
#unad.m.totlean <- list(
#  "PFOS" = glm(TotLean ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(TotLean ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(TotLean ~ LNPFNA2, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(TotLean ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSSA" = glm(TotLean ~ LNME_PFOSA, family = gaussian, data = PFAS_D),
#  "EtFOSSA" = glm(TotLean ~ LNET_PFOSA, family = gaussian, data = PFAS_D))
#modelsummary(unad.m.totlean, fmt = 2, title = "PFAS vs. TOTAL BODY LEAN MASS (Unadjusted)")

#unad.lnm.totlean <- list(
#  "PFOS" = glm(LNTOTLEAN ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNTOTLEAN ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNTOTLEAN ~ LNPFNA2, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNTOTLEAN ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSSA" = glm(LNTOTLEAN ~ LNME_PFOSA, family = gaussian, data = PFAS_D),
#  "EtFOSSA" = glm(LNTOTLEAN ~ LNET_PFOSA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.totlean, fmt = 2, title = "PFAS vs. LN-TOTAL BODY LEAN MASS (Unadjusted)")

# VAT AREA
#unad.lnm.vata <- list(
#  "PFOS" = glm(LNVAT_AREA ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNVAT_AREA ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNVAT_AREA ~ LNPFNA2, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNVAT_AREA ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSSA" = glm(LNVAT_AREA ~ LNME_PFOSA, family = gaussian, data = PFAS_D),
#  "EtFOSSA" = glm(LNVAT_AREA ~ LNET_PFOSA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.vata, fmt = 2, title = "PFAS vs. LN-VAT AREA (Unadjusted)")


# SAAT AREA
#unad.lnm.sata <- list(
#  "PFOS" = glm(LNSAT_AREA ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNSAT_AREA ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNSAT_AREA ~ LNPFNA2, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNSAT_AREA ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSSA" = glm(LNSAT_AREA ~ LNME_PFOSA, family = gaussian, data = PFAS_D),
#  "EtFOSSA" = glm(LNSAT_AREA ~ LNET_PFOSA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.sata, fmt = 2, title = "PFAS vs. LN-SAAT AREA (Unadjusted)")


# TAAT AREA
#unad.lnm.tata <- list(
#  "PFOS" = glm(LNTAT_AREA ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNTAT_AREA ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNTAT_AREA ~ LNPFNA2, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNTAT_AREA ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSSA" = glm(LNTAT_AREA ~ LNME_PFOSA, family = gaussian, data = PFAS_D),
#  "EtFOSSA" = glm(LNTAT_AREA ~ LNET_PFOSA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.tata, fmt = 2, title = "PFAS vs. LN-TAAT AREA (Unadjusted)")


# VAT MASS
#unad.lnm.vatm <- list(
#  "PFOS" = glm(LNVAT_MASS ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNVAT_MASS ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNVAT_MASS ~ LNPFNA2, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNVAT_MASS ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSSA" = glm(LNVAT_MASS ~ LNME_PFOSA, family = gaussian, data = PFAS_D),
#  "EtFOSSA" = glm(LNVAT_MASS ~ LNET_PFOSA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.vatm, fmt = 2, title = "PFAS vs. LN-VAT MASS (Unadjusted)")


# SAAT MASS
#unad.lnm.satm <- list(
#  "PFOS" = glm(LNSAT_MASS ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNSAT_MASS ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNSAT_MASS ~ LNPFNA2, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNSAT_MASS ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSSA" = glm(LNSAT_MASS ~ LNME_PFOSA, family = gaussian, data = PFAS_D),
#  "EtFOSSA" = glm(LNSAT_MASS ~ LNET_PFOSA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.satm, fmt = 2, title = "PFAS vs. LN-SAAT MASS (Unadjusted)")


# TAAT MASS
#unad.lnm.tatm <- list(
#  "PFOS" = glm(LNTAT_MASS ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNTAT_MASS ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNTAT_MASS ~ LNPFNA2, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNTAT_MASS ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSSA" = glm(LNTAT_MASS ~ LNME_PFOSA, family = gaussian, data = PFAS_D),
#  "EtFOSSA" = glm(LNTAT_MASS ~ LNET_PFOSA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.tatm, fmt = 2, title = "PFAS vs. LN-TAAT MASS (Unadjusted)")


# VAT VOLUME
#unad.lnm.vatv <- list(
#  "PFOS" = glm(LNVAT_VOLUME ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNVAT_VOLUME ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNVAT_VOLUME ~ LNPFNA2, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNVAT_VOLUME ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSSA" = glm(LNVAT_VOLUME ~ LNME_PFOSA, family = gaussian, data = PFAS_D),
#  "EtFOSSA" = glm(LNVAT_VOLUME ~ LNET_PFOSA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.vatv, fmt = 2, title = "PFAS vs. LN-VAT VOLUME (Unadjusted)")


# SAAT VOLUME
#unad.lnm.satv <- list(
#  "PFOS" = glm(LNSAT_VOLUME ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNSAT_VOLUME ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNSAT_VOLUME ~ LNPFNA2, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNSAT_VOLUME ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSSA" = glm(LNSAT_VOLUME ~ LNME_PFOSA, family = gaussian, data = PFAS_D),
#  "EtFOSSA" = glm(LNSAT_VOLUME ~ LNET_PFOSA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.satv, fmt = 2, title = "PFAS vs. LN-SAAT VOLUME (Unadjusted)")


# TAAT VOLUME
#unad.lnm.tatv <- list(
#  "PFOS" = glm(LNTAT_VOLUME ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNTAT_VOLUME ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNTAT_VOLUME ~ LNPFNA2, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNTAT_VOLUME ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSSA" = glm(LNTAT_VOLUME ~ LNME_PFOSA, family = gaussian, data = PFAS_D),
#  "EtFOSSA" = glm(LNTAT_VOLUME ~ LNET_PFOSA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.tatv, fmt = 2, title = "PFAS vs. LN-TAAT VOLUME (Unadjusted)")

```


```{r}
##### RUN ADJUSTED LINEAR REGRESSION MODELS, ANTHRO DATASET (N = 549)

# BMI
#ad.m.bmi <- list(
#  "PFOS" = glm(BMI ~ LNPFOS + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(BMI ~ LNPFOA + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(BMI ~ LNPFNA2 + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(BMI ~ LNPFHxS + age_enroll + race + edu + menar + smoke +  
#                  parity, family = gaussian, data = PFAS_A),
#  "MeFOSSA" = glm(BMI ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke +  
#                    parity, family = gaussian, data = PFAS_A),
#  "EtFOSSA" = glm(BMI ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke +  
#                    parity, family = gaussian, data = PFAS_A))
#
#modelsummary(ad.m.bmi, fmt = 2,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "PFAS vs. BMI (Adjusted)")

ad.lnm.bmi <- list(
  "PFOS" = glm(LNBMI ~ LNPFOS + age_enroll + race + edu + menar + smoke +  
                 parity, family = gaussian, data = PFAS_A),
  "PFOA" = glm(LNBMI ~ LNPFOA + age_enroll + race + edu + menar + smoke +  
                 parity, family = gaussian, data = PFAS_A),
  "PFNA" = glm(LNBMI ~ LNPFNA2 + age_enroll + race + edu + menar + smoke +  
                 parity, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(LNBMI ~ LNPFHxS + age_enroll + race + edu + menar + smoke +  
                  parity, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(LNBMI ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke +  
                    parity, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(LNBMI ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke +  
                    parity, family = gaussian, data = PFAS_A))

modelsummary(ad.lnm.bmi, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc", title = "PFAS vs. LN-BMI (Adjusted)")


# WAIST CIRCUMFERENCE
ad.m.waist <- list(
  "PFOS" = glm(Waist ~ LNPFOS + age_enroll + race + edu + menar + smoke +  
                 parity, family = gaussian, data = PFAS_A),
  "PFOA" = glm(Waist ~ LNPFOA + age_enroll + race + edu + menar + smoke +  
                 parity, family = gaussian, data = PFAS_A),
  "PFNA" = glm(Waist ~ LNPFNA2 + age_enroll + race + edu + menar + smoke +  
                 parity, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(Waist ~ LNPFHxS + age_enroll + race + edu + menar + smoke +  
                  parity, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(Waist ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke +  
                    parity, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(Waist ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke +  
                    parity, family = gaussian, data = PFAS_A))

modelsummary(ad.m.waist, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc", title = "PFAS vs. WAIST CIRCUMFERENCE (Adjusted)")

#ad.lnm.waist <- list(
#  "PFOS" = glm(LNWAIST ~ LNPFOS + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNWAIST ~ LNPFOA + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNWAIST ~ LNPFNA2 + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNWAIST ~ LNPFHxS + age_enroll + race + edu + menar + smoke +  
#                  parity, family = gaussian, data = PFAS_A),
#  "MeFOSSA" = glm(LNWAIST ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke +  
#                    parity, family = gaussian, data = PFAS_A),
#  "EtFOSSA" = glm(LNWAIST ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke +  
#                    parity, family = gaussian, data = PFAS_A))

#modelsummary(ad.lnm.waist, fmt = 2,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "PFAS vs. LN-WAIST CIRCUMFERENCE (Adjusted)")


# WAIST-TO-HIP RATIO
ad.m.whr <- list(
  "PFOS" = glm(WHR ~ LNPFOS + age_enroll + race + edu + menar + smoke +  
                 parity, family = gaussian, data = PFAS_A),
  "PFOA" = glm(WHR ~ LNPFOA + age_enroll + race + edu + menar + smoke +  
                 parity, family = gaussian, data = PFAS_A),
  "PFNA" = glm(WHR ~ LNPFNA2 + age_enroll + race + edu + menar + smoke +  
                 parity, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(WHR ~ LNPFHxS + age_enroll + race + edu + menar + smoke +  
                  parity, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(WHR ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke +  
                    parity, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(WHR ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke +  
                    parity, family = gaussian, data = PFAS_A))

modelsummary(ad.m.whr, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc", title = "PFAS vs. WHR (Adjusted)")

#ad.lnm.whr <- list(
#  "PFOS" = glm(LNWHR ~ LNPFOS + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNWHR ~ LNPFOA + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNWHR ~ LNPFNA2 + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNWHR ~ LNPFHxS + age_enroll + race + edu + menar + smoke +  
#                  parity, family = gaussian, data = PFAS_A),
#  "MeFOSSA" = glm(LNWHR ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke +  
#                    parity, family = gaussian, data = PFAS_A),
#  "EtFOSSA" = glm(LNWHR ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke +  
#                    parity, family = gaussian, data = PFAS_A))

#modelsummary(ad.lnm.whr, fmt = 2,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "PFAS vs. LN-WHR (Adjusted)")


# MUAC
ad.m.muac <- list(
  "PFOS" = glm(MUAC ~ LNPFOS + age_enroll + race + edu + menar + smoke +  
                 parity, family = gaussian, data = PFAS_A),
  "PFOA" = glm(MUAC ~ LNPFOA + age_enroll + race + edu + menar + smoke +  
                 parity, family = gaussian, data = PFAS_A),
  "PFNA" = glm(MUAC ~ LNPFNA2 + age_enroll + race + edu + menar + smoke +  
                 parity, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(MUAC ~ LNPFHxS + age_enroll + race + edu + menar + smoke +  
                  parity, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(MUAC ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke +  
                    parity, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(MUAC ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke +  
                    parity, family = gaussian, data = PFAS_A))

modelsummary(ad.m.muac, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc", title = "PFAS vs. MUAC (Adjusted)")

#ad.lnm.muac <- list(
#  "PFOS" = glm(LNMUAC ~ LNPFOS + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNMUAC ~ LNPFOA + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNMUAC ~ LNPFNA2 + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNMUAC ~ LNPFHxS + age_enroll + race + edu + menar + smoke +  
#                  parity, family = gaussian, data = PFAS_A),
#  "MeFOSSA" = glm(LNMUAC ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke +  
#                    parity, family = gaussian, data = PFAS_A),
#  "EtFOSSA" = glm(LNMUAC ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke +  
#                    parity, family = gaussian, data = PFAS_A))

#modelsummary(ad.lnm.muac, fmt = 2,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "PFAS vs. LN-MUAC (Adjusted)")


# WEIGHT
#ad.m.wt <- list(
#  "PFOS" = glm(Weight ~ LNPFOS + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(Weight ~ LNPFOA + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(Weight ~ LNPFNA2 + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(Weight ~ LNPFHxS + age_enroll + race + edu + menar + smoke +  
#                  parity, family = gaussian, data = PFAS_A),
#  "MeFOSSA" = glm(Weight ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke +  
#                    parity, family = gaussian, data = PFAS_A),
#  "EtFOSSA" = glm(Weight ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke +  
#                    parity, family = gaussian, data = PFAS_A))
#
#modelsummary(ad.m.wt, fmt = 2,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "PFAS vs. WEIGHT (Adjusted)")

#ad.lnm.wt <- list(
#  "PFOS" = glm(LNWT ~ LNPFOS + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNWT ~ LNPFOA + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNWT ~ LNPFNA2 + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNWT ~ LNPFHxS + age_enroll + race + edu + menar + smoke +  
#                  parity, family = gaussian, data = PFAS_A),
#  "MeFOSSA" = glm(LNWT ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke +  
#                    parity, family = gaussian, data = PFAS_A),
#  "EtFOSSA" = glm(LNWT ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke +  
#                    parity, family = gaussian, data = PFAS_A))

#modelsummary(ad.lnm.wt, fmt = 2,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "PFAS vs. LN-WEIGHT (Adjusted)")


# BODY FAT %
#ad.m.bfat <- list(
#  "PFOS" = glm(FatPct ~ LNPFOS + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(FatPct ~ LNPFOA + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(FatPct ~ LNPFNA2 + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(FatPct ~ LNPFHxS + age_enroll + race + edu + menar + smoke +  
#                  parity, family = gaussian, data = PFAS_A),
#  "MeFOSSA" = glm(FatPct ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke +  
#                    parity, family = gaussian, data = PFAS_A),
#  "EtFOSSA" = glm(FatPct ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke +  
#                    parity, family = gaussian, data = PFAS_A))

#modelsummary(ad.m.bfat, fmt = 2,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "PFAS vs. BODY FAT % (Adjusted)")

#ad.lnm.bfat <- list(
#  "PFOS" = glm(LNBFAT ~ LNPFOS + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNBFAT ~ LNPFOA + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNBFAT ~ LNPFNA2 + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNBFAT ~ LNPFHxS + age_enroll + race + edu + menar + smoke +  
#                  parity, family = gaussian, data = PFAS_A),
#  "MeFOSSA" = glm(LNBFAT ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke +  
#                    parity, family = gaussian, data = PFAS_A),
#  "EtFOSSA" = glm(LNBFAT ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke +  
#                    parity, family = gaussian, data = PFAS_A))

#modelsummary(ad.lnm.bfat, fmt = 2,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "PFAS vs. LN-BODY FAT % (Adjusted)")


# BODY FAT MASS
#ad.m.fat <- list(
#  "PFOS" = glm(FatMass ~ LNPFOS + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(FatMass ~ LNPFOA + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(FatMass ~ LNPFNA2 + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(FatMass ~ LNPFHxS + age_enroll + race + edu + menar + smoke +  
#                  parity, family = gaussian, data = PFAS_A),
#  "MeFOSSA" = glm(FatMass ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke +  
#                    parity, family = gaussian, data = PFAS_A),
#  "EtFOSSA" = glm(FatMass ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke +  
#                    parity, family = gaussian, data = PFAS_A))

#modelsummary(ad.m.fat, fmt = 2,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "PFAS vs. BODY FAT MASS (Adjusted)")

#ad.lnm.fat <- list(
#  "PFOS" = glm(LNFAT ~ LNPFOS + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNFAT ~ LNPFOA + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNFAT ~ LNPFNA2 + age_enroll + race + edu + menar + smoke +  
#                 parity, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNFAT ~ LNPFHxS + age_enroll + race + edu + menar + smoke +  
#                  parity, family = gaussian, data = PFAS_A),
#  "MeFOSSA" = glm(LNFAT ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke +  
#                    parity, family = gaussian, data = PFAS_A),
#  "EtFOSSA" = glm(LNFAT ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke +  
#                    parity, family = gaussian, data = PFAS_A))

#modelsummary(ad.lnm.fat, fmt = 2,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "PFAS vs. LN-BODY FAT MASS (Adjusted)")

```

```{r}
##### PLOT THE ADJUSTED LINEAR MODEL COEFFICIENTS 
modelplot(ad.lnm.bmi, coef_omit = "Interc")
modelplot(ad.m.wt, coef_omit = "Interc")
modelplot(ad.m.waist, coef_omit = "Interc")
modelplot(ad.m.whr, coef_omit = "Interc")

```

```{r}
##### RUN ADJUSTED LINEAR REGRESSION MODELS, ANTHRO + DXA DATASET (N = 429)

# TRUNK FAT MASS
# ad.m.trnkfat <- list(
#   "PFOS" = glm(TrnkFat ~ LNPFOS + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(TrnkFat ~ LNPFOA + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(TrnkFat ~ LNPFNA2 + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(TrnkFat ~ LNPFHxS + age_enroll + race + edu + menar + smoke + 
#                   parity, family = gaussian, data = PFAS_D),
#   "MeFOSSA" = glm(TrnkFat ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D),
#   "EtFOSSA" = glm(TrnkFat ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.m.trnkfat, fmt = 2, estimate = "{estimate}{stars}", 
#              statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
#              coef_omit = "Interc", title = "PFAS vs. TRUNK FAT MASS (Unadjusted)")

ad.lnm.trnkfat <- list(
  "PFOS" = glm(LNTKNFAT ~ LNPFOS + age_enroll + race + edu + menar + smoke + 
                 parity, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTKNFAT ~ LNPFOA + age_enroll + race + edu + menar + smoke + 
                 parity, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTKNFAT ~ LNPFNA2 + age_enroll + race + edu + menar + smoke + 
                 parity, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTKNFAT ~ LNPFHxS + age_enroll + race + edu + menar + smoke + 
                  parity, family = gaussian, data = PFAS_D),
  "MeFOSSA" = glm(LNTKNFAT ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke + 
                    parity, family = gaussian, data = PFAS_D),
  "EtFOSSA" = glm(LNTKNFAT ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke + 
                    parity, family = gaussian, data = PFAS_D))

modelsummary(ad.lnm.trnkfat, fmt = 2, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
             coef_omit = "Interc", title = "PFAS vs. LN-TRUNK FAT MASS (Unadjusted)")


# TOTAL BODY FAT MASS
# ad.m.totfat <- list(
#   "PFOS" = glm(TotFat ~ LNPFOS + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(TotFat ~ LNPFOA + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(TotFat ~ LNPFNA2 + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(TotFat ~ LNPFHxS + age_enroll + race + edu + menar + smoke + 
#                   parity, family = gaussian, data = PFAS_D),
#   "MeFOSSA" = glm(TotFat ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D),
#   "EtFOSSA" = glm(TotFat ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.m.totfat, fmt = 2, estimate = "{estimate}{stars}", 
#              statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
#              coef_omit = "Interc", title = "PFAS vs. TOTAL BODY FAT MASS (Unadjusted)")

ad.lnm.totfat <- list(
  "PFOS" = glm(LNTOTFAT ~ LNPFOS + age_enroll + race + edu + menar + smoke + 
                 parity, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTOTFAT ~ LNPFOA + age_enroll + race + edu + menar + smoke + 
                 parity, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTOTFAT ~ LNPFNA2 + age_enroll + race + edu + menar + smoke + 
                 parity, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTOTFAT ~ LNPFHxS + age_enroll + race + edu + menar + smoke + 
                  parity, family = gaussian, data = PFAS_D),
  "MeFOSSA" = glm(LNTOTFAT ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke + 
                    parity, family = gaussian, data = PFAS_D),
  "EtFOSSA" = glm(LNTOTFAT ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke + 
                    parity, family = gaussian, data = PFAS_D))

modelsummary(ad.lnm.totfat, fmt = 2, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
             coef_omit = "Interc", title = "PFAS vs. LN-TOTAL BODY FAT MASS (Unadjusted)")


# TOTAL BODY FAT %
ad.m.totpfat <- list(
  "PFOS" = glm(TotFatPct ~ LNPFOS + age_enroll + race + edu + menar + smoke + 
                 parity, family = gaussian, data = PFAS_D),
  "PFOA" = glm(TotFatPct ~ LNPFOA + age_enroll + race + edu + menar + smoke + 
                 parity, family = gaussian, data = PFAS_D),
  "PFNA" = glm(TotFatPct ~ LNPFNA2 + age_enroll + race + edu + menar + smoke + 
                 parity, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(TotFatPct ~ LNPFHxS + age_enroll + race + edu + menar + smoke + 
                  parity, family = gaussian, data = PFAS_D),
  "MeFOSSA" = glm(TotFatPct ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke + 
                    parity, family = gaussian, data = PFAS_D),
  "EtFOSSA" = glm(TotFatPct ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke + 
                    parity, family = gaussian, data = PFAS_D))

modelsummary(ad.m.totpfat, fmt = 2, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
             coef_omit = "Interc", title = "PFAS vs. TOTAL BODY FAT % (Unadjusted)")

# ad.lnm.totpfat <- list(
#   "PFOS" = glm(LNPFAT ~ LNPFOS + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNPFAT ~ LNPFOA + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNPFAT ~ LNPFNA2 + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNPFAT ~ LNPFHxS + age_enroll + race + edu + menar + smoke + 
#                   parity, family = gaussian, data = PFAS_D),
#   "MeFOSSA" = glm(LNPFAT ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D),
#   "EtFOSSA" = glm(LNPFAT ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.totpfat, fmt = 2, estimate = "{estimate}{stars}", 
#              statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
#              coef_omit = "Interc", title = "PFAS vs. LN-TOTAL BODY FAT % (Unadjusted)")


# TOTAL BODY LEAN MASS
# ad.m.totlean <- list(
#   "PFOS" = glm(TotLean ~ LNPFOS + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(TotLean ~ LNPFOA + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(TotLean ~ LNPFNA2 + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(TotLean ~ LNPFHxS + age_enroll + race + edu + menar + smoke + 
#                   parity, family = gaussian, data = PFAS_D),
#   "MeFOSSA" = glm(TotLean ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D),
#   "EtFOSSA" = glm(TotLean ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.m.totlean, fmt = 2, estimate = "{estimate}{stars}", 
#              statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
#              coef_omit = "Interc", title = "PFAS vs. TOTAL BODY LEAN MASS (Unadjusted)")

# ad.lnm.totlean <- list(
#   "PFOS" = glm(LNTOTLEAN ~ LNPFOS + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNTOTLEAN ~ LNPFOA + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNTOTLEAN ~ LNPFNA2 + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNTOTLEAN ~ LNPFHxS + age_enroll + race + edu + menar + smoke + 
#                   parity, family = gaussian, data = PFAS_D),
#   "MeFOSSA" = glm(LNTOTLEAN ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D),
#   "EtFOSSA" = glm(LNTOTLEAN ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.totlean, fmt = 2, estimate = "{estimate}{stars}", 
#              statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
#              coef_omit = "Interc", title = "PFAS vs. LN-TOTAL BODY LEAN MASS (Unadjusted)")


# VAT AREA
#ad.lnm.vata <- list(
#  "PFOS" = glm(LNVAT_AREA ~ LNPFOS + age_enroll + race + edu + menar + smoke + 
#                 parity, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNVAT_AREA ~ LNPFOA + age_enroll + race + edu + menar + smoke + 
#                 parity, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNVAT_AREA ~ LNPFNA2 + age_enroll + race + edu + menar + smoke + 
#                 parity, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNVAT_AREA ~ LNPFHxS + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#  "MeFOSSA" = glm(LNVAT_AREA ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke + 
#                    parity, family = gaussian, data = PFAS_D),
#  "EtFOSSA" = glm(LNVAT_AREA ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke + 
#                    parity, family = gaussian, data = PFAS_D))

#modelsummary(ad.lnm.vata, fmt = 2,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "PFAS vs. LN-VAT AREA (Adjusted)")


# SAAT AREA
#ad.lnm.sata <- list(
#  "PFOS" = glm(LNSAT_AREA ~ LNPFOS + age_enroll + race + edu + menar + smoke + 
#                 parity, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNSAT_AREA ~ LNPFOA + age_enroll + race + edu + menar + smoke + 
#                 parity, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNSAT_AREA ~ LNPFNA2 + age_enroll + race + edu + menar + smoke + 
#                 parity, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNSAT_AREA ~ LNPFHxS + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#  "MeFOSSA" = glm(LNSAT_AREA ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke + 
#                    parity, family = gaussian, data = PFAS_D),
#  "EtFOSSA" = glm(LNSAT_AREA ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke + 
#                    parity, family = gaussian, data = PFAS_D))

#modelsummary(ad.lnm.sata, fmt = 2,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "PFAS vs. LN-SAAT AREA (Adjusted)")


# TAAT AREA
# ad.lnm.tata <- list(
#   "PFOS" = glm(LNTAT_AREA ~ LNPFOS + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNTAT_AREA ~ LNPFOA + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNTAT_AREA ~ LNPFNA2 + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNTAT_AREA ~ LNPFHxS + age_enroll + race + edu + menar + smoke + 
#                   parity, family = gaussian, data = PFAS_D),
#   "MeFOSSA" = glm(LNTAT_AREA ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D),
#   "EtFOSSA" = glm(LNTAT_AREA ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.tata, fmt = 2,
#              estimate = "{estimate}{stars}",
#              statistic = c("SE: {std.error}",
#                            "95% CI: [{conf.low}, {conf.high}]"),
#              coef_omit = "Interc", title = "PFAS vs. LN-TAAT AREA (Adjusted)")


# VAT MASS
# ad.lnm.vatm <- list(
#   "PFOS" = glm(LNVAT_MASS ~ LNPFOS + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNVAT_MASS ~ LNPFOA + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNVAT_MASS ~ LNPFNA2 + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNVAT_MASS ~ LNPFHxS + age_enroll + race + edu + menar + smoke + 
#                   parity, family = gaussian, data = PFAS_D),
#   "MeFOSSA" = glm(LNVAT_MASS ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D),
#   "EtFOSSA" = glm(LNVAT_MASS ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.vatm, fmt = 2,
#              estimate = "{estimate}{stars}",
#              statistic = c("SE: {std.error}",
#                            "95% CI: [{conf.low}, {conf.high}]"),
#              coef_omit = "Interc", title = "PFAS vs. LN-VAT MASS (Adjusted)")


# SAAT MASS
# ad.lnm.satm <- list(
#   "PFOS" = glm(LNSAT_MASS ~ LNPFOS + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNSAT_MASS ~ LNPFOA + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNSAT_MASS ~ LNPFNA2 + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNSAT_MASS ~ LNPFHxS + age_enroll + race + edu + menar + smoke + 
#                   parity, family = gaussian, data = PFAS_D),
#   "MeFOSSA" = glm(LNSAT_MASS ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D),
#   "EtFOSSA" = glm(LNSAT_MASS ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.satm, fmt = 2,
#              estimate = "{estimate}{stars}",
#              statistic = c("SE: {std.error}",
#                            "95% CI: [{conf.low}, {conf.high}]"),
#              coef_omit = "Interc", title = "PFAS vs. LN-SAAT MASS (Adjusted)")


# TAAT MASS
# ad.lnm.tatm <- list(
#   "PFOS" = glm(LNTAT_MASS ~ LNPFOS + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNTAT_MASS ~ LNPFOA + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNTAT_MASS ~ LNPFNA2 + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNTAT_MASS ~ LNPFHxS + age_enroll + race + edu + menar + smoke + 
#                   parity, family = gaussian, data = PFAS_D),
#   "MeFOSSA" = glm(LNTAT_MASS ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D),
#   "EtFOSSA" = glm(LNTAT_MASS ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.tatm, fmt = 2,
#              estimate = "{estimate}{stars}",
#              statistic = c("SE: {std.error}",
#                            "95% CI: [{conf.low}, {conf.high}]"),
#              coef_omit = "Interc", title = "PFAS vs. LN-TAAT MASS (Adjusted)")


# VAT VOLUME
# ad.lnm.vatv <- list(
#   "PFOS" = glm(LNVAT_VOLUME ~ LNPFOS + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNVAT_VOLUME ~ LNPFOA + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNVAT_VOLUME ~ LNPFNA2 + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNVAT_VOLUME ~ LNPFHxS + age_enroll + race + edu + menar + smoke + 
#                   parity, family = gaussian, data = PFAS_D),
#   "MeFOSSA" = glm(LNVAT_VOLUME ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D),
#   "EtFOSSA" = glm(LNVAT_VOLUME ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.vatv, fmt = 2,
#              estimate = "{estimate}{stars}",
#              statistic = c("SE: {std.error}",
#                            "95% CI: [{conf.low}, {conf.high}]"),
#              coef_omit = "Interc", title = "PFAS vs. LN-VAT VOLUME (Adjusted)")


# SAAT VOLUME
# ad.lnm.satv <- list(
#   "PFOS" = glm(LNSAT_VOLUME ~ LNPFOS + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNSAT_VOLUME ~ LNPFOA + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNSAT_VOLUME ~ LNPFNA2 + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNSAT_VOLUME ~ LNPFHxS + age_enroll + race + edu + menar + smoke + 
#                   parity, family = gaussian, data = PFAS_D),
#   "MeFOSSA" = glm(LNSAT_VOLUME ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D),
#   "EtFOSSA" = glm(LNSAT_VOLUME ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.satv, fmt = 2,
#              estimate = "{estimate}{stars}",
#              statistic = c("SE: {std.error}",
#                            "95% CI: [{conf.low}, {conf.high}]"),
#              coef_omit = "Interc", title = "PFAS vs. LN-SAAT VOLUME (Adjusted)")


# TAAT VOLUME
# ad.lnm.tatv <- list(
#   "PFOS" = glm(LNTAT_VOLUME ~ LNPFOS + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNTAT_VOLUME ~ LNPFOA + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNTAT_VOLUME ~ LNPFNA2 + age_enroll + race + edu + menar + smoke + 
#                  parity, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNTAT_VOLUME ~ LNPFHxS + age_enroll + race + edu + menar + smoke + 
#                   parity, family = gaussian, data = PFAS_D),
#   "MeFOSSA" = glm(LNTAT_VOLUME ~ LNME_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D),
#   "EtFOSSA" = glm(LNTAT_VOLUME ~ LNET_PFOSA + age_enroll + race + edu + menar + smoke + 
#                     parity, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.tatv, fmt = 2,
#              estimate = "{estimate}{stars}",
#              statistic = c("SE: {std.error}",
#                            "95% CI: [{conf.low}, {conf.high}]"),
#              coef_omit = "Interc", title = "PFAS vs. LN-TAAT VOLUME (Adjusted)")

```

```{r}
##### PLOT THE ADJUSTED LINEAR MODEL COEFFICIENTS 
modelplot(ad.lnm.trnkfat, coef_omit = "Interc")
modelplot(ad.lnm.totfat, coef_omit = "Interc")
modelplot(ad.m.totpfat, coef_omit = "Interc")

```

