#####                                                                    #####
##### RUN MIXTURES ANALYSIS WITH QUANTILE G-COMPUTATION IN ANTHRO        #####
#####                                                                    #####

```{r}
##### LOAD PACKAGES
library('qgcomp')
library("tidyverse")
library("knitr")
library("ggplot2")

```

```{r}
##### LOAD DATASET
PFAS_A <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/PFAS_A.csv")

```

```{r}
##### TRANSFORM VARIABLES TO NUMERIC FOR BKMR COVARIATE MATRIX

# RENAME
PFAS_A$age_enroll <- PFAS_A$age_mom_enroll_d
PFAS_A$race <- PFAS_A$race2_mom_epi_epia_d
PFAS_A$edu <- PFAS_A$coll_grad
PFAS_A$income <- PFAS_A$gt70k
PFAS_A$menar <- PFAS_A$mom_firstperiod_12y
PFAS_A$smoke <- PFAS_A$smokpreg_final_d
PFAS_A$parity <- PFAS_A$parity_d
PFAS_A$married <- PFAS_A$married_cohab

# REFACTOR AND RELABEL 
PFAS_A$race <- ifelse(PFAS_A$race == "white", 0,
                     ifelse(PFAS_A$race == "black", 1,
                     ifelse(PFAS_A$race == "hispa", 2,
                     ifelse(PFAS_A$race == "asian", 3,
                     ifelse(PFAS_A$race == "other", 4, 4)))))
PFAS_A$edu <- ifelse(PFAS_A$edu == 1, 1, 0)
PFAS_A$bmi_cat <- ifelse(PFAS_A$bmi <18.5, 0,
                         ifelse(PFAS_A$bmi >=18.5 & PFAS_A$bmi < 25.0, 1, 
                         ifelse(PFAS_A$bmi >=25.0 & PFAS_A$bmi < 30.0, 2, 
                         ifelse(PFAS_A$bmi >=30.0 & PFAS_A$bmi < 35.0, 3,
                         ifelse(PFAS_A$bmi >=35.0, 4, 99)))))
PFAS_A$smoke <- ifelse(PFAS_A$smoke == "former", 0,
                         ifelse(PFAS_A$smoke == "smoke preg", 1,
                         ifelse(PFAS_A$smoke == "xnever", 2, 2)))
PFAS_A$income <- ifelse(PFAS_A$income == 1, 1, 0)
PFAS_A$parity <- ifelse(PFAS_A$parity == 0, 0,
                        ifelse(PFAS_A$parity == 1, 1,
                        ifelse(PFAS_A$parity > 1, 2, 0)))
PFAS_A$married <- ifelse(PFAS_A$married == 1, 1, 0)

# SET CATEGORICAL VARIABLES AS FACTORS
PFAS_A$edu <- as.factor(PFAS_A$edu)
PFAS_A$income <- as.factor(PFAS_A$income)
PFAS_A$bmi_cat <- as.factor(PFAS_A$bmi_cat)
PFAS_A$smoke <- as.factor(PFAS_A$smoke)
PFAS_A$parity <- as.factor(PFAS_A$parity)
PFAS_A$race <- as.factor(PFAS_A$race)
PFAS_A$married <- as.factor(PFAS_A$married)

# CENTER AND SCALE CONTINUOUS VARIABLES
# PFAS_A$age_enroll <- scale(PFAS_A$age_enroll)
# PFAS_A$menar <- scale(PFAS_A$menar)

```

```{r}
##### PREPARE VARIABLES FOR BKMR MODELS #####
##### ANTHRO DATASET (N = 549)

# SAVE THE NAMES OF THE PFAS IN THE MIXTURE
lnmix_a <- c("LNPFOS", "LNPFOA", "LNPFNA", "LNPFHxS", "LNMeFOSAA", "LNEtFOSAA")
l2mix_a <- c("L2PFOS", "L2PFOA", "L2PFNA", "L2PFHxS", "L2MeFOSAA", "L2EtFOSAA")
mix_a <- c("PFOS", "PFOA", "PFNA", "PFHxS", "MeFOSAA", "EtFOSAA")


# # SAVE THE NAMES OF THE COVARIATES
# cov_a <- c("age_enroll", "race", "menar", "income", "smoke", "parity", "married")

# SET THE OUTCOME
BMI <- PFAS_A$LNBMI
Waist <- PFAS_A$Waist
WHR <- PFAS_A$WHR
MUAC <- PFAS_A$MUAC

```

```{r}
##### BUILD QGC MODELS #####
# BMI
qc_bmi <- qgcomp.boot(BMI ~ age_enroll + race + menar + income + smoke + parity + married +
                          PFOS + PFOA + PFNA + PFHxS + MeFOSAA + EtFOSAA,
                        expnms = mix_a, data = PFAS_A, family=gaussian(), q=4, B = 500, seed = 125)
qc_bmi

lnqc_bmi <- qgcomp.boot(BMI ~ age_enroll + race + menar + income + smoke + parity + married +
                          LNPFOS + LNPFOA + LNPFNA + LNPFHxS + LNMeFOSAA + LNEtFOSAA,
                        expnms = lnmix_a, data = PFAS_A, family=gaussian(), q=4, B = 500, seed = 125)
lnqc_bmi


l2qc_bmi <- qgcomp.boot(BMI ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix_a, data = PFAS_A, family=gaussian(), q=4, B = 500, seed = 125)
l2qc_bmi


# WAIST CIRCUMFERENCE
lnqc_bmi <- qgcomp.boot(Waist ~ age_enroll + race + menar + income + smoke + parity + married +
                          LNPFOS + LNPFOA + LNPFNA + LNPFHxS + LNMeFOSAA + LNEtFOSAA,
                        expnms = lnmix_a, data = PFAS_A, family=gaussian(), q=4, B = 500, seed = 125)
lnqc_wc


l2qc_wc <- qgcomp.boot(Waist ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix_a, data = PFAS_A, family=gaussian(), q=4, B = 500, seed = 125)
l2qc_wc

# WAIST-TO-HIP-RATIO
lnqc_whr <- qgcomp.boot(WHR ~ age_enroll + race + menar + income + smoke + parity + married +
                          LNPFOS + LNPFOA + LNPFNA + LNPFHxS + LNMeFOSAA + LNEtFOSAA,
                        expnms = lnmix_a, data = PFAS_A, family=gaussian(), q=4, B = 500, seed = 125)
lnqc_whr


l2qc_whr <- qgcomp.boot(WHR ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix_a, data = PFAS_A, family=gaussian(), q=4, B = 500, seed = 125)
l2qc_whr

# MUAC
lnqc_muac <- qgcomp.boot(MUAC ~ age_enroll + race + menar + income + smoke + parity + married +
                          LNPFOS + LNPFOA + LNPFNA + LNPFHxS + LNMeFOSAA + LNEtFOSAA,
                        expnms = lnmix_a, data = PFAS_A, family=gaussian(), q=4, B = 500, seed = 125)
lnqc_muac


l2qc_muac <- qgcomp.boot(MUAC ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix_a, data = PFAS_A, family=gaussian(), q=4, B = 500, seed = 125)
l2qc_muac

```

```{r}
# ##### VIEW HOW EACH PFAS IS SCORED. THESE ARE QUANTIED EXPOSURES #####
# head(lnqc_bmi$qx)
# head(l2qc_bmi$qx)
# head(lnqc_wc$qx)
# head(l2qc_wci$qx)
# head(lnqc_whr$qx)
# head(l2qc_whr$qx)
# head(lnqc_muac$qx)
# head(l2qc_muac$qx)

```


```{r}

plot(lnqc_bmi)
plot(qc_wc)
plot(qc_whr)
plot(qc_muac)

```

```{r}
plot(lnqc_bmi2, pointwiseref = 3)

pointwisebound.boot(lnqc_bmi2, pointwiseref=3)
```

