#####                                  #####
##### RUN MIXTURES ANALYSIS WITH BKMR  #####
#####                                  #####

```{r}
##### LOAD PACKAGES
library("bkmr")
library("ggplot2")
library("beepr")
library("tidyverse")

```

```{r}
##### LOAD DATASET
PFAS_A <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/PFAS_A.csv")

```

```{r}
##### TRANSFORMVARIABLES TO NUMERIC FOR BKMR COVARIATE MATRIX

# RENAME
PFAS_A$age_enroll <- PFAS_A$age_mom_enroll_d
PFAS_A$race <- PFAS_A$race2_mom_epi_epia_d
PFAS_A$edu <- PFAS_A$coll_grad
PFAS_A$bmi <- PFAS_A$bmi_mom_prepreg_d
PFAS_A$smoke <- PFAS_A$smokpreg_final_d
PFAS_A$parity <- PFAS_A$parity_d
PFAS_A$married <- PFAS_A$married_cohab

# REFACTOR AND RELABEL 
PFAS_A$race <- ifelse(PFAS_A$race == "white", 0,
                     ifelse(PFAS_A$race == "black", 1,
                     ifelse(PFAS_A$race == "hispa", 2,
                     ifelse(PFAS_A$race == "asian", 3,
                     ifelse(PFAS_A$race == "other", 4, 4)))))
PFAS_A$edu <- ifelse(PFAS_A$edu == 1, 1, 0)
PFAS_A$bmi_cat <- ifelse(PFAS_A$bmi <18.5, 0,
                         ifelse(PFAS_A$bmi >=18.5 & PFAS_A$bmi < 25.0, 1, 
                         ifelse(PFAS_A$bmi >=25.0 & PFAS_A$bmi < 30.0, 2, 
                         ifelse(PFAS_A$bmi >=30.0 & PFAS_A$bmi < 35.0, 3,
                         ifelse(PFAS_A$bmi >=35.0, 4, 99)))))
PFAS_A$smoke <- ifelse(PFAS_A$smoke == "former", 0,
                         ifelse(PFAS_A$smoke == "smoke preg", 1,
                         ifelse(PFAS_A$smoke == "xnever", 2, 2)))
PFAS_A$parity <- ifelse(PFAS_A$parity == 0, 0,
                        ifelse(PFAS_A$parity == 1, 1,
                        ifelse(PFAS_A$parity > 1, 2, 0)))
PFAS_A$married <- ifelse(PFAS_A$married == 1, 1, 0)

# SET CATEGORICAL VARIABLES AS FACTORS
PFAS_A$edu <- as.factor(PFAS_A$edu)
PFAS_A$bmi_cat <- as.factor(PFAS_A$bmi_cat)
PFAS_A$smoke <- as.factor(PFAS_A$smoke)
PFAS_A$parity <- as.factor(PFAS_A$parity)
PFAS_A$race <- as.factor(PFAS_A$race)
PFAS_A$married <- as.factor(PFAS_A$married)

# CENTER AND SCALE CONTINUOUS VARIABLES
PFAS_A$age_enroll <- scale(PFAS_A$age_enroll)

```


```{r}
##### PREPARE VARIABLES FOR BKMR MODELS #####
##### ANTHRO DATASET (N = 549)

# CREATE MIXTURE OF PFAS
mixture_a <- as.matrix(cbind(PFAS_A$PFOS, PFAS_A$PFOA, PFAS_A$PFNA, PFAS_A$PFHxS, 
                              PFAS_A$MeFOSSA, PFAS_A$EtFOSSA))

# LN-TRANSFORM MIXTURE
lnmixture_a <- apply(mixture_a, 2, log)     

# SCALE MIXTURE VARIABLES TO THE MEAN
lnmixture_a_z <- scale(lnmixture_a)

# SET THE OUTCOME
BMI_a <- PFAS_A$BMI
Weight_a <- PFAS_A$Weight
Waist_a <- PFAS_A$Waist
Hip_a <- PFAS_A$Hip
MUAC_a <- PFAS_A$MUAC
FatPct_a <- PFAS_A$FatPct
FatMass_a <- PFAS_A$FatMass

# CREAT THE COVARIATE MATRIX
cov_a <- as.matrix(cbind(PFAS_A$age_enroll, PFAS_A$race, PFAS_A$bmi_cat, PFAS_A$edu, 
                       PFAS_A$smoke, PFAS_A$parity, PFAS_A$married))

# SET THE SEED
set.seed(127)

# CREATE KNOTS
knots_a <- fields::cover.design(lnmixture_a_z, nd = 50)$design

```

```{r}
##### BUILD BKMR MODELS 
# BMI
m_a_bmi <- kmbayes(y = BMI_a, z = lnmixture_a_z, x = cov_a, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_a)
beep(sound=5, expr=NULL)

# WEIGHT
m_a_wt <- kmbayes(y = Weight_a, z = lnmixture_a_z, x = cov_a, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_a)
beep(sound=5, expr=NULL)

# WAIST CIRCUMFERENCE
m_a_waist <- kmbayes(y = Waist_a, z = lnmixture_a_z, x = cov_a, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_a)
beep(sound=5, expr=NULL)

# HIP CIRCUMFERENCE
m_a_hip <- kmbayes(y = Hip_a, z = lnmixture_a_z, x = cov_a, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_a)
beep(sound=5, expr=NULL)

# MUAC
m_a_muac <- kmbayes(y = MUAC_a, z = lnmixture_a_z, x = cov_a, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_a)
beep(sound=5, expr=NULL)

# BODY FAT %
m_a_bfat <- kmbayes(y = FatPct_a, z = lnmixture_a_z, x = cov_a, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_a)
beep(sound=5, expr=NULL)

# BODY FAT MASS
m_a_fat <- kmbayes(y = FatMass_a, z = lnmixture_a_z, x = cov_a, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_a)
beep(sound=5, expr=NULL)

```

```{r}
##### VALUES TO KEEP AFTER BURIN/THIN
#
sel <- seq(0,25000,by = 50)

##### ACCESS CONVERGENCE WITH TRACEPLOTS
TracePlot(fit = mod.vat, par = "beta", sel = sel)
TracePlot(fit = mod.saat, par = "beta", sel = sel)
TracePlot(fit = mod.taat, par = "beta", sel = sel)
TracePlot(fit = mod.weight, par = "beta", sel = sel)
TracePlot(fit = mod.waist, par = "beta", sel = sel)
TracePlot(fit = mod.fat, par = "beta", sel = sel)

##### VALUES TO KEEP AFTER BURNING/THIN (ACCORDING TO THE TRACEPLOT FUNCTION ABOVE)
sel_final <- seq(1200, 25000, by = 1)

```

```{r}
##### ESIMATE POSTERIOR INCLUSION PROBABILITIES
# VAT
summary(mod.vat)
ExtractPIPs(mod.vat, sel = sel_final)

# SAAT
summary(mod.saat)
ExtractPIPs(mod.saat, sel = sel_final)

# TAAT
summary(mod.taat)
ExtractPIPs(mod.taat, sel = sel_final)

# Weight
summary(mod.weight)
ExtractPIPs(mod.weight, sel = sel_final)

# Waist
summary(mod.waist)
ExtractPIPs(mod.waist, sel = sel_final)

# Fat
summary(mod.fat)
ExtractPIPs(mod.fat, sel = sel_final)

```

```{r}
##### PREDICT UNIVARIATE EXPOSURE-RESPONSE FUNCTION
# VAT
pred_univar_vat <- PredictorResponseUnivar(fit = mod.vat, sel = sel_final, method = "approx")
pred_univar_vat

# SAAT
pred_univar_saat <- PredictorResponseUnivar(fit = mod.saat, sel = sel_final, method = "approx")
pred_univar_saat

# TAAT
pred_univar_taat <- PredictorResponseUnivar(fit = mod.taat, sel = sel_final, method = "approx")
pred_univar_taat

# Weight
pred_univar_weight <- PredictorResponseUnivar(fit = mod.weight, sel = sel_final, method = "approx")
pred_univar_weight

# Waist
pred_univar_waist <- PredictorResponseUnivar(fit = mod.waist, sel = sel_final, method = "approx")
pred_univar_waist

# Fat
pred_univar_fat <- PredictorResponseUnivar(fit = mod.fat, sel = sel_final, method = "approx")
pred_univar_fat


##### PLOT UNIVARIATE EXPOSURE-RESPONSE FUNCTION
uni_vat <- ggplot(pred_univar_vat, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity") + ylab("Change in VAT Area") + facet_wrap(~ variable) + xlab("PFAS")
uni_vat_ <- ggplot(pred_univar_vat[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Standardized PFOS ln(ng/mL)") + ylab("Change in VAT Area")
uni_vat
uni_vat_

uni_saat <- ggplot(pred_univar_saat, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity") + ylab("Change in SAAT Area") + facet_wrap(~ variable) + xlab("PFAS")
uni_saat

uni_taat <- ggplot(pred_univar_taat, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity") + ylab("Change in TAAT Area") + facet_wrap(~ variable) + xlab("PFAS")
uni_taat

uni_weight <- ggplot(pred_univar_weight, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity") + ylab("Change in Body Weight (kg)") + facet_wrap(~ variable) + xlab("PFAS")
uni_weight

uni_waist <- ggplot(pred_univar_waist, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity") + ylab("Change in Waist Circumference (cm)") + facet_wrap(~ variable) + xlab("PFAS")
uni_waist

uni_fat <- ggplot(pred_univar_fat, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity") + ylab("Change in Total Body Fat %") + facet_wrap(~ variable) + xlab("PFAS")
uni_fat

```

```{r}
##### PREDICT BIVARIATE EXPOSURE-RESPONSE CURVE TO ASSESS POTENTIAL INTERACTIONS
##### SUBESQUENTLY, PREDICT INTERACTIONS AMONG PFAS
# VAT
pred_bivar_vat <- PredictorResponseBivar(fit = mod.vat, min.plot.dist = 1, sel = sel_final, method = "approx")
pred_interact_vat <- PredictorResponseBivarLevels(pred.resp.df = pred_bivar_vat, Z = lnmixture_ad_z,
                                                        both_pairs = T, qs = c(0.25, 0.50, 0.75))
pred_interact_vat_1090 <- PredictorResponseBivarLevels(pred.resp.df = pred_bivar_vat, Z = lnmixture_ad_z, 
                                                             both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))
# SAAT
pred_bivar_saat <- PredictorResponseBivar(fit = mod.saat, min.plot.dist = 1, sel = sel_final, method = "approx")
pred_interact_saat <- PredictorResponseBivarLevels(pred.resp.df = pred_bivar_saat, Z = lnmixture_z,
                                                        both_pairs = T, qs = c(0.25, 0.50, 0.75))
pred_interact_saat_1090 <- PredictorResponseBivarLevels(pred.resp.df = pred_bivar_saat, Z = lnmixture_z, 
                                                             both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))
# TAAT
pred_bivar_taat <- PredictorResponseBivar(fit = mod.taat, min.plot.dist = 1, sel = sel_final, method = "approx")
pred_interact_taat <- PredictorResponseBivarLevels(pred.resp.df = pred_bivar_taat, Z = lnmixture_z,
                                                        both_pairs = T, qs = c(0.25, 0.50, 0.75))
pred_interact_taat_1090 <- PredictorResponseBivarLevels(pred.resp.df = pred_bivar_taat, Z = lnmixture_z, 
                                                             both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))
# Weight
pred_bivar_weight <- PredictorResponseBivar(fit = mod.weight, min.plot.dist = 1, sel = sel_final, method = "approx")
pred_interact_weight <- PredictorResponseBivarLevels(pred.resp.df = pred_bivar_weight, Z = lnmixture_z,
                                                        both_pairs = T, qs = c(0.25, 0.50, 0.75))
pred_interact_weight_1090 <- PredictorResponseBivarLevels(pred.resp.df = pred_bivar_weight, Z = lnmixture_z, 
                                                             both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))
# Waist
pred_bivar_waist <- PredictorResponseBivar(fit = mod.waist, min.plot.dist = 1, sel = sel_final, method = "approx")
pred_interact_waist <- PredictorResponseBivarLevels(pred.resp.df = pred_bivar_waist, Z = lnmixture_z,
                                                        both_pairs = T, qs = c(0.25, 0.50, 0.75))
pred_interact_waist_1090 <- PredictorResponseBivarLevels(pred.resp.df = pred_bivar_waist, Z = lnmixture_z, 
                                                             both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))
# Fat
pred_bivar_fat <- PredictorResponseBivar(fit = mod.fat, min.plot.dist = 1, sel = sel_final, method = "approx")
pred_interact_fat <- PredictorResponseBivarLevels(pred.resp.df = pred_bivar_fat, Z = lnmixture_z,
                                                        both_pairs = T, qs = c(0.25, 0.50, 0.75))
pred_interact_fat_1090 <- PredictorResponseBivarLevels(pred.resp.df = pred_bivar_fat, Z = lnmixture_z, 
                                                             both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))



##### PLOT INTERACTIONS BETWEEN EXPOSURE AND RESPONSE
##### NON-PARALLEL LINES WOULD INDICATE POTENTIAL INTERACTIONS
# VAT
m1_interact_vat <- ggplot(pred_interact_vat, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("PFAS1") +
  ggtitle("h(PFAS1 | Quantiles of PFAS2)") 
m1_interact_vat

# SAAT
m1_interact_saat <- ggplot(pred_interact_saat, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("PFAS1") +
  ggtitle("h(PFAS1 | Quantiles of PFAS2)") 
m1_interact_saat

# TAAT
m1_interact_taat <- ggplot(pred_interact_taat, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("PFAS1") +
  ggtitle("h(PFAS1 | Quantiles of PFAS2)") 
m1_interact_taat

# Weight
m1_interact_weight <- ggplot(pred_interact_weight, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("PFAS1") +
  ggtitle("h(PFAS1 | Quantiles of PFAS2)") 
m1_interact_weight

# Waist
m1_interact_waist <- ggplot(pred_interact_waist, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("PFAS1") +
  ggtitle("h(PFAS1 | Quantiles of PFAS2)") 
m1_interact_waist

# Fat
m1_interact_fat <- ggplot(pred_interact_fat, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("PFAS1") +
  ggtitle("h(PFAS1 | Quantiles of PFAS2)") 
m1_interact_fat

```

```{r}
##### DETERMINE RISK ASSOCIATED WITH THE OVERALL MIXTURE
##### SUBSEQUENTLY, ESTIMATE RISK FOR SINGLE PFAS AND INTERACTIONS AMONG PFAS
# VAT
risk_overall_vat <- OverallRiskSummaries(fit = mod.vat, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
risks_singvar_vat <- SingVarRiskSummaries(fit = mod.vat, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
risks_overall_interact_vat <- SingVarIntSummaries(fit = mod.vat, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)
# SAAT
risk_overall_saat <- OverallRiskSummaries(fit = mod.saat, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
risks_singvar_saat <- SingVarRiskSummaries(fit = mod.saat, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
risks_overall_interact_saat <- SingVarIntSummaries(fit = mod.saat, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)
# TAAT
risk_overall_taat <- OverallRiskSummaries(fit = mod.taat, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
risks_singvar_taat <- SingVarRiskSummaries(fit = mod.taat, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
risks_overall_interact_taat <- SingVarIntSummaries(fit = mod.taat, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)
# Weight
risk_overall_weight <- OverallRiskSummaries(fit = mod.weight, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
risks_singvar_weight <- SingVarRiskSummaries(fit = mod.weight, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
risks_overall_interact_weight <- SingVarIntSummaries(fit = mod.weight, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)
# Waist
risk_overall_waist <- OverallRiskSummaries(fit = mod.waist, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
risks_singvar_waist <- SingVarRiskSummaries(fit = mod.waist, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
risks_overall_interact_waist <- SingVarIntSummaries(fit = mod.waist, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)
# Fat
risk_overall_fat <- OverallRiskSummaries(fit = mod.fat, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
risks_singvar_fat <- SingVarRiskSummaries(fit = mod.fat, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
risks_overall_interact_fat <- SingVarIntSummaries(fit = mod.fat, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)



##### PLOT RISK ASSOCIATED WITH THE OVERALL MIXTURE
### VAT
overall_vat <- ggplot(risk_overall_vat, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "Change in VAT Area")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x=element_text(size=11),
               axis.text.y=element_text(size=11),
               axis.title.x=element_text(angle=0, color='black', size=11),
               axis.title.y=element_text(angle=90, color='black', size=11))
overall_vat

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
overall_sing_vat <- ggplot(risks_singvar_vat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) +
  geom_hline(aes(yintercept=0), linetype="dashed", color="gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name="PFAS") + scale_y_continuous(name="Change in VAT Area")
overall_sing_vat

# SINGLE VARIABLE INTERACTION TERMS
overall_interact_vat <- ggplot(risks_overall_interact_vat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip()
overall_interact_vat



### SAAT
overall_saat <- ggplot(risk_overall_saat, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "Change in SAAT Area")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x=element_text(size=11),
               axis.text.y=element_text(size=11),
               axis.title.x=element_text(angle=0, color='black', size=11),
               axis.title.y=element_text(angle=90, color='black', size=11))
overall_saat

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
overall_sing_saat <- ggplot(risks_singvar_saat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) +
  geom_hline(aes(yintercept=0), linetype="dashed", color="gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name="PFAS") + scale_y_continuous(name="Change in SAAT Area")
overall_sing_saat

# SINGLE VARIABLE INTERACTION TERMS
overall_interact_saat <- ggplot(risks_overall_interact_saat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip()
overall_interact_saat



### TAAT
overall_taat <- ggplot(risk_overall_taat, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "Change in TAAT Area")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x=element_text(size=11),
               axis.text.y=element_text(size=11),
               axis.title.x=element_text(angle=0, color='black', size=11),
               axis.title.y=element_text(angle=90, color='black', size=11))
overall_taat

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
overall_sing_taat <- ggplot(risks_singvar_taat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) +
  geom_hline(aes(yintercept=0), linetype="dashed", color="gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name="PFAS") + scale_y_continuous(name="Change in TAAT Area")
overall_sing_taat

# SINGLE VARIABLE INTERACTION TERMS
overall_interact_taat <- ggplot(risks_overall_interact_taat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip()
overall_interact_taat



### Weight
overall_weight <- ggplot(risk_overall_weight, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "Change in Body Weight (kg)")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x=element_text(size=11),
               axis.text.y=element_text(size=11),
               axis.title.x=element_text(angle=0, color='black', size=11),
               axis.title.y=element_text(angle=90, color='black', size=11))
overall_weight

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
overall_sing_weight <- ggplot(risks_singvar_weight, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) +
  geom_hline(aes(yintercept=0), linetype="dashed", color="gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name="PFAS") + scale_y_continuous(name="Change in Body Weight (kg)")
overall_sing_weight

# SINGLE VARIABLE INTERACTION TERMS
overall_interact_weight <- ggplot(risks_overall_interact_weight, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip()
overall_interact_weight



### Waist
overall_waist <- ggplot(risk_overall_waist, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "Change in Waist Circumference (cm)")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x=element_text(size=11),
               axis.text.y=element_text(size=11),
               axis.title.x=element_text(angle=0, color='black', size=11),
               axis.title.y=element_text(angle=90, color='black', size=11))
overall_waist

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
overall_sing_waist <- ggplot(risks_singvar_waist, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) +
  geom_hline(aes(yintercept=0), linetype="dashed", color="gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name="PFAS") + scale_y_continuous(name="Change in Waist Circumference (cm)")
overall_sing_waist

# SINGLE VARIABLE INTERACTION TERMS
overall_interact_waist <- ggplot(risks_overall_interact_waist, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip()
overall_interact_waist



### Fat
overall_fat <- ggplot(risk_overall_fat, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "Change in Total Body Fat (%)")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x=element_text(size=11),
               axis.text.y=element_text(size=11),
               axis.title.x=element_text(angle=0, color='black', size=11),
               axis.title.y=element_text(angle=90, color='black', size=11))
overall_fat

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
overall_sing_fat <- ggplot(risks_singvar_fat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) +
  geom_hline(aes(yintercept=0), linetype="dashed", color="gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name="PFAS") + scale_y_continuous(name="Change in Total Body Fat (%)")
overall_sing_fat

# SINGLE VARIABLE INTERACTION TERMS
overall_interact_fat <- ggplot(risks_overall_interact_fat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip()
overall_interact_fat

```

