#####                                                 #####
##### RUN MIXTURES ANALYSIS WITH BKMR IN DXA DATASET  #####
#####                                                 #####

```{r}
##### LOAD PACKAGES
library("bkmr")
library("ggplot2")
library("beepr")
library("tidyverse")

```

```{r}
##### LOAD DATASET
PFAS_D <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/PFAS_D.csv")

```

```{r}
##### TRANSFORMVARIABLES TO NUMERIC FOR BKMR COVARIATE MATRIX

# RENAME
PFAS_D$age_enroll <- PFAS_D$age_mom_enroll_d
PFAS_D$race <- PFAS_D$race2_mom_epi_epia_d
PFAS_D$edu <- PFAS_D$coll_grad
PFAS_D$bmi <- PFAS_D$bmi_mom_prepreg_d
PFAS_D$smoke <- PFAS_D$smokpreg_final_d
PFAS_D$parity <- PFAS_D$parity_d
PFAS_D$married <- PFAS_D$married_cohab

# REFACTOR AND RELABEL 
PFAS_D$race <- ifelse(PFAS_D$race == "white", 0,
                     ifelse(PFAS_D$race == "black", 1,
                     ifelse(PFAS_D$race == "hispa", 2,
                     ifelse(PFAS_D$race == "asian", 3,
                     ifelse(PFAS_D$race == "other", 4, 4)))))
PFAS_D$edu <- ifelse(PFAS_D$edu == 1, 1, 0)
PFAS_D$bmi_cat <- ifelse(PFAS_D$bmi <18.5, 0,
                         ifelse(PFAS_D$bmi >=18.5 & PFAS_D$bmi < 25.0, 1, 
                         ifelse(PFAS_D$bmi >=25.0 & PFAS_D$bmi < 30.0, 2, 
                         ifelse(PFAS_D$bmi >=30.0 & PFAS_D$bmi < 35.0, 3,
                         ifelse(PFAS_D$bmi >=35.0, 4, 99)))))
PFAS_D$smoke <- ifelse(PFAS_D$smoke == "former", 0,
                         ifelse(PFAS_D$smoke == "smoke preg", 1,
                         ifelse(PFAS_D$smoke == "xnever", 2, 2)))
PFAS_D$parity <- ifelse(PFAS_D$parity == 0, 0,
                        ifelse(PFAS_D$parity == 1, 1,
                        ifelse(PFAS_D$parity > 1, 2, 0)))
PFAS_D$married <- ifelse(PFAS_D$married == 1, 1, 0)

# SET CATEGORICAL VARIABLES AS FACTORS
PFAS_D$edu <- as.factor(PFAS_D$edu)
PFAS_D$bmi_cat <- as.factor(PFAS_D$bmi_cat)
PFAS_D$smoke <- as.factor(PFAS_D$smoke)
PFAS_D$parity <- as.factor(PFAS_D$parity)
PFAS_D$race <- as.factor(PFAS_D$race)
PFAS_D$married <- as.factor(PFAS_D$married)

# CENTER AND SCALE CONTINUOUS VARIABLES
PFAS_D$age_enroll <- scale(PFAS_D$age_enroll)

```


```{r}
##### PREPARE VARIABLES FOR BKMR MODELS #####
##### ANTHRO + DXA DATASET (N = 429)

# CREATE MIXTURE OF PFAS
mixture_ad <- as.matrix(cbind(PFAS_D$PFOS, PFAS_D$PFOA, PFAS_D$PFNA, PFAS_D$PFHxS, 
                              PFAS_D$MeFOSSA, PFAS_D$EtFOSSA))

# RENAME VARIABLES IN MIXTURE
colnames(mixture_ad) <- c("PFOS", "PFOA", "PFNA", "PFHxS", "MeFOSSA", "EtFOSSA")

# LOG2-TRANSFORM MIXTURE
lnmixture_ad <- apply(mixture_ad, 2, log)     

# SCALE MIXTURE VARIABLES TO THE MEAN
lnmixture_ad_z <- scale(lnmixture_ad)

# SET THE OUTCOME
LNTRNKFAT <- PFAS_D$LNTKNFAT
LNTOTFAT <- PFAS_D$LNTOTFAT
TotLean <- PFAS_D$TotLean
TotFatPct <- PFAS_D$TotFatPct

# CREATE THE COVARIATE MATRIX
cov_ad <- as.matrix(cbind(PFAS_D$age_enroll, PFAS_D$race, PFAS_D$bmi, PFAS_D$edu, 
                       PFAS_D$smoke, PFAS_D$parity, PFAS_D$married))

# SET THE SEED
set.seed(127)

# CREATE KNOTS
knots_ad <- fields::cover.design(lnmixture_ad_z, nd = 40)$design

```

```{r}
##### BUILD BKMR MODELS
# TOTAL TRUNK FAT MASS
m_trnkfat <- kmbayes(y = LNTRNKFAT, Z = lnmixture_ad_z, X = cov_ad, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_ad)
beep(sound=5, expr=NULL)

# TOTAL BODY FAT MASS
m_totfat <- kmbayes(y = LNTOTFAT, Z = lnmixture_ad_z, X = cov_ad, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_ad)
beep(sound=5, expr=NULL)

# TOTAL BODY LEAN MASS 
m_totlean <- kmbayes(y = TotLean, Z = lnmixture_ad_z, X = cov_ad, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_ad)
beep(sound=5, expr=NULL)

# TOTAL BODY FAT PERCENT
m_totfatpct <- kmbayes(y = TotFatPct, Z = lnmixture_ad_z, X = cov_ad, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_ad)
beep(sound=5, expr=NULL)

```

```{r}
##### VALUES TO KEEP AFTER BURIN/THIN
#
sel <- seq(0,25000,by = 50)

##### ACCESS CONVERGENCE WITH TRACEPLOTS
TracePlot(fit = m_trnkfat, par = "beta", sel = sel)
TracePlot(fit = m_totfat, par = "beta", sel = sel)
TracePlot(fit = m_totlean, par = "beta", sel = sel)
TracePlot(fit = m_totfatpct, par = "beta", sel = sel)

##### VALUES TO KEEP AFTER BURNING/THIN (ACCORDING TO THE TRACEPLOT FUNCTION ABOVE)
sel_final <- seq(1200, 25000, by = 1)

```

```{r}
##### ESIMATE POSTERIOR INCLUSION PROBABILITIES
# TOTAL TRUNK FAT MASS
#summary(m_trnkfat)
ExtractPIPs(m_trnkfat, sel = sel_final)

# TOTAL BODY FAT MASS
#summary(m_totfat)
ExtractPIPs(m_totfat, sel = sel_final)

# TOTAL BODY LEAN MASS
#summary(m_totlean)
ExtractPIPs(m_totlean, sel = sel_final)

# TOTAL BODY FAT PERCENT
#summary(m_totfatpct)
ExtractPIPs(m_totfatpct, sel = sel_final)

```

```{r}
##### PREDICT UNIVARIATE EXPOSURE-RESPONSE FUNCTION
# TOTAL TRUNK FAT MASS
univar_ad_trnkfat <- PredictorResponseUnivar(fit = m_trnkfat, sel = sel_final, method = "approx")
univar_ad_trnkfat

# TOTAL BODY FAT MASS
univar_ad_totfat <- PredictorResponseUnivar(fit = m_totfat, sel = sel_final, method = "approx")
univar_ad_totfat

# TOTAL BODY LEAN MASS
univar_ad_totlean <- PredictorResponseUnivar(fit = m_totlean, sel = sel_final, method = "approx")
univar_ad_totlean

# TOTAL BODY FAT PERCENT
univar_ad_totfatpct <- PredictorResponseUnivar(fit = m_totfatpct, sel = sel_final, method = "approx")
univar_ad_totfatpct


##### PLOT UNIVARIATE EXPOSURE-RESPONSE FUNCTION
# TOTAL TRUNK FAT MASS
uni_ad_trnkfat <- ggplot(univar_ad_trnkfat, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Scaled PFAS plasma concentration") + ylab("Difference in trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni1_ad_trnkfat <- ggplot(univar_ad_trnkfat[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOS plasma concentration") + ylab("Difference in trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni2_ad_trnkfat <- ggplot(univar_ad_trnkfat[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOA plasma concentration") + ylab("Difference in trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni3_ad_trnkfat <- ggplot(univar_ad_trnkfat[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFNA plasma concentration") + ylab("Difference in trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni4_ad_trnkfat <- ggplot(univar_ad_trnkfat[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFHxS plasma concentration") + ylab("Difference in trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni5_ad_trnkfat <- ggplot(univar_ad_trnkfat[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled MeFOSSA plasma concentration") + ylab("Difference in trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni6_ad_trnkfat <- ggplot(univar_ad_trnkfat[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled EtFOSSA plasma concentration") + ylab("Difference in trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni_ad_trnkfat
uni1_ad_trnkfat
uni2_ad_trnkfat
uni3_ad_trnkfat
uni4_ad_trnkfat
uni5_ad_trnkfat
uni6_ad_trnkfat

# TOTAL BODY FAT MASS
uni_ad_totfat <- ggplot(univar_ad_totfat, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Scaled PFAS plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni1_ad_totfat <- ggplot(univar_ad_totfat[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOS plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni2_ad_totfat <- ggplot(univar_ad_totfat[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOA plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni3_ad_totfat <- ggplot(univar_ad_totfat[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFNA plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni4_ad_totfat <- ggplot(univar_ad_totfat[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFHxS plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni5_ad_totfat <- ggplot(univar_ad_totfat[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled MeFOSSA plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni6_ad_totfat <- ggplot(univar_ad_totfat[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled EtFOSSA plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni_ad_totfat
uni1_ad_totfat
uni2_ad_totfat
uni3_ad_totfat
uni4_ad_totfat
uni5_ad_totfat
uni6_ad_totfat

# TOTAL BODY LEAN MASS
uni_ad_totlean <- ggplot(univar_ad_totlean, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Scaled PFAS plasma concentration") + ylab("Difference in body lean mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni1_ad_totlean <- ggplot(univar_ad_totlean[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOS plasma concentration") + ylab("Difference in body lean mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni2_ad_totlean <- ggplot(univar_ad_totlean[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOA plasma concentration") + ylab("Difference in body lean mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni3_ad_totlean <- ggplot(univar_ad_totlean[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFNA plasma concentration") + ylab("Difference in body lean mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni4_ad_totlean <- ggplot(univar_ad_totlean[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFHxS plasma concentration") + ylab("Difference in body lean mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni5_ad_totlean <- ggplot(univar_ad_totlean[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled MeFOSSA plasma concentration") + ylab("Difference in body lean mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni6_ad_totlean <- ggplot(univar_ad_totlean[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled EtFOSSA plasma concentration") + ylab("Difference in body lean mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni_ad_totlean
uni1_ad_totlean
uni2_ad_totlean
uni3_ad_totlean
uni4_ad_totlean
uni5_ad_totlean
uni6_ad_totlean

# TOTAL BODY FAT PERCENT
uni_ad_totfatpct <- ggplot(univar_ad_totfatpct, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Scaled PFAS plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni1_ad_totfatpct <- ggplot(univar_ad_totfatpct[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOS plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni2_ad_totfatpct <- ggplot(univar_ad_totfatpct[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOA plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni3_ad_totfatpct <- ggplot(univar_ad_totfatpct[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFNA plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni4_ad_totfatpct <- ggplot(univar_ad_totfatpct[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFHxS plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni5_ad_totfatpct <- ggplot(univar_ad_totfatpct[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled MeFOSSA plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni6_ad_totfatpct <- ggplot(univar_ad_totfatpct[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled EtFOSSA plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni_ad_totfatpct
uni1_ad_totfatpct
uni2_ad_totfatpct
uni3_ad_totfatpct
uni4_ad_totfatpct
uni5_ad_totfatpct
uni6_ad_totfatpct

```

```{r}
##### PREDICT BIVARIATE EXPOSURE-RESPONSE CURVE TO ASSESS POTENTIAL INTERACTIONS
##### SUBESQUENTLY, PREDICT INTERACTIONS AMONG PFAS
# TOTAL TRUNK FAT MASS
bivar_ad_trnkfat <- PredictorResponseBivar(fit = m_trnkfat, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_ad_trnkfat <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_trnkfat, Z = lnmixture_ad_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_ad_trnkfat_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_trnkfat, Z = lnmixture_ad_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# TOTAL BODY FAT MASS
bivar_ad_totfat <- PredictorResponseBivar(fit = m_totfat, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_ad_totfat <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_totfat, Z = lnmixture_ad_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_ad_totfat_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_totfat, Z = lnmixture_ad_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# TOTAL BODY LEAN MASS
bivar_ad_totlean <- PredictorResponseBivar(fit = m_totlean, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_ad_totlean <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_totlean, Z = lnmixture_ad_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_ad_totlean_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_totlean, Z = lnmixture_ad_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# TOTAL BODY FAT PERCENT
bivar_ad_totfatpct <- PredictorResponseBivar(fit = m_totfatpct, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_ad_totfatpct <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_totfatpct, Z = lnmixture_ad_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_ad_totfatpct_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_totfatpct, Z = lnmixture_ad_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))




##### PLOT INTERACTIONS BETWEEN EXPOSURE AND RESPONSE
##### NON-PARALLEL LINES WOULD INDICATE POTENTIAL INTERACTIONS
# TOTAL TRUNK FAT MASS
p_interact_ad_trnkfat <- ggplot(interact_ad_trnkfat, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("Log2-transformed PFAS 1") +
  ylab ("Difference in trunk fat mass (kg)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_ad_trnkfat

# TOTAL BODY FAT MASS
p_interact_ad_totfat <- ggplot(interact_ad_totfat, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("Log2-transformed PFAS 1") +
  ylab ("Difference in body fat mass (kg)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_ad_totfat

# TOTAL BODY LEAN MASS
p_interact_ad_totlean <- ggplot(interact_ad_totlean, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("Log2-transformed PFAS 1") +
  ylab ("Difference in body lean mass (kg)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_ad_totlean

# TOTAL BODY FAT PERCENT
p_interact_ad_totfatpct <- ggplot(interact_ad_totfatpct, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("Log2-transformed PFAS 1") +
  ylab ("Difference in VAT mass (kg/m^2)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_ad_totfatpct

```

```{r}
##### DETERMINE RISK ASSOCIATED WITH THE OVERALL MIXTURE
##### SUBSEQUENTLY, ESTIMATE RISK FOR SINGLE PFAS AND INTERACTIONS AMONG PFAS
# TOTAL TRUNK FAT MASS
overall_ad_trnkfat <- OverallRiskSummaries(fit = m_trnkfat, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_ad_trnkfat <- SingVarRiskSummaries(fit = m_trnkfat, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_ad_trnkfat <- SingVarIntSummaries(fit = m_trnkfat, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)

# TOTAL BODY FAT MASS
overall_ad_totfat <- OverallRiskSummaries(fit = m_totfat, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_ad_totfat <- SingVarRiskSummaries(fit = m_totfat, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_ad_totfat <- SingVarIntSummaries(fit = m_totfat, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)

# TOTAL BODY LEAN MASS
overall_ad_totlean <- OverallRiskSummaries(fit = m_totlean, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_ad_totlean <- SingVarRiskSummaries(fit = m_totlean, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_ad_totlean <- SingVarIntSummaries(fit = m_totlean, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)

# TOTAL BODY FAT PERCENT
overall_ad_totfatpct <- OverallRiskSummaries(fit = m_totfatpct, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_ad_totfatpct <- SingVarRiskSummaries(fit = m_totfatpct, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_ad_totfatpct <- SingVarIntSummaries(fit = m_totfatpct, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)




##### PLOT RISK ASSOCIATED WITH THE OVERALL MIXTURE
### TOTAL TRUNK FAT MASS
p_overall_ad_trnkfat <- ggplot(overall_ad_trnkfat, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "Change in trunk fat mass (kg)")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x = element_text(size = 11),
               axis.text.y = element_text(size = 11),
               axis.title.x = element_text(angle = 0, color = 'black', size = 11),
               axis.title.y = element_text(angle = 90, color = 'black', size = 11))
p_overall_ad_trnkfat

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_ad_trnkfat <- ggplot(singvar_ad_trnkfat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Scaled PFAS plasma concentration") + scale_y_continuous(name = "Change in trunk fat mass (kg)")
p_singvar_ad_trnkfat

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_ad_trnkfat <- ggplot(overall_interact_ad_trnkfat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in BMI (kg/m^2)") +
  xlab("PFAS")
p_overall_interact_ad_trnkfat


### TOTAL BODY FAT MASS
p_overall_ad_totfat <- ggplot(overall_ad_totfat, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "Change in body fat mass (kg)")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x = element_text(size = 11),
               axis.text.y = element_text(size = 11),
               axis.title.x = element_text(angle = 0, color = 'black', size = 11),
               axis.title.y = element_text(angle = 90, color = 'black', size = 11))
p_overall_ad_totfat

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_ad_totfat <- ggplot(singvar_ad_totfat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Scaled PFAS plasma concentration") + scale_y_continuous(name = "Change in body fat mass (kg)")
p_singvar_ad_totfat

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_ad_totfat <- ggplot(overall_interact_ad_totfat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in BMI (kg/m^2)") +
  xlab("PFAS")
p_overall_interact_ad_totfat


### TOTAL BODY LEAN MASS
p_overall_ad_totlean <- ggplot(overall_ad_totlean, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "Change in body lean mass (kg)")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x = element_text(size = 11),
               axis.text.y = element_text(size = 11),
               axis.title.x = element_text(angle = 0, color = 'black', size = 11),
               axis.title.y = element_text(angle = 90, color = 'black', size = 11))
p_overall_ad_totlean

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_ad_totlean <- ggplot(singvar_ad_totlean, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Scaled PFAS plasma concentration") + scale_y_continuous(name = "Change in body lean mass (kg)")
p_singvar_ad_totlean

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_ad_totlean <- ggplot(overall_interact_ad_totlean, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in BMI (kg/m^2)") +
  xlab("PFAS")
p_overall_interact_ad_totlean


### TOTAL BODY FAT PERCENT
p_overall_ad_totfatpct <- ggplot(overall_ad_totfatpct, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "Change in body fat (%)")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x = element_text(size = 11),
               axis.text.y = element_text(size = 11),
               axis.title.x = element_text(angle = 0, color = 'black', size = 11),
               axis.title.y = element_text(angle = 90, color = 'black', size = 11))
p_overall_ad_totfatpct

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_ad_totfatpct <- ggplot(singvar_ad_totfatpct, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Scaled PFAS plasma concentration") + scale_y_continuous(name = "Change in body fat (%)")
p_singvar_ad_totfatpct

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_ad_totfatpct <- ggplot(overall_interact_ad_totfatpct, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in BMI (kg/m^2)") +
  xlab("PFAS")
p_overall_interact_ad_totfatpct

```

