#####                                  #####
##### RUN MIXTURES ANALYSIS WITH BKMR  #####
#####                                  #####

```{r}
##### LOAD PACKAGES
library("bkmr")
library("ggplot2")
library("beepr")
library("tidyverse")

```

```{r}
##### LOAD DATASET
PFAS_A <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/PFAS_A.csv")

# SUBSET 
summary(PFAS_A$mom_age_comp_d_ma17)
PFAS_A <- subset(PFAS_A, mom_age_comp_d_ma17 < 51)

```

```{r}
##### TRANSFORMVARIABLES TO NUMERIC FOR BKMR COVARIATE MATRIX

# RENAME
PFAS_A$age_enroll <- PFAS_A$age_mom_enroll_d
PFAS_A$race <- PFAS_A$race2_mom_epi_epia_d
PFAS_A$edu <- PFAS_A$coll_grad
PFAS_A$bmi <- PFAS_A$bmi_mom_prepreg_d
PFAS_A$smoke <- PFAS_A$smokpreg_final_d
PFAS_A$parity <- PFAS_A$parity_d
PFAS_A$married <- PFAS_A$married_cohab

# REFACTOR AND RELABEL 
PFAS_A$race <- ifelse(PFAS_A$race == "white", 0,
                      ifelse(PFAS_A$race == "black", 1,
                             ifelse(PFAS_A$race == "hispa", 2,
                                    ifelse(PFAS_A$race == "asian", 3,
                                           ifelse(PFAS_A$race == "other", 4, 4)))))
PFAS_A$edu <- ifelse(PFAS_A$edu == 1, 1, 0)
PFAS_A$bmi_cat <- ifelse(PFAS_A$bmi <18.5, 0,
                         ifelse(PFAS_A$bmi >=18.5 & PFAS_A$bmi < 25.0, 1, 
                                ifelse(PFAS_A$bmi >=25.0 & PFAS_A$bmi < 30.0, 2, 
                                       ifelse(PFAS_A$bmi >=30.0 & PFAS_A$bmi < 35.0, 3,
                                              ifelse(PFAS_A$bmi >=35.0, 4, 99)))))
PFAS_A$smoke <- ifelse(PFAS_A$smoke == "former", 0,
                       ifelse(PFAS_A$smoke == "smoke preg", 1,
                              ifelse(PFAS_A$smoke == "xnever", 2, 2)))
PFAS_A$parity <- ifelse(PFAS_A$parity == 0, 0,
                        ifelse(PFAS_A$parity == 1, 1,
                               ifelse(PFAS_A$parity > 1, 2, 0)))
PFAS_A$married <- ifelse(PFAS_A$married == 1, 1, 0)

# SET CATEGORICAL VARIABLES AS FACTORS
PFAS_A$edu <- as.factor(PFAS_A$edu)
PFAS_A$bmi_cat <- as.factor(PFAS_A$bmi_cat)
PFAS_A$smoke <- as.factor(PFAS_A$smoke)
PFAS_A$parity <- as.factor(PFAS_A$parity)
PFAS_A$race <- as.factor(PFAS_A$race)
PFAS_A$married <- as.factor(PFAS_A$married)

# CENTER AND SCALE CONTINUOUS VARIABLES
PFAS_A$age_enroll <- scale(PFAS_A$age_enroll)

```


```{r}
##### PREPARE VARIABLES FOR BKMR MODELS #####
##### ANTHRO DATASET (N = 549)

# CREATE MIXTURE OF PFAS
mixture_a <- as.matrix(cbind(PFAS_A$PFOS, PFAS_A$PFOA, PFAS_A$PFNA, PFAS_A$PFHxS, 
                             PFAS_A$MeFOSSA, PFAS_A$EtFOSSA))

# RENAME VARIABLES IN MIXTURE
colnames(mixture_a) <- c("PFOS", "PFOA", "PFNA", "PFHxS", "MeFOSSA", "EtFOSSA")

# LOG2-TRANSFORM MIXTURE
lnmixture_a <- apply(mixture_a, 2, log)     

# SCALE MIXTURE VARIABLES TO THE MEAN
lnmixture_a_z <- scale(lnmixture_a)

# SET THE OUTCOME
BMI_a <- PFAS_A$BMI
Weight_a <- PFAS_A$Weight
Waist_a <- PFAS_A$Waist
Hip_a <- PFAS_A$Hip
MUAC_a <- PFAS_A$MUAC
FatPct_a <- PFAS_A$FatPct
FatMass_a <- PFAS_A$FatMass

# CREAT THE COVARIATE MATRIX
cov_a <- as.matrix(cbind(PFAS_A$age_enroll, PFAS_A$race, PFAS_A$bmi_cat, PFAS_A$edu, 
                         PFAS_A$smoke, PFAS_A$parity, PFAS_A$married))

# SET THE SEED
set.seed(127)

# CREATE KNOTS
knots_a <- fields::cover.design(lnmixture_a_z, nd = 50)$design

```

```{r}
##### BUILD BKMR MODELS 
# BMI
m_a_bmi <- kmbayes(y = BMI_a, Z = lnmixture_a_z, X = cov_a, iter=25000, family = "gaussian", 
                   verbose = FALSE, varsel = TRUE, knots = knots_a)
beep(sound=5, expr=NULL)

# WEIGHT
m_a_wt <- kmbayes(y = Weight_a, Z = lnmixture_a_z, X = cov_a, iter=25000, family = "gaussian", 
                  verbose = FALSE, varsel = TRUE, knots = knots_a)
beep(sound=5, expr=NULL)

# WAIST CIRCUMFERENCE
m_a_waist <- kmbayes(y = Waist_a, Z = lnmixture_a_z, X = cov_a, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_a)
beep(sound=5, expr=NULL)

# HIP CIRCUMFERENCE
m_a_hip <- kmbayes(y = Hip_a, Z = lnmixture_a_z, X = cov_a, iter=25000, family = "gaussian", 
                   verbose = FALSE, varsel = TRUE, knots = knots_a)
beep(sound=5, expr=NULL)

# MUAC
m_a_muac <- kmbayes(y = MUAC_a, Z = lnmixture_a_z, X = cov_a, iter=25000, family = "gaussian", 
                    verbose = FALSE, varsel = TRUE, knots = knots_a)
beep(sound=5, expr=NULL)

# BODY FAT %
m_a_bfat <- kmbayes(y = FatPct_a, Z = lnmixture_a_z, X = cov_a, iter=25000, family = "gaussian", 
                    verbose = FALSE, varsel = TRUE, knots = knots_a)
beep(sound=5, expr=NULL)

# BODY FAT MASS
m_a_fat <- kmbayes(y = FatMass_a, Z = lnmixture_a_z, X = cov_a, iter=25000, family = "gaussian", 
                   verbose = FALSE, varsel = TRUE, knots = knots_a)
beep(sound=5, expr=NULL)

```

```{r}
##### VALUES TO KEEP AFTER BURIN/THIN
#
sel <- seq(0,25000,by = 50)

##### ACCESS CONVERGENCE WITH TRACEPLOTS
TracePlot(fit = m_a_bmi, par = "beta", sel = sel)
TracePlot(fit = m_a_wt, par = "beta", sel = sel)
TracePlot(fit = m_a_waist, par = "beta", sel = sel)
TracePlot(fit = m_a_hip, par = "beta", sel = sel)
TracePlot(fit = m_a_muac, par = "beta", sel = sel)
TracePlot(fit = m_a_bfat, par = "beta", sel = sel)
TracePlot(fit = m_a_fat, par = "beta", sel = sel)

##### VALUES TO KEEP AFTER BURNING/THIN (ACCORDING TO THE TRACEPLOT FUNCTION ABOVE)
sel_final <- seq(1200, 25000, by = 1)

```

```{r}
##### ESIMATE POSTERIOR INCLUSION PROBABILITIES
# BMI
#summary(m_a_bmi)
ExtractPIPs(m_a_bmi, sel = sel_final)

# WEIGHT
#summary(m_a_wt)
ExtractPIPs(m_a_wt, sel = sel_final)

# WAIST CIRCUMFERENCE
#summary(m_a_waist)
ExtractPIPs(m_a_waist, sel = sel_final)

# HIP CIRCUMFERENCE
#summary(m_a_hip)
ExtractPIPs(m_a_hip, sel = sel_final)

# MUAC
#summary(m_a_muac)
ExtractPIPs(m_a_muac, sel = sel_final)

# BODT FAT %
#summary(m_a_bfat)
ExtractPIPs(m_a_bfat, sel = sel_final)

# BODY FAT MASS
#summary(m_a_fat)
ExtractPIPs(m_a_fat, sel = sel_final)

```

```{r}
##### PREDICT UNIVARIATE EXPOSURE-RESPONSE FUNCTION
# BMI
univar_a_bmi <- PredictorResponseUnivar(fit = m_a_bmi, sel = sel_final, method = "approx")
univar_a_bmi

# WEIGHT
univar_a_wt <- PredictorResponseUnivar(fit = m_a_wt, sel = sel_final, method = "approx")
univar_a_wt

# WAIST CIRCUMFERENCE
univar_a_waist <- PredictorResponseUnivar(fit = m_a_waist, sel = sel_final, method = "approx")
univar_a_waist

# HIP CIRCUMFERENCE
univar_a_hip <- PredictorResponseUnivar(fit = m_a_hip, sel = sel_final, method = "approx")
univar_a_hip

# MUAC
univar_a_muac <- PredictorResponseUnivar(fit = m_a_muac, sel = sel_final, method = "approx")
univar_a_muac

# BODY FAT %
univar_a_bfat <- PredictorResponseUnivar(fit = m_a_bfat, sel = sel_final, method = "approx")
univar_a_bfat

# BODY FAT MASS
univar_a_fat <- PredictorResponseUnivar(fit = m_a_fat, sel = sel_final, method = "approx")
univar_a_fat


##### PLOT UNIVARIATE EXPOSURE-RESPONSE FUNCTION
# BMI
uni_a_bmi <- ggplot(univar_a_bmi, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Scaled PFAS plasma concentration") + ylab("Difference in BMI (kg/m^2)") +
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni1_a_bmi <- ggplot(univar_a_bmi[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOS plasma concentration") + ylab("Difference in BMI (kg/m^2)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni2_a_bmi <- ggplot(univar_a_bmi[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOA plasma concentration") + ylab("Difference in BMI (kg/m^2)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni3_a_bmi <- ggplot(univar_a_bmi[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFNA plasma concentration") + ylab("Difference in BMI (kg/m^2)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni4_a_bmi <- ggplot(univar_a_bmi[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFHxS plasma concentration") + ylab("Difference in BMI (kg/m^2)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni5_a_bmi <- ggplot(univar_a_bmi[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled MeFOSSA plasma concentration") + ylab("Difference in BMI (kg/m^2)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni6_a_bmi <- ggplot(univar_a_bmi[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled EtFOSSA plasma concentration") + ylab("Difference in BMI (kg/m^2)") +
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni_a_bmi
uni1_a_bmi
uni2_a_bmi
uni3_a_bmi
uni4_a_bmi
uni5_a_bmi
uni6_a_bmi


# WEIGHT
uni_a_wt <- ggplot(univar_a_wt, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Scaled PFAS plasma concentration") + ylab("Difference in weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni1_a_wt <- ggplot(univar_a_wt[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOS plasma concentration") + ylab("Difference in weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni2_a_wt <- ggplot(univar_a_wt[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOA plasma concentration") + ylab("Difference in weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni3_a_wt <- ggplot(univar_a_wt[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFNA plasma concentration") + ylab("Difference in weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni4_a_wt <- ggplot(univar_a_wt[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFHxS plasma concentration") + ylab("Difference in weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni5_a_wt <- ggplot(univar_a_wt[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled MeFOSSA plasma concentration") + ylab("Difference in weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni6_a_wt <- ggplot(univar_a_wt[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled EtFOSSA plasma concentration") + ylab("Difference in weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni_a_wt
uni1_a_wt
uni2_a_wt
uni3_a_wt
uni4_a_wt
uni5_a_wt
uni6_a_wt


# WAIST CIRCUMFERENCE
uni_a_waist <- ggplot(univar_a_waist, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Scaled PFAS plasma concentration") + ylab("Difference in waist circumference (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni1_a_waist <- ggplot(univar_a_waist[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOS plasma concentration") + ylab("Difference in waist circumference (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni2_a_waist <- ggplot(univar_a_waist[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOA plasma concentration") + ylab("Difference in waist circumference (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni3_a_waist <- ggplot(univar_a_waist[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFNA plasma concentration") + ylab("Difference in waist circumference (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni4_a_waist <- ggplot(univar_a_waist[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFHxS plasma concentration") + ylab("Difference in waist circumference (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni5_a_waist <- ggplot(univar_a_waist[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled MeFOSSA plasma concentration") + ylab("Difference in waist circumference (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni6_a_waist <- ggplot(univar_a_waist[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled EtFOSSA plasma concentration") + ylab("Difference in waist circumference (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni_a_waist
uni1_a_waist
uni2_a_waist
uni3_a_waist
uni4_a_waist
uni5_a_waist
uni6_a_waist


# HIP CIRCUMFERENCE
uni_a_hip <- ggplot(univar_a_hip, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Scaled PFAS plasma concentration") + ylab("Difference in hip circumference (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni1_a_hip <- ggplot(univar_a_hip[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOS plasma concentration") + ylab("Difference in hip circumference (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni2_a_hip <- ggplot(univar_a_hip[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOA plasma concentration") + ylab("Difference in hip circumference (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni3_a_hip <- ggplot(univar_a_hip[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFNA plasma concentration") + ylab("Difference in hip circumference (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni4_a_hip <- ggplot(univar_a_hip[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFHxS plasma concentration") + ylab("Difference in hip circumference (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni5_a_hip <- ggplot(univar_a_hip[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled MeFOSSA plasma concentration") + ylab("Difference in hip circumference (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni6_a_hip <- ggplot(univar_a_hip[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled EtFOSSA plasma concentration") + ylab("Difference in hip circumference (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni_a_hip
uni1_a_hip
uni2_a_hip
uni3_a_hip
uni4_a_hip
uni5_a_hip
uni6_a_hip


# MUAC
uni_a_muac <- ggplot(univar_a_muac, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Scaled PFAS plasma concentration") + ylab("Difference in MUAC (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni1_a_muac <- ggplot(univar_a_muac[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOS plasma concentration") + ylab("Difference in MUAC (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni2_a_muac <- ggplot(univar_a_muac[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOA plasma concentration") + ylab("Difference in MUAC (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni3_a_muac <- ggplot(univar_a_muac[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFNA plasma concentration") + ylab("Difference in MUAC (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni4_a_muac <- ggplot(univar_a_muac[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFHxS plasma concentration") + ylab("Difference in MUAC (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni5_a_muac <- ggplot(univar_a_muac[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled MeFOSSA plasma concentration") + ylab("Difference in MUAC (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni6_a_muac <- ggplot(univar_a_muac[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled EtFOSSA plasma concentration") + ylab("Difference in MUAC (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni_a_muac
uni1_a_muac
uni2_a_muac
uni3_a_muac
uni4_a_muac
uni5_a_muac
uni6_a_muac


# BODY FAT %
uni_a_bfat <- ggplot(univar_a_bfat, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Scaled PFAS plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni1_a_bfat <- ggplot(univar_a_bfat[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOS plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni2_a_bfat <- ggplot(univar_a_bfat[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOA plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni3_a_bfat <- ggplot(univar_a_bfat[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFNA plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni4_a_bfat <- ggplot(univar_a_bfat[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFHxS plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni5_a_bfat <- ggplot(univar_a_bfat[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled MeFOSSA plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni6_a_bfat <- ggplot(univar_a_bfat[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled EtFOSSA plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni_a_bfat
uni1_a_bfat
uni2_a_bfat
uni3_a_bfat
uni4_a_bfat
uni5_a_bfat
uni6_a_bfat


# BODY FAT MASS
uni_a_fat <- ggplot(univar_a_fat, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Scaled PFAS plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni1_a_fat <- ggplot(univar_a_fat[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOS plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni2_a_fat <- ggplot(univar_a_fat[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOA plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni3_a_fat <- ggplot(univar_a_fat[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFNA plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni4_a_fat <- ggplot(univar_a_fat[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFHxS plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni5_a_fat <- ggplot(univar_a_fat[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled MeFOSSA plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni6_a_fat <- ggplot(univar_a_fat[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled EtFOSSA plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed')

uni_a_fat
uni1_a_fat
uni2_a_fat
uni3_a_fat
uni4_a_fat
uni5_a_fat
uni6_a_fat

```

```{r}
##### PREDICT BIVARIATE EXPOSURE-RESPONSE CURVE TO ASSESS POTENTIAL INTERACTIONS
##### SUBESQUENTLY, PREDICT INTERACTIONS AMONG PFAS
# BMI
bivar_a_bmi <- PredictorResponseBivar(fit = m_a_bmi, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_a_bmi <- PredictorResponseBivarLevels(pred.resp.df = bivar_a_bmi, Z = lnmixture_a_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_a_bmi_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_a_bmi, Z = lnmixture_a_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# WEIGHT
bivar_a_wt <- PredictorResponseBivar(fit = m_a_wt, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_a_wt <- PredictorResponseBivarLevels(pred.resp.df = bivar_a_wt, Z = lnmixture_a_z,
                                              both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_a_wt_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_a_wt, Z = lnmixture_a_z,
                                                   both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# WAIST CIRCUMFERENCE
bivar_a_waist <- PredictorResponseBivar(fit = m_a_waist, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_a_waist <- PredictorResponseBivarLevels(pred.resp.df = bivar_a_waist, Z = lnmixture_a_z,
                                                 both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_a_waist_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_a_waist, Z = lnmixture_a_z,
                                                      both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# HIP CIRCUMFERENCE
bivar_a_hip <- PredictorResponseBivar(fit = m_a_hip, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_a_hip <- PredictorResponseBivarLevels(pred.resp.df = bivar_a_hip, Z = lnmixture_a_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_a_hip_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_a_hip, Z = lnmixture_a_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# MUAC
bivar_a_muac <- PredictorResponseBivar(fit = m_a_muac, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_a_muac <- PredictorResponseBivarLevels(pred.resp.df = bivar_a_muac, Z = lnmixture_a_z,
                                                both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_a_muac_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_a_muac, Z = lnmixture_a_z,
                                                     both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# BODY FAT %
bivar_a_bfat <- PredictorResponseBivar(fit = m_a_bfat, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_a_bfat <- PredictorResponseBivarLevels(pred.resp.df = bivar_a_bfat, Z = lnmixture_a_z,
                                                both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_a_bfat_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_a_bfat, Z = lnmixture_a_z,
                                                     both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# BODY FAT MASS
bivar_a_fat <- PredictorResponseBivar(fit = m_a_fat, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_a_fat <- PredictorResponseBivarLevels(pred.resp.df = bivar_a_fat, Z = lnmixture_a_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_a_fat_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_a_fat, Z = lnmixture_a_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))



##### PLOT INTERACTIONS BETWEEN EXPOSURE AND RESPONSE
##### NON-PARALLEL LINES WOULD INDICATE POTENTIAL INTERACTIONS
# BMI
p_interact_a_bmi <- ggplot(interact_a_bmi, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("Log2-transformed PFAS 1") +
  ylab ("Difference in BMI (kg/m^2)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_a_bmi

# WEIGHT
p_interact_a_wt <- ggplot(interact_a_wt, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("Log2-transformed PFAS 1") +
  ylab ("Difference in weight (kg)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_a_wt

# WAIST
p_interact_a_waist <- ggplot(interact_a_waist, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("Log2-transformed PFAS 1") +
  ylab ("Difference in waist circumference (cm)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_a_waist 

# HIP
p_interact_a_hip <- ggplot(interact_a_hip, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("Log2-transformed PFAS 1") +
  ylab ("Difference in hip circumference (cm)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_a_hip

# MUAC
p_interact_a_muac <- ggplot(interact_a_muac, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("Log2-transformed PFAS 1") +
  ylab ("Difference in MUAC (cm)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_a_muac

# BODY FAT %
p_interact_a_bfat <- ggplot(interact_a_bfat, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("Log2-transformed PFAS 1") +
  ylab ("Difference in bofy fat (%)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_a_bfat

# BODY FAT MASS
p_interact_a_fat <- ggplot(interact_a_fat, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("Log2-transformed PFAS 1") +
  ylab ("Difference in body fat mass (kg)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_a_fat

```

```{r}
##### DETERMINE RISK ASSOCIATED WITH THE OVERALL MIXTURE
##### SUBSEQUENTLY, ESTIMATE RISK FOR SINGLE PFAS AND INTERACTIONS AMONG PFAS
# BMI
overall_a_bmi <- OverallRiskSummaries(fit = m_a_bmi, q.fixed = 0.50, sel = sel_final,
                                      method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_a_bmi <- SingVarRiskSummaries(fit = m_a_bmi, qs.diff = c(0.25, 0.75),
                                      q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_a_bmi <- SingVarIntSummaries(fit = m_a_bmi, qs.diff = c(0.25, 0.75),
                                              qs.fixed = c(0.25, 0.75),sel=sel_final)

# WEIGHT
overall_a_wt <- OverallRiskSummaries(fit = m_a_wt, q.fixed = 0.50, sel = sel_final,
                                     method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_a_wt <- SingVarRiskSummaries(fit = m_a_wt, qs.diff = c(0.25, 0.75),
                                     q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_a_wt <- SingVarIntSummaries(fit = m_a_wt, qs.diff = c(0.25, 0.75),
                                             qs.fixed = c(0.25, 0.75),sel=sel_final)

# WAIST CIRCUMFERENCE
overall_a_waist <- OverallRiskSummaries(fit = m_a_waist, q.fixed = 0.50, sel = sel_final,
                                        method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_a_waist <- SingVarRiskSummaries(fit = m_a_waist, qs.diff = c(0.25, 0.75),
                                        q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_a_waist <- SingVarIntSummaries(fit = m_a_waist, qs.diff = c(0.25, 0.75),
                                                qs.fixed = c(0.25, 0.75),sel=sel_final)

# HIP CIRCUMFERENCE
overall_a_hip <- OverallRiskSummaries(fit = m_a_hip, q.fixed = 0.50, sel = sel_final,
                                      method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_a_hip <- SingVarRiskSummaries(fit = m_a_hip, qs.diff = c(0.25, 0.75),
                                      q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_a_hip <- SingVarIntSummaries(fit = m_a_hip, qs.diff = c(0.25, 0.75),
                                              qs.fixed = c(0.25, 0.75),sel=sel_final)

# MUAC
overall_a_muac <- OverallRiskSummaries(fit = m_a_muac, q.fixed = 0.50, sel = sel_final,
                                       method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_a_muac <- SingVarRiskSummaries(fit = m_a_muac, qs.diff = c(0.25, 0.75),
                                       q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_a_muac <- SingVarIntSummaries(fit = m_a_muac, qs.diff = c(0.25, 0.75),
                                               qs.fixed = c(0.25, 0.75),sel=sel_final)

# BODY FAT %
overall_a_bfat <- OverallRiskSummaries(fit = m_a_bfat, q.fixed = 0.50, sel = sel_final,
                                       method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_a_bfat <- SingVarRiskSummaries(fit = m_a_bfat, qs.diff = c(0.25, 0.75),
                                       q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_a_bfat <- SingVarIntSummaries(fit = m_a_bfat, qs.diff = c(0.25, 0.75),
                                               qs.fixed = c(0.25, 0.75),sel=sel_final)

# BODT FAT MASS
overall_a_fat <- OverallRiskSummaries(fit = m_a_fat, q.fixed = 0.50, sel = sel_final,
                                      method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_a_fat <- SingVarRiskSummaries(fit = m_a_fat, qs.diff = c(0.25, 0.75),
                                      q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_a_fat <- SingVarIntSummaries(fit = m_a_fat, qs.diff = c(0.25, 0.75),
                                              qs.fixed = c(0.25, 0.75),sel=sel_final)



##### PLOT RISK ASSOCIATED WITH THE OVERALL MIXTURE
### BMI
p_overall_a_bmi <- ggplot(overall_a_bmi, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
  geom_pointrange() +
  scale_y_continuous(name = "Change in BMI (kg/m^2)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 11),
    axis.text.y = element_text(size = 11),
    axis.title.x = element_text(angle = 0, color = 'black', size = 11),
    axis.title.y = element_text(angle = 90, color = 'black', size = 11))
p_overall_a_bmi

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_a_bmi <- ggplot(singvar_a_bmi, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                             col = q.fixed)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Scaled PFAS plasma concentration") + scale_y_continuous(name = "Change in BMI (kg/m^2)")
p_singvar_a_bmi

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_a_bmi <- ggplot(overall_interact_a_bmi, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in BMI (kg/m^2)") +
  xlab("PFAS")
p_overall_interact_a_bmi


### WEIGHT
p_overall_a_wt <- ggplot(overall_a_wt, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
  geom_pointrange() +
  scale_y_continuous(name = "Change in weight (kg)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 11),
    axis.text.y = element_text(size = 11),
    axis.title.x = element_text(angle = 0, color = 'black', size = 11),
    axis.title.y = element_text(angle = 90, color = 'black', size = 11))
p_overall_a_wt

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_a_wt <- ggplot(singvar_a_wt, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                           col = q.fixed)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Scaled PFAS plasma concentration") + scale_y_continuous(name = "Change in weight (kg)")
p_singvar_a_wt

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_a_wt <- ggplot(overall_interact_a_wt, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in weight (kg)") +
  xlab("PFAS")
p_overall_interact_a_wt


### WAIST CIRCUMFERENCE
p_overall_a_waist <- ggplot(overall_a_waist, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
  geom_pointrange() +
  scale_y_continuous(name = "Change in waist circumference (cm)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 11),
    axis.text.y = element_text(size = 11),
    axis.title.x = element_text(angle = 0, color = 'black', size = 11),
    axis.title.y = element_text(angle = 90, color = 'black', size = 11))
p_overall_a_waist

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_a_waist <- ggplot(singvar_a_waist, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                                 col = q.fixed)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Scaled PFAS plasma concentration") + scale_y_continuous(name = "Change in waist circumference (cm)")
p_singvar_a_waist

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_a_waist <- ggplot(overall_interact_a_waist, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in waist circumference (cm)") +
  xlab("PFAS")
p_overall_interact_a_waist


### HIP CIRCUMFERENCE
p_overall_a_hip <- ggplot(overall_a_hip, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
  geom_pointrange() +
  scale_y_continuous(name = "Change in hip circumference (cm)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 11),
    axis.text.y = element_text(size = 11),
    axis.title.x = element_text(angle = 0, color = 'black', size = 11),
    axis.title.y = element_text(angle = 90, color = 'black', size = 11))
p_overall_a_hip

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_a_hip <- ggplot(singvar_a_hip, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                             col = q.fixed)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Scaled PFAS plasma concentration") + scale_y_continuous(name = "Change in hip circumference (cm)")
p_singvar_a_hip

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_a_hip <- ggplot(overall_interact_a_hip, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in hip circumference (cm)") +
  xlab("PFAS")
p_overall_interact_a_hip


### MUAC
p_overall_a_muac <- ggplot(overall_a_muac, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
  geom_pointrange() +
  scale_y_continuous(name = "Change in MUAC (cm)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 11),
    axis.text.y = element_text(size = 11),
    axis.title.x = element_text(angle = 0, color = 'black', size = 11),
    axis.title.y = element_text(angle = 90, color = 'black', size = 11))
p_overall_a_muac

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_a_muac <- ggplot(singvar_a_muac, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                               col = q.fixed)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Scaled PFAS plasma concentration") + scale_y_continuous(name = "Change in MUAC (cm)")
p_singvar_a_muac

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_a_muac <- ggplot(overall_interact_a_muac, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in MUAC (cm)") +
  xlab("PFAS")
p_overall_interact_a_muac


### BODY FAT %
p_overall_a_bfat <- ggplot(overall_a_bfat, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
  geom_pointrange() +
  scale_y_continuous(name = "Change in body fat (%)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 11),
    axis.text.y = element_text(size = 11),
    axis.title.x = element_text(angle = 0, color = 'black', size = 11),
    axis.title.y = element_text(angle = 90, color = 'black', size = 11))
p_overall_a_bfat

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_a_bfat <- ggplot(singvar_a_bfat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                               col = q.fixed)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Scaled PFAS plasma concentration") + scale_y_continuous(name = "Change in body fat (%)")
p_singvar_a_bfat

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_a_bfat <- ggplot(overall_interact_a_bfat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in body fat (%)") +
  xlab("PFAS")
p_overall_interact_a_bfat


### BODY FAT MASS
p_overall_a_fat <- ggplot(overall_a_fat, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
  geom_pointrange() +
  scale_y_continuous(name = "Change in body fat mass (kg)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 11),
    axis.text.y = element_text(size = 11),
    axis.title.x = element_text(angle = 0, color = 'black', size = 11),
    axis.title.y = element_text(angle = 90, color = 'black', size = 11))
p_overall_a_fat

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_a_fat <- ggplot(singvar_a_fat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                             col = q.fixed)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Scaled PFAS plasma concentration") + scale_y_continuous(name = "Change in body fat mass (kg)")
p_singvar_a_fat

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_a_fat <- ggplot(overall_interact_a_fat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in body fat mass (kg)") +
  xlab("PFAS")
p_overall_interact_a_fat

```

