#####                                                  #####
##### RUN MIXTURES ANALYSIS WITH BKMR IN ANTHRO        #####
#####                                                  #####

```{r}
##### LOAD PACKAGES
library("bkmr")
library("ggplot2")
library("beepr")
library("tidyverse")

```

```{r}
##### LOAD DATASET
PFAS_A <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/PFAS_A.csv")

```

```{r}
##### TRANSFORM VARIABLES TO NUMERIC FOR BKMR COVARIATE MATRIX

# RENAME
PFAS_A$age_enroll <- PFAS_A$age_mom_enroll_d
PFAS_A$race <- PFAS_A$race2_mom_epi_epia_d
PFAS_A$edu <- PFAS_A$coll_grad
PFAS_A$menar <- PFAS_A$mom_firstperiod_12y
PFAS_A$smoke <- PFAS_A$smokpreg_final_d
PFAS_A$parity <- PFAS_A$parity_d
PFAS_A$married <- PFAS_A$married_cohab

# REFACTOR AND RELABEL 
PFAS_A$race <- ifelse(PFAS_A$race == "white", 0,
                     ifelse(PFAS_A$race == "black", 1,
                     ifelse(PFAS_A$race == "hispa", 2,
                     ifelse(PFAS_A$race == "asian", 3,
                     ifelse(PFAS_A$race == "other", 4, 4)))))
PFAS_A$edu <- ifelse(PFAS_A$edu == 1, 1, 0)
PFAS_A$bmi_cat <- ifelse(PFAS_A$bmi <18.5, 0,
                         ifelse(PFAS_A$bmi >=18.5 & PFAS_A$bmi < 25.0, 1, 
                         ifelse(PFAS_A$bmi >=25.0 & PFAS_A$bmi < 30.0, 2, 
                         ifelse(PFAS_A$bmi >=30.0 & PFAS_A$bmi < 35.0, 3,
                         ifelse(PFAS_A$bmi >=35.0, 4, 99)))))
PFAS_A$smoke <- ifelse(PFAS_A$smoke == "former", 0,
                         ifelse(PFAS_A$smoke == "smoke preg", 1,
                         ifelse(PFAS_A$smoke == "xnever", 2, 2)))
PFAS_A$parity <- ifelse(PFAS_A$parity == 0, 0,
                        ifelse(PFAS_A$parity == 1, 1,
                        ifelse(PFAS_A$parity > 1, 2, 0)))
PFAS_A$married <- ifelse(PFAS_A$married == 1, 1, 0)

# SET CATEGORICAL VARIABLES AS FACTORS
PFAS_A$edu <- as.factor(PFAS_A$edu)
PFAS_A$bmi_cat <- as.factor(PFAS_A$bmi_cat)
PFAS_A$smoke <- as.factor(PFAS_A$smoke)
PFAS_A$parity <- as.factor(PFAS_A$parity)
PFAS_A$race <- as.factor(PFAS_A$race)
PFAS_A$married <- as.factor(PFAS_A$married)

# CENTER AND SCALE CONTINUOUS VARIABLES
#PFAS_A$age_enroll <- scale(PFAS_A$age_enroll)

```

```{r}
##### PREPARE VARIABLES FOR BKMR MODELS #####
##### ANTHRO DATASET (N = 549)

# CREATE MIXTURE OF PFAS
mixture_a <- as.matrix(cbind(PFAS_A$PFOS, PFAS_A$PFOA, PFAS_A$PFNA, PFAS_A$PFHxS, 
                              PFAS_A$MeFOSSA, PFAS_A$EtFOSSA))

# RENAME VARIABLES IN MIXTURE
colnames(mixture_a) <- c("PFOS", "PFOA", "PFNA", "PFHxS", "MeFOSSA", "EtFOSSA")

# LN-TRANSFORM MIXTURE
lnmixture_a <- apply(mixture_a, 2, log)     

# SCALE MIXTURE VARIABLES TO THE MEAN
lnmixture_a_z <- scale(lnmixture_a)

# SET THE OUTCOME
BMI <- PFAS_A$LNBMI
Waist <- PFAS_A$Waist
WHR <- PFAS_A$WHR
MUAC <- PFAS_A$MUAC

# CREAT THE COVARIATE MATRIX
cov_a <- as.matrix(cbind(PFAS_A$age_enroll, PFAS_A$race, PFAS_A$menar, PFAS_A$edu, 
                       PFAS_A$smoke, PFAS_A$parity, PFAS_A$married))

# SET THE SEED
set.seed(127)

# CREATE KNOTS
knots_a <- fields::cover.design(lnmixture_a_z, nd = 50)$design

```

```{r}
##### BUILD BKMR MODELS 
# BMI
m_bmi <- kmbayes(y = BMI, Z = lnmixture_a_z, X = cov_a, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_a)
beep(sound=5, expr=NULL)

# WAIST CIRCUMFERENCE
m_waist <- kmbayes(y = Waist, Z = lnmixture_a_z, X = cov_a, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_a)
beep(sound=5, expr=NULL)

# WAIST-TO-HIP-RATIO
m_whr <- kmbayes(y = WHR, Z = lnmixture_a_z, X = cov_a, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_a)
beep(sound=5, expr=NULL)

# MUAC
m_muac <- kmbayes(y = MUAC, Z = lnmixture_a_z, X = cov_a, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_a)
beep(sound=5, expr=NULL)

```

```{r}
##### VALUES TO KEEP AFTER BURIN/THIN
#
sel <- seq(0,25000,by = 50)

##### ACCESS CONVERGENCE WITH TRACEPLOTS
TracePlot(fit = m_bmi, par = "beta", sel = sel)
TracePlot(fit = m_waist, par = "beta", sel = sel)
TracePlot(fit = m_whr, par = "beta", sel = sel)
TracePlot(fit = m_muac, par = "beta", sel = sel)


##### VALUES TO KEEP AFTER BURNING/THIN (ACCORDING TO THE TRACEPLOT FUNCTION ABOVE)
sel_final <- seq(1200, 25000, by = 1)

```

```{r}
##### ESIMATE POSTERIOR INCLUSION PROBABILITIES
# BMI
#summary(m_bmi)
ExtractPIPs(m_bmi, sel = sel_final)

# WAIST CIRCUMFERENCE
#summary(m_waist)
ExtractPIPs(m_waist, sel = sel_final)

# WAIST-TO-HIP-RATIO
#summary(m_whr)
ExtractPIPs(m_whr, sel = sel_final)

# MUAC
#summary(m_muac)
ExtractPIPs(m_muac, sel = sel_final)

```

```{r}
##### PREDICT UNIVARIATE EXPOSURE-RESPONSE FUNCTION
# BMI
univar_bmi <- PredictorResponseUnivar(fit = m_bmi, sel = sel_final, method = "approx")
univar_bmi


# WAIST CIRCUMFERENCE
univar_waist <- PredictorResponseUnivar(fit = m_waist, sel = sel_final, method = "approx")
univar_waist

# WAIST-TO-HIP-RATIO
univar_whr <- PredictorResponseUnivar(fit = m_whr, sel = sel_final, method = "approx")
univar_whr

# MUAC
univar_muac <- PredictorResponseUnivar(fit = m_muac, sel = sel_final, method = "approx")
univar_muac



##### PLOT UNIVARIATE EXPOSURE-RESPONSE FUNCTION
# BMI
uni_bmi <- ggplot(univar_bmi, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Scaled PFAS plasma concentration") + ylab("Difference in BMI (kg/m^2)") +
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni1_bmi <- ggplot(univar_bmi[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOS plasma concentration") + ylab("Difference in BMI (kg/m^2)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni2_bmi <- ggplot(univar_bmi[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOA plasma concentration") + ylab("Difference in BMI (kg/m^2)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni3_bmi <- ggplot(univar_bmi[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFNA plasma concentration") + ylab("Difference in BMI (kg/m^2)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni4_bmi <- ggplot(univar_bmi[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFHxS plasma concentration") + ylab("Difference in BMI (kg/m^2)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni5_bmi <- ggplot(univar_bmi[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled MeFOSSA plasma concentration") + ylab("Difference in BMI (kg/m^2)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni6_bmi <- ggplot(univar_bmi[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled EtFOSSA plasma concentration") + ylab("Difference in BMI (kg/m^2)") +
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni_bmi
uni1_bmi
uni2_bmi
uni3_bmi
uni4_bmi
uni5_bmi
uni6_bmi


# WEIGHT
uni_wt <- ggplot(univar_wt, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Scaled PFAS plasma concentration") + ylab("Difference in weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni1_wt <- ggplot(univar_wt[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOS plasma concentration") + ylab("Difference in weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni2_wt <- ggplot(univar_wt[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOA plasma concentration") + ylab("Difference in weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni3_wt <- ggplot(univar_wt[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFNA plasma concentration") + ylab("Difference in weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni4_wt <- ggplot(univar_wt[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFHxS plasma concentration") + ylab("Difference in weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni5_wt <- ggplot(univar_wt[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled MeFOSSA plasma concentration") + ylab("Difference in weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni6_wt <- ggplot(univar_wt[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled EtFOSSA plasma concentration") + ylab("Difference in weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni_wt
uni1_wt
uni2_wt
uni3_wt
uni4_wt
uni5_wt
uni6_wt


# WAIST CIRCUMFERENCE
uni_waist <- ggplot(univar_waist, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Scaled PFAS plasma concentration") + ylab("Difference in waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni1_waist <- ggplot(univar_waist[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOS plasma concentration") + ylab("Difference in waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni2_waist <- ggplot(univar_waist[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOA plasma concentration") + ylab("Difference in waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni3_waist <- ggplot(univar_waist[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFNA plasma concentration") + ylab("Difference in waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni4_waist <- ggplot(univar_waist[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFHxS plasma concentration") + ylab("Difference in waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni5_waist <- ggplot(univar_waist[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled MeFOSSA plasma concentration") + ylab("Difference in waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni6_waist <- ggplot(univar_waist[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled EtFOSSA plasma concentration") + ylab("Difference in waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni_waist
uni1_waist
uni2_waist
uni3_waist
uni4_waist
uni5_waist
uni6_waist


# WAIST-TO-HIP-RATIO
uni_whr <- ggplot(univar_whr, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Scaled PFAS plasma concentration") + ylab("Difference in waist-to-hip ratio")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni1_whr <- ggplot(univar_whr[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOS plasma concentration") + ylab("Difference in waist-to-hip ratio")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni2_whr <- ggplot(univar_whr[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOA plasma concentration") + ylab("Difference in waist-to-hip ratio")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni3_whr <- ggplot(univar_whr[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFNA plasma concentration") + ylab("Difference in waist-to-hip ratio")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni4_whr <- ggplot(univar_whr[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFHxS plasma concentration") + ylab("Difference in waist-to-hip ratio")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni5_whr <- ggplot(univar_whr[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled MeFOSSA plasma concentration") + ylab("Difference in waist-to-hip ratio")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni6_whr <- ggplot(univar_whr[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled EtFOSSA plasma concentration") + ylab("Difference in waist-to-hip ratio")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni_whr
uni1_whr
uni2_whr
uni3_whr
uni4_whr
uni5_whr
uni6_whr


# MUAC
uni_muac <- ggplot(univar_muac, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Scaled PFAS plasma concentration") + ylab("Difference in MUAC (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni1_muac <- ggplot(univar_muac[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOS plasma concentration") + ylab("Difference in MUAC (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni2_muac <- ggplot(univar_muac[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOA plasma concentration") + ylab("Difference in MUAC (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni3_muac <- ggplot(univar_muac[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFNA plasma concentration") + ylab("Difference in MUAC (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni4_muac <- ggplot(univar_muac[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFHxS plasma concentration") + ylab("Difference in MUAC (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni5_muac <- ggplot(univar_muac[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled MeFOSSA plasma concentration") + ylab("Difference in MUAC (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni6_muac <- ggplot(univar_muac[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled EtFOSSA plasma concentration") + ylab("Difference in MUAC (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni_muac
uni1_muac
uni2_muac
uni3_muac
uni4_muac
uni5_muac
uni6_muac
uni_bmi

# BODY FAT %
uni_bfat <- ggplot(univar_bfat, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Scaled PFAS plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni1_bfat <- ggplot(univar_bfat[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOS plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni2_bfat <- ggplot(univar_bfat[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOA plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni3_bfat <- ggplot(univar_bfat[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFNA plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni4_bfat <- ggplot(univar_bfat[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFHxS plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni5_bfat <- ggplot(univar_bfat[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled MeFOSSA plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni6_bfat <- ggplot(univar_bfat[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled EtFOSSA plasma concentration") + ylab("Difference in body fat (%)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni_bfat
uni1_bfat
uni2_bfat
uni3_bfat
uni4_bfat
uni5_bfat
uni6_bfat


# BODY FAT MASS
uni_fat <- ggplot(univar_fat, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Scaled PFAS plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni1_fat <- ggplot(univar_fat[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOS plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni2_fat <- ggplot(univar_fat[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFOA plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni3_fat <- ggplot(univar_fat[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFNA plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni4_fat <- ggplot(univar_fat[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled PFHxS plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni5_fat <- ggplot(univar_fat[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled MeFOSSA plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni6_fat <- ggplot(univar_fat[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled EtFOSSA plasma concentration") + ylab("Difference in body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 20))  

uni_fat
uni1_fat
uni2_fat
uni3_fat
uni4_fat
uni5_fat
uni6_fat

```

```{r}
##### PREDICT BIVARIATE EXPOSURE-RESPONSE CURVE TO ASSESS POTENTIAL INTERACTIONS
##### SUBESQUENTLY, PREDICT INTERACTIONS AMONG PFAS
# BMI
bivar_bmi <- PredictorResponseBivar(fit = m_bmi, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_bmi <- PredictorResponseBivarLevels(pred.resp.df = bivar_bmi, Z = lnmixture_a_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_bmi_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_bmi, Z = lnmixture_a_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# WEIGHT
bivar_wt <- PredictorResponseBivar(fit = m_wt, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_wt <- PredictorResponseBivarLevels(pred.resp.df = bivar_wt, Z = lnmixture_a_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_wt_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_wt, Z = lnmixture_a_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# WAIST CIRCUMFERENCE
bivar_waist <- PredictorResponseBivar(fit = m_waist, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_waist <- PredictorResponseBivarLevels(pred.resp.df = bivar_waist, Z = lnmixture_a_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_waist_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_waist, Z = lnmixture_a_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# WAIST-TO-HIP-RATIO
bivar_whr <- PredictorResponseBivar(fit = m_whr, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_whr <- PredictorResponseBivarLevels(pred.resp.df = bivar_whr, Z = lnmixture_a_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_whr_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_whr, Z = lnmixture_a_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# MUAC
bivar_muac <- PredictorResponseBivar(fit = m_muac, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_muac <- PredictorResponseBivarLevels(pred.resp.df = bivar_muac, Z = lnmixture_a_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_muac_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_muac, Z = lnmixture_a_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# BODY FAT %
bivar_bfat <- PredictorResponseBivar(fit = m_bfat, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_bfat <- PredictorResponseBivarLevels(pred.resp.df = bivar_bfat, Z = lnmixture_a_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_bfat_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_bfat, Z = lnmixture_a_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# BODY FAT MASS
bivar_fat <- PredictorResponseBivar(fit = m_fat, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_fat <- PredictorResponseBivarLevels(pred.resp.df = bivar_fat, Z = lnmixture_a_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_fat_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_fat, Z = lnmixture_a_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))



##### PLOT INTERACTIONS BETWEEN EXPOSURE AND RESPONSE
##### NON-PARALLEL LINES WOULD INDICATE POTENTIAL INTERACTIONS
# BMI
p_interact_bmi <- ggplot(interact_bmi, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) + theme(
               axis.title.x=element_text(angle=0, color='black', size=15),
               axis.title.y=element_text(angle=90, color='black', size=15)) +
  xlab ("Log2-transformed PFAS 1") +
  ylab ("Difference in BMI (kg/m^2)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_bmi

# WEIGHT
p_interact_wt <- ggplot(interact_wt, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) + theme(
               axis.title.x=element_text(angle=0, color='black', size=15),
               axis.title.y=element_text(angle=90, color='black', size=15)) +
  xlab ("Log2-transformed PFAS 1") +
  ylab ("Difference in weight (kg)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_wt

# WAIST CIRCUMFERENCE
p_interact_waist <- ggplot(interact_waist, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) + theme(
               axis.title.x=element_text(angle=0, color='black', size=15),
               axis.title.y=element_text(angle=90, color='black', size=15)) +
  xlab ("Log2-transformed PFAS 1") +
  ylab ("Difference in waist circ. (cm)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_waist 

# WAIST-TO-HIP RATIO
p_interact_whr <- ggplot(interact_whr, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) + theme(
               axis.title.x=element_text(angle=0, color='black', size=15),
               axis.title.y=element_text(angle=90, color='black', size=15)) +
  xlab ("Log2-transformed PFAS 1") +
  ylab ("Difference in waist-to-hip ratio") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_whr

# MUAC
p_interact_muac <- ggplot(interact_muac, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) + theme(
               axis.title.x=element_text(angle=0, color='black', size=15),
               axis.title.y=element_text(angle=90, color='black', size=15)) +
  xlab ("Log2-transformed PFAS 1") +
  ylab ("Difference in MUAC (cm)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_muac

# BODY FAT %
p_interact_bfat <- ggplot(interact_bfat, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) + theme(
               axis.title.x=element_text(angle=0, color='black', size=15),
               axis.title.y=element_text(angle=90, color='black', size=15)) +
  xlab ("Log2-transformed PFAS 1") +
  ylab ("Difference in bofy fat (%)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_bfat

# BODY FAT MASS
p_interact_fat <- ggplot(interact_fat, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) + theme(
               axis.title.x=element_text(angle=0, color='black', size=15),
               axis.title.y=element_text(angle=90, color='black', size=15)) +
  xlab ("Log2-transformed PFAS 1") +
  ylab ("Difference in body fat mass (kg)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_fat

```

```{r}
##### DETERMINE RISK ASSOCIATED WITH THE OVERALL MIXTURE
##### SUBSEQUENTLY, ESTIMATE RISK FOR SINGLE PFAS AND INTERACTIONS AMONG PFAS
# BMI
overall_bmi <- OverallRiskSummaries(fit = m_bmi, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_bmi <- SingVarRiskSummaries(fit = m_bmi, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_bmi <- SingVarIntSummaries(fit = m_bmi, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)

# WEIGHT
overall_wt <- OverallRiskSummaries(fit = m_wt, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_wt <- SingVarRiskSummaries(fit = m_wt, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_wt <- SingVarIntSummaries(fit = m_wt, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)

# WAIST CIRCUMFERENCE
overall_waist <- OverallRiskSummaries(fit = m_waist, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_waist <- SingVarRiskSummaries(fit = m_waist, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_waist <- SingVarIntSummaries(fit = m_waist, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)

# WAIST-TO-HIP-RATIO
overall_whr <- OverallRiskSummaries(fit = m_whr, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_whr <- SingVarRiskSummaries(fit = m_whr, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_whr <- SingVarIntSummaries(fit = m_whr, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)

# MUAC
overall_muac <- OverallRiskSummaries(fit = m_muac, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_muac <- SingVarRiskSummaries(fit = m_muac, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_muac <- SingVarIntSummaries(fit = m_muac, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)

# BODY FAT %
overall_bfat <- OverallRiskSummaries(fit = m_bfat, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_bfat <- SingVarRiskSummaries(fit = m_bfat, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_bfat <- SingVarIntSummaries(fit = m_bfat, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)

# BODT FAT MASS
overall_fat <- OverallRiskSummaries(fit = m_fat, q.fixed = 0.50, sel = sel_final,
                                      method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_fat <- SingVarRiskSummaries(fit = m_fat, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_fat <- SingVarIntSummaries(fit = m_fat, qs.diff = c(0.25, 0.75),
                                              qs.fixed = c(0.25, 0.75),sel=sel_final)



##### PLOT RISK ASSOCIATED WITH THE OVERALL MIXTURE
### BMI
p_overall_bmi <- ggplot(overall_bmi, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
               geom_pointrange() +
               scale_y_continuous(name = "Change in BMI (kg/m^2)")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x = element_text(size = 20),
               axis.text.y = element_text(size = 20),
               axis.title.x = element_text(angle = 0, color = 'black', size = 20),
               axis.title.y = element_text(angle = 90, color = 'black', size = 20))
p_overall_bmi

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_bmi <- ggplot(singvar_bmi, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) + theme(text = element_text(size = 20)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Scaled PFAS plasma concentration") + scale_y_continuous(name = "Change in BMI (kg/m^2)")
p_singvar_bmi

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_bmi <- ggplot(overall_interact_bmi, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +theme(text = element_text(size = 20)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in BMI (kg/m^2)") +
  xlab("PFAS")
p_overall_interact_bmi


### WEIGHT
p_overall_wt <- ggplot(overall_wt, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
               geom_pointrange() +
               scale_y_continuous(name = "Change in weight (kg)")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x = element_text(size = 20),
               axis.text.y = element_text(size = 20),
               axis.title.x = element_text(angle = 0, color = 'black', size = 20),
               axis.title.y = element_text(angle = 90, color = 'black', size = 20))
p_overall_wt

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_wt <- ggplot(singvar_wt, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) + theme(text = element_text(size = 20)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Scaled PFAS plasma concentration") + scale_y_continuous(name = "Change in weight (kg)")
p_singvar_wt

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_wt <- ggplot(overall_interact_wt, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) + theme(text = element_text(size = 20)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in weight (kg)") +
  xlab("PFAS")
p_overall_interact_wt


### WAIST CIRCUMFERENCE
p_overall_waist <- ggplot(overall_waist, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
               geom_pointrange() +
               scale_y_continuous(name = "Change in waist circ. (cm)")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x = element_text(size = 20),
               axis.text.y = element_text(size = 20),
               axis.title.x = element_text(angle = 0, color = 'black', size = 20),
               axis.title.y = element_text(angle = 90, color = 'black', size = 20))
p_overall_waist

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_waist <- ggplot(singvar_waist, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) + theme(text = element_text(size = 20)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Scaled PFAS plasma concentration") + scale_y_continuous(name = "Change in waist circ. (cm)")
p_singvar_waist

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_waist <- ggplot(overall_interact_waist, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) + theme(text = element_text(size = 20)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in waist circ. (cm)") +
  xlab("PFAS")
p_overall_interact_waist


### WAIST-TO-HIP-RATIO
p_overall_whr <- ggplot(overall_whr, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
               geom_pointrange() +
               scale_y_continuous(name = "Change in waist-to-hip ratio")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x = element_text(size = 20),
               axis.text.y = element_text(size = 20),
               axis.title.x = element_text(angle = 0, color = 'black', size = 20),
               axis.title.y = element_text(angle = 90, color = 'black', size = 20))
p_overall_whr

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_whr <- ggplot(singvar_whr, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) + theme(text = element_text(size = 20)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Scaled PFAS plasma concentration") + scale_y_continuous(name = "Change in waist-to-hip ratio")
p_singvar_whr

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_whr <- ggplot(overall_interact_whr, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) + theme(text = element_text(size = 20)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in waist-to-hip ratio") +
  xlab("PFAS")
p_overall_interact_whr


### MUAC
p_overall_muac <- ggplot(overall_muac, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
               geom_pointrange() +
               scale_y_continuous(name = "Change in MUAC (cm)")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x = element_text(size = 20),
               axis.text.y = element_text(size = 20),
               axis.title.x = element_text(angle = 0, color = 'black', size = 20),
               axis.title.y = element_text(angle = 90, color = 'black', size = 20))
p_overall_muac

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_muac <- ggplot(singvar_muac, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) + theme(text = element_text(size = 20)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Scaled PFAS plasma concentration") + scale_y_continuous(name = "Change in MUAC (cm)")
p_singvar_muac

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_muac <- ggplot(overall_interact_muac, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) + theme(text = element_text(size = 20)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in MUAC (cm)") +
  xlab("PFAS")
p_overall_interact_muac


### BODY FAT %
p_overall_bfat <- ggplot(overall_bfat, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
               geom_pointrange() +
               scale_y_continuous(name = "Change in body fat (%)")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x = element_text(size = 20),
               axis.text.y = element_text(size = 20),
               axis.title.x = element_text(angle = 0, color = 'black', size = 20),
               axis.title.y = element_text(angle = 90, color = 'black', size = 20))
p_overall_bfat

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_bfat <- ggplot(singvar_bfat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) + theme(text = element_text(size = 20)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Scaled PFAS plasma concentration") + scale_y_continuous(name = "Change in body fat (%)")
p_singvar_bfat

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_bfat <- ggplot(overall_interact_bfat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) + theme(text = element_text(size = 20)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in body fat (%)") +
  xlab("PFAS")
p_overall_interact_bfat


### BODY FAT MASS
p_overall_fat <- ggplot(overall_fat, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
               geom_pointrange() +
               scale_y_continuous(name = "Change in body fat mass (kg)")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x = element_text(size = 20),
               axis.text.y = element_text(size = 20),
               axis.title.x = element_text(angle = 0, color = 'black', size = 20),
               axis.title.y = element_text(angle = 90, color = 'black', size = 20))
p_overall_fat

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_fat <- ggplot(singvar_fat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) + theme(text = element_text(size = 20)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Scaled PFAS plasma concentration") + scale_y_continuous(name = "Change in body fat mass (kg)")
p_singvar_fat

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_fat <- ggplot(overall_interact_fat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) + theme(text = element_text(size = 20)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in body fat mass (kg)") +
  xlab("PFAS")
p_overall_interact_fat

```
