#####                                                        #####
##### CLEAN PFAS DATA SET AND ENFORCE ELIGIBILITY CRITERIA #####
#####                                                        #####

```{r}
##### LOAD PACKAGES
library("sas7bdat")
library("haven")
library("data.table")

```

```{r}
##### LOAD DATASET
PFAS <- read.sas7bdat("C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/ja_062922.sas7bdat")
BMI <- read.sas7bdat("C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/ja_071022.sas7bdat")
PFAS <- merge(BMI, PFAS, by = "aid", all.y = T)

PFAS[PFAS == "NaN"] <- NA
PFAS[PFAS == ""] <- NA

```


```{r}
##### DROP UNNECESSARY VARIABLES
#PFAS <- subset(PFASBP, select = c(aid, ga_days, mom_agey_bp, g_age_days_COLL_D_BLD1, sys, dias,  
#                                      Me_PFOSA_AcOH2, PFOA, PFHxS, PFNA2, PFOS, Et_PFOSA_AcOH,
#                                      bmi_mom_prepreg_d,  race2_mom_epi_epia_d,parity_d, coll_grad, 
#                                      gt70k, income_hh_epq_epqa_d, htn_rx_preg, t1diab_mom_epi_epia_d, 
#                                      t2diab_mom_epi_epia_d, highbp_mom_epi_epia_d,mod_pre_d, 
#                                      vig_pre_d, smokpreg_final_d,alc_d_f1,alc_d_bef_learn_f1, 
#                                      alc_d_aft_learn_f1, count))

```

```{r}
##### DETERMINE PFAS MISSINGNESS
summary(PFAS$PFOS)
summary(PFAS$PFOA)
summary(PFAS$PFOSA)
summary(PFAS$PFNA2)
summary(PFAS$PFHxS)
summary(PFAS$PFDeA)
summary(PFAS$Me_PFOSA_AcOH2)
summary(PFAS$Et_PFOSA_AcOH) # INDIVIDUALS ARE MISSING ALL OR NONE OF EACH PFAS (N = 483)

##### DETERMINE OUTCOME MISSINGNESS
summary(PFAS$VAT_AREA_mdxa17)
summary(PFAS$VAT_MASS_mdxa17)
summary(PFAS$VAT_VOLUME_mdxa17)
summary(PFAS$SAT_AREA_mdxa17)
summary(PFAS$SAT_MASS_mdxa17)
summary(PFAS$SAT_VOLUME_mdxa17)
summary(PFAS$TAT_AREA_mdxa17)
summary(PFAS$TAT_MASS_mdxa17)
summary(PFAS$TAT_VOLUME_mdxa17) # INDIVIDUALS ARE MISSING ALL OR NONE OF EACH DXA MEASURE (N = 1577)

summary(PFAS$WEIGHT_mdxa17) # 1577 MISSING
summary(PFAS$mom_bmi_MT) # 1424 MISSING
summary(PFAS$mom_waist_ma17) # 1419 MISSING
summary(PFAS$mom_hip_ma17) # 1420 MISSING
summary(PFAS$mom_bodyfat_ma17) # 1427 MISSING, BODY FAT %
summary(PFAS$mom_fat_ma17) # 1428 MISSING, BODY FAT MASS


##### EXCLUDE INELEGIBLE PARTICIPANTS
PFAS_1 <- subset(PFAS, !is.na(PFOS)) # MISSING 1ST OR 2ND TRIMESTER PFAS DATA (I.E., 22 WEEKS GESTATION)

table(PFAS_1$t1diab_mom_epi_epia_d)
table(PFAS_1$t2diab_mom_epi_epia_d)
PFAS_2 <- subset(PFAS_1, t1diab_mom_epi_epia_d == 2 | is.na(t1diab_mom_epi_epia_d)) # HISTORY OF T1 DIABETES
PFAS_2 <- subset(PFAS_2, t2diab_mom_epi_epia_d == 2 | is.na(t2diab_mom_epi_epia_d)) # HISTORY OF T2 DIABETES

PFAS_3 <- subset(PFAS_2, !is.na(mom_bmi_MT)) # MISSING BMI (N = 1076)
PFAS_4 <- subset(PFAS_3, !is.na(mom_waist_ma17)) # MISSING WAIST MEASUREMENT (N = 0)
PFAS_5 <- subset(PFAS_4, !is.na(mom_hip_ma17)) # MISSING HIP MEASUREMENT (N = 1)
PFAS_6 <- subset(PFAS_5, !is.na(mom_bodyfat_ma17)) # MISSING TOTAL BODY FAT % (N = 3)
PFAS_7 <- subset(PFAS_6, !is.na(mom_fat_ma17)) # MISSING BODY FAT MASS (N = 1)
PFAS_8 <- subset(PFAS_7, !is.na(WEIGHT_mdxa17)) # MISSING BODY WEIGHT (N = 1)

PFAS_9 <- subset(PFAS_8, !is.na(VAT_AREA_mdxa17)) # MISSING DXA MEASURES (N = 121)

```

```{r}
##### DROP UNNECESSARY VARIABLES
#PFAS_5 <- subset(PFASBP_5, select = -c(htn_rx_preg, t1diab_mom_epi_epia_d, t2diab_mom_epi_epia_d,
#                                     highbp_mom_epi_epia_d))

##### SAVE DATASET
write.csv(PFAS_6, "C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/PFAS_C.csv", row.names = T)
write_sas(PFAS_6, "C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/PFAS_C.sas7bdat")
# THE "C" AT THE END OF THE SAVED FILES INDICATES THAT THE DATASET IS CLEAN

```

