#####                                  #####
##### RUN MIXTURES ANALYSIS WITH BKMR  #####
#####                                  #####

```{r}
##### LOAD PACKAGES
library("bkmr")
library("ggplot2")
library("beepr")
library("tidyverse")

```

```{r}
##### LOAD DATASET
PFAS_AD <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/PFAS_AD.csv")

```

```{r}
##### TRANSFORMVARIABLES TO NUMERIC FOR BKMR COVARIATE MATRIX

# RENAME
PFAS_AD$age_enroll <- PFAS_AD$age_mom_enroll_d
PFAS_AD$race <- PFAS_AD$race2_mom_epi_epia_d
PFAS_AD$edu <- PFAS_AD$coll_grad
PFAS_AD$bmi <- PFAS_AD$bmi_mom_prepreg_d
PFAS_AD$smoke <- PFAS_AD$smokpreg_final_d
PFAS_AD$parity <- PFAS_AD$parity_d
PFAS_AD$married <- PFAS_AD$married_cohab

# REFACTOR AND RELABEL 
PFAS_AD$race <- ifelse(PFAS_AD$race == "white", 0,
                     ifelse(PFAS_AD$race == "black", 1,
                     ifelse(PFAS_AD$race == "hispa", 2,
                     ifelse(PFAS_AD$race == "asian", 3,
                     ifelse(PFAS_AD$race == "other", 4, 4)))))
PFAS_AD$edu <- ifelse(PFAS_AD$edu == 1, 1, 0)
PFAS_AD$bmi_cat <- ifelse(PFAS_AD$bmi <18.5, 0,
                         ifelse(PFAS_AD$bmi >=18.5 & PFAS_AD$bmi < 25.0, 1, 
                         ifelse(PFAS_AD$bmi >=25.0 & PFAS_AD$bmi < 30.0, 2, 
                         ifelse(PFAS_AD$bmi >=30.0 & PFAS_AD$bmi < 35.0, 3,
                         ifelse(PFAS_AD$bmi >=35.0, 4, 99)))))
PFAS_AD$smoke <- ifelse(PFAS_AD$smoke == "former", 0,
                         ifelse(PFAS_AD$smoke == "smoke preg", 1,
                         ifelse(PFAS_AD$smoke == "xnever", 2, 2)))
PFAS_AD$parity <- ifelse(PFAS_AD$parity == 0, 0,
                        ifelse(PFAS_AD$parity == 1, 1,
                        ifelse(PFAS_AD$parity > 1, 2, 0)))
PFAS_AD$married <- ifelse(PFAS_AD$married == 1, 1, 0)

# SET CATEGORICAL VARIABLES AS FACTORS
PFAS_AD$edu <- as.factor(PFAS_AD$edu)
PFAS_AD$bmi_cat <- as.factor(PFAS_AD$bmi_cat)
PFAS_AD$smoke <- as.factor(PFAS_AD$smoke)
PFAS_AD$parity <- as.factor(PFAS_AD$parity)
PFAS_AD$race <- as.factor(PFAS_AD$race)
PFAS_AD$married <- as.factor(PFAS_AD$married)

# CENTER AND SCALE CONTINUOUS VARIABLES
PFAS_AD$age_enroll <- scale(PFAS_AD$age_enroll)

```


```{r}
##### PREPARE VARIABLES FOR BKMR MODELS #####
##### ANTHRO + DXA DATASET (N = 429)

# CREATE MIXTURE OF PFAS
mixture_ad <- as.matrix(cbind(PFAS_AD$PFOS, PFAS_AD$PFOA, PFAS_AD$PFNA, PFAS_AD$PFHxS, 
                              PFAS_AD$MeFOSSA, PFAS_AD$EtFOSSA))

# LN-TRANSFORM MIXTURE
lnmixture_ad <- apply(mixture_ad, 2, log)     

# SCALE MIXTURE VARIABLES TO THE MEAN
lnmixture_ad_z <- scale(lnmixture_ad)

# SET THE OUTCOME
VAT_A <- PFAS_AD$LNVAT_AREA
SAAT_A <- PFAS_AD$LNSAT_AREA
TAAT_A <- PFAS_AD$LNTAT_AREA
VAT_M <- PFAS_AD$LNVAT_MASS
SAAT_M <- PFAS_AD$LNSAT_MASS
TAAT_M <- PFAS_AD$LNTAT_MASS
VAT_V <- PFAS_AD$LNVAT_VOLUME
SAAT_V <- PFAS_AD$LNSAT_VOLUME
TAAT_V <- PFAS_AD$LNTAT_VOLUME
BMI_ad <- PFAS_AD$BMI
Weight_ad <- PFAS_AD$Weight
Waist_ad <- PFAS_AD$Waist
Hip_ad <- PFAS_AD$Hip
MUAC_ad <- PFAS_AD$MUAC
FatPct_ad <- PFAS_AD$FatPct
FatMass_ad <- PFAS_AD$FatMass

# CREAT THE COVARIATE MATRIX
cov_ad <- as.matrix(cbind(PFAS_AD$age_enroll, PFAS_AD$race, PFAS_AD$bmi_cat, PFAS_AD$edu, 
                       PFAS_AD$smoke, PFAS_AD$parity, PFAS_AD$married))

# SET THE SEED
set.seed(127)

# CREATE KNOTS
knots_ad <- fields::cover.design(lnmixture_ad_z, nd = 40)$design

```

```{r}
##### BUILD BKMR MODELS
# VAT AREA 
m_ad_vata <- kmbayes(y = VAT_A, Z = lnmixture_ad_z, X = cov_ad, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_ad)
beep(sound=5, expr=NULL)

# SAAAT AREA 
m_ad_saata <- kmbayes(y = SAAT_A, Z = lnmixture_ad_z, X = cov_ad, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_ad)
beep(sound=5, expr=NULL)

# TAAT AREA 
m_ad_taata <- kmbayes(y = TAAT_A, Z = lnmixture_ad_z, X = cov_ad, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_ad)
beep(sound=5, expr=NULL)

# VAT MASS 
m_ad_vatm <- kmbayes(y = VAT_M, Z = lnmixture_ad_z, X = cov_ad, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_ad)
beep(sound=5, expr=NULL)

# SAAAT MASS 
m_ad_saatm <- kmbayes(y = SAAT_M, Z = lnmixture_ad_z, X = cov_ad, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_ad)
beep(sound=5, expr=NULL)

# TAAT MASS 
m_ad_taatm <- kmbayes(y = TAAT_M, Z = lnmixture_ad_z, X = cov_ad, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_ad)
beep(sound=5, expr=NULL)

# VAT VOLUME 
m_ad_vatv <- kmbayes(y = VAT_V, Z = lnmixture_ad_z, X = cov_ad, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_ad)
beep(sound=5, expr=NULL)

# SAAAT VOLUME 
m_ad_saatv <- kmbayes(y = SAAT_V, Z = lnmixture_ad_z, X = cov_ad, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_ad)
beep(sound=5, expr=NULL)

# TAAT VOLUME 
m_ad_taatv <- kmbayes(y = TAAT_V, Z = lnmixture_ad_z, X = cov_ad, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_ad)
beep(sound=5, expr=NULL)

# BMI
m_ad_bmi <- kmbayes(y = BMI_ad, Z = lnmixture_ad_z, X = cov_ad, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_ad)
beep(sound=5, expr=NULL)

# WEIGHT
m_ad_wt <- kmbayes(y = Weight_ad, Z = lnmixture_ad_z, X = cov_ad, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_ad)
beep(sound=5, expr=NULL)

# WAIST CIRCUMFERENCE
m_ad_waist <- kmbayes(y = Waist_ad, Z = lnmixture_ad_z, X = cov_ad, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_ad)
beep(sound=5, expr=NULL)

# HIP CIRCUMFERENCE
m_ad_hip <- kmbayes(y = Hip_ad, Z = lnmixture_ad_z, X = cov_ad, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_ad)
beep(sound=5, expr=NULL)

# MUAC
m_ad_muac <- kmbayes(y = MUAC_ad, Z = lnmixture_ad_z, X = cov_ad, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_ad)
beep(sound=5, expr=NULL)

# BODY FAT %
m_ad_bfat <- kmbayes(y = FatPct_ad, Z = lnmixture_ad_z, X = cov_ad, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_ad)
beep(sound=5, expr=NULL)

# BODY FAT MASS
m_ad_fat <- kmbayes(y = FatMass_ad, Z = lnmixture_ad_z, X = cov_ad, iter=25000, family = "gaussian", 
                     verbose = FALSE, varsel = TRUE, knots = knots_ad)
beep(sound=5, expr=NULL)

```

```{r}
##### VALUES TO KEEP AFTER BURIN/THIN
#
sel <- seq(0,25000,by = 50)

##### ACCESS CONVERGENCE WITH TRACEPLOTS
TracePlot(fit = m_ad_vata, par = "beta", sel = sel)
TracePlot(fit = m_ad_saata, par = "beta", sel = sel)
TracePlot(fit = m_ad_taata, par = "beta", sel = sel)
TracePlot(fit = m_ad_vatm, par = "beta", sel = sel)
TracePlot(fit = m_ad_saatm, par = "beta", sel = sel)
TracePlot(fit = m_ad_taatm, par = "beta", sel = sel)
TracePlot(fit = m_ad_vatv, par = "beta", sel = sel)
TracePlot(fit = m_ad_saatv, par = "beta", sel = sel)
TracePlot(fit = m_ad_taatv, par = "beta", sel = sel)
TracePlot(fit = m_ad_bmi, par = "beta", sel = sel)
TracePlot(fit = m_ad_wt, par = "beta", sel = sel)
TracePlot(fit = m_ad_waist, par = "beta", sel = sel)
TracePlot(fit = m_ad_hip, par = "beta", sel = sel)
TracePlot(fit = m_ad_muac, par = "beta", sel = sel)
TracePlot(fit = m_ad_bfat, par = "beta", sel = sel)
TracePlot(fit = m_ad_fat, par = "beta", sel = sel)

##### VALUES TO KEEP AFTER BURNING/THIN (ACCORDING TO THE TRACEPLOT FUNCTION ABOVE)
sel_final <- seq(1200, 25000, by = 1)

```

```{r}
##### ESIMATE POSTERIOR INCLUSION PROBABILITIES
# VAT AREA
summary(m_ad_vata)
ExtractPIPs(m_ad_vata, sel = sel_final)

# SAAT AREA
summary(m_ad_saata)
ExtractPIPs(m_ad_saata, sel = sel_final)

# TAAT AREA
summary(m_ad_taata)
ExtractPIPs(m_ad_taata, sel = sel_final)

# VAT MASS
summary(m_ad_vatm)
ExtractPIPs(m_ad_vatm, sel = sel_final)

# SAAT MASS
summary(m_ad_saatm)
ExtractPIPs(m_ad_saatm, sel = sel_final)

# TAAT MASS
summary(m_ad_taatm)
ExtractPIPs(m_ad_taatm, sel = sel_final)

# VAT VOLUME
summary(m_ad_vatv)
ExtractPIPs(m_ad_vatv, sel = sel_final)

# SAAT VOLUME
summary(m_ad_saatv)
ExtractPIPs(m_ad_saatv, sel = sel_final)

# TAAT VOLUME
summary(m_ad_taatv)
ExtractPIPs(m_ad_taatv, sel = sel_final)

# BMI
summary(m_ad_bmi)
ExtractPIPs(m_ad_bmi, sel = sel_final)

# WEIGHT
summary(m_ad_wt)
ExtractPIPs(m_ad_wt, sel = sel_final)

# WAIST CIRCUMFERENCE
summary(m_ad_waist)
ExtractPIPs(m_ad_waist, sel = sel_final)

# HIP CIRCUMFERENCE
summary(m_ad_hip)
ExtractPIPs(m_ad_hip, sel = sel_final)

# MUAC
summary(m_ad_muac)
ExtractPIPs(m_ad_muac, sel = sel_final)

# BODT FAT %
summary(m_ad_bfat)
ExtractPIPs(m_ad_bfat, sel = sel_final)

# BODY FAT MASS
summary(m_ad_fat)
ExtractPIPs(m_ad_fat, sel = sel_final)

```

```{r}
##### PREDICT UNIVARIATE EXPOSURE-RESPONSE FUNCTION
# VAT AREA
univar_ad_vata <- PredictorResponseUnivar(fit = m_ad_vata, sel = sel_final, method = "approx")
univar_ad_vata

# SAAT AREA
univar_ad_saata <- PredictorResponseUnivar(fit = m_ad_saata, sel = sel_final, method = "approx")
univar_ad_saata

# TAAT AREA
univar_ad_taata <- PredictorResponseUnivar(fit = m_ad_taata, sel = sel_final, method = "approx")
univar_ad_taata

# VAT MASS
univar_ad_vatm <- PredictorResponseUnivar(fit = m_ad_vatm, sel = sel_final, method = "approx")
univar_ad_vatm

# SAAT MASS
univar_ad_saatm <- PredictorResponseUnivar(fit = m_ad_saatm, sel = sel_final, method = "approx")
univar_ad_saatm

# TAAT MASS
univar_ad_taatm <- PredictorResponseUnivar(fit = m_ad_taatm, sel = sel_final, method = "approx")
univar_ad_taatm

# VAT VOLUME
univar_ad_vata <- PredictorResponseUnivar(fit = m_ad_vata, sel = sel_final, method = "approx")
univar_ad_vata

# SAAT VOLUME
univar_ad_saatv <- PredictorResponseUnivar(fit = m_ad_saatv, sel = sel_final, method = "approx")
univar_ad_saatv

# TAAT VOLUME
univar_ad_taatv <- PredictorResponseUnivar(fit = m_ad_taatv, sel = sel_final, method = "approx")
univar_ad_taatv

# BMI
univar_ad_bmi <- PredictorResponseUnivar(fit = m_ad_bmi, sel = sel_final, method = "approx")
univar_ad_bmi

# WEIGHT
univar_ad_wt <- PredictorResponseUnivar(fit = m_ad_wt, sel = sel_final, method = "approx")
univar_ad_wt

# WAIST CIRCUMFERENCE
univar_ad_waist <- PredictorResponseUnivar(fit = m_ad_waist, sel = sel_final, method = "approx")
univar_ad_waist

# HIP CIRCUMFERENCE
univar_ad_hip <- PredictorResponseUnivar(fit = m_ad_hip, sel = sel_final, method = "approx")
univar_ad_hip

# MUAC
univar_ad_muac <- PredictorResponseUnivar(fit = m_ad_muac, sel = sel_final, method = "approx")
univar_ad_muac

# BODY FAT %
univar_ad_bfat <- PredictorResponseUnivar(fit = m_ad_bfat, sel = sel_final, method = "approx")
univar_ad_bfat

# BODY FAT MASS
univar_ad_fat <- PredictorResponseUnivar(fit = m_ad_fat, sel = sel_final, method = "approx")
univar_ad_fat


##### PLOT UNIVARIATE EXPOSURE-RESPONSE FUNCTION
# VAT AREA
uni_ad_vata <- ggplot(univar_ad_vata, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Serum ln-transformed concentration") + ylab("Difference in BMI (kg/m^2)")

uni1_ad_vata <- ggplot(univar_ad_vata[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOS concentration") + ylab("Difference in BMI (kg/m^2)")

uni2_ad_vata <- ggplot(univar_ad_vata[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOA concentration") + ylab("Difference in BMI (kg/m^2)")

uni3_ad_vata <- ggplot(univar_ad_vata[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFNA concentration") + ylab("Difference in BMI (kg/m^2)")

uni4_ad_vata <- ggplot(univar_ad_vata[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFHxS concentration") + ylab("Difference in BMI (kg/m^2)")

uni5_ad_vata <- ggplot(univar_ad_vata[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-MeFOSSA concentration") + ylab("Difference in BMI (kg/m^2)")

uni6_ad_vata <- ggplot(univar_ad_vata[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-EtFOSSA concentration") + ylab("Difference in BMI (kg/m^2)")

uni_ad_vata
uni1_ad_vata
uni2_ad_vata
uni3_ad_vata
uni4_ad_vata
uni5_ad_vata
uni6_ad_vata

# SAAT AREA
uni_ad_saata <- ggplot(univar_ad_saata, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Serum ln-transformed concentration") + ylab("Difference in BMI (kg/m^2)")

uni1_ad_saata <- ggplot(univar_ad_saata[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOS concentration") + ylab("Difference in BMI (kg/m^2)")

uni2_ad_saata <- ggplot(univar_ad_saata[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOA concentration") + ylab("Difference in BMI (kg/m^2)")

uni3_ad_saata <- ggplot(univar_ad_saata[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFNA concentration") + ylab("Difference in BMI (kg/m^2)")

uni4_ad_saata <- ggplot(univar_ad_saata[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFHxS concentration") + ylab("Difference in BMI (kg/m^2)")

uni5_ad_saata <- ggplot(univar_ad_saata[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-MeFOSSA concentration") + ylab("Difference in BMI (kg/m^2)")

uni6_ad_saata <- ggplot(univar_ad_saata[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-EtFOSSA concentration") + ylab("Difference in BMI (kg/m^2)")

uni_ad_saata
uni1_ad_saata
uni2_ad_saata
uni3_ad_saata
uni4_ad_saata
uni5_ad_saata
uni6_ad_saata

# TAAT AREA
uni_ad_taata <- ggplot(univar_ad_taata, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Serum ln-transformed concentration") + ylab("Difference in BMI (kg/m^2)")

uni1_ad_taata <- ggplot(univar_ad_taata[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOS concentration") + ylab("Difference in BMI (kg/m^2)")

uni2_ad_taata <- ggplot(univar_ad_taata[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOA concentration") + ylab("Difference in BMI (kg/m^2)")

uni3_ad_taata <- ggplot(univar_ad_taata[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFNA concentration") + ylab("Difference in BMI (kg/m^2)")

uni4_ad_taata <- ggplot(univar_ad_taata[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFHxS concentration") + ylab("Difference in BMI (kg/m^2)")

uni5_ad_taata <- ggplot(univar_ad_taata[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-MeFOSSA concentration") + ylab("Difference in BMI (kg/m^2)")

uni6_ad_taata <- ggplot(univar_ad_taata[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-EtFOSSA concentration") + ylab("Difference in BMI (kg/m^2)")

uni_ad_taata
uni1_ad_taata
uni2_ad_taata
uni3_ad_taata
uni4_ad_taata
uni5_ad_taata
uni6_ad_taata

# VAT MASS
uni_ad_vatm <- ggplot(univar_ad_vatm, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Serum ln-transformed concentration") + ylab("Difference in BMI (kg/m^2)")

uni1_ad_vatm <- ggplot(univar_ad_vatm[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOS concentration") + ylab("Difference in BMI (kg/m^2)")

uni2_ad_vatm <- ggplot(univar_ad_vatm[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOA concentration") + ylab("Difference in BMI (kg/m^2)")

uni3_ad_vatm <- ggplot(univar_ad_vatm[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFNA concentration") + ylab("Difference in BMI (kg/m^2)")

uni4_ad_vatm <- ggplot(univar_ad_vatm[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFHxS concentration") + ylab("Difference in BMI (kg/m^2)")

uni5_ad_vatm <- ggplot(univar_ad_vatm[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-MeFOSSA concentration") + ylab("Difference in BMI (kg/m^2)")

uni6_ad_vatm <- ggplot(univar_ad_vatm[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-EtFOSSA concentration") + ylab("Difference in BMI (kg/m^2)")

uni_ad_vatm
uni1_ad_vatm
uni2_ad_vatm
uni3_ad_vatm
uni4_ad_vatm
uni5_ad_vatm
uni6_ad_vatm

# SAAT MASS
uni_ad_saatm <- ggplot(univar_ad_saatm, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Serum ln-transformed concentration") + ylab("Difference in BMI (kg/m^2)")

uni1_ad_saatm <- ggplot(univar_ad_saatm[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOS concentration") + ylab("Difference in BMI (kg/m^2)")

uni2_ad_saatm <- ggplot(univar_ad_saatm[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOA concentration") + ylab("Difference in BMI (kg/m^2)")

uni3_ad_saatm <- ggplot(univar_ad_saatm[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFNA concentration") + ylab("Difference in BMI (kg/m^2)")

uni4_ad_saatm <- ggplot(univar_ad_saatm[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFHxS concentration") + ylab("Difference in BMI (kg/m^2)")

uni5_ad_saatm <- ggplot(univar_ad_saatm[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-MeFOSSA concentration") + ylab("Difference in BMI (kg/m^2)")

uni6_ad_saatm <- ggplot(univar_ad_saatm[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-EtFOSSA concentration") + ylab("Difference in BMI (kg/m^2)")

uni_ad_saatm
uni1_ad_saatm
uni2_ad_saatm
uni3_ad_saatm
uni4_ad_saatm
uni5_ad_saatm
uni6_ad_saatm

# TAAT MASS
uni_ad_taatm <- ggplot(univar_ad_taatm, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Serum ln-transformed concentration") + ylab("Difference in BMI (kg/m^2)")

uni1_ad_taatm <- ggplot(univar_ad_taatm[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOS concentration") + ylab("Difference in BMI (kg/m^2)")

uni2_ad_taatm <- ggplot(univar_ad_taatm[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOA concentration") + ylab("Difference in BMI (kg/m^2)")

uni3_ad_taatm <- ggplot(univar_ad_taatm[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFNA concentration") + ylab("Difference in BMI (kg/m^2)")

uni4_ad_taatm <- ggplot(univar_ad_taatm[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFHxS concentration") + ylab("Difference in BMI (kg/m^2)")

uni5_ad_taatm <- ggplot(univar_ad_taatm[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-MeFOSSA concentration") + ylab("Difference in BMI (kg/m^2)")

uni6_ad_taatm <- ggplot(univar_ad_taatm[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-EtFOSSA concentration") + ylab("Difference in BMI (kg/m^2)")

uni_ad_taatm
uni1_ad_taatm
uni2_ad_taatm
uni3_ad_taatm
uni4_ad_taatm
uni5_ad_taatm
uni6_ad_taatm

# VAT VOLUME
uni_ad_vatv <- ggplot(univar_ad_vatv, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Serum ln-transformed concentration") + ylab("Difference in BMI (kg/m^2)")

uni1_ad_vatv <- ggplot(univar_ad_vatv[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOS concentration") + ylab("Difference in BMI (kg/m^2)")

uni2_ad_vatv <- ggplot(univar_ad_vatv[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOA concentration") + ylab("Difference in BMI (kg/m^2)")

uni3_ad_vatv <- ggplot(univar_ad_vatv[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFNA concentration") + ylab("Difference in BMI (kg/m^2)")

uni4_ad_vatv <- ggplot(univar_ad_vatv[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFHxS concentration") + ylab("Difference in BMI (kg/m^2)")

uni5_ad_vatv <- ggplot(univar_ad_vatv[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-MeFOSSA concentration") + ylab("Difference in BMI (kg/m^2)")

uni6_ad_vatv <- ggplot(univar_ad_vatv[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-EtFOSSA concentration") + ylab("Difference in BMI (kg/m^2)")

uni_ad_vatv
uni1_ad_vatv
uni2_ad_vatv
uni3_ad_vatv
uni4_ad_vatv
uni5_ad_vatv
uni6_ad_vatv

# SAAT VOLUME
uni_ad_saatv <- ggplot(univar_ad_saatv, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Serum ln-transformed concentration") + ylab("Difference in BMI (kg/m^2)")

uni1_ad_saatv <- ggplot(univar_ad_saatv[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOS concentration") + ylab("Difference in BMI (kg/m^2)")

uni2_ad_saatv <- ggplot(univar_ad_saatv[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOA concentration") + ylab("Difference in BMI (kg/m^2)")

uni3_ad_saatv <- ggplot(univar_ad_saatv[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFNA concentration") + ylab("Difference in BMI (kg/m^2)")

uni4_ad_saatv <- ggplot(univar_ad_saatv[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFHxS concentration") + ylab("Difference in BMI (kg/m^2)")

uni5_ad_saatv <- ggplot(univar_ad_saatv[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-MeFOSSA concentration") + ylab("Difference in BMI (kg/m^2)")

uni6_ad_saatv <- ggplot(univar_ad_saatv[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-EtFOSSA concentration") + ylab("Difference in BMI (kg/m^2)")

uni_ad_saatv
uni1_ad_saatv
uni2_ad_saatv
uni3_ad_saatv
uni4_ad_saatv
uni5_ad_saatv
uni6_ad_saatv

# TAAT VOLUME
uni_ad_taatv <- ggplot(univar_ad_taatv, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Serum ln-transformed concentration") + ylab("Difference in BMI (kg/m^2)")

uni1_ad_taatv <- ggplot(univar_ad_taatv[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOS concentration") + ylab("Difference in BMI (kg/m^2)")

uni2_ad_taatv <- ggplot(univar_ad_taatv[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOA concentration") + ylab("Difference in BMI (kg/m^2)")

uni3_ad_taatv <- ggplot(univar_ad_taatv[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFNA concentration") + ylab("Difference in BMI (kg/m^2)")

uni4_ad_taatv <- ggplot(univar_ad_taatv[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFHxS concentration") + ylab("Difference in BMI (kg/m^2)")

uni5_ad_taatv <- ggplot(univar_ad_taatv[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-MeFOSSA concentration") + ylab("Difference in BMI (kg/m^2)")

uni6_ad_taatv <- ggplot(univar_ad_taatv[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-EtFOSSA concentration") + ylab("Difference in BMI (kg/m^2)")

uni_ad_taatv
uni1_ad_taatv
uni2_ad_taatv
uni3_ad_taatv
uni4_ad_taatv
uni5_ad_taatv
uni6_ad_taatv

# BMI
uni_ad_bmi <- ggplot(univar_ad_bmi, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Serum ln-transformed concentration") + ylab("Difference in BMI (kg/m^2)")

uni1_ad_bmi <- ggplot(univar_ad_bmi[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOS concentration") + ylab("Difference in BMI (kg/m^2)")

uni2_ad_bmi <- ggplot(univar_ad_bmi[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOA concentration") + ylab("Difference in BMI (kg/m^2)")

uni3_ad_bmi <- ggplot(univar_ad_bmi[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFNA concentration") + ylab("Difference in BMI (kg/m^2)")

uni4_ad_bmi <- ggplot(univar_ad_bmi[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFHxS concentration") + ylab("Difference in BMI (kg/m^2)")

uni5_ad_bmi <- ggplot(univar_ad_bmi[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-MeFOSSA concentration") + ylab("Difference in BMI (kg/m^2)")

uni6_ad_bmi <- ggplot(univar_ad_bmi[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-EtFOSSA concentration") + ylab("Difference in BMI (kg/m^2)")

uni_ad_bmi
uni1_ad_bmi
uni2_ad_bmi
uni3_ad_bmi
uni4_ad_bmi
uni5_ad_bmi
uni6_ad_bmi


# WEIGHT
uni_ad_wt <- ggplot(univar_ad_wt, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Serum ln-transformed concentration") + ylab("Difference in weight (kg)")

uni1_ad_wt <- ggplot(univar_ad_wt[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOS concentration") + ylab("Difference in weight (kg)")

uni2_ad_wt <- ggplot(univar_ad_wt[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOA concentration") + ylab("Difference in weight (kg)")

uni3_ad_wt <- ggplot(univar_ad_wt[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFNA concentration") + ylab("Difference in weight (kg)")

uni4_ad_wt <- ggplot(univar_ad_wt[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFHxS concentration") + ylab("Difference in weight (kg)")

uni5_ad_wt <- ggplot(univar_ad_wt[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-MeFOSSA concentration") + ylab("Difference in weight (kg)")

uni6_ad_wt <- ggplot(univar_ad_wt[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-EtFOSSA concentration") + ylab("Difference in weight (kg)")

uni_ad_wt
uni1_ad_wt
uni2_ad_wt
uni3_ad_wt
uni4_ad_wt
uni5_ad_wt
uni6_ad_wt


# WAIST CIRCUMFERENCE
uni_ad_waist <- ggplot(univar_ad_waist, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Serum ln-transformed concentration") + ylab("Difference in waist circumference (cm)")

uni1_ad_waist <- ggplot(univar_ad_waist[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOS concentration") + ylab("Difference in waist circumference (cm)")

uni2_ad_waist <- ggplot(univar_ad_waist[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOA concentration") + ylab("Difference in waist circumference (cm)")

uni3_ad_waist <- ggplot(univar_ad_waist[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFNA concentration") + ylab("Difference in waist circumference (cm)")

uni4_ad_waist <- ggplot(univar_ad_waist[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFHxS concentration") + ylab("Difference in waist circumference (cm)")

uni5_ad_waist <- ggplot(univar_ad_waist[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-MeFOSSA concentration") + ylab("Difference in waist circumference (cm)")

uni6_ad_waist <- ggplot(univar_ad_waist[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-EtFOSSA concentration") + ylab("Difference in waist circumference (cm)")

uni_ad_waist
uni1_ad_waist
uni2_ad_waist
uni3_ad_waist
uni4_ad_waist
uni5_ad_waist
uni6_ad_waist


# HIP CIRCUMFERENCE
uni_ad_hip <- ggplot(univar_ad_hip, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Serum ln-transformed concentration") + ylab("Difference in hip circumference (cm)")

uni1_ad_hip <- ggplot(univar_ad_hip[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOS concentration") + ylab("Difference in hip circumference (cm)")

uni2_ad_hip <- ggplot(univar_ad_hip[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOA concentration") + ylab("Difference in hip circumference (cm)")

uni3_ad_hip <- ggplot(univar_ad_hip[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFNA concentration") + ylab("Difference in hip circumference (cm)")

uni4_ad_hip <- ggplot(univar_ad_hip[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFHxS concentration") + ylab("Difference in hip circumference (cm)")

uni5_ad_hip <- ggplot(univar_ad_hip[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-MeFOSSA concentration") + ylab("Difference in hip circumference (cm)")

uni6_ad_hip <- ggplot(univar_ad_hip[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-EtFOSSA concentration") + ylab("Difference in hip circumference (cm)")

uni_ad_hip
uni1_ad_hip
uni2_ad_hip
uni3_ad_hip
uni4_ad_hip
uni5_ad_hip
uni6_ad_hip


# MUAC
uni_ad_muac <- ggplot(univar_ad_muac, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Serum ln-transformed concentration") + ylab("Difference in MUAC (cm)")

uni1_ad_muac <- ggplot(univar_ad_muac[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOS concentration") + ylab("Difference in MUAC (cm)")

uni2_ad_muac <- ggplot(univar_ad_muac[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOA concentration") + ylab("Difference in MUAC (cm)")

uni3_ad_muac <- ggplot(univar_ad_muac[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFNA concentration") + ylab("Difference in MUAC (cm)")

uni4_ad_muac <- ggplot(univar_ad_muac[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFHxS concentration") + ylab("Difference in MUAC (cm)")

uni5_ad_muac <- ggplot(univar_ad_muac[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-MeFOSSA concentration") + ylab("Difference in MUAC (cm)")

uni6_ad_muac <- ggplot(univar_ad_muac[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-EtFOSSA concentration") + ylab("Difference in MUAC (cm)")

uni_ad_muac
uni1_ad_muac
uni2_ad_muac
uni3_ad_muac
uni4_ad_muac
uni5_ad_muac
uni6_ad_muac


# BODY FAT %
uni_ad_bfat <- ggplot(univar_ad_bfat, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Serum ln-transformed concentration") + ylab("Difference in body fat (%)")

uni1_ad_bfat <- ggplot(univar_ad_bfat[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOS concentration") + ylab("Difference in body fat (%)")

uni2_ad_bfat <- ggplot(univar_ad_bfat[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOA concentration") + ylab("Difference in body fat (%)")

uni3_ad_bfat <- ggplot(univar_ad_bfat[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFNA concentration") + ylab("Difference in body fat (%)")

uni4_ad_bfat <- ggplot(univar_ad_bfat[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFHxS concentration") + ylab("Difference in body fat (%)")

uni5_ad_bfat <- ggplot(univar_ad_bfat[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-MeFOSSA concentration") + ylab("Difference in body fat (%)")

uni6_ad_bfat <- ggplot(univar_ad_bfat[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-EtFOSSA concentration") + ylab("Difference in body fat (%)")

uni_ad_bfat
uni1_ad_bfat
uni2_ad_bfat
uni3_ad_bfat
uni4_ad_bfat
uni5_ad_bfat
uni6_ad_bfat


# BODY FAT MASS
uni_ad_fat <- ggplot(univar_ad_fat, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity") + xlab("Serum ln-transformed concentration") + ylab("Difference in body fat (kg/m^2)")

uni1_ad_fat <- ggplot(univar_ad_fat[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOS concentration") + ylab("Difference in body fat (kg/m^2)")

uni2_ad_fat <- ggplot(univar_ad_fat[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFOA concentration") + ylab("Difference in body fat (kg/m^2)")

uni3_ad_fat <- ggplot(univar_ad_fat[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFNA concentration") + ylab("Difference in body fat (kg/m^2)")

uni4_ad_fat <- ggplot(univar_ad_fat[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-PFHxS concentration") + ylab("Difference in body fat (kg/m^2)")

uni5_ad_fat <- ggplot(univar_ad_fat[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-MeFOSSA concentration") + ylab("Difference in body fat (kg/m^2)")

uni6_ad_fat <- ggplot(univar_ad_fat[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Scaled ln-EtFOSSA concentration") + ylab("Difference in body fat (kg/m^2)")

uni_ad_fat
uni1_ad_fat
uni2_ad_fat
uni3_ad_fat
uni4_ad_fat
uni5_ad_fat
uni6_ad_fat

```


*** LEFT OFF HERE ****



```{r}
##### PREDICT BIVARIATE EXPOSURE-RESPONSE CURVE TO ASSESS POTENTIAL INTERACTIONS
##### SUBESQUENTLY, PREDICT INTERACTIONS AMONG PFAS
# BMI
bivar_ad_bmi <- PredictorResponseBivar(fit = m_ad_bmi, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_ad_bmi <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_bmi, Z = lnmixture_ad_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_ad_bmi_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_bmi, Z = lnmixture_ad_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# WEIGHT
bivar_ad_wt <- PredictorResponseBivar(fit = m_ad_wt, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_ad_wt <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_wt, Z = lnmixture_ad_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_ad_wt_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_wt, Z = lnmixture_ad_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# WAIST CIRCUMFERENCE
bivar_ad_waist <- PredictorResponseBivar(fit = m_ad_waist, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_ad_waist <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_waist, Z = lnmixture_ad_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_ad_waist_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_waist, Z = lnmixture_ad_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# HIP CIRCUMFERENCE
bivar_ad_hip <- PredictorResponseBivar(fit = m_ad_hip, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_ad_hip <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_hip, Z = lnmixture_ad_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_ad_hip_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_hip, Z = lnmixture_ad_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# MUAC
bivar_ad_muac <- PredictorResponseBivar(fit = m_ad_muac, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_ad_muac <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_muac, Z = lnmixture_ad_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_ad_muac_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_muac, Z = lnmixture_ad_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# BODY FAT %
bivar_ad_bfat <- PredictorResponseBivar(fit = m_ad_bfat, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_ad_bfat <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_bfat, Z = lnmixture_ad_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_ad_bfat_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_bfat, Z = lnmixture_ad_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# BODY FAT MASS
bivar_ad_fat <- PredictorResponseBivar(fit = m_ad_fat, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_ad_fat <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_fat, Z = lnmixture_ad_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_ad_fat_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_ad_fat, Z = lnmixture_ad_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))



##### PLOT INTERACTIONS BETWEEN EXPOSURE AND RESPONSE
##### NON-PARALLEL LINES WOULD INDICATE POTENTIAL INTERACTIONS
# BMI
p_interact_ad_bmi <- ggplot(interact_ad_bmi, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("Ln-transformed PFAS 1") +
  ylab ("Difference in BMI (kg/m^2)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_vat

# WEIGHT
p_interact_ad_wt <- ggplot(interact_ad_wt, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("Ln-transformed PFAS 1") +
  ylab ("Difference in weight (kg)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_vat

# WAIST
p_interact_ad_waist <- ggplot(interact_ad_waist, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("Ln-transformed PFAS 1") +
  ylab ("Difference in waist circumference (cm)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_vat

# HIP
p_interact_ad_hip <- ggplot(interact_ad_hip, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("Ln-transformed PFAS 1") +
  ylab ("Difference in hip circumference (cm)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_vat

# MUAC
p_interact_ad_muac <- ggplot(interact_ad_muac, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("Ln-transformed PFAS 1") +
  ylab ("Difference in MUAC (cm)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_vat

# BODY FAT %
p_interact_ad_bfat <- ggplot(interact_ad_bfat, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("Ln-transformed PFAS 1") +
  ylab ("Difference in bofy fat (%)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_vat

# BODY FAT MASS
p_interact_ad_fat <- ggplot(interact_ad_fat, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("Ln-transformed PFAS 1") +
  ylab ("Difference in body fat (kg/m^2)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_vat

```

```{r}
##### DETERMINE RISK ASSOCIATED WITH THE OVERALL MIXTURE
##### SUBSEQUENTLY, ESTIMATE RISK FOR SINGLE PFAS AND INTERACTIONS AMONG PFAS
# BMI
overall_ad_bmi <- OverallRiskSummaries(fit = m_ad_bmi, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_ad_bmi <- SingVarRiskSummaries(fit = m_ad_bmi, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_ad_bmi <- SingVarIntSummaries(fit = m_ad_bmi, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)

# WEIGHT
overall_ad_wt <- OverallRiskSummaries(fit = m_ad_wt, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_ad_wt <- SingVarRiskSummaries(fit = m_ad_wt, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_ad_wt <- SingVarIntSummaries(fit = m_ad_wt, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)

# WAIST CIRCUMFERENCE
overall_ad_waist <- OverallRiskSummaries(fit = m_ad_waist, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_ad_waist <- SingVarRiskSummaries(fit = m_ad_waist, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_ad_waist <- SingVarIntSummaries(fit = m_ad_waist, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)

# HIP CIRCUMFERENCE
overall_ad_hip <- OverallRiskSummaries(fit = m_ad_hip, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_ad_hip <- SingVarRiskSummaries(fit = m_ad_hip, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_ad_hip <- SingVarIntSummaries(fit = m_ad_hip, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)

# MUAC
overall_ad_muac <- OverallRiskSummaries(fit = m_ad_muac, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_ad_muac <- SingVarRiskSummaries(fit = m_ad_muac, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_ad_muac <- SingVarIntSummaries(fit = m_ad_muac, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)

# BODY FAT %
overall_ad_bfat <- OverallRiskSummaries(fit = m_ad_bfat, q.fixed = 0.50, sel = sel_final,
                                               method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_ad_bfat <- SingVarRiskSummaries(fit = m_ad_bfat, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_ad_bfat <- SingVarIntSummaries(fit = m_ad_bfat, qs.diff = c(0.25, 0.75),
                                       qs.fixed = c(0.25, 0.75),sel=sel_final)

# BODT FAT MASS
overall_ad_fat <- OverallRiskSummaries(fit = m_ad_fat, q.fixed = 0.50, sel = sel_final,
                                      method = "approx", qs = seq(0.25, 0.75, by = 0.05))
singvar_ad_fat <- SingVarRiskSummaries(fit = m_ad_fat, qs.diff = c(0.25, 0.75),
                                            q.fixed = c(0.25, 0.50, 0.75),sel=sel_final, method = "approx")
overall_interact_ad_fat <- SingVarIntSummaries(fit = m_ad_fat, qs.diff = c(0.25, 0.75),
                                              qs.fixed = c(0.25, 0.75),sel=sel_final)



##### PLOT RISK ASSOCIATED WITH THE OVERALL MIXTURE
### BMI
p_overall_ad_bmi <- ggplot(overall_ad_bmi, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "Change in BMI (kg/m^2)")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x = element_text(size = 11),
               axis.text.y = element_text(size = 11),
               axis.title.x = element_text(angle = 0, color = 'black', size = 11),
               axis.title.y = element_text(angle = 90, color = 'black', size = 11))
p_overall_ad_bmi

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_ad_bmi <- ggplot(singvar_ad_bmi, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Ln-transformed PFAS concentration") + scale_y_continuous(name = "Change in BMI (kg/m^2)")
p_singvar_ad_bmi

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_ad_bmi <- ggplot(overall_interact_ad_bmi, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in BMI (kg/m^2)") +
  xlab("PFAS")
p_overall_interact_ad_bmi


### WEIGHT
p_overall_ad_wt <- ggplot(overall_ad_wt, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "Change in weight (kg)")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x = element_text(size = 11),
               axis.text.y = element_text(size = 11),
               axis.title.x = element_text(angle = 0, color = 'black', size = 11),
               axis.title.y = element_text(angle = 90, color = 'black', size = 11))
p_overall_ad_wt

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_ad_wt <- ggplot(singvar_ad_wt, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Ln-transformed PFAS concentration") + scale_y_continuous(name = "Change in weight (kg)")
p_singvar_ad_wt

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_ad_wt <- ggplot(overall_interact_ad_wt, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in weight (kg)") +
  xlab("PFAS")
p_overall_interact_ad_wt


### WAIST CIRCUMFERENCE
p_overall_ad_waist <- ggplot(overall_ad_waist, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "Change in waist circumference (cm)")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x = element_text(size = 11),
               axis.text.y = element_text(size = 11),
               axis.title.x = element_text(angle = 0, color = 'black', size = 11),
               axis.title.y = element_text(angle = 90, color = 'black', size = 11))
p_overall_ad_waist

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_ad_waist <- ggplot(singvar_ad_waist, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Ln-transformed PFAS concentration") + scale_y_continuous(name = "Change in waist circumference (cm)")
p_singvar_ad_waist

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_ad_waist <- ggplot(overall_interact_ad_waist, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in waist circumference (cm)") +
  xlab("PFAS")
p_overall_interact_ad_waist


### HIP CIRCUMFERENCE
p_overall_ad_hip <- ggplot(overall_ad_hip, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "Change in hip circumference (cm)")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x = element_text(size = 11),
               axis.text.y = element_text(size = 11),
               axis.title.x = element_text(angle = 0, color = 'black', size = 11),
               axis.title.y = element_text(angle = 90, color = 'black', size = 11))
p_overall_ad_hip

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_ad_hip <- ggplot(singvar_ad_hip, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Ln-transformed PFAS concentration") + scale_y_continuous(name = "Change in hip circumference (cm)")
p_singvar_ad_hip

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_ad_hip <- ggplot(overall_interact_ad_hip, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in hip circumference (cm)") +
  xlab("PFAS")
p_overall_interact_ad_hip


### MUAC
p_overall_ad_muac <- ggplot(overall_ad_muac, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "Change in MUAC (cm)")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x = element_text(size = 11),
               axis.text.y = element_text(size = 11),
               axis.title.x = element_text(angle = 0, color = 'black', size = 11),
               axis.title.y = element_text(angle = 90, color = 'black', size = 11))
p_overall_ad_muac

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_ad_muac <- ggplot(singvar_ad_muac, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Ln-transformed PFAS concentration") + scale_y_continuous(name = "Change in MUAC (cm)")
p_singvar_ad_muac

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_ad_muac <- ggplot(overall_interact_ad_muac, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in MUAC (cm)") +
  xlab("PFAS")
p_overall_interact_ad_muac


### BODY FAT %
p_overall_ad_bfat <- ggplot(overall_ad_bfat, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "Change in body fat (%)")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x = element_text(size = 11),
               axis.text.y = element_text(size = 11),
               axis.title.x = element_text(angle = 0, color = 'black', size = 11),
               axis.title.y = element_text(angle = 90, color = 'black', size = 11))
p_overall_ad_bfat

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_ad_bfat <- ggplot(singvar_ad_bfat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Ln-transformed PFAS concentration") + scale_y_continuous(name = "Change in body fat (%)")
p_singvar_ad_bfat

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_ad_bfat <- ggplot(overall_interact_ad_bfat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in body fat (%)") +
  xlab("PFAS")
p_overall_interact_ad_bfat


### BODY FAT MASS
p_overall_ad_fat <- ggplot(overall_ad_fat, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "Change in body fat (kg/m^2)")+
               xlab("PFAS quantile") +
               theme_classic()+ theme(
               axis.text.x = element_text(size = 11),
               axis.text.y = element_text(size = 11),
               axis.title.x = element_text(angle = 0, color = 'black', size = 11),
               axis.title.y = element_text(angle = 90, color = 'black', size = 11))
p_overall_ad_fat

# SINGLE VARIABLE EFFECT ESTIMATES
# HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
p_singvar_ad_fat <- ggplot(singvar_ad_fat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                col = q.fixed)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "gray") +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_x_discrete(name = "Ln-transformed PFAS concentration") + scale_y_continuous(name = "Change in body fat (kg/m^2)")
p_singvar_ad_fat

# SINGLE VARIABLE INTERACTION TERMS
p_overall_interact_ad_fat <- ggplot(overall_interact_ad_fat, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +
  geom_hline(yintercept = 0, lty = 2, col = "brown") + coord_flip() +
  ylab("Difference in body fat (kg/m^2)") +
  xlab("PFAS")
p_overall_interact_ad_fat

```

