#####                                                       #####
##### PRE-LIMINARY ANALYSIS: SENSITIVITY ANANLYSIS (IPTW)   #####
#####                                                       #####

```{r}
##### LOAD PACKAGES
library("tidyverse")
library("modelsummary")
library("kableExtra")
library("gt")
library("shiny")
library("olsrr")

```

```{r}
##### LOAD DATASET
PFAS_A <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/PFAS_A.csv")
PFAS_D <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/PFAS_D.csv")

```

```{r}
##### PREPARE VARIABLES FOR WEIGHTS AND LINEAR REGRESSION

# SET CATEGORICAL VARIABLES AS FACTORS
PFAS_A$edu <- as.factor(PFAS_A$edu)
PFAS_A$income <- as.factor(PFAS_A$income)
PFAS_A$smoke <- as.factor(PFAS_A$smoke)
PFAS_A$parity <- as.factor(PFAS_A$parity)
PFAS_A$race <- as.factor(PFAS_A$race)
PFAS_A$married <- as.factor(PFAS_A$married)

PFAS_D$edu <- as.factor(PFAS_D$edu)
PFAS_D$income <- as.factor(PFAS_D$income)
PFAS_D$smoke <- as.factor(PFAS_D$smoke)
PFAS_D$parity <- as.factor(PFAS_D$parity)
PFAS_D$race <- as.factor(PFAS_D$race)
PFAS_D$married <- as.factor(PFAS_D$married)

```

```{r}
##### BUILD STABILIZED INVERSE PROBABILITY OF CONTINUOUS TREATMENT WEIGHTS, ANTHRO DATASET #####
##### NUMERATOR
# https://www.andrewheiss.com/blog/2020/12/01/ipw-binary-continuous/#continuous-treatments
# The numerator is the probability distribution of just the treatment variable.
# We'll use a normal distribution for it (hence dnorm()). We need to feed
# dnorm() the grant amount for each person, the predicted value from a simple
# grant ~ 1 model, and the sd of the residuals from that model

# PFOS
PFOS_num_m <- lm(L2PFOS ~ 1, data = PFAS_A)
PFOSnum <- dnorm(PFAS_A$L2PFOS,
             predict(PFOS_num_m),
             sd(PFOS_num_m$residuals))

# PFOA
PFOA_num_m <- lm(L2PFOA ~ 1, data = PFAS_A)
PFOAnum <- dnorm(PFAS_A$L2PFOA,
             predict(PFOA_num_m),
             sd(PFOA_num_m$residuals))

# PFNA
PFNA_num_m <- lm(L2PFNA ~ 1, data = PFAS_A)
PFNAnum <- dnorm(PFAS_A$L2PFNA,
             predict(PFNA_num_m),
             sd(PFNA_num_m$residuals))

# PFHxS
PFHxS_num_m <- lm(L2PFHxS ~ 1, data = PFAS_A)
PFHxSnum <- dnorm(PFAS_A$L2PFHxS,
             predict(PFHxS_num_m),
             sd(PFHxS_num_m$residuals))

# MeFOSAA
MeFOSAA_num_m <- lm(L2MeFOSAA ~ 1, data = PFAS_A)
MeFOSAAnum <- dnorm(PFAS_A$L2MeFOSAA,
             predict(MeFOSAA_num_m),
             sd(MeFOSAA_num_m$residuals))

# EtFOSAA
EtFOSAA_num_m <- lm(L2EtFOSAA ~ 1, data = PFAS_A)
EtFOSAAnum <- dnorm(PFAS_A$L2EtFOSAA,
             predict(EtFOSAA_num_m),
             sd(EtFOSAA_num_m$residuals))


##### DENOMINATOR
# The denominator is the probability distribution of the treatment variable
# explained by the confounders. We'll again use a normal distribution for it.
# We'll feed dnorm() the grant amount, the predicted value from a model that
# includes the confounders, and the sd of the residuals from that model

# PFOS
PFOS_den_m <- lm(L2PFOS ~ age_enroll + race + income + menar + smoke +  
                 parity + married, data = PFAS_A)
PFOSden <- dnorm(PFAS_A$L2PFOS,
             predict(PFOS_den_m),
             sd(PFOS_den_m$residuals))

# PFOA
PFOA_den_m <- lm(L2PFOA ~ age_enroll + race + income + menar + smoke +  
                 parity + married, data = PFAS_A)
PFOAden <- dnorm(PFAS_A$L2PFOA,
             predict(PFOA_den_m),
             sd(PFOA_den_m$residuals))

# PFNA
PFNA_den_m <- lm(L2PFNA ~ age_enroll + race + income + menar + smoke +  
                 parity + married, data = PFAS_A)
PFNAden <- dnorm(PFAS_A$L2PFNA,
             predict(PFNA_den_m),
             sd(PFNA_den_m$residuals))

# PFHxS
PFHxS_den_m <- lm(L2PFHxS ~ age_enroll + race + income + menar + smoke +  
                 parity + married, data = PFAS_A)
PFHxSden <- dnorm(PFAS_A$L2PFHxS,
             predict(PFHxS_den_m),
             sd(PFHxS_den_m$residuals))

# MeFOSAA
MeFOSAA_den_m <- lm(L2MeFOSAA ~ age_enroll + race + income + menar + smoke +  
                 parity + married, data = PFAS_A)
MeFOSAAden <- dnorm(PFAS_A$L2MeFOSAA,
             predict(MeFOSAA_den_m),
             sd(MeFOSAA_den_m$residuals))

# EtFOSAA
EtFOSAA_den_m <- lm(L2EtFOSAA ~ age_enroll + race + income + menar + smoke +  
                 parity + married, data = PFAS_A)
EtFOSAAden <- dnorm(PFAS_A$L2EtFOSAA,
             predict(EtFOSAA_den_m),
             sd(EtFOSAA_den_m$residuals))


##### BUILD THE WEIGHT
# Finally, we make actual IPW weights by building the fraction

# PFOS
PFAS_A <- PFAS_A %>% 
  mutate(PFOS_w = PFOSnum / PFOSden)
summary(PFAS_A$PFOS_w)

# PFOA
PFAS_A <- PFAS_A %>% 
  mutate(PFOA_w = PFOAnum / PFOAden)
summary(PFAS_A$PFOA_w)

# PFNA
PFAS_A <- PFAS_A %>% 
  mutate(PFNA_w = PFNAnum / PFNAden)
summary(PFAS_A$PFNA_w)

# PFHxS
PFAS_A <- PFAS_A %>% 
  mutate(PFHxS_w = PFHxSnum / PFHxSden)
summary(PFAS_A$PFHxS_w)

# MeFOSAA
PFAS_A <- PFAS_A %>% 
  mutate(MeFOSAA_w = MeFOSAAnum / MeFOSAAden)
summary(PFAS_A$MeFOSAA_w)

# EtFOSAA
PFAS_A <- PFAS_A %>% 
  mutate(EtFOSAA_w = EtFOSAAnum / EtFOSAAden)
summary(PFAS_A$EtFOSAA_w)


##### REMOVE INDIVIDUALS WITH ABNORMALLY HIGH WEIGHTS
PFAS_A_W <- subset(PFAS_A, PFAS_A$PFOS_w < 6) # N = 0
PFAS_A_W <- subset(PFAS_A_W, PFAS_A_W$PFOA_w < 6) # N = 1
PFAS_A_W <- subset(PFAS_A_W, PFAS_A_W$PFNA_w < 6) # N = 1
PFAS_A_W <- subset(PFAS_A_W, PFAS_A_W$PFHxS_w < 6) # N = 3
PFAS_A_W <- subset(PFAS_A_W, PFAS_A_W$MeFOSAA_w < 6) # N = 0 
PFAS_A_W <- subset(PFAS_A_W, PFAS_A_W$EtFOSAA_w < 6) # N = 0

```

```{r}
##### BUILD STABILIZED INVERSE PROBABILITY OF CONTINUOUS TREATMENT WEIGHTS, ANTHRO + DXA DATASET #####
##### NUMERATOR
# https://www.andrewheiss.com/blog/2020/12/01/ipw-binary-continuous/#continuous-treatments
# The numerator is the probability distribution of just the treatment variable.
# We'll use a normal distribution for it (hence dnorm()). We need to feed
# dnorm() the grant amount for each person, the predicted value from a simple
# grant ~ 1 model, and the sd of the residuals from that model

# PFOS
PFOS_num_m <- lm(L2PFOS ~ 1, data = PFAS_D)
PFOSnum <- dnorm(PFAS_D$L2PFOS,
             predict(PFOS_num_m),
             sd(PFOS_num_m$residuals))

# PFOA
PFOA_num_m <- lm(L2PFOA ~ 1, data = PFAS_D)
PFOAnum <- dnorm(PFAS_D$L2PFOA,
             predict(PFOA_num_m),
             sd(PFOA_num_m$residuals))

# PFNA
PFNA_num_m <- lm(L2PFNA ~ 1, data = PFAS_D)
PFNAnum <- dnorm(PFAS_D$L2PFNA,
             predict(PFNA_num_m),
             sd(PFNA_num_m$residuals))

# PFHxS
PFHxS_num_m <- lm(L2PFHxS ~ 1, data = PFAS_D)
PFHxSnum <- dnorm(PFAS_D$L2PFHxS,
             predict(PFHxS_num_m),
             sd(PFHxS_num_m$residuals))

# MeFOSAA
MeFOSAA_num_m <- lm(L2MeFOSAA ~ 1, data = PFAS_D)
MeFOSAAnum <- dnorm(PFAS_D$L2MeFOSAA,
             predict(MeFOSAA_num_m),
             sd(MeFOSAA_num_m$residuals))

# EtFOSAA
EtFOSAA_num_m <- lm(L2EtFOSAA ~ 1, data = PFAS_D)
EtFOSAAnum <- dnorm(PFAS_D$L2EtFOSAA,
             predict(EtFOSAA_num_m),
             sd(EtFOSAA_num_m$residuals))


##### DENOMINATOR
# The denominator is the probability distribution of the treatment variable
# explained by the confounders. We'll again use a normal distribution for it.
# We'll feed dnorm() the grant amount, the predicted value from a model that
# includes the confounders, and the sd of the residuals from that model

# PFOS
PFOS_den_m <- lm(L2PFOS ~ age_enroll + race + income + menar + smoke +  
                 parity + married, data = PFAS_D)
PFOSden <- dnorm(PFAS_D$L2PFOS,
             predict(PFOS_den_m),
             sd(PFOS_den_m$residuals))

# PFOA
PFOA_den_m <- lm(L2PFOA ~ age_enroll + race + income + menar + smoke +  
                 parity + married, data = PFAS_D)
PFOAden <- dnorm(PFAS_D$L2PFOA,
             predict(PFOA_den_m),
             sd(PFOA_den_m$residuals))

# PFNA
PFNA_den_m <- lm(L2PFNA ~ age_enroll + race + income + menar + smoke +  
                 parity + married, data = PFAS_D)
PFNAden <- dnorm(PFAS_D$L2PFNA,
             predict(PFNA_den_m),
             sd(PFNA_den_m$residuals))

# PFHxS
PFHxS_den_m <- lm(L2PFHxS ~ age_enroll + race + income + menar + smoke +  
                 parity + married, data = PFAS_D)
PFHxSden <- dnorm(PFAS_D$L2PFHxS,
             predict(PFHxS_den_m),
             sd(PFHxS_den_m$residuals))

# MeFOSAA
MeFOSAA_den_m <- lm(L2MeFOSAA ~ age_enroll + race + income + menar + smoke +  
                 parity + married, data = PFAS_D)
MeFOSAAden <- dnorm(PFAS_D$L2MeFOSAA,
             predict(MeFOSAA_den_m),
             sd(MeFOSAA_den_m$residuals))

# EtFOSAA
EtFOSAA_den_m <- lm(L2EtFOSAA ~ age_enroll + race + income + menar + smoke +  
                 parity + married, data = PFAS_D)
EtFOSAAden <- dnorm(PFAS_D$L2EtFOSAA,
             predict(EtFOSAA_den_m),
             sd(EtFOSAA_den_m$residuals))


##### BUILD THE WEIGHT
# Finally, we make actual IPW weights by building the fraction

# PFOS
PFAS_D <- PFAS_D %>% 
  mutate(PFOS_w = PFOSnum / PFOSden)
summary(PFAS_D$PFOS_w)

# PFOA
PFAS_D <- PFAS_D %>% 
  mutate(PFOA_w = PFOAnum / PFOAden)
summary(PFAS_D$PFOA_w)

# PFNA
PFAS_D <- PFAS_D %>% 
  mutate(PFNA_w = PFNAnum / PFNAden)
summary(PFAS_D$PFNA_w)

# PFHxS
PFAS_D <- PFAS_D %>% 
  mutate(PFHxS_w = PFHxSnum / PFHxSden)
summary(PFAS_D$PFHxS_w)

# MeFOSAA
PFAS_D <- PFAS_D %>% 
  mutate(MeFOSAA_w = MeFOSAAnum / MeFOSAAden)
summary(PFAS_D$MeFOSAA_w)

# EtFOSAA
PFAS_D <- PFAS_D %>% 
  mutate(EtFOSAA_w = EtFOSAAnum / EtFOSAAden)
summary(PFAS_D$EtFOSAA_w)


##### REMOVE INDIVIDUALS WITH ABNORMALLY HIGH WEIGHTS
PFAS_D_W <- subset(PFAS_D, PFAS_D$PFOS_w < 6) # N = 1
PFAS_D_W <- subset(PFAS_D_W, PFAS_D_W$PFOA_w < 6) # N = 2
PFAS_D_W <- subset(PFAS_D_W, PFAS_D_W$PFNA_w < 6) # N = 0
PFAS_D_W <- subset(PFAS_D_W, PFAS_D_W$PFHxS_w < 6) # N = 2
PFAS_D_W <- subset(PFAS_D_W, PFAS_D_W$MeFOSAA_w < 6) # N = 0 
PFAS_D_W <- subset(PFAS_D_W, PFAS_D_W$EtFOSAA_w < 6) # N = 0

```

```{r}
##### RUN ADJUSTED LINEAR REGRESSION MODELS, ANTHRO DATASET (N = 544)

# BMI
ad.l2m.lnbmi <- list(
  "PFOS" = glm(LNBMI ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFOA" = glm(LNBMI ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFNA" = glm(LNBMI ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(LNBMI ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(LNBMI ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(LNBMI ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A))

modelsummary(ad.l2m.lnbmi, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-BMI")


wad.l2m.lnbmi <- list(
  "PFOS" = glm(LNBMI ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A_W, weights = PFOS_w),
  "PFOA" = glm(LNBMI ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A_W, weights = PFOA_w),
  "PFNA" = glm(LNBMI ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A_W, weights = PFNA_w),
  "PFHxS" = glm(LNBMI ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married, family = gaussian, data = PFAS_A_W, weights = PFHxS_w),
  "MeFOSSA" = glm(LNBMI ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A_W, weights = MeFOSAA_w),
  "EtFOSSA" = glm(LNBMI ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A_W, weights = EtFOSAA_w))

modelsummary(wad.l2m.lnbmi, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-BMI (IPT Weighted)")



# WAIST CIRCUMFERENCE
ad.l2m.waist <- list(
  "PFOS" = glm(Waist ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFOA" = glm(Waist ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFNA" = glm(Waist ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(Waist ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(Waist ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(Waist ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A))

modelsummary(ad.l2m.waist, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WAIST CIRCUMFERENCE")


wad.l2m.waist <- list(
  "PFOS" = glm(Waist ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A_W, weights = PFOS_w),
  "PFOA" = glm(Waist ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A_W, weights = PFOA_w),
  "PFNA" = glm(Waist ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A_W, weights = PFNA_w),
  "PFHxS" = glm(Waist ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married, family = gaussian, data = PFAS_A_W, weights = PFHxS_w),
  "MeFOSSA" = glm(Waist ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A_W, weights = MeFOSAA_w),
  "EtFOSSA" = glm(Waist ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A_W, weights = EtFOSAA_w))

modelsummary(wad.l2m.waist, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WAIST CIRCUMFERENCE (IPT Weighted)")



# WAIST-TO-HIP RATIO
ad.l2m.whr <- list(
  "PFOS" = glm(WHR ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFOA" = glm(WHR ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFNA" = glm(WHR ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(WHR ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(WHR ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(WHR ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A))

modelsummary(ad.l2m.whr, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WHR")


wad.l2m.whr <- list(
  "PFOS" = glm(WHR ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A_W, weights = PFOS_w),
  "PFOA" = glm(WHR ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A_W, weights = PFOA_w),
  "PFNA" = glm(WHR ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A_W, weights = PFNA_w),
  "PFHxS" = glm(WHR ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married, family = gaussian, data = PFAS_A_W, weights = PFHxS_w),
  "MeFOSSA" = glm(WHR ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A_W, weights = MeFOSAA_w),
  "EtFOSSA" = glm(WHR ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A_W, weights = EtFOSAA_w))

modelsummary(wad.l2m.whr, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WHR (IPT Weighted)")



# MUAC
ad.l2m.muac <- list(
  "PFOS" = glm(MUAC ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFOA" = glm(MUAC ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFNA" = glm(MUAC ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(MUAC ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married, family = gaussian, data = PFAS_A),
  "MeFOSSA" = glm(MUAC ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A),
  "EtFOSSA" = glm(MUAC ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A))

modelsummary(ad.l2m.muac, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. MUAC")


wad.l2m.muac <- list(
  "PFOS" = glm(MUAC ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A_W, weights = PFOS_w),
  "PFOA" = glm(MUAC ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A_W, weights = PFOA_w),
  "PFNA" = glm(MUAC ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A_W, weights = PFNA_w),
  "PFHxS" = glm(MUAC ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married, family = gaussian, data = PFAS_A_W, weights = PFHxS_w),
  "MeFOSSA" = glm(MUAC ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A_W, weights = MeFOSAA_w),
  "EtFOSSA" = glm(MUAC ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A_W, weights = EtFOSAA_w))

modelsummary(wad.l2m.muac, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. MUAC (IPT Weighted)")

```

```{r}
##### RUN ADJUSTED LINEAR REGRESSION MODELS, ANTHRO + DXA DATASET (N = 424)

# TRUNK FAT MASS
ad.l2m.lntrnkfat <- list(
  "PFOS" = glm(LNTKNFAT ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTKNFAT ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTKNFAT ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTKNFAT ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married, family = gaussian, data = PFAS_D),
  "MeFOSSA" = glm(LNTKNFAT ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D),
  "EtFOSSA" = glm(LNTKNFAT ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D))

modelsummary(ad.l2m.lntrnkfat, fmt = 2, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-TRUNK FAT MASS")


wad.l2m.lntrnkfat <- list(
  "PFOS" = glm(LNTKNFAT ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D_W, weights = PFOS_w),
  "PFOA" = glm(LNTKNFAT ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D_W, weights = PFOA_w),
  "PFNA" = glm(LNTKNFAT ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D_W, weights = PFNA_w),
  "PFHxS" = glm(LNTKNFAT ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married, family = gaussian, data = PFAS_D_W, weights = PFHxS_w),
  "MeFOSSA" = glm(LNTKNFAT ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D_W, weights = MeFOSAA_w),
  "EtFOSSA" = glm(LNTKNFAT ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D_W, weights = EtFOSAA_w))

modelsummary(wad.l2m.lntrnkfat, fmt = 2, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-TRUNK FAT MASS (IPT Weighted)")



# TOTAL BODY FAT MASS
ad.l2m.lntotfat <- list(
  "PFOS" = glm(LNTOTFAT ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTOTFAT ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTOTFAT ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTOTFAT ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married, family = gaussian, data = PFAS_D),
  "MeFOSSA" = glm(LNTOTFAT ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D),
  "EtFOSSA" = glm(LNTOTFAT ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D))

modelsummary(ad.l2m.lntotfat, fmt = 2, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-TOTAL BODY FAT MASS")


wad.l2m.lntotfat <- list(
  "PFOS" = glm(LNTOTFAT ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D_W, weights = PFOS_w),
  "PFOA" = glm(LNTOTFAT ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D_W, weights = PFOA_w),
  "PFNA" = glm(LNTOTFAT ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D_W, weights = PFNA_w),
  "PFHxS" = glm(LNTOTFAT ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married, family = gaussian, data = PFAS_D_W, weights = PFHxS_w),
  "MeFOSSA" = glm(LNTOTFAT ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D_W, weights = MeFOSAA_w),
  "EtFOSSA" = glm(LNTOTFAT ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D_W, weights = EtFOSAA_w))

modelsummary(wad.l2m.lntotfat, fmt = 2, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-TOTAL BODY FAT MASS (IPT Weighted)")



# TOTAL BODY FAT %
ad.l2m.totpfat <- list(
  "PFOS" = glm(TotFatPct ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFOA" = glm(TotFatPct ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFNA" = glm(TotFatPct ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(TotFatPct ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married, family = gaussian, data = PFAS_D),
  "MeFOSSA" = glm(TotFatPct ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D),
  "EtFOSSA" = glm(TotFatPct ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D))

modelsummary(ad.l2m.totpfat, fmt = 2, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. TOTAL BODY FAT %")



ad.l2m.totpfat <- list(
  "PFOS" = glm(TotFatPct ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D_W, weights = PFOS_w),
  "PFOA" = glm(TotFatPct ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D_W, weights = PFOA_w),
  "PFNA" = glm(TotFatPct ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D_W, weights = PFNA_w),
  "PFHxS" = glm(TotFatPct ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married, family = gaussian, data = PFAS_D_W, weights = PFHxS_w),
  "MeFOSSA" = glm(TotFatPct ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D_W, weights = MeFOSAA_w),
  "EtFOSSA" = glm(TotFatPct ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D_W, weights = EtFOSAA_w))

modelsummary(ad.l2m.totpfat, fmt = 2, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. TOTAL BODY FAT % (IPT Weighted)")

```

