#####                                                       #####
##### EVALUATE DISTRIBUTION OF VARIABLES AND CREATE TABLE 1 #####
#####                                                       #####

```{r}
##### LOAD PACKAGES
library("tidyverse")
library("dplyr")
library("table1")
library("gtools")
library("corrplot")
library("Hmisc")

```

```{r}
##### LOAD DATASET
PFAS_A <-read.csv("C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/PFAS_A_COMP.csv")
PFAS_D <-read.csv("C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/PFAS_D_COMP.csv")
PFAS_X <-read.csv("C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/PFAS_X.csv")

```

```{r}
##### CREATE WAIST-TO-HIP RATIO
PFAS_A$WHR <- PFAS_A$mom_waist_ma17 / PFAS_A$mom_hip_ma17

```


```{r}
##### LOG-TRANSFORM PFAS TO OBSERVE SHAPE OF DISTRIBUTION
PFAS_A$LNPFOS <- log(PFAS_A$PFOS)
PFAS_A$LNPFOA <- log(PFAS_A$PFOA)
PFAS_A$LNPFNA2 <- log(PFAS_A$PFNA2)
PFAS_A$LNPFHxS <- log(PFAS_A$PFHxS)
PFAS_A$LNME_PFOSA <- log(PFAS_A$Me_PFOSA_AcOH2)
PFAS_A$LNET_PFOSA <- log(PFAS_A$Et_PFOSA_AcOH)

PFAS_A$LN2PFOS <- log(PFAS_A$PFOS, 2)
PFAS_A$LN2PFOA <- log(PFAS_A$PFOA, 2)
PFAS_A$LN2PFNA2 <- log(PFAS_A$PFNA2, 2)
PFAS_A$LN2PFHxS <- log(PFAS_A$PFHxS, 2)
PFAS_A$LN2ME_PFOSA <- log(PFAS_A$Me_PFOSA_AcOH2, 2)
PFAS_A$LN2ET_PFOSA <- log(PFAS_A$Et_PFOSA_AcOH, 2)


PFAS_D$LNPFOS <- log(PFAS_D$PFOS)
PFAS_D$LNPFOA <- log(PFAS_D$PFOA)
PFAS_D$LNPFNA2 <- log(PFAS_D$PFNA2)
PFAS_D$LNPFHxS <- log(PFAS_D$PFHxS)
PFAS_D$LNME_PFOSA <- log(PFAS_D$Me_PFOSA_AcOH2)
PFAS_D$LNET_PFOSA <- log(PFAS_D$Et_PFOSA_AcOH)

PFAS_D$LN2PFOS <- log(PFAS_D$PFOS, 2)
PFAS_D$LN2PFOA <- log(PFAS_D$PFOA, 2)
PFAS_D$LN2PFNA2 <- log(PFAS_D$PFNA2, 2)
PFAS_D$LN2PFHxS <- log(PFAS_D$PFHxS, 2)
PFAS_D$LN2ME_PFOSA <- log(PFAS_D$Me_PFOSA_AcOH2, 2)
PFAS_D$LN2ET_PFOSA <- log(PFAS_D$Et_PFOSA_AcOH, 2)



##### LOG-TRANSFORM DXA MEASURES (AND BMI/WEIGHT GAIN/WAIST CIRCUMFERENCE) TO OBSERVE SHAPE OF DISTRIBUTION
PFAS_A$LNBMI <- log(PFAS_A$mom_bmi_MT)
PFAS_A$LNWAIST <- log(PFAS_A$mom_waist_ma17)
PFAS_A$LNWHR <- log(PFAS_A$WHR)
PFAS_A$LNMUAC <- log(PFAS_A$mom_muac_ma17)
PFAS_A$LNBFAT <- log(PFAS_A$mom_bodyfat_ma17)
PFAS_A$LNFAT <- log(PFAS_A$mom_fat_ma17)
PFAS_A$LNWT <- log(PFAS_A$mom_weight_ma17)
PFAS_A$LNFFAT <- log(PFAS_A$mom_ffm_ma17)

PFAS_D$LNVAT_AREA <- log(PFAS_D$VAT_AREA_mdxa17)
PFAS_D$LNSAT_AREA <- log(PFAS_D$SAT_AREA_mdxa17)
PFAS_D$LNTAT_AREA <- log(PFAS_D$TAT_AREA_mdxa17)
PFAS_D$LNVAT_MASS <- log(PFAS_D$VAT_MASS_mdxa17)
PFAS_D$LNSAT_MASS <- log(PFAS_D$SAT_MASS_mdxa17)
PFAS_D$LNTAT_MASS <- log(PFAS_D$TAT_MASS_mdxa17)
PFAS_D$LNVAT_VOLUME <- log(PFAS_D$VAT_VOLUME_mdxa17)
PFAS_D$LNSAT_VOLUME <- log(PFAS_D$SAT_VOLUME_mdxa17)
PFAS_D$LNTAT_VOLUME <- log(PFAS_D$TAT_VOLUME_mdxa17)

```

```{r}
##### DESCRIBE PFAS DISTRIBUTION, ANTHRO DATASET
hist(PFAS_A$PFOS)
hist(PFAS_A$PFOA)
hist(PFAS_A$PFNA2)
hist(PFAS_A$PFHxS)
hist(PFAS_A$Me_PFOSA_AcOH2)
hist(PFAS_A$Et_PFOSA_AcOH)

# DESCRIBE LNPFAS DISTRIBUTION, ANTHRO DATASET
hist(PFAS_A$LNPFOS)
hist(PFAS_A$LNPFOA)
hist(PFAS_A$LNPFNA2)
hist(PFAS_A$LNPFHxS)
hist(PFAS_A$LNME_PFOSA)
hist(PFAS_A$LNET_PFOSA)

# DESCRIBE LNPFAS DISTRIBUTION, ANTHRO DATASET
hist(PFAS_A$LN2PFOS)
hist(PFAS_A$LN2PFOA)
hist(PFAS_A$LN2PFNA2)
hist(PFAS_A$LN2PFHxS)
hist(PFAS_A$LN2ME_PFOSA)
hist(PFAS_A$LN2ET_PFOSA)


##### DESCRIBE PFAS DISTRIBUTION, ANTHRO + DXA DATASET
hist(PFAS_D$PFOS)
hist(PFAS_D$PFOA)
hist(PFAS_D$PFNA2)
hist(PFAS_D$PFHxS)
hist(PFAS_D$Me_PFOSA_AcOH2)
hist(PFAS_D$Et_PFOSA_AcOH)

# DESCRIBE LNPFAS DISTRIBUTION, ANTHRO + DXA DATASET
hist(PFAS_D$LNPFOS)
hist(PFAS_D$LNPFOA)
hist(PFAS_D$LNPFNA2)
hist(PFAS_D$LNPFHxS)
hist(PFAS_D$LNME_PFOSA)
hist(PFAS_D$LNET_PFOSA)

# DESCRIBE LN2PFAS DISTRIBUTION, ANTHRO + DXA DATASET
hist(PFAS_D$LN2PFOS)
hist(PFAS_D$LN2PFOA)
hist(PFAS_D$LN2PFNA2)
hist(PFAS_D$LN2PFHxS)
hist(PFAS_D$LN2ME_PFOSA)
hist(PFAS_D$LN2ET_PFOSA)


```

```{r}
##### DESCRIBE DISTRIBUTION OF OUTCOME MEASURES, ANTHRO DATASET
hist(PFAS_A$mom_bmi_MT)
hist(PFAS_A$mom_waist_ma17)
hist(PFAS_A$WHR)
hist(PFAS_A$mom_muac_ma17)
hist(PFAS_A$mom_bodyfat_ma17)
hist(PFAS_A$mom_fat_ma17)
hist(PFAS_A$mom_weight_ma17)
hist(PFAS_A$mom_ffm_ma17)

boxplot(PFAS_A$mom_bmi_MT)
boxplot(PFAS_A$mom_weight_ma17)
boxplot(PFAS_A$mom_waist_ma17)
boxplot(PFAS_A$WHR)
boxplot(PFAS_A$mom_muac_ma17)
boxplot(PFAS_A$mom_bodyfat_ma17)
boxplot(PFAS_A$mom_fat_ma17)

ks.test(PFAS_A$mom_bmi_MT, 'pnorm')
ks.test(PFAS_A$mom_waist_ma17, 'pnorm')
ks.test(PFAS_A$WHR, 'pnorm')
ks.test(PFAS_A$mom_muac_ma17, 'pnorm')
ks.test(PFAS_A$mom_bodyfat_ma17, 'pnorm')
ks.test(PFAS_A$mom_fat_ma17, 'pnorm')
ks.test(PFAS_A$mom_weight_ma17, 'pnorm')

# DESCRIBE THE LOG-DISTRIBUTION OF OUTCOME MEASURES, ANTHRO DATASET
hist(PFAS_A$LNBMI)
hist(PFAS_A$LNWAIST)
hist(PFAS_A$LNWHR)
hist(PFAS_A$LNMUAC)
hist(PFAS_A$LNBFAT)
hist(PFAS_A$LNFAT)
hist(PFAS_A$LNWT)
hist(PFAS_A$LNFFAT)


##### DESCRIBE DISTRIBUTION OF OUTCOME MEASURES, ANTHRO + DXA DATASET
hist(PFAS_D$VAT_AREA_mdxa17)
hist(PFAS_D$SAT_AREA_mdxa17)
hist(PFAS_D$TAT_AREA_mdxa17)
hist(PFAS_D$VAT_MASS_mdxa17)
hist(PFAS_D$SAT_MASS_mdxa17)
hist(PFAS_D$TAT_MASS_mdxa17)
hist(PFAS_D$VAT_VOLUME_mdxa17)
hist(PFAS_D$SAT_VOLUME_mdxa17)
hist(PFAS_D$TAT_VOLUME_mdxa17)


# DESCRIBE THE LOG-DISTRIBUTION OF OUTCOME MEASURES, ANTHRO + DXA DATASET
hist(PFAS_D$LNVAT_AREA)
hist(PFAS_D$LNSAT_AREA)
hist(PFAS_D$LNTAT_AREA)
hist(PFAS_D$LNVAT_MASS)
hist(PFAS_D$LNSAT_MASS)
hist(PFAS_D$LNTAT_MASS)
hist(PFAS_D$LNVAT_VOLUME)
hist(PFAS_D$LNSAT_VOLUME)
hist(PFAS_D$LNTAT_VOLUME)

ks.test(PFAS_D$VAT_AREA_mdxa17, 'pnorm')
ks.test(PFAS_D$SAT_AREA_mdxa17, 'pnorm')
ks.test(PFAS_D$TAT_AREA_mdxa17, 'pnorm')
ks.test(PFAS_D$VAT_MASS_mdxa17, 'pnorm')
ks.test(PFAS_D$SAT_MASS_mdxa17, 'pnorm')
ks.test(PFAS_D$TAT_MASS_mdxa17, 'pnorm')
ks.test(PFAS_D$VAT_VOLUME_mdxa17, 'pnorm')
ks.test(PFAS_D$SAT_VOLUME_mdxa17, 'pnorm')

```

```{r}
##### ANTHRO DATASET #####

##### RENAME
PFAS_A$age_enroll <- PFAS_A$age_mom_enroll_d
PFAS_A$age_fu <- (PFAS_A$mom_age_days_comp_d_ma17)/365
PFAS_A$fu_time <- (PFAS_A$age_days_comp_d_ma17)/365
PFAS_A$race <- PFAS_A$race2_mom_epi_epia_d
PFAS_A$edu <- PFAS_A$coll_grad
PFAS_A$bmi <- PFAS_A$bmi_mom_prepreg_d
PFAS_A$smoke <- PFAS_A$smokpreg_final_d
PFAS_A$income <- PFAS_A$gt70k
PFAS_A$parity <- PFAS_A$parity_d
PFAS_A$married <- PFAS_A$married_cohab


##### RE-LABEL 
PFAS_A$race <- ifelse(PFAS_A$race == "white", 0,
                     ifelse(PFAS_A$race == "black", 1,
                     ifelse(PFAS_A$race == "hispa", 2,
                     ifelse(PFAS_A$race == "asian", 3,
                     ifelse(PFAS_A$race == "other", 4, 4)))))
PFAS_A$edu <- ifelse(PFAS_A$edu == 1, 1, 0)
PFAS_A$bmi_cat <- ifelse(PFAS_A$bmi <18.5, 0,
                         ifelse(PFAS_A$bmi >=18.5 & PFAS_A$bmi < 25.0, 1, 
                         ifelse(PFAS_A$bmi >=25.0 & PFAS_A$bmi < 30.0, 2, 
                         ifelse(PFAS_A$bmi >=30.0 & PFAS_A$bmi < 35.0, 3,
                         ifelse(PFAS_A$bmi >=35.0, 4, 99)))))
PFAS_A$smoke <- ifelse(PFAS_A$smoke == "former", 0,
                         ifelse(PFAS_A$smoke == "smoke preg", 1,
                         ifelse(PFAS_A$smoke == "xnever", 2, 2)))
PFAS_A$income <- ifelse(PFAS_A$income == 1, 1, 0)
PFAS_A$parity <- ifelse(PFAS_A$parity == 0, 0,
                        ifelse(PFAS_A$parity == 1, 1,
                        ifelse(PFAS_A$parity > 1, 2, 0)))
PFAS_A$married <- ifelse(PFAS_A$married == 1, 1, 0)


##### REFACTOR
PFAS_A$race <- factor(PFAS_A$race,
                        levels = c(0, 1, 2, 3, 4),
                        labels = c("White", "Black", "Hispanic", "Asian", "Other/More than 1 race"))
PFAS_A$edu <- factor(PFAS_A$edu,
                       levels = c(0, 1),
                       labels = c(" < college degree", ">= college degree"))
PFAS_A$bmi_cat <- factor(PFAS_A$bmi_cat,
                       levels = c(0, 1, 2, 3, 4),
                       labels = c("Underweight (< 18.5)", "Normal weight (18.5 to 24.9)", 
                                  "Overweight (25.0 to 29.9)", "Obese (30.0 to 34.9)", 
                                  "Extremely obese (>= 35)"))
PFAS_A$smoke <- factor(PFAS_A$smoke,
                         levels = c(0, 1, 2),
                         labels = c("Former smoker", "Smoked during pregnancy", "Never smoked"))
PFAS_A$income <- factor(PFAS_A$income,
                       levels = c(0, 1),
                       labels = c(" <= $70,000", "> $70,000"))
PFAS_A$parity <- factor(PFAS_A$parity,
                          levels = c(0, 1, 2),
                          labels = c("0", "1", ">= 2"))
PFAS_A$married <- factor(PFAS_A$married,
                          levels = c(0, 1),
                          labels = c("No", "Yes"))

##### LABEL
label(PFAS_A$age_enroll) <- "Maternal age at enrollment"
label(PFAS_A$age_fu) <- "Maternal age at follow-up"
label(PFAS_A$fu_time) <- "Follow-up time"
label(PFAS_A$race) <- "Race/Ethnicity"
label(PFAS_A$edu) <- "Education"
label(PFAS_A$bmi_cat) <- "Pre-pregnancy BMI"
label(PFAS_A$smoke) <- "Smoking status"
label(PFAS_A$income) <- "Annual household income"
label(PFAS_A$parity) <- "Parity"
label(PFAS_A$married) <- "Married or cohabitating"

##### ADD UNITS
units(PFAS_A$age_enroll)  <- "years"
units(PFAS_A$age_fu)  <- "years"
units(PFAS_A$fu_time)  <- "years"
units(PFAS_A$bmi_cat)  <- "kg/m2"

##### TABE 1
table1(~ age_enroll + age_fu + fu_time + race + bmi_cat + edu + income + parity + 
         smoke + married, data = PFAS_A, overall = "Total")

```

```{r}
##### ANTHRO + DXA DATASET #####

##### RENAME
PFAS_D$age_enroll <- PFAS_D$age_mom_enroll_d
PFAS_D$age_fu <- (PFAS_D$mom_age_days_mdxa17)/365
PFAS_D$fu_time <- (PFAS_D$age_days_mdxa17)/365
PFAS_D$race <- PFAS_D$race2_mom_epi_epia_d
PFAS_D$edu <- PFAS_D$coll_grad
PFAS_D$bmi <- PFAS_D$bmi_mom_prepreg_d
PFAS_D$smoke <- PFAS_D$smokpreg_final_d
PFAS_D$income <- PFAS_D$gt70k
PFAS_D$parity <- PFAS_D$parity_d
PFAS_A$married <- PFAS_A$married_cohab

##### RE-LABEL 
PFAS_D$race <- ifelse(PFAS_D$race == "white", 0,
                     ifelse(PFAS_D$race == "black", 1,
                     ifelse(PFAS_D$race == "hispa", 2,
                     ifelse(PFAS_D$race == "asian", 3,
                     ifelse(PFAS_D$race == "other", 4, 4)))))
PFAS_D$edu <- ifelse(PFAS_D$edu == 1, 1, 0)
PFAS_D$bmi_cat <- ifelse(PFAS_D$bmi <18.5, 0,
                         ifelse(PFAS_D$bmi >=18.5 & PFAS_D$bmi < 25.0, 1, 
                         ifelse(PFAS_D$bmi >=25.0 & PFAS_D$bmi < 30.0, 2, 
                         ifelse(PFAS_D$bmi >=30.0 & PFAS_D$bmi < 35.0, 3,
                         ifelse(PFAS_D$bmi >=35.0, 4, 99)))))
PFAS_D$smoke <- ifelse(PFAS_D$smoke == "former", 0,
                         ifelse(PFAS_D$smoke == "smoke preg", 1,
                         ifelse(PFAS_D$smoke == "xnever", 2, 2)))
PFAS_D$income <- ifelse(PFAS_D$income == 1, 1, 0)
PFAS_D$parity <- ifelse(PFAS_D$parity == 0, 0,
                        ifelse(PFAS_D$parity == 1, 1,
                        ifelse(PFAS_D$parity > 1, 2, 0)))
PFAS_D$married <- ifelse(PFAS_D$married == 1, 1, 0)


##### REFACTOR
PFAS_D$race <- factor(PFAS_D$race,
                        levels = c(0, 1, 2, 3, 4),
                        labels = c("White", "Black", "Hispanic", "Asian", "Other/More than 1 race"))
PFAS_D$edu <- factor(PFAS_D$edu,
                       levels = c(0, 1),
                       labels = c(" < college degree", ">= college degree"))
PFAS_D$bmi_cat <- factor(PFAS_D$bmi_cat,
                       levels = c(0, 1, 2, 3, 4),
                       labels = c("Underweight (< 18.5)", "Normal weight (18.5 to 24.9)", 
                                  "Overweight (25.0 to 29.9)", "Obese (30.0 to 34.9)", 
                                  "Extremely obese (>= 35)"))
PFAS_D$smoke <- factor(PFAS_D$smoke,
                         levels = c(0, 1, 2),
                         labels = c("Former smoker", "Smoked during pregnancy", "Never smoked"))
PFAS_D$income <- factor(PFAS_D$income,
                       levels = c(0, 1),
                       labels = c(" <= $70,000", "> $70,000"))
PFAS_D$parity <- factor(PFAS_D$parity,
                          levels = c(0, 1, 2),
                          labels = c("0", "1", ">= 2"))
PFAS_D$married <- factor(PFAS_D$married,
                          levels = c(0, 1),
                          labels = c("No", "Yes"))

##### LABEL
label(PFAS_D$age_enroll) <- "Maternal age at enrollment"
label(PFAS_D$age_fu) <- "Maternal age at follow-up"
label(PFAS_D$fu_time) <- "Follow-up time"
label(PFAS_D$race) <- "Race/Ethnicity"
label(PFAS_D$edu) <- "Education"
label(PFAS_D$bmi_cat) <- "Pre-pregnancy BMI"
label(PFAS_D$smoke) <- "Smoking status"
label(PFAS_D$income) <- "Annual household income"
label(PFAS_D$parity) <- "Parity"
label(PFAS_D$married) <- "Married or cohabitating"

##### ADD UNITS
units(PFAS_D$age_enroll)  <- "years"
units(PFAS_D$age_fu)  <- "years"
units(PFAS_D$fu_time)  <- "years"
units(PFAS_D$bmi_cat)  <- "kg/m2"

##### TABE 1
table1(~ age_enroll + age_fu + fu_time + race + bmi_cat + edu + income + parity + 
         smoke + married, data = PFAS_D, overall = "Total")

```

```{r}
##### EXCLUSION DATASET #####

##### RENAME
PFAS_X$age_enroll <- PFAS_X$age_mom_enroll_d
PFAS_X$race <- PFAS_X$race2_mom_epi_epia_d
PFAS_X$edu <- PFAS_X$coll_grad
PFAS_X$bmi <- PFAS_X$bmi_mom_prepreg_d
PFAS_X$smoke <- PFAS_X$smokpreg_final_d
PFAS_X$income <- PFAS_X$gt70k
PFAS_X$parity <- PFAS_X$pari_d
PFAS_A$married <- PFAS_A$married_cohab

##### RE-LABEL 
PFAS_X$race <- ifelse(PFAS_X$race == "white", 0,
                     ifelse(PFAS_X$race == "black", 1,
                     ifelse(PFAS_X$race == "hispa", 2,
                     ifelse(PFAS_X$race == "asian", 3,
                     ifelse(PFAS_X$race == "other", 4, 4)))))
PFAS_X$edu <- ifelse(PFAS_X$edu == 1, 1, 0)
PFAS_X$bmi_cat <- ifelse(PFAS_X$bmi <18.5, 0,
                         ifelse(PFAS_X$bmi >=18.5 & PFAS_X$bmi < 25.0, 1, 
                         ifelse(PFAS_X$bmi >=25.0 & PFAS_X$bmi < 30.0, 2, 
                         ifelse(PFAS_X$bmi >=30.0 & PFAS_X$bmi < 35.0, 3,
                         ifelse(PFAS_X$bmi >=35.0, 4, 99)))))
PFAS_X$smoke <- ifelse(PFAS_X$smoke == "former", 0,
                         ifelse(PFAS_X$smoke == "smoke preg", 1,
                         ifelse(PFAS_X$smoke == "xnever", 2, 2)))
PFAS_X$income <- ifelse(PFAS_X$income == 1, 1, 0)
PFAS_X$parity <- ifelse(PFAS_X$parity == 0, 0,
                        ifelse(PFAS_X$parity == 1, 1,
                        ifelse(PFAS_X$parity > 1, 2, 0)))
PFAS_X$married <- ifelse(PFAS_X$married == 1, 1, 0)


##### REFACTOR
PFAS_X$race <- factor(PFAS_X$race,
                        levels = c(0, 1, 2, 3, 4),
                        labels = c("White", "Black", "Hispanic", "Asian", "Other/More than 1 race"))
PFAS_X$edu <- factor(PFAS_X$edu,
                       levels = c(0, 1),
                       labels = c(" < college degree", ">= college degree"))
PFAS_X$bmi_cat <- factor(PFAS_X$bmi_cat,
                       levels = c(0, 1, 2, 3, 4),
                       labels = c("Underweight (< 18.5)", "Normal weight (18.5 to 24.9)", 
                                  "Overweight (25.0 to 29.9)", "Obese (30.0 to 34.9)", 
                                  "Extremely obese (>= 35)"))
PFAS_X$smoke <- factor(PFAS_X$smoke,
                         levels = c(0, 1, 2),
                         labels = c("Former smoker", "Smoked during pregnancy", "Never smoked"))
PFAS_X$income <- factor(PFAS_X$income,
                       levels = c(0, 1),
                       labels = c(" <= $70,000", "> $70,000"))
PFAS_X$parity <- factor(PFAS_X$parity,
                          levels = c(0, 1, 2),
                          labels = c("0", "1", ">= 2"))
PFAS_X$married <- factor(PFAS_X$married,
                          levels = c(0, 1),
                          labels = c("No", "Yes"))

##### LABEL
label(PFAS_X$age_enroll) <- "Maternal age at enrollment"
label(PFAS_X$race) <- "Race/Ethnicity"
label(PFAS_X$edu) <- "Education"
label(PFAS_X$bmi_cat) <- "Pre-pregnancy BMI"
label(PFAS_X$smoke) <- "Smoking status"
label(PFAS_X$income) <- "Annual household income"
label(PFAS_X$parity) <- "Parity"
label(PFAS_X$married) <- "Married or cohabitating"

##### ADD UNITS
units(PFAS_X$age_enroll)  <- "years"
units(PFAS_X$bmi_cat)  <- "kg/m2"

##### TABE 1
table1(~ age_enroll + race + bmi_cat + edu + income + parity + 
         smoke + married, data = PFAS_X, overall = "Total")

```

```{r}
##### ANTHRO DATASET #####

##### PFAS DISTRIBUTION TABLE
summary(PFAS_A$PFOS)
summary(PFAS_A$PFOA)
summary(PFAS_A$PFNA2)
summary(PFAS_A$PFHxS)
summary(PFAS_A$Me_PFOSA_AcOH2)
summary(PFAS_A$Et_PFOSA_AcOH)

# RENAME PFAS FOR THE PLOT
colnames(PFAS_A)[colnames(PFAS_A) == "Me_PFOSA_AcOH2"] <- "MeFOSSA"
colnames(PFAS_A)[colnames(PFAS_A) == "Et_PFOSA_AcOH"] <- "EtFOSSA"
colnames(PFAS_A)[colnames(PFAS_A) == "PFNA2"] <- "PFNA"

##### PFAS CORRELATION MATRIX
PFAS_A_corr <- PFAS_A[ , c("PFOS", "PFOA", "PFNA", "PFHxS", "MeFOSSA", "EtFOSSA")]
p_corr <- cor(PFAS_A_corr)
round(p_corr, 2)

corrplot(p_corr, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)

```

```{r}
##### ANTHRO + DXA DATASET #####

##### PFAS DISTRIBUTION TABLE
summary(PFAS_D$PFOS)
summary(PFAS_D$PFOA)
summary(PFAS_D$PFNA2)
summary(PFAS_D$PFHxS)
summary(PFAS_D$Me_PFOSA_AcOH2)
summary(PFAS_D$Et_PFOSA_AcOH)

# RENAME PFAS FOR THE PLOT
colnames(PFAS_D)[colnames(PFAS_D) == "Me_PFOSA_AcOH2"] <- "MeFOSSA"
colnames(PFAS_D)[colnames(PFAS_D) == "Et_PFOSA_AcOH"] <- "EtFOSSA"
colnames(PFAS_D)[colnames(PFAS_D) == "PFNA2"] <- "PFNA"

##### PFAS CORRELATION MATRIX
PFAS_D_corr <- PFAS_D[ , c("PFOS", "PFOA", "PFNA", "PFHxS", "MeFOSSA", "EtFOSSA")]
p_corr <- cor(PFAS_D_corr)
round(p_corr, 2)

corrplot(p_corr, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)


```

```{r}
##### ANTHRO DATASET #####

##### OUTCOMES DISTRIBUTION TABLE
summary(PFAS_A$mom_bmi_MT)
summary(PFAS_A$mom_weight_ma17)
summary(PFAS_A$mom_waist_ma17)
summary(PFAS_A$WHR)
summary(PFAS_A$mom_muac_ma17)
summary(PFAS_A$mom_bodyfat_ma17)
summary(PFAS_A$mom_fat_ma17)
summary(PFAS_A$mom_ffm_ma17)

# RENAME PFAS FOR THE PLOT
colnames(PFAS_A)[colnames(PFAS_A) == "mom_bmi_MT"] <- "BMI"
colnames(PFAS_A)[colnames(PFAS_A) == "mom_weight_ma17"] <- "Weight"
colnames(PFAS_A)[colnames(PFAS_A) == "mom_waist_ma17"] <- "Waist"
colnames(PFAS_A)[colnames(PFAS_A) == "WHR"] <- "WHR"
colnames(PFAS_A)[colnames(PFAS_A) == "mom_muac_ma17"] <- "MUAC"
colnames(PFAS_A)[colnames(PFAS_A) == "mom_bodyfat_ma17"] <- "FatPct"
colnames(PFAS_A)[colnames(PFAS_A) == "mom_fat_ma17"] <- "FatMass"
colnames(PFAS_A)[colnames(PFAS_A) == "mom_ffm_ma17"] <- "FatFreeMass"

##### OUTCOMES CORRELATION MATRIX
OUTCOMES_A_corr <- PFAS_A[ , c("BMI", "Weight","Waist", "WHR", "MUAC", "FatPct", "FatMass", "FatFreeMass")]
o_A_corr <- cor(OUTCOMES_A_corr)
round(o_A_corr, 2)

corrplot(o_A_corr, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)

corrplot.mixed(cor(o_A_corr),
               upper = "circle",
               tl.col = "black")

```

```{r}
##### ANTHRO + DXA DATASET #####

##### OUTCOMES DISTRIBUTION TABLE
summary(PFAS_D$VAT_AREA_mdxa17)
summary(PFAS_D$SAT_AREA_mdxa17)
summary(PFAS_D$TAT_AREA_mdxa17)
summary(PFAS_D$VAT_MASS_mdxa17)
summary(PFAS_D$SAT_MASS_mdxa17)
summary(PFAS_D$TAT_MASS_mdxa17)
summary(PFAS_D$VAT_VOLUME_mdxa17)
summary(PFAS_D$SAT_VOLUME_mdxa17)
summary(PFAS_D$TAT_VOLUME_mdxa17)

# RENAME PFAS FOR THE PLOT
colnames(PFAS_D)[colnames(PFAS_D) == "VAT_AREA_mdxa17"] <- "VT area"
colnames(PFAS_D)[colnames(PFAS_D) == "SAT_AREA_mdxa17"] <- "ST area"
colnames(PFAS_D)[colnames(PFAS_D) == "TAT_AREA_mdxa17"] <- "TT area"
colnames(PFAS_D)[colnames(PFAS_D) == "VAT_VOLUME_mdxa17"] <- "VT vol"
colnames(PFAS_D)[colnames(PFAS_D) == "SAT_VOLUME_mdxa17"] <- "ST vol"
colnames(PFAS_D)[colnames(PFAS_D) == "TAT_VOLUME_mdxa17"] <- "TT vol"
colnames(PFAS_D)[colnames(PFAS_D) == "VAT_MASS_mdxa17"] <- "VT mass"
colnames(PFAS_D)[colnames(PFAS_D) == "SAT_MASS_mdxa17"] <- "ST mass"
colnames(PFAS_D)[colnames(PFAS_D) == "TAT_MASS_mdxa17"] <- "TT mass"


##### OUTCOMES CORRELATION MATRIX
OUTCOMES_D_corr <- PFAS_D[ , c("VT area", "ST area", "TT area", "VT vol", "ST vol", 
                               "TT vol", "VT mass", "ST mass", "TT mass")]
o_D_corr <- cor(OUTCOMES_D_corr)
round(o_D_corr, 2)

corrplot(o_D_corr, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)

corrplot.mixed(cor(o_D_corr),
               upper = "circle",
               tl.col = "black")

```

```{r}
##### SAVE DATASET
write.csv(PFAS_A, file = "C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/PFAS_A.csv", row.names = T)
write.csv(PFAS_D, file = "C:/Users/jarva/Desktop/James-Todd Lab/PFASandAdiposity/Data/PFAS_D.csv", row.names = T)

```
