#####                                                       #####
##### PRE-LIMINARY ANALYSIS                                 #####
#####                                                       #####

```{r}
##### LOAD PACKAGES
library("tidyverse")
library("modelsummary")
library("kableExtra")
library("gt")
library("shiny")
library("olsrr")
library("dplyr")

```

```{r}
##### LOAD DATASET
PFAS_A <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/P3.PFASandAdiposity/Data/PFAS_A.csv")
PFAS_D <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/P3.PFASandAdiposity/Data/PFAS_D.csv")

```

```{r}
##### PREPARE VARIABLES FOR LINEAR REGRESSION

# SET CATEGORICAL VARIABLES AS FACTORS
PFAS_A$bmi_cat <- as.factor(PFAS_A$bmi_cat)
PFAS_A$race <- as.factor(PFAS_A$race)
PFAS_A$income <- as.factor(PFAS_A$income)
PFAS_A$parity <- as.factor(PFAS_A$parity)
PFAS_A$smoke <- as.factor(PFAS_A$smoke)
PFAS_A$married <- as.factor(PFAS_A$married)
PFAS_A$edu <- as.factor(PFAS_A$edu)

PFAS_D$bmi_cat <- as.factor(PFAS_D$bmi_cat)
PFAS_D$race <- as.factor(PFAS_D$race)
PFAS_D$income <- as.factor(PFAS_D$income)
PFAS_D$parity <- as.factor(PFAS_D$parity)
PFAS_D$smoke <- as.factor(PFAS_D$smoke)
PFAS_D$married <- as.factor(PFAS_D$married)
PFAS_D$edu <- as.factor(PFAS_D$edu)

```

```{r}
##### RUN ADJUSTED LINEAR REGRESSION MODELS, ANTHRO DATASET (N = 545)

# BMI
ad1.l2m.lnbmi <- list(
  "PFOS" = glm(LNBMI ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFOA" = glm(LNBMI ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFNA" = glm(LNBMI ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(LNBMI ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(LNBMI ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(LNBMI ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A))

modelsummary(ad1.l2m.lnbmi, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-BMI (Adjusted)")

ad2.l2m.lnbmi <- list(
  "PFOS" = glm(LNBMI ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "PFOA" = glm(LNBMI ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "PFNA" = glm(LNBMI ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(LNBMI ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(LNBMI ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(LNBMI ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi_cat, family = gaussian, data = PFAS_A))

modelsummary(ad2.l2m.lnbmi, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-BMI (Adjusted, BMI Cat)")

ad3.l2m.lnbmi <- list(
  "PFOS" = glm(LNBMI ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFOA" = glm(LNBMI ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFNA" = glm(LNBMI ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(LNBMI ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married + bmi, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(LNBMI ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(LNBMI ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi, family = gaussian, data = PFAS_A))

modelsummary(ad3.l2m.lnbmi, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-BMI (Adjusted, BMI)")


# DIFFERENCE IN BMI
ad1.l2m.dbmi <- list(
  "PFOS" = glm(DBMI ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFOA" = glm(DBMI ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFNA" = glm(DBMI ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(DBMI ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(DBMI ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(DBMI ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A))

modelsummary(ad1.l2m.dbmi, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. DIFF IN BMI (Adjusted)")

ad2.l2m.dbmi <- list(
  "PFOS" = glm(DBMI ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "PFOA" = glm(DBMI ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "PFNA" = glm(DBMI ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(DBMI ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(DBMI ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(DBMI ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi_cat, family = gaussian, data = PFAS_A))

modelsummary(ad2.l2m.dbmi, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. DIFF IN BMI (Adjusted, BMI Cat)")

ad3.l2m.dbmi <- list(
  "PFOS" = glm(DBMI ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFOA" = glm(DBMI ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFNA" = glm(DBMI ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(DBMI ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married + bmi, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(DBMI ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(DBMI ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi, family = gaussian, data = PFAS_A))

modelsummary(ad3.l2m.dbmi, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. DIFF IN BMI (Adjusted, BMI)")


# WAIST CIRCUMFERENCE
ad1.l2m.waist <- list(
  "PFOS" = glm(Waist ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFOA" = glm(Waist ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFNA" = glm(Waist ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(Waist ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(Waist ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(Waist ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A))

modelsummary(ad1.l2m.waist, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WAIST CIRCUMFERENCE (Adjusted)")

ad2.l2m.waist <- list(
  "PFOS" = glm(Waist ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "PFOA" = glm(Waist ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "PFNA" = glm(Waist ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(Waist ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(Waist ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(Waist ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi_cat, family = gaussian, data = PFAS_A))

modelsummary(ad2.l2m.waist, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WAIST CIRCUMFERENCE (Adjusted, BMI Cat)")

ad3.l2m.waist <- list(
  "PFOS" = glm(Waist ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFOA" = glm(Waist ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFNA" = glm(Waist ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(Waist ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married + bmi, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(Waist ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(Waist ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi, family = gaussian, data = PFAS_A))

modelsummary(ad3.l2m.waist, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WAIST CIRCUMFERENCE (Adjusted, BMI)")


# WAIST-TO-HIP RATIO
ad1.l2m.whr <- list(
  "PFOS" = glm(WHR ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFOA" = glm(WHR ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFNA" = glm(WHR ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(WHR ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(WHR ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(WHR ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A))

modelsummary(ad1.l2m.whr, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WHR (Adjusted)")

ad2.l2m.whr <- list(
  "PFOS" = glm(WHR ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "PFOA" = glm(WHR ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "PFNA" = glm(WHR ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(WHR ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(WHR ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(WHR ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi_cat, family = gaussian, data = PFAS_A))

modelsummary(ad2.l2m.whr, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WHR (Adjusted, BMI Cat)")

ad3.l2m.whr <- list(
  "PFOS" = glm(WHR ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFOA" = glm(WHR ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFNA" = glm(WHR ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(WHR ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married + bmi, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(WHR ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(WHR ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi, family = gaussian, data = PFAS_A))

modelsummary(ad3.l2m.whr, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WHR (Adjusted, BMI)")


# WAIST-TO-HEIGHT RATIO
ad1.l2m.whtr <- list(
  "PFOS" = glm(WHtR ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFOA" = glm(WHtR ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFNA" = glm(WHtR ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(WHtR ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(WHtR ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(WHtR ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A))

modelsummary(ad1.l2m.whtr, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WHtR (Adjusted)")

ad3.l2m.whtr <- list(
  "PFOS" = glm(WHtR ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFOA" = glm(WHtR ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFNA" = glm(WHtR ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(WHtR ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married + bmi, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(WHtR ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(WHtR ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi, family = gaussian, data = PFAS_A))

modelsummary(ad3.l2m.whtr, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WHtR (Adjusted, BMI)")

ad2.l2m.whtr <- list(
  "PFOS" = glm(WHtR ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "PFOA" = glm(WHtR ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "PFNA" = glm(WHtR ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(WHtR ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(WHtR ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(WHtR ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi_cat, family = gaussian, data = PFAS_A))

modelsummary(ad2.l2m.whtr, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WHtR (Adjusted, BMI Cat)")

ad3.l2m.whtr <- list(
  "PFOS" = glm(WHtR ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFOA" = glm(WHtR ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFNA" = glm(WHtR ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(WHtR ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married + bmi, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(WHtR ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(WHtR ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi, family = gaussian, data = PFAS_A))

modelsummary(ad3.l2m.whtr, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WHtR (Adjusted, BMI)")


# MUAC
ad1.l2m.muac <- list(
  "PFOS" = glm(MUAC ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFOA" = glm(MUAC ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFNA" = glm(MUAC ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(MUAC ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(MUAC ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(MUAC ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married, family = gaussian, data = PFAS_A))

modelsummary(ad1.l2m.muac, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. MUAC (Adjusted)")

ad2.l2m.muac <- list(
  "PFOS" = glm(MUAC ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "PFOA" = glm(MUAC ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "PFNA" = glm(MUAC ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(MUAC ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(MUAC ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi_cat, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(MUAC ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi_cat, family = gaussian, data = PFAS_A))

modelsummary(ad2.l2m.muac, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. MUAC (Adjusted, BMI Cat)")

ad3.l2m.muac <- list(
  "PFOS" = glm(MUAC ~ L2PFOS + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFOA" = glm(MUAC ~ L2PFOA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFNA" = glm(MUAC ~ L2PFNA + age_enroll + race + income + menar + smoke +  
                 parity + married + bmi, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(MUAC ~ L2PFHxS + age_enroll + race + income + menar + smoke +  
                  parity + married + bmi, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(MUAC ~ L2MeFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(MUAC ~ L2EtFOSAA + age_enroll + race + income + menar + smoke +  
                    parity + married + bmi, family = gaussian, data = PFAS_A))

modelsummary(ad3.l2m.muac, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. MUAC (Adjusted, BMI)")

```


```{r}
##### RUN ADJUSTED LINEAR REGRESSION MODELS, ANTHRO + DXA DATASET (N = 432)

# TRUNK FAT MASS
ad1.l2m.lntrnkfat <- list(
  "PFOS" = glm(LNTKNFAT ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTKNFAT ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTKNFAT ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTKNFAT ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(LNTKNFAT ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(LNTKNFAT ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D))

modelsummary(ad1.l2m.lntrnkfat, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-TRUNK FAT MASS (Adjusted)")

ad2.l2m.lntrnkfat <- list(
  "PFOS" = glm(LNTKNFAT ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTKNFAT ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTKNFAT ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTKNFAT ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(LNTKNFAT ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(LNTKNFAT ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married + bmi_cat, family = gaussian, data = PFAS_D))

modelsummary(ad2.l2m.lntrnkfat, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-TRUNK FAT MASS (Adjusted, BMI Cat)")

ad3.l2m.lntrnkfat <- list(
  "PFOS" = glm(LNTKNFAT ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTKNFAT ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTKNFAT ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTKNFAT ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married + bmi, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(LNTKNFAT ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married + bmi, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(LNTKNFAT ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married + bmi, family = gaussian, data = PFAS_D))

modelsummary(ad3.l2m.lntrnkfat, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-TRUNK FAT MASS (Adjusted, BMI)")


# TOTAL BODY FAT MASS
ad1.l2m.lntotfat <- list(
  "PFOS" = glm(LNTOTFAT ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTOTFAT ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTOTFAT ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTOTFAT ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(LNTOTFAT ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(LNTOTFAT ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D))

modelsummary(ad1.l2m.lntotfat, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-TOTAL BODY FAT MASS (Adjusted)")

ad2.l2m.lntotfat <- list(
  "PFOS" = glm(LNTOTFAT ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTOTFAT ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTOTFAT ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTOTFAT ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(LNTOTFAT ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(LNTOTFAT ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married + bmi_cat, family = gaussian, data = PFAS_D))

modelsummary(ad2.l2m.lntotfat, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-TOTAL BODY FAT MASS (Adjusted, BMI Cat)")

ad3.l2m.lntotfat <- list(
  "PFOS" = glm(LNTOTFAT ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTOTFAT ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTOTFAT ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTOTFAT ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married + bmi, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(LNTOTFAT ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married + bmi, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(LNTOTFAT ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married + bmi, family = gaussian, data = PFAS_D))

modelsummary(ad3.l2m.lntotfat, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-TOTAL BODY FAT MASS (Adjusted, BMI)")


# TRUNK FAT MASS INDEX
ad1.l2m.lntfin <- list(
  "PFOS" = glm(LNTFIN ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTFIN ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTFIN ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTFIN ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(LNTFIN ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(LNTFIN ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D))

modelsummary(ad1.l2m.lntfin, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-TRUNK FAT MASS INDEX (Adjusted)")

ad2.l2m.lntfin <- list(
  "PFOS" = glm(LNTFIN ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTFIN ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTFIN ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTFIN ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(LNTFIN ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(LNTFIN ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married + bmi_cat, family = gaussian, data = PFAS_D))

modelsummary(ad2.l2m.lntfin, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-TRUNK FAT MASS INDEX (Adjusted, BMI Cat)")

ad3.l2m.lntfin <- list(
  "PFOS" = glm(LNTFIN ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTFIN ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTFIN ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTFIN ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married + bmi, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(LNTFIN ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married + bmi, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(LNTFIN ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married + bmi, family = gaussian, data = PFAS_D))

modelsummary(ad3.l2m.lntfin, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-TRUNK FAT MASS INDEX (Adjusted, BMI)")


# TOTAL BODY FAT MASS INDEX
ad1.l2m.lnbfin <- list(
  "PFOS" = glm(LNBFIN ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNBFIN ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNBFIN ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNBFIN ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(LNBFIN ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(LNBFIN ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D))

modelsummary(ad1.l2m.lnbfin, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-TOTAL BODY FAT MASS INDEX (Adjusted)")

ad2.l2m.lnbfin <- list(
  "PFOS" = glm(LNBFIN ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNBFIN ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNBFIN ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNBFIN ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(LNBFIN ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(LNBFIN ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married + bmi_cat, family = gaussian, data = PFAS_D))

modelsummary(ad2.l2m.lnbfin, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-TOTAL BODY FAT MASS INDEX (Adjusted, BMI Cat)")

ad3.l2m.lnbfin <- list(
  "PFOS" = glm(LNBFIN ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNBFIN ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNBFIN ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNBFIN ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married + bmi, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(LNBFIN ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married + bmi, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(LNBFIN ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married + bmi, family = gaussian, data = PFAS_D))

modelsummary(ad3.l2m.lnbfin, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-TOTAL BODY FAT MASS INDEX (Adjusted, BMI)")


# TOTAL BODY FAT %
ad1.l2m.totpfat <- list(
  "PFOS" = glm(TotFatPct ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFOA" = glm(TotFatPct ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFNA" = glm(TotFatPct ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(TotFatPct ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(TotFatPct ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(TotFatPct ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married, family = gaussian, data = PFAS_D))

modelsummary(ad1.l2m.totpfat, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. TOTAL BODY FAT % (Adjusted)")

ad2.l2m.totpfat <- list(
  "PFOS" = glm(TotFatPct ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "PFOA" = glm(TotFatPct ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "PFNA" = glm(TotFatPct ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(TotFatPct ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(TotFatPct ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married + bmi_cat, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(TotFatPct ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married + bmi_cat, family = gaussian, data = PFAS_D))

modelsummary(ad2.l2m.totpfat, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. TOTAL BODY FAT % (Adjusted, BMI Cat)")

ad3.l2m.totpfat <- list(
  "PFOS" = glm(TotFatPct ~ L2PFOS + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi, family = gaussian, data = PFAS_D),
  "PFOA" = glm(TotFatPct ~ L2PFOA + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi, family = gaussian, data = PFAS_D),
  "PFNA" = glm(TotFatPct ~ L2PFNA + age_enroll + race + income + menar + smoke + 
                 parity + married + bmi, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(TotFatPct ~ L2PFHxS + age_enroll + race + income + menar + smoke + 
                  parity + married + bmi, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(TotFatPct ~ L2MeFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married + bmi, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(TotFatPct ~ L2EtFOSAA + age_enroll + race + income + menar + smoke + 
                    parity + married + bmi, family = gaussian, data = PFAS_D))

modelsummary(ad3.l2m.totpfat, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. TOTAL BODY FAT % (Adjusted, BMI)")

```

```{r}
##### EMPLOY FDR CORRECTION
PFAS_A <- PFAS_A %>% relocate(aid, L2PFOS, L2PFOA, L2PFNA, L2PFHxS, L2MeFOSAA, L2EtFOSAA, everything()) 
PFAS_D <- PFAS_D %>% relocate(aid, L2PFOS, L2PFOA, L2PFNA, L2PFHxS, L2MeFOSAA, L2EtFOSAA, everything()) 

# BMI
pval_BMI <- NULL
for (i in 2:7){
m_BMI <- glm(PFAS_A$LNBMI ~ PFAS_A[[i]] + PFAS_A$age_enroll + PFAS_A$race + 
                PFAS_A$income + PFAS_A$menar + PFAS_A$smoke +  PFAS_A$parity + 
                PFAS_A$married, family = gaussian)
p_BMI <- summary(m_BMI)$coefficients[2,]
pval_BMI <- rbind(pval_BMI, p_BMI)
rownames(pval_BMI)[i-1] <- paste("X", i-1, sep="")
}

pval_BMI_set <- pval_BMI[,4]
BH_BMI <- p.adjust(pval_BMI_set, method="BH")
BY_BMI <- p.adjust(pval_BMI_set, method="BY")
FDR_BMI <- p.adjust(pval_BMI_set, method="fdr")
FWER_BMI <- as.data.frame(cbind(pval_BMI_set, BH_BMI, BY_BMI, FDR_BMI))
FWER_BMI


# Waist
pval_Waist <- NULL
for (i in 2:7){
m_Waist <- glm(PFAS_A$Waist ~ PFAS_A[[i]] + PFAS_A$age_enroll + PFAS_A$race + 
                PFAS_A$income + PFAS_A$menar + PFAS_A$smoke +  PFAS_A$parity + 
                PFAS_A$married, family = gaussian)
p_Waist <- summary(m_Waist)$coefficients[2,]
pval_Waist <- rbind(pval_Waist, p_Waist)
rownames(pval_Waist)[i-1] <- paste("X", i-1, sep="")
}

pval_Waist_set <- pval_Waist[,4]
BH_Waist <- p.adjust(pval_Waist_set, method="BH")
BY_Waist <- p.adjust(pval_Waist_set, method="BY")
FDR_Waist <- p.adjust(pval_Waist_set, method="fdr")
FWER_Waist <- as.data.frame(cbind(pval_Waist_set, BH_Waist, BY_Waist, FDR_Waist))
FWER_Waist


# WHR
pval_WHR <- NULL
for (i in 2:7){
m_WHR <- glm(PFAS_A$WHR ~ PFAS_A[[i]] + PFAS_A$age_enroll + PFAS_A$race + 
                PFAS_A$income + PFAS_A$menar + PFAS_A$smoke +  PFAS_A$parity + 
                PFAS_A$married, family = gaussian)
p_WHR <- summary(m_WHR)$coefficients[2,]
pval_WHR <- rbind(pval_WHR, p_WHR)
rownames(pval_WHR)[i-1] <- paste("X", i-1, sep="")
}

pval_WHR_set <- pval_WHR[,4]
BH_WHR <- p.adjust(pval_WHR_set, method="BH")
BY_WHR <- p.adjust(pval_WHR_set, method="BY")
FDR_WHR <- p.adjust(pval_WHR_set, method="fdr")
FWER_WHR <- as.data.frame(cbind(pval_WHR_set, BH_WHR, BY_WHR, FDR_WHR))
FWER_WHR


# WHtR
pval_WHtR <- NULL
for (i in 2:7){
m_WHtR <- glm(PFAS_A$WHtR ~ PFAS_A[[i]] + PFAS_A$age_enroll + PFAS_A$race + 
                PFAS_A$income + PFAS_A$menar + PFAS_A$smoke +  PFAS_A$parity + 
                PFAS_A$married, family = gaussian)
p_WHtR <- summary(m_WHtR)$coefficients[2,]
pval_WHtR <- rbind(pval_WHtR, p_WHtR)
rownames(pval_WHtR)[i-1] <- paste("X", i-1, sep="")
}

pval_WHtR_set <- pval_WHtR[,4]
BH_WHtR <- p.adjust(pval_WHtR_set, method="BH")
BY_WHtR <- p.adjust(pval_WHtR_set, method="BY")
FDR_WHtR <- p.adjust(pval_WHtR_set, method="fdr")
FWER_WHtR <- as.data.frame(cbind(pval_WHtR_set, BH_WHtR, BY_WHtR, FDR_WHtR))
FWER_WHtR


# MUAC
pval_MUAC <- NULL
for (i in 2:7){
m_MUAC <- glm(PFAS_A$MUAC ~ PFAS_A[[i]] + PFAS_A$age_enroll + PFAS_A$race + 
                PFAS_A$income + PFAS_A$menar + PFAS_A$smoke +  PFAS_A$parity + 
                PFAS_A$married, family = gaussian)
p_MUAC <- summary(m_MUAC)$coefficients[2,]
pval_MUAC <- rbind(pval_MUAC, p_MUAC)
rownames(pval_MUAC)[i-1] <- paste("X", i-1, sep="")
}

pval_MUAC_set <- pval_MUAC[,4]
BH_MUAC <- p.adjust(pval_MUAC_set, method="BH")
BY_MUAC <- p.adjust(pval_MUAC_set, method="BY")
FDR_MUAC <- p.adjust(pval_MUAC_set, method="fdr")
FWER_MUAC <- as.data.frame(cbind(pval_MUAC_set, BH_MUAC, BY_MUAC, FDR_MUAC))
FWER_MUAC


# TRNK
pval_TRNK <- NULL
for (i in 2:7){
m_TRNK <- glm(PFAS_D$LNTKNFAT ~ PFAS_D[[i]] + PFAS_D$age_enroll + PFAS_D$race + 
                PFAS_D$income + PFAS_D$menar + PFAS_D$smoke +  PFAS_D$parity + 
                PFAS_D$married, family = gaussian)
p_TRNK <- summary(m_TRNK)$coefficients[2,]
pval_TRNK <- rbind(pval_TRNK, p_TRNK)
rownames(pval_TRNK)[i-1] <- paste("X", i-1, sep="")
}

pval_TRNK_set <- pval_TRNK[,4]
BH_TRNK <- p.adjust(pval_TRNK_set, method="BH")
BY_TRNK <- p.adjust(pval_TRNK_set, method="BY")
FDR_TRNK <- p.adjust(pval_TRNK_set, method="fdr")
FWER_TRNK <- as.data.frame(cbind(pval_TRNK_set, BH_TRNK, BY_TRNK, FDR_TRNK))
FWER_TRNK


# FAT
pval_FAT <- NULL
for (i in 2:7){
m_FAT <- glm(PFAS_D$LNTOTFAT ~ PFAS_D[[i]] + PFAS_D$age_enroll + PFAS_D$race + 
                PFAS_D$income + PFAS_D$menar + PFAS_D$smoke +  PFAS_D$parity + 
                PFAS_D$married, family = gaussian)
p_FAT <- summary(m_FAT)$coefficients[2,]
pval_FAT <- rbind(pval_FAT, p_FAT)
rownames(pval_FAT)[i-1] <- paste("X", i-1, sep="")
}

pval_FAT_set <- pval_FAT[,4]
BH_FAT <- p.adjust(pval_FAT_set, method="BH")
BY_FAT <- p.adjust(pval_FAT_set, method="BY")
FDR_FAT <- p.adjust(pval_FAT_set, method="fdr")
FWER_FAT <- as.data.frame(cbind(pval_FAT_set, BH_FAT, BY_FAT, FDR_FAT))
FWER_FAT


# TRUNK FAT INDEX
pval_TFIN <- NULL
for (i in 2:7){
m_TFIN <- glm(PFAS_D$LNTFIN ~ PFAS_D[[i]] + PFAS_D$age_enroll + PFAS_D$race + 
                PFAS_D$income + PFAS_D$menar + PFAS_D$smoke +  PFAS_D$parity + 
                PFAS_D$married, family = gaussian)
p_TFIN <- summary(m_TFIN)$coefficients[2,]
pval_TFIN <- rbind(pval_TFIN, p_TFIN)
rownames(pval_TFIN)[i-1] <- paste("X", i-1, sep="")
}

pval_TFIN_set <- pval_TFIN[,4]
BH_TFIN <- p.adjust(pval_TFIN_set, method="BH")
BY_TFIN <- p.adjust(pval_TFIN_set, method="BY")
FDR_TFIN <- p.adjust(pval_TFIN_set, method="fdr")
FWER_TFIN <- as.data.frame(cbind(pval_TFIN_set, BH_TFIN, BY_TFIN, FDR_TFIN))
FWER_TFIN


# BODY FAT INDEX
pval_BFIN <- NULL
for (i in 2:7){
m_BFIN <- glm(PFAS_D$LNBFIN ~ PFAS_D[[i]] + PFAS_D$age_enroll + PFAS_D$race + 
                PFAS_D$income + PFAS_D$menar + PFAS_D$smoke +  PFAS_D$parity + 
                PFAS_D$married, family = gaussian)
p_BFIN <- summary(m_BFIN)$coefficients[2,]
pval_BFIN <- rbind(pval_BFIN, p_BFIN)
rownames(pval_BFIN)[i-1] <- paste("X", i-1, sep="")
}

pval_BFIN_set <- pval_BFIN[,4]
BH_BFIN <- p.adjust(pval_BFIN_set, method="BH")
BY_BFIN <- p.adjust(pval_BFIN_set, method="BY")
FDR_BFIN <- p.adjust(pval_BFIN_set, method="fdr")
FWER_BFIN <- as.data.frame(cbind(pval_BFIN_set, BH_BFIN, BY_BFIN, FDR_BFIN))
FWER_BFIN


# PFAT
pval_PFAT <- NULL
for (i in 2:7){
m_PFAT <- glm(PFAS_D$TotFatPct ~ PFAS_D[[i]] + PFAS_D$age_enroll + PFAS_D$race + 
                PFAS_D$income + PFAS_D$menar + PFAS_D$smoke +  PFAS_D$parity + 
                PFAS_D$married, family = gaussian)
p_PFAT <- summary(m_PFAT)$coefficients[2,]
pval_PFAT <- rbind(pval_PFAT, p_PFAT)
rownames(pval_PFAT)[i-1] <- paste("X", i-1, sep="")
}

pval_PFAT_set <- pval_PFAT[,4]
BH_PFAT <- p.adjust(pval_PFAT_set, method="BH")
BY_PFAT <- p.adjust(pval_PFAT_set, method="BY")
FDR_PFAT <- p.adjust(pval_PFAT_set, method="fdr")
FWER_PFAT <- as.data.frame(cbind(pval_PFAT_set, BH_PFAT, BY_PFAT, FDR_PFAT))
FWER_PFAT

```
