#####                                                       #####
##### PRE-LIMINARY ANALYSIS: SENSITIVITY ANANLYSIS (IPCW)   #####
#####                                                       #####

```{r message=FALSE, warning=FALSE}
##### LOAD PACKAGES
library("tidyverse")
library("modelsummary")
library("kableExtra")
library("gt")
library("shiny")
library("olsrr")

```

```{r message=FALSE, warning=FALSE}
##### LOAD DATASET
PFAS_IPW <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/P3.PFASandAdiposity/Data/PFAS_IPW_COMP.csv")
PFAS_A <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/P3.PFASandAdiposity/Data/PFAS_A.csv")
PFAS_D <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/P3.PFASandAdiposity/Data/PFAS_D.csv")

```

```{r}
##### PREPARE DATASET FOR WEIGHTED REGRESSION
PFAS_IPW$Weight <- PFAS_IPW$mom_weight_ma17
PFAS_IPW$Waist <- PFAS_IPW$mom_waist_ma17
# PFAS_IPW$LNBMI <- log(PFAS_IPW$mom_bmi_MT)
# PFAS_IPW$MUAC <- PFAS_IPW$mom_muac_ma17
PFAS_IPW$TrnkFat <- PFAS_IPW$TRUNK_FAT_mdxa17
PFAS_IPW$TotFat <- PFAS_IPW$WBTOT_FAT_mdxa17
# PFAS_IPW$TotFatPct <- PFAS_IPW$WBTOT_PFAT_mdxa17

# CREATE INDICATOR VARIABLES TO TELL US WHO WAS CENSORED
PFAS_IPW$a.cens <- ifelse(is.na(PFAS_IPW$Weight) | is.na(PFAS_IPW$Waist), 1, 0)
PFAS_IPW$d.cens <- ifelse(is.na(PFAS_IPW$TrnkFat) | is.na(PFAS_IPW$TotFat), 1, 0)

table(PFAS_IPW$a.cens)
table(PFAS_IPW$d.cens)

```

```{r}
##### PREPARE VARIABLES FOR WEIGHTS AND LINEAR REGRESSION
PFAS_IPW$L2PFOS <- log(PFAS_IPW$PFOS, 2)
PFAS_IPW$L2PFOA <- log(PFAS_IPW$PFOA, 2)
PFAS_IPW$L2PFNA <- log(PFAS_IPW$PFNA2, 2)
PFAS_IPW$L2PFHxS <- log(PFAS_IPW$PFHxS, 2)
PFAS_IPW$L2MeFOSAA <- log(PFAS_IPW$Me_PFOSA_AcOH2, 2)
PFAS_IPW$L2EtFOSAA <- log(PFAS_IPW$Et_PFOSA_AcOH, 2)


##### RENAME
PFAS_IPW$height <- PFAS_IPW$mom_height_ma17
PFAS_IPW$age <- PFAS_IPW$age_mom_enroll_d
PFAS_IPW$race <- PFAS_IPW$race2_mom_epi_epia_d
PFAS_IPW$edu <- PFAS_IPW$coll_grad
PFAS_IPW$menar <- PFAS_IPW$mom_firstperiod_12y
PFAS_IPW$bmi <- PFAS_IPW$bmi_mom_prepreg_d
PFAS_IPW$smoke <- PFAS_IPW$smokpreg_final_d
PFAS_IPW$income <- PFAS_IPW$gt70k
PFAS_IPW$parity <- PFAS_IPW$parity_d
PFAS_IPW$married <- PFAS_IPW$married_cohab
PFAS_IPW$fish <- PFAS_IPW$fish_d_f1
PFAS_IPW$darkmeat <- PFAS_IPW$dark_meat_f1
PFAS_IPW$exer <- PFAS_IPW$mod_pre_d + PFAS_IPW$vig_pre_d


##### RE-LABEL 
PFAS_IPW$race <- ifelse(PFAS_IPW$race == "white", 0,
                     ifelse(PFAS_IPW$race == "black", 1,
                     ifelse(PFAS_IPW$race == "hispa", 2,
                     ifelse(PFAS_IPW$race == "asian", 3,
                     ifelse(PFAS_IPW$race == "other", 4, 4)))))
PFAS_IPW$edu <- ifelse(PFAS_IPW$edu == 1, 1, 0)
PFAS_IPW$bmi_cat <- ifelse(PFAS_IPW$bmi <18.5, 0,
                         ifelse(PFAS_IPW$bmi >=18.5 & PFAS_IPW$bmi < 25.0, 1, 
                         ifelse(PFAS_IPW$bmi >=25.0 & PFAS_IPW$bmi < 30.0, 2, 
                         ifelse(PFAS_IPW$bmi >=30.0 & PFAS_IPW$bmi < 35.0, 3,
                         ifelse(PFAS_IPW$bmi >=35.0, 4, 99)))))
PFAS_IPW$bmi_yn <- ifelse(PFAS_IPW$bmi <25.0, 0, 1)
PFAS_IPW$smoke <- ifelse(PFAS_IPW$smoke == "former", 0,
                         ifelse(PFAS_IPW$smoke == "smoke preg", 1,
                         ifelse(PFAS_IPW$smoke == "xnever", 2, 2)))
PFAS_IPW$income <- ifelse(PFAS_IPW$income == 1, 1, 0)
PFAS_IPW$parity <- ifelse(PFAS_IPW$parity == 0, 0,
                        ifelse(PFAS_IPW$parity == 1, 1,
                        ifelse(PFAS_IPW$parity > 1, 2, 0)))
PFAS_IPW$married <- ifelse(PFAS_IPW$married == 1, 1, 0)
PFAS_IPW$exer_cat <- ifelse(PFAS_IPW$exer <= 0, 0, 1)
PFAS_IPW$meno_cat <- ifelse(PFAS_IPW$mom_period_stopped_qu17 == 2, 0,
                        ifelse(PFAS_IPW$mom_period_stopped_qu17 == 1, 1, NA))


##### REFACTOR
PFAS_IPW$race <- factor(PFAS_IPW$race,
                        levels = c(0, 1, 2, 3, 4),
                        labels = c("White", "Black", "Hispanic", "Asian", "Other/More than 1 race"))
PFAS_IPW$edu <- factor(PFAS_IPW$edu,
                       levels = c(0, 1),
                       labels = c(" < college degree", ">= college degree"))
PFAS_IPW$bmi_cat <- factor(PFAS_IPW$bmi_cat,
                       levels = c(0, 1, 2, 3, 4),
                       labels = c("Underweight (< 18.5)", "Normal weight (18.5 to 24.9)", 
                                  "Overweight (25.0 to 29.9)", "Obese (30.0 to 34.9)", 
                                  "Extremely obese (>= 35)"))
PFAS_IPW$smoke <- factor(PFAS_IPW$smoke,
                         levels = c(0, 1, 2),
                         labels = c("Former smoker", "Smoked during pregnancy", "Never smoked"))
PFAS_IPW$income <- factor(PFAS_IPW$income,
                       levels = c(0, 1),
                       labels = c(" <= $70,000", "> $70,000"))
PFAS_IPW$parity <- factor(PFAS_IPW$parity,
                          levels = c(0, 1, 2),
                          labels = c("0", "1", ">= 2"))
PFAS_IPW$married <- factor(PFAS_IPW$married,
                          levels = c(0, 1),
                          labels = c("No", "Yes"))


# SET CATEGORICAL VARIABLES AS FACTORS
PFAS_IPW$bmi_cat <- as.factor(PFAS_IPW$bmi_cat)
PFAS_IPW$bmi_yn <- as.factor(PFAS_IPW$bmi_yn)
PFAS_IPW$edu <- as.factor(PFAS_IPW$edu)
PFAS_IPW$income <- as.factor(PFAS_IPW$income)
PFAS_IPW$smoke <- as.factor(PFAS_IPW$smoke)
PFAS_IPW$parity <- as.factor(PFAS_IPW$parity)
PFAS_IPW$race <- as.factor(PFAS_IPW$race)
PFAS_IPW$married <- as.factor(PFAS_IPW$married)
PFAS_IPW$meno_cat <- as.factor(PFAS_IPW$meno_cat)

PFAS_A$edu <- as.factor(PFAS_A$edu)
PFAS_A$income <- as.factor(PFAS_A$income)
PFAS_A$smoke <- as.factor(PFAS_A$smoke)
PFAS_A$parity <- as.factor(PFAS_A$parity)
PFAS_A$race <- as.factor(PFAS_A$race)
PFAS_A$married <- as.factor(PFAS_A$married)

PFAS_D$edu <- as.factor(PFAS_D$edu)
PFAS_D$income <- as.factor(PFAS_D$income)
PFAS_D$smoke <- as.factor(PFAS_D$smoke)
PFAS_D$parity <- as.factor(PFAS_D$parity)
PFAS_D$race <- as.factor(PFAS_D$race)
PFAS_D$married <- as.factor(PFAS_D$married)

```

```{r}
##### PREPARE VARIABLES FOR LINEAR REGRESSION

# RENAME
PFAS_A$age <- PFAS_A$age_mom_enroll_d
PFAS_A$menar <- PFAS_A$mom_firstperiod_12y
PFAS_A$bmi <- PFAS_A$bmi_mom_prepreg_d
PFAS_A$race <- PFAS_A$race2_mom_epi_epia_d
PFAS_A$income <- PFAS_A$gt70k
PFAS_A$parity <- PFAS_A$parity_d
PFAS_A$smoke <- PFAS_A$smokpreg_final_d
PFAS_A$married <- PFAS_A$married_cohab
PFAS_A$edu <- PFAS_A$coll_grad
PFAS_A$fish <- PFAS_A$fish_d_f1
PFAS_A$darkmeat <- PFAS_A$dark_meat_f1

# REFACTOR AND RELABEL 
PFAS_A$bmi_yn <- ifelse(PFAS_A$bmi <25.0, 0, 1)
PFAS_A$bmi_cat <- ifelse(PFAS_A$bmi <18.5, 0,
                         ifelse(PFAS_A$bmi >=18.5 & PFAS_A$bmi < 25.0, 1, 
                                ifelse(PFAS_A$bmi >=25.0 & PFAS_A$bmi < 30.0, 2, 
                                       ifelse(PFAS_A$bmi >=30.0 & PFAS_A$bmi < 35.0, 3,
                                              ifelse(PFAS_A$bmi >=35.0, 4, NA)))))
PFAS_A$race <- ifelse(PFAS_A$race == "white", 0,
                      ifelse(PFAS_A$race == "black", 1,
                             ifelse(PFAS_A$race == "hispa", 2,
                                    ifelse(PFAS_A$race == "asian", 3,
                                           ifelse(PFAS_A$race == "other", 4, 4)))))
PFAS_A$income <- ifelse(PFAS_A$income == 1, 1, 0)
PFAS_A$parity <- ifelse(PFAS_A$parity == 0, 0,
                        ifelse(PFAS_A$parity == 1, 1,
                               ifelse(PFAS_A$parity > 1, 2, 0)))
PFAS_A$smoke <- ifelse(PFAS_A$smoke == "former", 0,
                       ifelse(PFAS_A$smoke == "smoke preg", 1,
                              ifelse(PFAS_A$smoke == "xnever", 2, 2)))
PFAS_A$married <- ifelse(PFAS_A$married == 1, 1, 0)
PFAS_A$edu <- ifelse(PFAS_A$edu == 1, 1, 0)

# SET CATEGORICAL VARIABLES AS FACTORS
PFAS_A$bmi_yn <- as.factor(PFAS_A$bmi_yn)
PFAS_A$bmi_cat <- as.factor(PFAS_A$bmi_cat)
PFAS_A$race <- as.factor(PFAS_A$race)
PFAS_A$income <- as.factor(PFAS_A$income)
PFAS_A$parity <- as.factor(PFAS_A$parity)
PFAS_A$smoke <- as.factor(PFAS_A$smoke)
PFAS_A$married <- as.factor(PFAS_A$married)
PFAS_A$edu <- as.factor(PFAS_A$edu)
PFAS_A$meno_cat <- as.factor(PFAS_A$meno_cat)

```

```{r}
##### PREPARE VARIABLES FOR LINEAR REGRESSION

# RENAME
PFAS_D$age <- PFAS_D$age_mom_enroll_d
PFAS_D$menar <- PFAS_D$mom_firstperiod_12y
PFAS_D$bmi <- PFAS_D$bmi_mom_prepreg_d
PFAS_D$race <- PFAS_D$race2_mom_epi_epia_d
PFAS_D$income <- PFAS_D$gt70k
PFAS_D$parity <- PFAS_D$parity_d
PFAS_D$smoke <- PFAS_D$smokpreg_final_d
PFAS_D$married <- PFAS_D$married_cohab
PFAS_D$edu <- PFAS_D$coll_grad
PFAS_D$fish <- PFAS_D$fish_d_f1
PFAS_D$darkmeat <- PFAS_D$dark_meat_f1

# REFACTOR AND RELABEL 
PFAS_D$bmi_yn <- ifelse(PFAS_D$bmi <25.0, 0, 1)
PFAS_D$bmi_cat <- ifelse(PFAS_D$bmi <18.5, 0,
                         ifelse(PFAS_D$bmi >=18.5 & PFAS_D$bmi < 25.0, 1, 
                                ifelse(PFAS_D$bmi >=25.0 & PFAS_D$bmi < 30.0, 2, 
                                       ifelse(PFAS_D$bmi >=30.0 & PFAS_D$bmi < 35.0, 3,
                                              ifelse(PFAS_D$bmi >=35.0, 4, NA)))))
PFAS_D$race <- ifelse(PFAS_D$race == "white", 0,
                      ifelse(PFAS_D$race == "black", 1,
                             ifelse(PFAS_D$race == "hispa", 2,
                                    ifelse(PFAS_D$race == "asian", 3,
                                           ifelse(PFAS_D$race == "other", 4, 4)))))
PFAS_D$income <- ifelse(PFAS_D$income == 1, 1, 0)
PFAS_D$parity <- ifelse(PFAS_D$parity == 0, 0,
                        ifelse(PFAS_D$parity == 1, 1,
                               ifelse(PFAS_D$parity > 1, 2, 0)))
PFAS_D$smoke <- ifelse(PFAS_D$smoke == "former", 0,
                       ifelse(PFAS_D$smoke == "smoke preg", 1,
                              ifelse(PFAS_D$smoke == "xnever", 2, 2)))
PFAS_D$married <- ifelse(PFAS_D$married == 1, 1, 0)
PFAS_D$edu <- ifelse(PFAS_D$edu == 1, 1, 0)

# SET CATEGORICAL VARIABLES AS FACTORS
PFAS_D$bmi_yn <- as.factor(PFAS_D$bmi_yn)
PFAS_D$bmi_cat <- as.factor(PFAS_D$bmi_cat)
PFAS_D$race <- as.factor(PFAS_D$race)
PFAS_D$income <- as.factor(PFAS_D$income)
PFAS_D$parity <- as.factor(PFAS_D$parity)
PFAS_D$smoke <- as.factor(PFAS_D$smoke)
PFAS_D$married <- as.factor(PFAS_D$married)
PFAS_D$edu <- as.factor(PFAS_D$edu)
PFAS_D$meno_cat <- as.factor(PFAS_D$meno_cat)

```

```{r}
# model <- lm(a.cens ~ L2PFOS + age + race + bmi_cat + edu + smoke +  
#                  parity + married + exer + fish + darkmeat, data = PFAS_IPW)
# ols_step_best_subset(model)

```

```{r}
##### ESTIMATE THE NUMERATOR OF CENSORING WEIGHTS FOR ANTHRO DATASET
# PFOS
a_n_PFOS <- glm(a.cens ~ L2PFOS, family = binomial(), data = PFAS_IPW)
a_pn_PFOS <- 1-predict(a_n_PFOS, type = "response")

# PFOA
a_n_PFOA <- glm(a.cens ~ L2PFOA, family = binomial(), data = PFAS_IPW)
a_pn_PFOA <- 1-predict(a_n_PFOA, type = "response")

# PFNA
a_n_PFNA <- glm(a.cens ~ L2PFNA, family = binomial(), data = PFAS_IPW)
a_pn_PFNA <- 1-predict(a_n_PFNA, type = "response")

# PFHxS
a_n_PFHxS <- glm(a.cens ~ L2PFHxS, family = binomial(), data = PFAS_IPW)
a_pn_PFHxS <- 1-predict(a_n_PFHxS, type = "response")

# MeFOSAA
a_n_MeFOSAA <- glm(a.cens ~ L2MeFOSAA, family = binomial(), data = PFAS_IPW)
a_pn_MeFOSAA <- 1-predict(a_n_MeFOSAA, type = "response")

# EtFOSAA
a_n_EtFOSAA <- glm(a.cens ~ L2EtFOSAA, family = binomial(), data = PFAS_IPW)
a_pn_EtFOSAA <- 1-predict(a_n_EtFOSAA, type = "response")


##### ESTIMATE THE DENOMINATOR OF CENSORING WEIGHTS FOR ANTHRO DATASET
# PFOS
a_d_PFOS <- glm(a.cens ~ L2PFOS + age + race + bmi_cat + edu + smoke +  
                 parity + married + exer, family = binomial(), data = PFAS_IPW)
a_pd_PFOS <- 1-predict(a_d_PFOS, type = "response")

# PFOA
a_d_PFOA <- glm(a.cens ~ L2PFOA + age + race + bmi_cat + edu + smoke +  
                 parity + married + exer, family = binomial(), data = PFAS_IPW)
a_pd_PFOA <- 1-predict(a_d_PFOA, type = "response")

# PFNA
a_d_PFNA <- glm(a.cens ~ L2PFNA + age + race + bmi_cat + edu + smoke +  
                 parity + married + exer, family = binomial(), data = PFAS_IPW)
a_pd_PFNA <- 1-predict(a_d_PFNA, type = "response")

# PFHxS
a_d_PFHxS <- glm(a.cens ~ L2PFHxS + age + race + bmi_cat + edu + smoke +  
                 parity + married + exer, family = binomial(), data = PFAS_IPW)
a_pd_PFHxS <- 1-predict(a_d_PFHxS, type = "response")

# MeFOSAA
a_d_MeFOSAA <- glm(a.cens ~ L2MeFOSAA + age + race + bmi_cat + edu + smoke +  
                 parity + married + exer, family = binomial(), data = PFAS_IPW)
a_pd_MeFOSAA <- 1-predict(a_d_MeFOSAA, type = "response")

# EtFOSAA
a_d_EtFOSAA <- glm(a.cens ~ L2EtFOSAA + age + race + bmi_cat + edu + smoke +  
                 parity + married + exer, family = binomial(), data = PFAS_IPW)
a_pd_EtFOSAA <- 1-predict(a_d_EtFOSAA, type = "response")


##### CREAT WEIGHTS FOR ANTHRO DATASET
# PFOS
PFAS_IPW$PFOS_w <- a_pn_PFOS / a_pd_PFOS
summary(PFAS_IPW$PFOS_w)

# PFOA
PFAS_IPW$PFOA_w <- a_pn_PFOA / a_pd_PFOA
summary(PFAS_IPW$PFOA_w)

# PFNA
PFAS_IPW$PFNA_w <- a_pn_PFNA / a_pd_PFNA
summary(PFAS_IPW$PFNA_w)

# PFHxS
PFAS_IPW$PFHxS_w <- a_pn_PFHxS / a_pd_PFHxS
summary(PFAS_IPW$PFHxS_w)

# MeFOSAA
PFAS_IPW$MeFOSAA_w <- a_pn_MeFOSAA / a_pd_MeFOSAA
summary(PFAS_IPW$MeFOSAA_w)

# EtFOSAA
PFAS_IPW$EtFOSAA_w <- a_pn_EtFOSAA / a_pd_EtFOSAA
summary(PFAS_IPW$EtFOSAA_w)

```

```{r}
##### ESTIMATE THE NUMERATOR OF CENSORING WEIGHTS FOR DXA DATASET
# PFOS
d_n_PFOS <- glm(d.cens ~ L2PFOS, family = binomial(), data = PFAS_IPW)
d_pn_PFOS <- 1-predict(d_n_PFOS, type = "response")

# PFOA
d_n_PFOA <- glm(d.cens ~ L2PFOA, family = binomial(), data = PFAS_IPW)
d_pn_PFOA <- 1-predict(d_n_PFOA, type = "response")

# PFNA
d_n_PFNA <- glm(d.cens ~ L2PFNA, family = binomial(), data = PFAS_IPW)
d_pn_PFNA <- 1-predict(d_n_PFNA, type = "response")

# PFHxS
d_n_PFHxS <- glm(d.cens ~ L2PFHxS, family = binomial(), data = PFAS_IPW)
d_pn_PFHxS <- 1-predict(d_n_PFHxS, type = "response")

# MeFOSAA
d_n_MeFOSAA <- glm(d.cens ~ L2MeFOSAA, family = binomial(), data = PFAS_IPW)
d_pn_MeFOSAA <- 1-predict(d_n_MeFOSAA, type = "response")

# EtFOSAA
d_n_EtFOSAA <- glm(d.cens ~ L2EtFOSAA, family = binomial(), data = PFAS_IPW)
d_pn_EtFOSAA <- 1-predict(d_n_EtFOSAA, type = "response")


##### ESTIMATE THE DENOMINATOR OF CENSORING WEIGHTS FOR DXA DATASET
# PFOS
d_d_PFOS <- glm(d.cens ~ L2PFOS + age + race + bmi_cat + edu + smoke +  
                 parity + married + exer, family = binomial(), data = PFAS_IPW)
d_pd_PFOS <- 1-predict(d_d_PFOS, type = "response")

# PFOA
d_d_PFOA <- glm(d.cens ~ L2PFOA + age + race + bmi_cat + edu + smoke +  
                 parity + married + exer, family = binomial(), data = PFAS_IPW)
d_pd_PFOA <- 1-predict(d_d_PFOA, type = "response")

# PFNA
d_d_PFNA <- glm(d.cens ~ L2PFNA + age + race + bmi_cat + edu + smoke +  
                 parity + married + exer, family = binomial(), data = PFAS_IPW)
d_pd_PFNA <- 1-predict(d_d_PFNA, type = "response")

# PFHxS
d_d_PFHxS <- glm(d.cens ~ L2PFHxS + age + race + bmi_cat + edu + smoke +  
                 parity + married + exer, family = binomial(), data = PFAS_IPW)
d_pd_PFHxS <- 1-predict(d_d_PFHxS, type = "response")

# MeFOSAA
d_d_MeFOSAA <- glm(d.cens ~ L2MeFOSAA + age + race + bmi_cat + edu + smoke +  
                 parity + married + exer, family = binomial(), data = PFAS_IPW)
d_pd_MeFOSAA <- 1-predict(d_d_MeFOSAA, type = "response")

# EtFOSAA
d_d_EtFOSAA <- glm(d.cens ~ L2EtFOSAA + age + race + bmi_cat + edu + smoke +  
                 parity + married + exer, family = binomial(), data = PFAS_IPW)
d_pd_EtFOSAA <- 1-predict(d_d_EtFOSAA, type = "response")


##### CREAT WEIGHTS FOR DXA DATASET
# PFOS
PFAS_IPW$PFOS_w <- d_pn_PFOS / d_pd_PFOS
summary(PFAS_IPW$PFOS_w)

# PFOA
PFAS_IPW$PFOA_w <- d_pn_PFOA / d_pd_PFOA
summary(PFAS_IPW$PFOA_w)

# PFNA
PFAS_IPW$PFNA_w <- d_pn_PFNA / d_pd_PFNA
summary(PFAS_IPW$PFNA_w)

# PFHxS
PFAS_IPW$PFHxS_w <- d_pn_PFHxS / d_pd_PFHxS
summary(PFAS_IPW$PFHxS_w)

# MeFOSAA
PFAS_IPW$MeFOSAA_w <- d_pn_MeFOSAA / d_pd_MeFOSAA
summary(PFAS_IPW$MeFOSAA_w)

# EtFOSAA
PFAS_IPW$EtFOSAA_w <- d_pn_EtFOSAA / d_pd_EtFOSAA
summary(PFAS_IPW$EtFOSAA_w)

```

```{r}
##### RUN ADJUSTED LINEAR REGRESSION MODELS, ANTHRO DATASET (N = 547)

# WEIGHT
ad.l2m.wt <- list(
  "PFOS" = glm(Weight ~ L2PFOS + age + race + bmi_cat  + smoke + 
                 parity + married + fish + height, family = gaussian, data = PFAS_A),
  "PFOA" = glm(Weight ~ L2PFOA + age + race + bmi_cat + smoke +
                 parity + married + fish + height, family = gaussian, data = PFAS_A),
  "PFNA" = glm(Weight ~ L2PFNA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(Weight ~ L2PFHxS + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(Weight ~ L2MeFOSAA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(Weight ~ L2EtFOSAA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_A))

modelsummary(ad.l2m.wt, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WEIGHT")



wad.l2m.wt <- list(
  "PFOS" = glm(Weight ~ L2PFOS + age + race + bmi_cat  + smoke + 
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOS_w),
  "PFOA" = glm(Weight ~ L2PFOA + age + race + bmi_cat + smoke +
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOA_w),
  "PFNA" = glm(Weight ~ L2PFNA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFNA_w),
  "PFHxS" = glm(Weight ~ L2PFHxS + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFHxS_w),
  "MeFOSAA" = glm(Weight ~ L2MeFOSAA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = MeFOSAA_w),
  "EtFOSAA" = glm(Weight ~ L2EtFOSAA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = EtFOSAA_w))

modelsummary(wad.l2m.wt, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WEIGHT (IPC Weighted)")



wad.l2m.wt.sens1 <- list(
  "PFOS" = glm(Weight ~ L2PFOS*bmi_yn + age + race  + smoke + 
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOS_w),
  "PFOA" = glm(Weight ~ L2PFOA*bmi_yn + age + race + smoke +
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOA_w),
  "PFNA" = glm(Weight ~ L2PFNA*bmi_yn + age + race + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFNA_w),
  "PFHxS" = glm(Weight ~ L2PFHxS*bmi_yn + age + race + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFHxS_w),
  "MeFOSAA" = glm(Weight ~ L2MeFOSAA*bmi_yn + age + race + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = MeFOSAA_w),
  "EtFOSAA" = glm(Weight ~ L2EtFOSAA*bmi_yn + age + race + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = EtFOSAA_w))

modelsummary(wad.l2m.wt.sens1, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WEIGHT (IPC Weighted, Sens)")



wad.l2m.wt.sens2 <- list(
  "PFOS" = glm(Weight ~ L2PFOS*meno_cat + age + race + bmi_cat + smoke + 
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOS_w),
  "PFOA" = glm(Weight ~ L2PFOA*meno_cat + age + race + smoke +
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOA_w),
  "PFNA" = glm(Weight ~ L2PFNA*meno_cat + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFNA_w),
  "PFHxS" = glm(Weight ~ L2PFHxS*meno_cat + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFHxS_w),
  "MeFOSAA" = glm(Weight ~ L2MeFOSAA*meno_cat + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = MeFOSAA_w),
  "EtFOSAA" = glm(Weight ~ L2EtFOSAA*meno_cat + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = EtFOSAA_w))

modelsummary(wad.l2m.wt.sens2, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WEIGHT (IPC Weighted, Sens)")





# WAIST CIRCUMFERENCE
ad.l2m.waist <- list(
  "PFOS" = glm(Waist ~ L2PFOS + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_A),
  "PFOA" = glm(Waist ~ L2PFOA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_A),
  "PFNA" = glm(Waist ~ L2PFNA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(Waist ~ L2PFHxS + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(Waist ~ L2MeFOSAA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(Waist ~ L2EtFOSAA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_A))

modelsummary(ad.l2m.waist, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WAIST CIRCUMFERENCE")



wad.l2m.waist <- list(
  "PFOS" = glm(Waist ~ L2PFOS + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOS_w),
  "PFOA" = glm(Waist ~ L2PFOA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOA_w),
  "PFNA" = glm(Waist ~ L2PFNA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFNA_w),
  "PFHxS" = glm(Waist ~ L2PFHxS + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFHxS_w),
  "MeFOSAA" = glm(Waist ~ L2MeFOSAA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = MeFOSAA_w),
  "EtFOSAA" = glm(Waist ~ L2EtFOSAA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = EtFOSAA_w))

modelsummary(wad.l2m.waist, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WAIST CIRCUMFERENCE (IPC Weighted)")



wad.l2m.waist.sens1 <- list(
  "PFOS" = glm(Waist ~ L2PFOS*meno_cat + age + race + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOS_w),
  "PFOA" = glm(Waist ~ L2PFOA*meno_cat + age + race + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOA_w),
  "PFNA" = glm(Waist ~ L2PFNA*meno_cat + age + race + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFNA_w),
  "PFHxS" = glm(Waist ~ L2PFHxS*meno_cat + age + race + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFHxS_w),
  "MeFOSAA" = glm(Waist ~ L2MeFOSAA*meno_cat + age + race + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = MeFOSAA_w),
  "EtFOSAA" = glm(Waist ~ L2EtFOSAA*meno_cat + age + race + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = EtFOSAA_w))

modelsummary(wad.l2m.waist.sens1, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WAIST CIRCUMFERENCE (IPC Weighted, Sens)")



wad.l2m.waist.sens2 <- list(
  "PFOS" = glm(Waist ~ L2PFOS*meno_cat + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOS_w),
  "PFOA" = glm(Waist ~ L2PFOA*meno_cat + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOA_w),
  "PFNA" = glm(Waist ~ L2PFNA*meno_cat + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFNA_w),
  "PFHxS" = glm(Waist ~ L2PFHxS*meno_cat + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFHxS_w),
  "MeFOSAA" = glm(Waist ~ L2MeFOSAA*meno_cat + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = MeFOSAA_w),
  "EtFOSAA" = glm(Waist ~ L2EtFOSAA*meno_cat + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = EtFOSAA_w))

modelsummary(wad.l2m.waist.sens2, fmt = 2,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WAIST CIRCUMFERENCE (IPC Weighted, Sens)")

```

```{r}
##### RUN ADJUSTED LINEAR REGRESSION MODELS, ANTHRO + DXA DATASET (N = 424)

# TRUNK FAT MASS
ad.l2m.trnkfat <- list(
  "PFOS" = glm(TrnkFat ~ L2PFOS + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_D),
  "PFOA" = glm(TrnkFat ~ L2PFOA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_D),
  "PFNA" = glm(TrnkFat ~ L2PFNA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(TrnkFat ~ L2PFHxS + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(TrnkFat ~ L2MeFOSAA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(TrnkFat ~ L2EtFOSAA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_D))

modelsummary(ad.l2m.trnkfat, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. TRUNK FAT MASS")



wad.l2m.trnkfat <- list(
  "PFOS" = glm(TrnkFat ~ L2PFOS + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOS_w),
  "PFOA" = glm(TrnkFat ~ L2PFOA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOA_w),
  "PFNA" = glm(TrnkFat ~ L2PFNA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFNA_w),
  "PFHxS" = glm(TrnkFat ~ L2PFHxS + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFHxS_w),
  "MeFOSAA" = glm(TrnkFat ~ L2MeFOSAA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = MeFOSAA_w),
  "EtFOSAA" = glm(TrnkFat ~ L2EtFOSAA + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = EtFOSAA_w))

modelsummary(wad.l2m.trnkfat, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. TRUNK FAT MASS (IPC Weighted)")



wad.l2m.trnkfat.sens1 <- list(
  "PFOS" = glm(TrnkFat ~ L2PFOS*bmi_yn + age + race + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOS_w),
  "PFOA" = glm(TrnkFat ~ L2PFOA*bmi_yn + age + race + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOA_w),
  "PFNA" = glm(TrnkFat ~ L2PFNA*bmi_yn + age + race + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFNA_w),
  "PFHxS" = glm(TrnkFat ~ L2PFHxS*bmi_yn + age + race + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFHxS_w),
  "MeFOSAA" = glm(TrnkFat ~ L2MeFOSAA*bmi_yn + age + race + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = MeFOSAA_w),
  "EtFOSAA" = glm(TrnkFat ~ L2EtFOSAA*bmi_yn + age + race + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = EtFOSAA_w))

modelsummary(wad.l2m.trnkfat.sens1, fmt = 2, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. TRUNK FAT MASS (IPC Weighted, Sens)")



wad.l2m.trnkfat.sens2 <- list(
  "PFOS" = glm(TrnkFat ~ L2PFOS*meno_cat + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOS_w),
  "PFOA" = glm(TrnkFat ~ L2PFOA*meno_cat + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOA_w),
  "PFNA" = glm(TrnkFat ~ L2PFNA*meno_cat + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFNA_w),
  "PFHxS" = glm(TrnkFat ~ L2PFHxS*meno_cat + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFHxS_w),
  "MeFOSAA" = glm(TrnkFat ~ L2MeFOSAA*meno_cat + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = MeFOSAA_w),
  "EtFOSAA" = glm(TrnkFat ~ L2EtFOSAA*meno_cat + age + race + bmi_cat + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = EtFOSAA_w))

modelsummary(wad.l2m.trnkfat.sens2, fmt = 2, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. TRUNK FAT MASS (IPC Weighted, Sens)")




# TOTAL BODY FAT MASS
ad.l2m.totfat <- list(
  "PFOS" = glm(TotFat ~ L2PFOS + age + race + bmi_cat + smoke + exer_cat +
                 parity + married + fish + height, family = gaussian, data = PFAS_D),
  "PFOA" = glm(TotFat ~ L2PFOA + age + race + bmi_cat + smoke + exer_cat +
                 parity + married + fish + height, family = gaussian, data = PFAS_D),
  "PFNA" = glm(TotFat ~ L2PFNA + age + race + bmi_cat + smoke + 
                 parity + married + fish + height, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(TotFat ~ L2PFHxS + age + race + bmi_cat + smoke + 
                  parity + married + fish + height, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(TotFat ~ L2MeFOSAA + age + race + bmi_cat + smoke + 
                    parity + married + fish + height, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(TotFat ~ L2EtFOSAA + age + race + bmi_cat + smoke + 
                    parity + married + fish + height, family = gaussian, data = PFAS_D))

modelsummary(ad.l2m.totfat, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. TOTAL BODY FAT MASS")


wad.l2m.totfat <- list(
  "PFOS" = glm(TotFat ~ L2PFOS + age + race + bmi_cat + smoke + exer_cat +
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOS_w),
  "PFOA" = glm(TotFat ~ L2PFOA + age + race + bmi_cat + smoke + exer_cat +
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOA_w),
  "PFNA" = glm(TotFat ~ L2PFNA + age + race + bmi_cat + smoke + 
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFNA_w),
  "PFHxS" = glm(TotFat ~ L2PFHxS + age + race + bmi_cat + smoke + 
                  parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFHxS_w),
  "MeFOSAA" = glm(TotFat ~ L2MeFOSAA + age + race + bmi_cat + smoke + 
                    parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = MeFOSAA_w),
  "EtFOSAA" = glm(TotFat ~ L2EtFOSAA + age + race + bmi_cat + smoke + 
                    parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = EtFOSAA_w))

modelsummary(wad.l2m.totfat, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. TOTAL BODY FAT MASS (IPW Weighted)")



wad.l2m.totfat.sens1 <- list(
  "PFOS" = glm(TotFat ~ L2PFOS*bmi_yn + age + race + smoke + exer_cat +
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOS_w),
  "PFOA" = glm(TotFat ~ L2PFOA*bmi_yn + age + race + smoke + exer_cat +
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOA_w),
  "PFNA" = glm(TotFat ~ L2PFNA*bmi_yn + age + race + smoke + 
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFNA_w),
  "PFHxS" = glm(TotFat ~ L2PFHxS*bmi_yn + age + race + smoke + 
                  parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFHxS_w),
  "MeFOSAA" = glm(TotFat ~ L2MeFOSAA*bmi_yn + age + race + smoke + 
                    parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = MeFOSAA_w),
  "EtFOSAA" = glm(TotFat ~ L2EtFOSAA*bmi_yn + age + race + smoke + 
                    parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = EtFOSAA_w))

modelsummary(wad.l2m.totfat.sens1, fmt = 2, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. TOTAL BODY FAT MASS (IPW Weighted, Sens)")



wad.l2m.totfat.sens2 <- list(
  "PFOS" = glm(TotFat ~ L2PFOS*bmi_yn + age + race + bmi_cat + smoke + exer_cat +
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOS_w),
  "PFOA" = glm(TotFat ~ L2PFOA*bmi_yn + age + race + bmi_cat + smoke + exer_cat +
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFOA_w),
  "PFNA" = glm(TotFat ~ L2PFNA*bmi_yn + age + race + bmi_cat + smoke + 
                 parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFNA_w),
  "PFHxS" = glm(TotFat ~ L2PFHxS*bmi_yn + age + race + bmi_cat + smoke + 
                  parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = PFHxS_w),
  "MeFOSAA" = glm(TotFat ~ L2MeFOSAA*bmi_yn + age + race + bmi_cat + smoke + 
                    parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = MeFOSAA_w),
  "EtFOSAA" = glm(TotFat ~ L2EtFOSAA*bmi_yn + age + race + bmi_cat + smoke + 
                    parity + married + fish + height, family = gaussian, data = PFAS_IPW, weights = EtFOSAA_w))

modelsummary(wad.l2m.totfat.sens2, fmt = 2, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. TOTAL BODY FAT MASS (IPW Weighted, Sens)")

```

```{r}
##### EMPLOY FDR CORRECTION
PFAS_IPW_w <- subset(PFAS_IPW, select = c(aid, PFOS_w, PFOA_w, PFNA_w, PFHxS_w, MeFOSAA_w, EtFOSAA_w))

PFAS_IPW_A <- inner_join(PFAS_A, PFAS_IPW_w, by = "aid")
PFAS_IPW_D <- inner_join(PFAS_D, PFAS_IPW_w, by = "aid")

PFAS_IPW_A <- subset(PFAS_IPW_A, select = c(aid, PFOS_w, PFOA_w, PFNA_w, PFHxS_w, MeFOSAA_w, EtFOSAA_w))
PFAS_IPW_D <- subset(PFAS_IPW_D, select = c(aid, PFOS_w, PFOA_w, PFNA_w, PFHxS_w, MeFOSAA_w, EtFOSAA_w))


PFAS_A <- PFAS_A %>% relocate(aid, L2PFOS, L2PFOA, L2PFNA, L2PFHxS, L2MeFOSAA, L2EtFOSAA, everything()) 
PFAS_D <- PFAS_D %>% relocate(aid, L2PFOS, L2PFOA, L2PFNA, L2PFHxS, L2MeFOSAA, L2EtFOSAA, everything()) 


# WEIGHT
pval_cens_WT <- NULL
for (i in 2:7) {
m_WT <- glm(PFAS_A$Weight ~ PFAS_A[[i]] + PFAS_A$age + PFAS_A$race + 
                PFAS_A$bmi_cat + PFAS_A$smoke +  PFAS_A$parity + 
                PFAS_A$married + PFAS_A$fish + PFAS_A$height, family = gaussian, weight = PFAS_IPW_A[[i]])
p_WT <- summary(m_WT)$coefficients[2,]
pval_cens_WT <- rbind(pval_cens_WT, p_WT)
rownames(pval_cens_WT)[i-1] <- paste("X", i-1, sep="")
}

pval_cens_WT_set <- pval_cens_WT[,4]
BH_WT <- p.adjust(pval_cens_WT_set, method="BH")
BY_WT <- p.adjust(pval_cens_WT_set, method="BY")
FDR_WT <- p.adjust(pval_cens_WT_set, method="fdr")
FWER_WT <- as.data.frame(cbind(pval_cens_WT_set, BH_WT, BY_WT, FDR_WT))
FWER_WT



# Waist
pval_cens_Waist <- NULL
for (i in 2:7){
m_Waist <- glm(PFAS_A$Waist ~ PFAS_A[[i]] + PFAS_A$age + PFAS_A$race + 
                PFAS_A$bmi_cat + PFAS_A$smoke +  PFAS_A$parity + 
                PFAS_A$married + PFAS_A$fish + PFAS_A$height, family = gaussian, weight = PFAS_IPW_A[[i]])
p_Waist <- summary(m_Waist)$coefficients[2,]
pval_cens_Waist <- rbind(pval_cens_Waist, p_Waist)
rownames(pval_cens_Waist)[i-1] <- paste("X", i-1, sep="")
}

pval_cens_Waist_set <- pval_cens_Waist[,4]
BH_Waist <- p.adjust(pval_cens_Waist_set, method="BH")
BY_Waist <- p.adjust(pval_cens_Waist_set, method="BY")
FDR_Waist <- p.adjust(pval_cens_Waist_set, method="fdr")
FWER_Waist <- as.data.frame(cbind(pval_cens_Waist_set, BH_Waist, BY_Waist, FDR_Waist))
FWER_Waist


# TRNK
pval_cens_TRNK <- NULL
for (i in 2:7){
m_TRNK <- glm(PFAS_D$TrnkFat ~ PFAS_D[[i]] + PFAS_D$age + PFAS_D$race + 
                PFAS_D$bmi_cat + PFAS_D$smoke +  PFAS_D$parity + 
                PFAS_D$married + PFAS_D$fish + PFAS_D$height, family = gaussian, weight = PFAS_IPW_D[[i]])
p_TRNK <- summary(m_TRNK)$coefficients[2,]
pval_cens_TRNK <- rbind(pval_cens_TRNK, p_TRNK)
rownames(pval_cens_TRNK)[i-1] <- paste("X", i-1, sep="")
}

pval_cens_TRNK_set <- pval_cens_TRNK[,4]
BH_TRNK <- p.adjust(pval_cens_TRNK_set, method="BH")
BY_TRNK <- p.adjust(pval_cens_TRNK_set, method="BY")
FDR_TRNK <- p.adjust(pval_cens_TRNK_set, method="fdr")
FWER_TRNK <- as.data.frame(cbind(pval_cens_TRNK_set, BH_TRNK, BY_TRNK, FDR_TRNK))
FWER_TRNK


# FAT
pval_cens_FAT <- NULL
for (i in 2:7){
m_FAT <- glm(PFAS_D$TotFat ~ PFAS_D[[i]] + PFAS_D$age + PFAS_D$race + 
                PFAS_D$bmi_cat + PFAS_D$smoke +  PFAS_D$parity + 
                PFAS_D$married + PFAS_D$fish + PFAS_D$height, family = gaussian, weight = PFAS_IPW_D[[i]])
p_FAT <- summary(m_FAT)$coefficients[2,]
pval_cens_FAT <- rbind(pval_cens_FAT, p_FAT)
rownames(pval_cens_FAT)[i-1] <- paste("X", i-1, sep="")
}

pval_cens_FAT_set <- pval_cens_FAT[,4]
BH_FAT <- p.adjust(pval_cens_FAT_set, method="BH")
BY_FAT <- p.adjust(pval_cens_FAT_set, method="BY")
FDR_FAT <- p.adjust(pval_cens_FAT_set, method="fdr")
FWER_FAT <- as.data.frame(cbind(pval_cens_FAT_set, BH_FAT, BY_FAT, FDR_FAT))
FWER_FAT

```
