#####                                                       #####
##### PRE-LIMINARY ANALYSIS                                 #####
#####                                                       #####

```{r message=FALSE, warning=FALSE}
##### LOAD PACKAGES
library("tidyverse")
library("modelsummary")
library("kableExtra")
library("gt")
library("shiny")
library("olsrr")
library("dplyr")

```

```{r}
##### LOAD DATASET
PFAS_A <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/P3.PFASandAdiposity/Data/PFAS_A.csv")
PFAS_D <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/P3.PFASandAdiposity/Data/PFAS_D.csv")

```

```{r}
##### PREPARE VARIABLES FOR LINEAR REGRESSION

# SET CATEGORICAL VARIABLES AS FACTORS
PFAS_A$race <- as.factor(PFAS_A$race)
PFAS_A$income <- as.factor(PFAS_A$income)
PFAS_A$parity <- as.factor(PFAS_A$parity)
PFAS_A$smoke <- as.factor(PFAS_A$smoke)
PFAS_A$married <- as.factor(PFAS_A$married)
PFAS_A$edu <- as.factor(PFAS_A$edu)

PFAS_D$race <- as.factor(PFAS_D$race)
PFAS_D$income <- as.factor(PFAS_D$income)
PFAS_D$parity <- as.factor(PFAS_D$parity)
PFAS_D$smoke <- as.factor(PFAS_D$smoke)
PFAS_D$married <- as.factor(PFAS_D$married)
PFAS_D$edu <- as.factor(PFAS_D$edu)

```

```{r}
##### RUN UNADJUSTED LINEAR REGRESSION MODELS, ANTHRO DATASET (N = 545)

# BMI
# unad.lnm.lnbmi <- list(
#   "PFOS" = glm(LNBMI ~ LNPFOS, family = gaussian, data = PFAS_A),
#   "PFOA" = glm(LNBMI ~ LNPFOA, family = gaussian, data = PFAS_A),
#   "PFNA" = glm(LNBMI ~ LNPFNA, family = gaussian, data = PFAS_A),
#   "PFHxS" = glm(LNBMI ~ LNPFHxS, family = gaussian, data = PFAS_A),
#   "MeFOSAA" = glm(LNBMI ~ LNMeFOSAA, family = gaussian, data = PFAS_A),
#   "EtFOSAA" = glm(LNBMI ~ LNEtFOSAA, family = gaussian, data = PFAS_A))
# modelsummary(unad.lnm.lnbmi, fmt = 4, title = "LN-PFAS vs. LN-BMI (Unadjusted)")

# unad.l2m.lnbmi <- list(
#   "PFOS" = glm(LNBMI ~ L2PFOS, family = gaussian, data = PFAS_A),
#   "PFOA" = glm(LNBMI ~ L2PFOA, family = gaussian, data = PFAS_A),
#   "PFNA" = glm(LNBMI ~ L2PFNA, family = gaussian, data = PFAS_A),
#   "PFHxS" = glm(LNBMI ~ L2PFHxS, family = gaussian, data = PFAS_A),
#   "MeFOSAA" = glm(LNBMI ~ L2MeFOSAA, family = gaussian, data = PFAS_A),
#   "EtFOSAA" = glm(LNBMI ~ L2EtFOSAA, family = gaussian, data = PFAS_A))
# modelsummary(unad.l2m.lnbmi, fmt = 4, title = "LOG2-PFAS vs. LN-BMI (Unadjusted)")

unad.l2m.bmi <- list(
 "PFOS" = glm(BMI ~ L2PFOS, family = gaussian, data = PFAS_A),
 "PFOA" = glm(BMI ~ L2PFOA, family = gaussian, data = PFAS_A),
 "PFNA" = glm(BMI ~ L2PFNA, family = gaussian, data = PFAS_A),
 "PFHxS" = glm(BMI ~ L2PFHxS, family = gaussian, data = PFAS_A),
 "MeFOSAA" = glm(BMI ~ L2MeFOSAA, family = gaussian, data = PFAS_A),
 "EtFOSAA" = glm(BMI ~ L2EtFOSAA, family = gaussian, data = PFAS_A))
modelsummary(unad.l2m.bmi, fmt = 4, title = "LOG2-PFAS vs. BMI (Unadjusted)")


# WEIGHT
unad.l2m.wt <- list(
  "PFOS" = glm(Weight ~ L2PFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(Weight ~ L2PFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(Weight ~ L2PFNA, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(Weight ~ L2PFHxS, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(Weight ~ L2MeFOSAA, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(Weight ~ L2EtFOSAA, family = gaussian, data = PFAS_A))
modelsummary(unad.l2m.wt, fmt = 4, title = "LOG2-PFAS vs. WEIGHT (Unadjusted)")


# DIFFERENCE IN BMI
unad.l2m.dbmi <- list(
  "PFOS" = glm(DBMI ~ L2PFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(DBMI ~ L2PFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(DBMI ~ L2PFNA, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(DBMI ~ L2PFHxS, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(DBMI ~ L2MeFOSAA, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(DBMI ~ L2EtFOSAA, family = gaussian, data = PFAS_A))
modelsummary(unad.l2m.dbmi, fmt = 4, title = "LOG2-PFAS vs. DIFF IN BMI (Unadjusted)")


# WAIST CIRCUMFERENCE
# unad.lnm.waist <- list(
#   "PFOS" = glm(Waist ~ LNPFOS, family = gaussian, data = PFAS_A),
#   "PFOA" = glm(Waist ~ LNPFOA, family = gaussian, data = PFAS_A),
#   "PFNA" = glm(Waist ~ LNPFNA, family = gaussian, data = PFAS_A),
#   "PFHxS" = glm(Waist ~ LNPFHxS, family = gaussian, data = PFAS_A),
#   "MeFOSAA" = glm(Waist ~ LNMeFOSAA, family = gaussian, data = PFAS_A),
#   "EtFOSAA" = glm(Waist ~ LNEtFOSAA, family = gaussian, data = PFAS_A))
# modelsummary(unad.lnm.waist, fmt = 4, title = "LN-PFAS vs. WAIST CIRCUMFERENCE (Unadjusted)")

unad.l2m.waist <- list(
  "PFOS" = glm(Waist ~ L2PFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(Waist ~ L2PFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(Waist ~ L2PFNA, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(Waist ~ L2PFHxS, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(Waist ~ L2MeFOSAA, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(Waist ~ L2EtFOSAA, family = gaussian, data = PFAS_A))
modelsummary(unad.l2m.waist, fmt = 4, title = "LOG2-PFAS vs. WAIST CIRCUMFERENCE (Unadjusted)")

#unad.lnm.lnwaist <- list(
#  "PFOS" = glm(LNWAIST ~ LNPFOS, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNWAIST ~ LNPFOA, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNWAIST ~ LNPFNA, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNWAIST ~ LNPFHxS, family = gaussian, data = PFAS_A),
#  "MeFOSAA" = glm(LNWAIST ~ LNMeFOSAA, family = gaussian, data = PFAS_A),
#  "EtFOSAA" = glm(LNWAIST ~ LNEtFOSAA, family = gaussian, data = PFAS_A))
#modelsummary(unad.lnm.lnwaist, fmt = 4, title = "LN-PFAS vs. LN-WAIST CIRCUMFERENCE (Unadjusted)")


# WAIST-TO-HIP RATIO
# unad.lnm.whr <- list(
#   "PFOS" = glm(WHR ~ LNPFOS, family = gaussian, data = PFAS_A),
#   "PFOA" = glm(WHR ~ LNPFOA, family = gaussian, data = PFAS_A),
#   "PFNA" = glm(WHR ~ LNPFNA, family = gaussian, data = PFAS_A),
#   "PFHxS" = glm(WHR ~ LNPFHxS, family = gaussian, data = PFAS_A),
#   "MeFOSAA" = glm(WHR ~ LNMeFOSAA, family = gaussian, data = PFAS_A),
#   "EtFOSAA" = glm(WHR ~ LNEtFOSAA, family = gaussian, data = PFAS_A))
# modelsummary(unad.lnm.whr, fmt = 4, title = "LN-PFAS vs. WHR (Unadjusted)")

unad.l2m.whr <- list(
  "PFOS" = glm(WHR ~ L2PFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(WHR ~ L2PFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(WHR ~ L2PFNA, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(WHR ~ L2PFHxS, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(WHR ~ L2MeFOSAA, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(WHR ~ L2EtFOSAA, family = gaussian, data = PFAS_A))
modelsummary(unad.l2m.whr, fmt = 4, title = "LOG2-PFAS vs. WHR (Unadjusted)")

#unad.lnm.lnwhr <- list(
#  "PFOS" = glm(LNWHR ~ LNPFOS, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNWHR ~ LNPFOA, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNWHR ~ LNPFNA, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNWHR ~ LNPFHxS, family = gaussian, data = PFAS_A),
#  "MeFOSAA" = glm(LNWHR ~ LNMeFOSAA, family = gaussian, data = PFAS_A),
#  "EtFOSAA" = glm(LNWHR ~ LNEtFOSAA, family = gaussian, data = PFAS_A))
#modelsummary(unad.lnm.lnwhr, fmt = 4, title = "LN-PFAS vs. LN-WHR (Unadjusted)")


# WAIST-TO-HEIGHT RATIO
# unad.lnm.whtr <- list(
#   "PFOS" = glm(WHtR ~ LNPFOS, family = gaussian, data = PFAS_A),
#   "PFOA" = glm(WHtR ~ LNPFOA, family = gaussian, data = PFAS_A),
#   "PFNA" = glm(WHtR ~ LNPFNA, family = gaussian, data = PFAS_A),
#   "PFHxS" = glm(WHtR ~ LNPFHxS, family = gaussian, data = PFAS_A),
#   "MeFOSAA" = glm(WHtR ~ LNMeFOSAA, family = gaussian, data = PFAS_A),
#   "EtFOSAA" = glm(WHtR ~ LNEtFOSAA, family = gaussian, data = PFAS_A))
# modelsummary(unad.lnm.whtr, fmt = 4, title = "LN-PFAS vs. WHtR (Unadjusted)")

unad.l2m.whtr <- list(
  "PFOS" = glm(WHtR ~ L2PFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(WHtR ~ L2PFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(WHtR ~ L2PFNA, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(WHtR ~ L2PFHxS, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(WHtR ~ L2MeFOSAA, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(WHtR ~ L2EtFOSAA, family = gaussian, data = PFAS_A))
modelsummary(unad.l2m.whtr, fmt = 4, title = "LOG2-PFAS vs. WHtR (Unadjusted)")


# MUAC
# unad.lnm.muac <- list(
#   "PFOS" = glm(MUAC ~ LNPFOS, family = gaussian, data = PFAS_A),
#   "PFOA" = glm(MUAC ~ LNPFOA, family = gaussian, data = PFAS_A),
#   "PFNA" = glm(MUAC ~ LNPFNA, family = gaussian, data = PFAS_A),
#   "PFHxS" = glm(MUAC ~ LNPFHxS, family = gaussian, data = PFAS_A),
#   "MeFOSAA" = glm(MUAC ~ LNMeFOSAA, family = gaussian, data = PFAS_A),
#   "EtFOSAA" = glm(MUAC ~ LNEtFOSAA, family = gaussian, data = PFAS_A))
# modelsummary(unad.lnm.muac, fmt = 4, title = "LN-PFAS vs. MUAC (Unadjusted)")

unad.l2m.muac <- list(
  "PFOS" = glm(MUAC ~ L2PFOS, family = gaussian, data = PFAS_A),
  "PFOA" = glm(MUAC ~ L2PFOA, family = gaussian, data = PFAS_A),
  "PFNA" = glm(MUAC ~ L2PFNA, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(MUAC ~ L2PFHxS, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(MUAC ~ L2MeFOSAA, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(MUAC ~ L2EtFOSAA, family = gaussian, data = PFAS_A))
modelsummary(unad.l2m.muac, fmt = 4, title = "LOG2-PFAS vs. MUAC (Unadjusted)")

#unad.lnm.lnmuac <- list(
#  "PFOS" = glm(LNMUAC ~ LNPFOS, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNMUAC ~ LNPFOA, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNMUAC ~ LNPFNA, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNMUAC ~ LNPFHxS, family = gaussian, data = PFAS_A),
#  "MeFOSAA" = glm(LNMUAC ~ LNMeFOSAA, family = gaussian, data = PFAS_A),
#  "EtFOSAA" = glm(LNMUAC ~ LNEtFOSAA, family = gaussian, data = PFAS_A))
#modelsummary(unad.lnm.lnmuac, fmt = 4, title = "LN-PFAS vs. LN-MUAC (Unadjusted)")


# WEIGHT
#unad.lnm.wt <- list(
#  "PFOS" = glm(Weight ~ LNPFOS, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(Weight ~ LNPFOA, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(Weight ~ LNPFNA, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(Weight ~ LNPFHxS, family = gaussian, data = PFAS_A),
#  "MeFOSAA" = glm(Weight ~ LNMeFOSAA, family = gaussian, data = PFAS_A),
#  "EtFOSAA" = glm(Weight ~ LNEtFOSAA, family = gaussian, data = PFAS_A))
#modelsummary(unad.lnm.wt, fmt = 4, title = "LN-PFAS vs. WEIGHT (Unadjusted)")

#unad.lnm.lnwt <- list(
#  "PFOS" = glm(LNWT ~ LNPFOS, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNWT ~ LNPFOA, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNWT ~ LNPFNA, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNWT ~ LNPFHxS, family = gaussian, data = PFAS_A),
#  "MeFOSAA" = glm(LNWT ~ LNMeFOSAA, family = gaussian, data = PFAS_A),
#  "EtFOSAA" = glm(LNWT ~ LNEtFOSAA, family = gaussian, data = PFAS_A))
#modelsummary(unad.lnm.lnwt, fmt = 4, title = "LN-PFAS vs. LN-WEIGHT (Unadjusted)")


# BODY FAT MASS
#unad.lnm.fat <- list(
#  "PFOS" = glm(FatMass ~ LNPFOS, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(FatMass ~ LNPFOA, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(FatMass ~ LNPFNA, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(FatMass ~ LNPFHxS, family = gaussian, data = PFAS_A),
#  "MeFOSAA" = glm(FatMass ~ LNMeFOSAA, family = gaussian, data = PFAS_A),
#  "EtFOSAA" = glm(FatMass ~ LNEtFOSAA, family = gaussian, data = PFAS_A))
#modelsummary(unad.lnm.fat, fmt = 4, title = "LN-PFAS vs. BODY FAT MASS (Unadjusted)")

#unad.lnm.lnfat <- list(
#  "PFOS" = glm(LNFAT ~ LNPFOS, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNFAT ~ LNPFOA, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNFAT ~ LNPFNA, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNFAT ~ LNPFHxS, family = gaussian, data = PFAS_A),
#  "MeFOSAA" = glm(LNFAT ~ LNMeFOSAA, family = gaussian, data = PFAS_A),
#  "EtFOSAA" = glm(LNFAT ~ LNEtFOSAA, family = gaussian, data = PFAS_A))
#modelsummary(unad.lnm.lnfat, fmt = 4, title = "LN-PFAS vs. LN-BODY FAT MASS (Unadjusted)")


# BODY FAT %
#unad.lnm.bfat <- list(
#  "PFOS" = glm(FatPct ~ LNPFOS, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(FatPct ~ LNPFOA, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(FatPct ~ LNPFNA, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(FatPct ~ LNPFHxS, family = gaussian, data = PFAS_A),
#  "MeFOSAA" = glm(FatPct ~ LNMeFOSAA, family = gaussian, data = PFAS_A),
#  "EtFOSAA" = glm(FatPct ~ LNEtFOSAA, family = gaussian, data = PFAS_A))
#modelsummary(unad.lnm.bfat, fmt = 4, title = "LN-PFAS vs. BODY FAT % (Unadjusted)")


```

```{r}
##### RUN UNADJUSTED LINEAR REGRESSION MODELS, ANTHRO + DXA DATASET (N = 432)

# TRUNK FAT MASS
#unad.lnm.trnkfat <- list(
#  "PFOS" = glm(TrnkFat ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(TrnkFat ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(TrnkFat ~ LNPFNA, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(TrnkFat ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSAA" = glm(TrnkFat ~ LNMeFOSAA, family = gaussian, data = PFAS_D),
#  "EtFOSAA" = glm(TrnkFat ~ LNEtFOSAA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.trnkfat, fmt = 4, title = "LN-PFAS vs. TRUNK FAT MASS (Unadjusted)")

# unad.lnm.lntrnkfat <- list(
#   "PFOS" = glm(LNTKNFAT ~ LNPFOS, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNTKNFAT ~ LNPFOA, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNTKNFAT ~ LNPFNA, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNTKNFAT ~ LNPFHxS, family = gaussian, data = PFAS_D),
#   "MeFOSAA" = glm(LNTKNFAT ~ LNMeFOSAA, family = gaussian, data = PFAS_D),
#   "EtFOSAA" = glm(LNTKNFAT ~ LNEtFOSAA, family = gaussian, data = PFAS_D))
# modelsummary(unad.lnm.lntrnkfat, fmt = 4, title = "LN-PFAS vs. LN-TRUNK FAT MASS (Unadjusted)")

unad.l2m.lntrnkfat <- list(
  "PFOS" = glm(LNTKNFAT ~ L2PFOS, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTKNFAT ~ L2PFOA, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTKNFAT ~ L2PFNA, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTKNFAT ~ L2PFHxS, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(LNTKNFAT ~ L2MeFOSAA, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(LNTKNFAT ~ L2EtFOSAA, family = gaussian, data = PFAS_D))
modelsummary(unad.l2m.lntrnkfat, fmt = 4, title = "LOG2-PFAS vs. LN-TRUNK FAT MASS (Unadjusted)")


# TOTAL BODY FAT MASS
#unad.lnm.totfat <- list(
#  "PFOS" = glm(TotFat ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(TotFat ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(TotFat ~ LNPFNA, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(TotFat ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSAA" = glm(TotFat ~ LNMeFOSAA, family = gaussian, data = PFAS_D),
#  "EtFOSAA" = glm(TotFat ~ LNEtFOSAA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.totfat, fmt = 4, title = "LN-PFAS vs. TOTAL BODY FAT MASS (Unadjusted)")

# unad.lnm.lntotfat <- list(
#   "PFOS" = glm(LNTOTFAT ~ LNPFOS, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNTOTFAT ~ LNPFOA, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNTOTFAT ~ LNPFNA, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNTOTFAT ~ LNPFHxS, family = gaussian, data = PFAS_D),
#   "MeFOSAA" = glm(LNTOTFAT ~ LNMeFOSAA, family = gaussian, data = PFAS_D),
#   "EtFOSAA" = glm(LNTOTFAT ~ LNEtFOSAA, family = gaussian, data = PFAS_D))
# modelsummary(unad.lnm.lntotfat, fmt = 4, title = "LN-PFAS vs. LN-TOTAL BODY FAT MASS (Unadjusted)")

unad.l2m.lntotfat <- list(
  "PFOS" = glm(LNTOTFAT ~ L2PFOS, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTOTFAT ~ L2PFOA, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTOTFAT ~ L2PFNA, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTOTFAT ~ L2PFHxS, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(LNTOTFAT ~ L2MeFOSAA, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(LNTOTFAT ~ L2EtFOSAA, family = gaussian, data = PFAS_D))
modelsummary(unad.l2m.lntotfat, fmt = 4, title = "LOG2-PFAS vs. LN-TOTAL BODY FAT MASS (Unadjusted)")


# TRUNK FAT MASS INDEX
unad.l2m.lntfin <- list(
  "PFOS" = glm(LNTFIN ~ L2PFOS, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTFIN ~ L2PFOA, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTFIN ~ L2PFNA, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTFIN ~ L2PFHxS, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(LNTFIN ~ L2MeFOSAA, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(LNTFIN ~ L2EtFOSAA, family = gaussian, data = PFAS_D))
modelsummary(unad.l2m.lntfin, fmt = 4, title = "LOG2-PFAS vs. LN-TRUNK FAT MASS INDEX (Unadjusted)")


# TOTAL BODY FAT MASS INDEX
unad.l2m.lnbfin <- list(
  "PFOS" = glm(LNBFIN ~ L2PFOS, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNBFIN ~ L2PFOA, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNBFIN ~ L2PFNA, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNBFIN ~ L2PFHxS, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(LNBFIN ~ L2MeFOSAA, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(LNBFIN ~ L2EtFOSAA, family = gaussian, data = PFAS_D))
modelsummary(unad.l2m.lnbfin, fmt = 4, title = "LOG2-PFAS vs. LN-TOTAL BODY FAT MASS INDEX (Unadjusted)")


# TOTAL BODY FAT %
# unad.lnm.totpfat <- list(
#   "PFOS" = glm(TotFatPct ~ LNPFOS, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(TotFatPct ~ LNPFOA, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(TotFatPct ~ LNPFNA, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(TotFatPct ~ LNPFHxS, family = gaussian, data = PFAS_D),
#   "MeFOSAA" = glm(TotFatPct ~ LNMeFOSAA, family = gaussian, data = PFAS_D),
#   "EtFOSAA" = glm(TotFatPct ~ LNEtFOSAA, family = gaussian, data = PFAS_D))
# modelsummary(unad.lnm.totpfat, fmt = 4, title = "LN-PFAS vs. TOTAL BODY FAT % (Unadjusted)")

unad.l2m.totpfat <- list(
  "PFOS" = glm(TotFatPct ~ L2PFOS, family = gaussian, data = PFAS_D),
  "PFOA" = glm(TotFatPct ~ L2PFOA, family = gaussian, data = PFAS_D),
  "PFNA" = glm(TotFatPct ~ L2PFNA, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(TotFatPct ~ L2PFHxS, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(TotFatPct ~ L2MeFOSAA, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(TotFatPct ~ L2EtFOSAA, family = gaussian, data = PFAS_D))
modelsummary(unad.l2m.totpfat, fmt = 4, title = "LOG2-PFAS vs. TOTAL BODY FAT % (Unadjusted)")

#unad.lnm.lntotpfat <- list(
#  "PFOS" = glm(LNPFAT ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNPFAT ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNPFAT ~ LNPFNA, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNPFAT ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSAA" = glm(LNPFAT ~ LNMeFOSAA, family = gaussian, data = PFAS_D),
#  "EtFOSAA" = glm(LNPFAT ~ LNEtFOSAA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.lntotpfat, fmt = 4, title = "LN-PFAS vs. LN-TOTAL BODY FAT % (Unadjusted)")


# TOTAL BODY LEAN MASS
#unad.lnm.totlean <- list(
#  "PFOS" = glm(TotLean ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(TotLean ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(TotLean ~ LNPFNA, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(TotLean ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSAA" = glm(TotLean ~ LNMeFOSAA, family = gaussian, data = PFAS_D),
#  "EtFOSAA" = glm(TotLean ~ LNEtFOSAA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.totlean, fmt = 4, title = "LN-PFAS vs. TOTAL BODY LEAN MASS (Unadjusted)")

#unad.lnm.lntotlean <- list(
#  "PFOS" = glm(LNTOTLEAN ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNTOTLEAN ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNTOTLEAN ~ LNPFNA, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNTOTLEAN ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSAA" = glm(LNTOTLEAN ~ LNMeFOSAA, family = gaussian, data = PFAS_D),
#  "EtFOSAA" = glm(LNTOTLEAN ~ LNEtFOSAA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.lntotlean, fmt = 4, title = "LN-PFAS vs. LN-TOTAL BODY LEAN MASS (Unadjusted)")

# VAT AREA
#unad.lnm.lnvata <- list(
#  "PFOS" = glm(LNVAT_AREA ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNVAT_AREA ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNVAT_AREA ~ LNPFNA, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNVAT_AREA ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSAA" = glm(LNVAT_AREA ~ LNMeFOSAA, family = gaussian, data = PFAS_D),
#  "EtFOSAA" = glm(LNVAT_AREA ~ LNEtFOSAA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.lnvata, fmt = 4, title = "LN-PFAS vs. LN-VAT AREA (Unadjusted)")


# SAAT AREA
#unad.lnm.lnsata <- list(
#  "PFOS" = glm(LNSAT_AREA ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNSAT_AREA ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNSAT_AREA ~ LNPFNA, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNSAT_AREA ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSAA" = glm(LNSAT_AREA ~ LNMeFOSAA, family = gaussian, data = PFAS_D),
#  "EtFOSAA" = glm(LNSAT_AREA ~ LNEtFOSAA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.lnsata, fmt = 4, title = "LN-PFAS vs. LN-SAAT AREA (Unadjusted)")


# TAAT AREA
#unad.lnm.lntata <- list(
#  "PFOS" = glm(LNTAT_AREA ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNTAT_AREA ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNTAT_AREA ~ LNPFNA, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNTAT_AREA ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSAA" = glm(LNTAT_AREA ~ LNMeFOSAA, family = gaussian, data = PFAS_D),
#  "EtFOSAA" = glm(LNTAT_AREA ~ LNEtFOSAA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.lntata, fmt = 4, title = "LN-PFAS vs. LN-TAAT AREA (Unadjusted)")


# VAT MASS
#unad.lnm.lnvatm <- list(
#  "PFOS" = glm(LNVAT_MASS ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNVAT_MASS ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNVAT_MASS ~ LNPFNA, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNVAT_MASS ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSAA" = glm(LNVAT_MASS ~ LNMeFOSAA, family = gaussian, data = PFAS_D),
#  "EtFOSAA" = glm(LNVAT_MASS ~ LNEtFOSAA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.lnvatm, fmt = 4, title = "LN-PFAS vs. LN-VAT MASS (Unadjusted)")


# SAAT MASS
#unad.lnm.lnsatm <- list(
#  "PFOS" = glm(LNSAT_MASS ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNSAT_MASS ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNSAT_MASS ~ LNPFNA, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNSAT_MASS ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSAA" = glm(LNSAT_MASS ~ LNMeFOSAA, family = gaussian, data = PFAS_D),
#  "EtFOSAA" = glm(LNSAT_MASS ~ LNEtFOSAA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.lnsatm, fmt = 4, title = "LN-PFAS vs. LN-SAAT MASS (Unadjusted)")


# TAAT MASS
#unad.lnm.lntatm <- list(
#  "PFOS" = glm(LNTAT_MASS ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNTAT_MASS ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNTAT_MASS ~ LNPFNA, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNTAT_MASS ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSAA" = glm(LNTAT_MASS ~ LNMeFOSAA, family = gaussian, data = PFAS_D),
#  "EtFOSAA" = glm(LNTAT_MASS ~ LNEtFOSAA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.lntatm, fmt = 4, title = "LN-PFAS vs. LN-TAAT MASS (Unadjusted)")


# VAT VOLUME
#unad.lnm.lnvatv <- list(
#  "PFOS" = glm(LNVAT_VOLUME ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNVAT_VOLUME ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNVAT_VOLUME ~ LNPFNA, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNVAT_VOLUME ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSAA" = glm(LNVAT_VOLUME ~ LNMeFOSAA, family = gaussian, data = PFAS_D),
#  "EtFOSAA" = glm(LNVAT_VOLUME ~ LNEtFOSAA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.lnvatv, fmt = 4, title = "LN-PFAS vs. LN-VAT VOLUME (Unadjusted)")


# SAAT VOLUME
#unad.lnm.lnsatv <- list(
#  "PFOS" = glm(LNSAT_VOLUME ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNSAT_VOLUME ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNSAT_VOLUME ~ LNPFNA, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNSAT_VOLUME ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSAA" = glm(LNSAT_VOLUME ~ LNMeFOSAA, family = gaussian, data = PFAS_D),
#  "EtFOSAA" = glm(LNSAT_VOLUME ~ LNEtFOSAA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.lnsatv, fmt = 4, title = "LN-PFAS vs. LN-SAAT VOLUME (Unadjusted)")


# TAAT VOLUME
#unad.lnm.lntatv <- list(
#  "PFOS" = glm(LNTAT_VOLUME ~ LNPFOS, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNTAT_VOLUME ~ LNPFOA, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNTAT_VOLUME ~ LNPFNA, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNTAT_VOLUME ~ LNPFHxS, family = gaussian, data = PFAS_D),
#  "MeFOSAA" = glm(LNTAT_VOLUME ~ LNMeFOSAA, family = gaussian, data = PFAS_D),
#  "EtFOSAA" = glm(LNTAT_VOLUME ~ LNEtFOSAA, family = gaussian, data = PFAS_D))
#modelsummary(unad.lnm.lntatv, fmt = 4, title = "LN-PFAS vs. LN-TAAT VOLUME (Unadjusted)")

```

```{r}
##### RUN ADJUSTED LINEAR REGRESSION MODELS, ANTHRO DATASET (N = 545)

# BMI
# ad.lnm.lnbmi <- list(
#   "PFOS" = glm(LNBMI ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#   "PFOA" = glm(LNBMI ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#   "PFNA" = glm(LNBMI ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#   "PFHxS" = glm(LNBMI ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke +  
#                   parity + married + fish, family = gaussian, data = PFAS_A),
#   "MeFOSAA" = glm(LNBMI ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                     parity + married + fish, family = gaussian, data = PFAS_A),
#   "EtFOSAA" = glm(LNBMI ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                     parity + married + fish, family = gaussian, data = PFAS_A))
# 
# modelsummary(ad.lnm.lnbmi, fmt = 4,
#              estimate = "{estimate}{stars}",
#              statistic = c("SE: {std.error}",
#                            "95% CI: [{conf.low}, {conf.high}]"),
#              coef_omit = "Interc", title = "LN-PFAS vs. LN-BMI (Adjusted)")

# ad.l2m.lnbmi <- list(
#   "PFOS" = glm(LNBMI ~ L2PFOS + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#   "PFOA" = glm(LNBMI ~ L2PFOA + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#   "PFNA" = glm(LNBMI ~ L2PFNA + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#   "PFHxS" = glm(LNBMI ~ L2PFHxS + age_enroll + race + bmi_cat + income + smoke +  
#                   parity + married + fish, family = gaussian, data = PFAS_A),
#   "MeFOSAA" = glm(LNBMI ~ L2MeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                     parity + married + fish, family = gaussian, data = PFAS_A),
#   "EtFOSAA" = glm(LNBMI ~ L2EtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                     parity + married + fish, family = gaussian, data = PFAS_A))
# 
# modelsummary(ad.l2m.lnbmi, fmt = 4,
#              estimate = "{estimate}{stars}",
#              statistic = c("SE: {std.error}",
#                            "95% CI: [{conf.low}, {conf.high}]",
#                            "p = {p.value}"),
#              coef_omit = "Interc", title = "LOG2-PFAS vs. LN-BMI (Adjusted)")

ad.l2m.bmi <- list(
  "PFOS" = glm(BMI ~ L2PFOS + age_enroll + race + bmi_cat + bmi_cat + income + smoke +  
                 parity + married + fish, family = gaussian, data = PFAS_A),
  "PFOA" = glm(BMI ~ L2PFOA + age_enroll + race + bmi_cat + income + smoke +  
                 parity + married + fish, family = gaussian, data = PFAS_A),
  "PFNA" = glm(BMI ~ L2PFNA + age_enroll + race + bmi_cat + income + smoke +  
                 parity + married + fish, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(BMI ~ L2PFHxS + age_enroll + race + bmi_cat + income + smoke +  
                  parity + married + fish, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(BMI ~ L2MeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
                    parity + married + fish, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(BMI ~ L2EtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
                    parity + married + fish, family = gaussian, data = PFAS_A))

modelsummary(ad.l2m.bmi, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. BMI (Adjusted)")


# WEIGHT
ad.l2m.wt <- list(
  "PFOS" = glm(Weight ~ L2PFOS + age_enroll + race + bmi_cat + income + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_A),
  "PFOA" = glm(Weight ~ L2PFOA + age_enroll + race + bmi_cat + income + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_A),
  "PFNA" = glm(Weight ~ L2PFNA + age_enroll + race + bmi_cat + income + smoke +  
                 parity + married + fish + height, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(Weight ~ L2PFHxS + age_enroll + race + bmi_cat + income + smoke +  
                  parity + married + fish + height, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(Weight ~ L2MeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
                    parity + married + fish + height, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(Weight ~ L2EtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
                    parity + married + fish + height, family = gaussian, data = PFAS_A))

modelsummary(ad.l2m.wt, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WEIGHT (Adjusted)")


# DIFFERENCE IN BMI
ad.l2m.dbmi <- list(
  "PFOS" = glm(DBMI ~ L2PFOS + age_enroll + race + bmi_cat + income + smoke +  
                 parity + married + fish, family = gaussian, data = PFAS_A),
  "PFOA" = glm(DBMI ~ L2PFOA + age_enroll + race + bmi_cat + income + smoke +  
                 parity + married + fish, family = gaussian, data = PFAS_A),
  "PFNA" = glm(DBMI ~ L2PFNA + age_enroll + race + bmi_cat + income + smoke +  
                 parity + married + fish, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(DBMI ~ L2PFHxS + age_enroll + race + bmi_cat + income + smoke +  
                  parity + married + fish, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(DBMI ~ L2MeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
                    parity + married + fish, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(DBMI ~ L2EtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
                    parity + married + fish, family = gaussian, data = PFAS_A))

modelsummary(ad.l2m.dbmi, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. DIFF IN BMI (Adjusted)")


# WAIST CIRCUMFERENCE
# ad.lnm.waist <- list(
#   "PFOS" = glm(Waist ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#   "PFOA" = glm(Waist ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#   "PFNA" = glm(Waist ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#   "PFHxS" = glm(Waist ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke +  
#                   parity + married + fish, family = gaussian, data = PFAS_A),
#   "MeFOSAA" = glm(Waist ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                     parity + married + fish, family = gaussian, data = PFAS_A),
#   "EtFOSAA" = glm(Waist ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                     parity + married + fish, family = gaussian, data = PFAS_A))
# 
# modelsummary(ad.lnm.waist, fmt = 4,
#              estimate = "{estimate}{stars}",
#              statistic = c("SE: {std.error}",
#                            "95% CI: [{conf.low}, {conf.high}]"),
#              coef_omit = "Interc", title = "LN-PFAS vs. WAIST CIRCUMFERENCE (Adjusted)")

ad.l2m.waist <- list(
  "PFOS" = glm(Waist ~ L2PFOS + age_enroll + race + bmi_cat + income + smoke +  
                 parity + married + fish, family = gaussian, data = PFAS_A),
  "PFOA" = glm(Waist ~ L2PFOA + age_enroll + race + bmi_cat + income + smoke +  
                 parity + married + fish, family = gaussian, data = PFAS_A),
  "PFNA" = glm(Waist ~ L2PFNA + age_enroll + race + bmi_cat + income + smoke +  
                 parity + married + fish, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(Waist ~ L2PFHxS + age_enroll + race + bmi_cat + income + smoke +  
                  parity + married + fish, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(Waist ~ L2MeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
                    parity + married + fish, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(Waist ~ L2EtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
                    parity + married + fish, family = gaussian, data = PFAS_A))

modelsummary(ad.l2m.waist, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WAIST CIRCUMFERENCE (Adjusted)")

#ad.lnm.lnwaist <- list(
#  "PFOS" = glm(LNWAIST ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNWAIST ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNWAIST ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNWAIST ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#  "MeFOSAA" = glm(LNWAIST ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                    parity + married + fish, family = gaussian, data = PFAS_A),
#  "EtFOSAA" = glm(LNWAIST ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                    parity + married + fish, family = gaussian, data = PFAS_A))

#modelsummary(ad.lnm.lnwaist, fmt = 4,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "LN-PFAS vs. LN-WAIST CIRCUMFERENCE (Adjusted)")


# WAIST-TO-HIP RATIO
# ad.lnm.whr <- list(
#   "PFOS" = glm(WHR ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#   "PFOA" = glm(WHR ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#   "PFNA" = glm(WHR ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#   "PFHxS" = glm(WHR ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke +  
#                   parity + married + fish, family = gaussian, data = PFAS_A),
#   "MeFOSAA" = glm(WHR ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                     parity + married + fish, family = gaussian, data = PFAS_A),
#   "EtFOSAA" = glm(WHR ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                     parity + married + fish, family = gaussian, data = PFAS_A))
# 
# modelsummary(ad.lnm.whr, fmt = 4,
#              estimate = "{estimate}{stars}",
#              statistic = c("SE: {std.error}",
#                            "95% CI: [{conf.low}, {conf.high}]"),
#              coef_omit = "Interc", title = "LN-PFAS vs. WHR (Adjusted)")

ad.l2m.whr <- list(
  "PFOS" = glm(WHR ~ L2PFOS + age_enroll + race + bmi_cat + income + smoke +  
                 parity + married + fish, family = gaussian, data = PFAS_A),
  "PFOA" = glm(WHR ~ L2PFOA + age_enroll + race + bmi_cat + income + smoke +  
                 parity + married + fish, family = gaussian, data = PFAS_A),
  "PFNA" = glm(WHR ~ L2PFNA + age_enroll + race + bmi_cat + income + smoke +  
                 parity + married + fish, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(WHR ~ L2PFHxS + age_enroll + race + bmi_cat + income + smoke +  
                  parity + married + fish, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(WHR ~ L2MeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
                    parity + married + fish, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(WHR ~ L2EtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
                    parity + married + fish, family = gaussian, data = PFAS_A))

modelsummary(ad.l2m.whr, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WHR (Adjusted)")

#ad.lnm.lnwhr <- list(
#  "PFOS" = glm(LNWHR ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNWHR ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNWHR ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNWHR ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#  "MeFOSAA" = glm(LNWHR ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                    parity + married + fish, family = gaussian, data = PFAS_A),
#  "EtFOSAA" = glm(LNWHR ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                    parity + married + fish, family = gaussian, data = PFAS_A))

#modelsummary(ad.lnm.lnwhr, fmt = 4,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "LN-PFAS vs. LN-WHR (Adjusted)")


# WAIST-TO-HEIGHT RATIO
# ad.lnm.whr <- list(
#   "PFOS" = glm(WHtR ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#   "PFOA" = glm(WHtR ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#   "PFNA" = glm(WHtR ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#   "PFHxS" = glm(WHtR ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke +  
#                   parity + married + fish, family = gaussian, data = PFAS_A),
#   "MeFOSAA" = glm(WHtR ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                     parity + married + fish, family = gaussian, data = PFAS_A),
#   "EtFOSAA" = glm(WHtR ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                     parity + married + fish, family = gaussian, data = PFAS_A))
# 
# modelsummary(ad.lnm.whtr, fmt = 4,
#              estimate = "{estimate}{stars}",
#              statistic = c("SE: {std.error}",
#                            "95% CI: [{conf.low}, {conf.high}]"),
#              coef_omit = "Interc", title = "LN-PFAS vs. WHtR (Adjusted)")

ad.l2m.whtr <- list(
  "PFOS" = glm(WHtR ~ L2PFOS + age_enroll + race + bmi_cat + income + smoke +  
                 parity + married + fish, family = gaussian, data = PFAS_A),
  "PFOA" = glm(WHtR ~ L2PFOA + age_enroll + race + bmi_cat + income + smoke +  
                 parity + married + fish, family = gaussian, data = PFAS_A),
  "PFNA" = glm(WHtR ~ L2PFNA + age_enroll + race + bmi_cat + income + smoke +  
                 parity + married + fish, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(WHtR ~ L2PFHxS + age_enroll + race + bmi_cat + income + smoke +  
                  parity + married + fish, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(WHtR ~ L2MeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
                    parity + married + fish, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(WHtR ~ L2EtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
                    parity + married + fish, family = gaussian, data = PFAS_A))

modelsummary(ad.l2m.whtr, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. WHtR (Adjusted)")


# MUAC
# ad.lnm.muac <- list(
#   "PFOS" = glm(MUAC ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#   "PFOA" = glm(MUAC ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#   "PFNA" = glm(MUAC ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#   "PFHxS" = glm(MUAC ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke +  
#                   parity + married + fish, family = gaussian, data = PFAS_A),
#   "MeFOSAA" = glm(MUAC ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                     parity + married + fish, family = gaussian, data = PFAS_A),
#   "EtFOSAA" = glm(MUAC ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                     parity + married + fish, family = gaussian, data = PFAS_A))
# 
# modelsummary(ad.lnm.muac, fmt = 4,
#              estimate = "{estimate}{stars}",
#              statistic = c("SE: {std.error}",
#                            "95% CI: [{conf.low}, {conf.high}]"),
#              coef_omit = "Interc", title = "LN-PFAS vs. MUAC (Adjusted)")

ad.l2m.muac <- list(
  "PFOS" = glm(MUAC ~ L2PFOS + age_enroll + race + bmi_cat + income + smoke +  
                 parity + married + fish, family = gaussian, data = PFAS_A),
  "PFOA" = glm(MUAC ~ L2PFOA + age_enroll + race + bmi_cat + income + smoke +  
                 parity + married + fish, family = gaussian, data = PFAS_A),
  "PFNA" = glm(MUAC ~ L2PFNA + age_enroll + race + bmi_cat + income + smoke +  
                 parity + married + fish, family = gaussian, data = PFAS_A),
  "PFHxS" = glm(MUAC ~ L2PFHxS + age_enroll + race + bmi_cat + income + smoke +  
                  parity + married + fish, family = gaussian, data = PFAS_A),
  "MeFOSAA" = glm(MUAC ~ L2MeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
                    parity + married + fish, family = gaussian, data = PFAS_A),
  "EtFOSAA" = glm(MUAC ~ L2EtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
                    parity + married + fish, family = gaussian, data = PFAS_A))

modelsummary(ad.l2m.muac, fmt = 4,
             estimate = "{estimate}{stars}",
             statistic = c("SE: {std.error}",
                           "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"),
             coef_omit = "Interc", title = "LOG2-PFAS vs. MUAC (Adjusted)")

#ad.lnm.lnmuac <- list(
#  "PFOS" = glm(LNMUAC ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNMUAC ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNMUAC ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNMUAC ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#  "MeFOSAA" = glm(LNMUAC ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                    parity + married + fish, family = gaussian, data = PFAS_A),
#  "EtFOSAA" = glm(LNMUAC ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                    parity + married + fish, family = gaussian, data = PFAS_A))

#modelsummary(ad.lnm.lnmuac, fmt = 4,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "LN-PFAS vs. LN-MUAC (Adjusted)")


# WEIGHT
#ad.lnm.wt <- list(
#  "PFOS" = glm(Weight ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(Weight ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(Weight ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(Weight ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#  "MeFOSAA" = glm(Weight ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                    parity + married + fish, family = gaussian, data = PFAS_A),
#  "EtFOSAA" = glm(Weight ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                    parity + married + fish, family = gaussian, data = PFAS_A))
#
#modelsummary(ad.lnm.wt, fmt = 4,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "LN-PFAS vs. WEIGHT (Adjusted)")

#ad.lnm.lnwt <- list(
#  "PFOS" = glm(LNWT ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNWT ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNWT ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNWT ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#  "MeFOSAA" = glm(LNWT ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                    parity + married + fish, family = gaussian, data = PFAS_A),
#  "EtFOSAA" = glm(LNWT ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                    parity + married + fish, family = gaussian, data = PFAS_A))

#modelsummary(ad.lnm.lnwt, fmt = 4,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "LN-PFAS vs. LN-WEIGHT (Adjusted)")


# BODY FAT %
#ad.lnm.bfat <- list(
#  "PFOS" = glm(FatPct ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(FatPct ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(FatPct ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(FatPct ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#  "MeFOSAA" = glm(FatPct ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                    parity + married + fish, family = gaussian, data = PFAS_A),
#  "EtFOSAA" = glm(FatPct ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                    parity + married + fish, family = gaussian, data = PFAS_A))

#modelsummary(ad.lnm.bfat, fmt = 4,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "LN-PFAS vs. BODY FAT % (Adjusted)")

#ad.lnm.lnbfat <- list(
#  "PFOS" = glm(LNBFAT ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNBFAT ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNBFAT ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNBFAT ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#  "MeFOSAA" = glm(LNBFAT ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                    parity + married + fish, family = gaussian, data = PFAS_A),
#  "EtFOSAA" = glm(LNBFAT ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                    parity + married + fish, family = gaussian, data = PFAS_A))

#modelsummary(ad.lnm.lnbfat, fmt = 4,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "LN-PFAS vs. LN-BODY FAT % (Adjusted)")


# BODY FAT MASS
#ad.lnm.fat <- list(
#  "PFOS" = glm(FatMass ~ LNPFOS + age_enroll + race + bmi_cat + income +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(FatMass ~ LNPFOA + age_enroll + race + bmi_cat + income +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(FatMass ~ LNPFNA + age_enroll + race + bmi_cat + income +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(FatMass ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#  "MeFOSAA" = glm(FatMass ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                    parity + married + fish, family = gaussian, data = PFAS_A),
#  "EtFOSAA" = glm(FatMass ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                    parity + married + fish, family = gaussian, data = PFAS_A))

#modelsummary(ad.lnm.fat, fmt = 4,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "LN-PFAS vs. BODY FAT MASS (Adjusted)")

#ad.lnm.lnfat <- list(
#  "PFOS" = glm(LNFAT ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFOA" = glm(LNFAT ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFNA" = glm(LNFAT ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke +  
#                 parity + married + fish, family = gaussian, data = PFAS_A),
#  "PFHxS" = glm(LNFAT ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke +  
#                  parity + married + fish, family = gaussian, data = PFAS_A),
#  "MeFOSAA" = glm(LNFAT ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                    parity + married + fish, family = gaussian, data = PFAS_A),
#  "EtFOSAA" = glm(LNFAT ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke +  
#                    parity + married + fish, family = gaussian, data = PFAS_A))

#modelsummary(ad.lnm.lnfat, fmt = 4,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "LN-PFAS vs. LN-BODY FAT MASS (Adjusted)")

```


```{r}
##### RUN ADJUSTED LINEAR REGRESSION MODELS, ANTHRO + DXA DATASET (N = 432)

# TRUNK FAT MASS
# ad.lnm.trnkfat <- list(
#   "PFOS" = glm(TrnkFat ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(TrnkFat ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(TrnkFat ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(TrnkFat ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke + 
#                   parity + married + fish, family = gaussian, data = PFAS_D),
#   "MeFOSAA" = glm(TrnkFat ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D),
#   "EtFOSAA" = glm(TrnkFat ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.trnkfat, fmt = 4, estimate = "{estimate}{stars}", 
#              statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
#              coef_omit = "Interc", title = "LN-PFAS vs. TRUNK FAT MASS (Adjusted)")

# ad.lnm.lntrnkfat <- list(
#   "PFOS" = glm(LNTKNFAT ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNTKNFAT ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNTKNFAT ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNTKNFAT ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke + 
#                   parity + married + fish, family = gaussian, data = PFAS_D),
#   "MeFOSAA" = glm(LNTKNFAT ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D),
#   "EtFOSAA" = glm(LNTKNFAT ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.lntrnkfat, fmt = 4, estimate = "{estimate}{stars}", 
#              statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
#              coef_omit = "Interc", title = "LN-PFAS vs. LN-TRUNK FAT MASS (Adjusted)")

ad.l2m.lntrnkfat <- list(
  "PFOS" = glm(LNTKNFAT ~ L2PFOS + age_enroll + race + bmi_cat + income + smoke + 
                 parity + married + fish, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTKNFAT ~ L2PFOA + age_enroll + race + bmi_cat + income + smoke + 
                 parity + married + fish, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTKNFAT ~ L2PFNA + age_enroll + race + bmi_cat + income + smoke + 
                 parity + married + fish, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTKNFAT ~ L2PFHxS + age_enroll + race + bmi_cat + income + smoke + 
                  parity + married + fish, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(LNTKNFAT ~ L2MeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
                    parity + married + fish, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(LNTKNFAT ~ L2EtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
                    parity + married + fish, family = gaussian, data = PFAS_D))

modelsummary(ad.l2m.lntrnkfat, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-TRUNK FAT MASS (Adjusted)")


# TOTAL BODY FAT MASS
# ad.lnm.totfat <- list(
#   "PFOS" = glm(TotFat ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(TotFat ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(TotFat ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(TotFat ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke + 
#                   parity + married + fish, family = gaussian, data = PFAS_D),
#   "MeFOSAA" = glm(TotFat ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D),
#   "EtFOSAA" = glm(TotFat ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.totfat, fmt = 4, estimate = "{estimate}{stars}", 
#              statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
#              coef_omit = "Interc", title = "LN-PFAS vs. TOTAL BODY FAT MASS (Adjusted)")

# ad.lnm.lntotfat <- list(
#   "PFOS" = glm(LNTOTFAT ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNTOTFAT ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNTOTFAT ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNTOTFAT ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke + 
#                   parity + married + fish, family = gaussian, data = PFAS_D),
#   "MeFOSAA" = glm(LNTOTFAT ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D),
#   "EtFOSAA" = glm(LNTOTFAT ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.lntotfat, fmt = 4, estimate = "{estimate}{stars}", 
#              statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
#              coef_omit = "Interc", title = "LN-PFAS vs. LN-TOTAL BODY FAT MASS (Adjusted)")

ad.l2m.lntotfat <- list(
  "PFOS" = glm(LNTOTFAT ~ L2PFOS + age_enroll + race + bmi_cat + income + smoke + 
                 parity + married + fish, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTOTFAT ~ L2PFOA + age_enroll + race + bmi_cat + income + smoke + 
                 parity + married + fish, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTOTFAT ~ L2PFNA + age_enroll + race + bmi_cat + income + smoke + 
                 parity + married + fish, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTOTFAT ~ L2PFHxS + age_enroll + race + bmi_cat + income + smoke + 
                  parity + married + fish, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(LNTOTFAT ~ L2MeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
                    parity + married + fish, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(LNTOTFAT ~ L2EtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
                    parity + married + fish, family = gaussian, data = PFAS_D))

modelsummary(ad.l2m.lntotfat, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-TOTAL BODY FAT MASS (Adjusted)")


# TRUNK FAT MASS INDEX
ad.l2m.lntfin <- list(
  "PFOS" = glm(LNTFIN ~ L2PFOS + age_enroll + race + bmi_cat + income + smoke + 
                 parity + married + fish, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNTFIN ~ L2PFOA + age_enroll + race + bmi_cat + income + smoke + 
                 parity + married + fish, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNTFIN ~ L2PFNA + age_enroll + race + bmi_cat + income + smoke + 
                 parity + married + fish, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNTFIN ~ L2PFHxS + age_enroll + race + bmi_cat + income + smoke + 
                  parity + married + fish, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(LNTFIN ~ L2MeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
                    parity + married + fish, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(LNTFIN ~ L2EtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
                    parity + married + fish, family = gaussian, data = PFAS_D))

modelsummary(ad.l2m.lntfin, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-TRUNK FAT MASS INDEX (Adjusted)")


# TOTAL BODY FAT MASS INDEX
ad.l2m.lnbfin <- list(
  "PFOS" = glm(LNBFIN ~ L2PFOS + age_enroll + race + bmi_cat + income + smoke + 
                 parity + married + fish, family = gaussian, data = PFAS_D),
  "PFOA" = glm(LNBFIN ~ L2PFOA + age_enroll + race + bmi_cat + income + smoke + 
                 parity + married + fish, family = gaussian, data = PFAS_D),
  "PFNA" = glm(LNBFIN ~ L2PFNA + age_enroll + race + bmi_cat + income + smoke + 
                 parity + married + fish, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(LNBFIN ~ L2PFHxS + age_enroll + race + bmi_cat + income + smoke + 
                  parity + married + fish, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(LNBFIN ~ L2MeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
                    parity + married + fish, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(LNBFIN ~ L2EtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
                    parity + married + fish, family = gaussian, data = PFAS_D))

modelsummary(ad.l2m.lnbfin, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. LN-TOTAL BODY FAT MASS INDEX (Adjusted)")


# TOTAL BODY FAT %
# ad.lnm.totpfat <- list(
#   "PFOS" = glm(TotFatPct ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(TotFatPct ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(TotFatPct ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(TotFatPct ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke + 
#                   parity + married + fish, family = gaussian, data = PFAS_D),
#   "MeFOSAA" = glm(TotFatPct ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D),
#   "EtFOSAA" = glm(TotFatPct ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.totpfat, fmt = 4, estimate = "{estimate}{stars}", 
#              statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
#              coef_omit = "Interc", title = "LN-PFAS vs. TOTAL BODY FAT % (Adjusted)")

ad.l2m.totpfat <- list(
  "PFOS" = glm(TotFatPct ~ L2PFOS + age_enroll + race + bmi_cat + income + smoke + 
                 parity + married + fish, family = gaussian, data = PFAS_D),
  "PFOA" = glm(TotFatPct ~ L2PFOA + age_enroll + race + bmi_cat + income + smoke + 
                 parity + married + fish, family = gaussian, data = PFAS_D),
  "PFNA" = glm(TotFatPct ~ L2PFNA + age_enroll + race + bmi_cat + income + smoke + 
                 parity + married + fish, family = gaussian, data = PFAS_D),
  "PFHxS" = glm(TotFatPct ~ L2PFHxS + age_enroll + race + bmi_cat + income + smoke + 
                  parity + married + fish, family = gaussian, data = PFAS_D),
  "MeFOSAA" = glm(TotFatPct ~ L2MeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
                    parity + married + fish, family = gaussian, data = PFAS_D),
  "EtFOSAA" = glm(TotFatPct ~ L2EtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
                    parity + married + fish, family = gaussian, data = PFAS_D))

modelsummary(ad.l2m.totpfat, fmt = 4, estimate = "{estimate}{stars}", 
             statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]",
                           "p = {p.value}"), 
             coef_omit = "Interc", title = "LOG2-PFAS vs. TOTAL BODY FAT % (Adjusted)")

# ad.lnm.lntotpfat <- list(
#   "PFOS" = glm(LNPFAT ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNPFAT ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNPFAT ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNPFAT ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke + 
#                   parity + married + fish, family = gaussian, data = PFAS_D),
#   "MeFOSAA" = glm(LNPFAT ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D),
#   "EtFOSAA" = glm(LNPFAT ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.lntotpfat, fmt = 4, estimate = "{estimate}{stars}", 
#              statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
#              coef_omit = "Interc", title = "LN-PFAS vs. LN-TOTAL BODY FAT % (Adjusted)")


# TOTAL BODY LEAN MASS
# ad.lnm.totlean <- list(
#   "PFOS" = glm(TotLean ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(TotLean ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(TotLean ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(TotLean ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke + 
#                   parity + married + fish, family = gaussian, data = PFAS_D),
#   "MeFOSAA" = glm(TotLean ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D),
#   "EtFOSAA" = glm(TotLean ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.totlean, fmt = 4, estimate = "{estimate}{stars}", 
#              statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
#              coef_omit = "Interc", title = "LN-PFAS vs. TOTAL BODY LEAN MASS (Adjusted)")

# ad.lnm.lntotlean <- list(
#   "PFOS" = glm(LNTOTLEAN ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNTOTLEAN ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNTOTLEAN ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNTOTLEAN ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke + 
#                   parity + married + fish, family = gaussian, data = PFAS_D),
#   "MeFOSAA" = glm(LNTOTLEAN ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D),
#   "EtFOSAA" = glm(LNTOTLEAN ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.lntotlean, fmt = 4, estimate = "{estimate}{stars}", 
#              statistic = c("SE: {std.error}", "95% CI: [{conf.low}, {conf.high}]"), 
#              coef_omit = "Interc", title = "LN-PFAS vs. LN-TOTAL BODY LEAN MASS (Adjusted)")


# VAT AREA
#ad.lnm.lnvata <- list(
#  "PFOS" = glm(LNVAT_AREA ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke + 
#                 parity + married + fish, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNVAT_AREA ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke + 
#                 parity + married + fish, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNVAT_AREA ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke + 
#                 parity + married + fish, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNVAT_AREA ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#  "MeFOSAA" = glm(LNVAT_AREA ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                    parity + married + fish, family = gaussian, data = PFAS_D),
#  "EtFOSAA" = glm(LNVAT_AREA ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                    parity + married + fish, family = gaussian, data = PFAS_D))

#modelsummary(ad.lnm.lnvata, fmt = 4,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "LN-PFAS vs. LN-VAT AREA (Adjusted)")


# SAAT AREA
#ad.lnm.lnsata <- list(
#  "PFOS" = glm(LNSAT_AREA ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke + 
#                 parity + married + fish, family = gaussian, data = PFAS_D),
#  "PFOA" = glm(LNSAT_AREA ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke + 
#                 parity + married + fish, family = gaussian, data = PFAS_D),
#  "PFNA" = glm(LNSAT_AREA ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke + 
#                 parity + married + fish, family = gaussian, data = PFAS_D),
#  "PFHxS" = glm(LNSAT_AREA ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#  "MeFOSAA" = glm(LNSAT_AREA ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                    parity + married + fish, family = gaussian, data = PFAS_D),
#  "EtFOSAA" = glm(LNSAT_AREA ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                    parity + married + fish, family = gaussian, data = PFAS_D))

#modelsummary(ad.lnm.lnsata, fmt = 4,
#             estimate = "{estimate}{stars}",
#             statistic = c("SE: {std.error}",
#                           "95% CI: [{conf.low}, {conf.high}]"),
#             coef_omit = "Interc", title = "LN-PFAS vs. LN-SAAT AREA (Adjusted)")


# TAAT AREA
# ad.lnm.lntata <- list(
#   "PFOS" = glm(LNTAT_AREA ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNTAT_AREA ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNTAT_AREA ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNTAT_AREA ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke + 
#                   parity + married + fish, family = gaussian, data = PFAS_D),
#   "MeFOSAA" = glm(LNTAT_AREA ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D),
#   "EtFOSAA" = glm(LNTAT_AREA ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.lntata, fmt = 4,
#              estimate = "{estimate}{stars}",
#              statistic = c("SE: {std.error}",
#                            "95% CI: [{conf.low}, {conf.high}]"),
#              coef_omit = "Interc", title = "LN-PFAS vs. LN-TAAT AREA (Adjusted)")


# VAT MASS
# ad.lnm.lnvatm <- list(
#   "PFOS" = glm(LNVAT_MASS ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNVAT_MASS ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNVAT_MASS ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNVAT_MASS ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke + 
#                   parity + married + fish, family = gaussian, data = PFAS_D),
#   "MeFOSAA" = glm(LNVAT_MASS ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D),
#   "EtFOSAA" = glm(LNVAT_MASS ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.lnvatm, fmt = 4,
#              estimate = "{estimate}{stars}",
#              statistic = c("SE: {std.error}",
#                            "95% CI: [{conf.low}, {conf.high}]"),
#              coef_omit = "Interc", title = "LN-PFAS vs. LN-VAT MASS (Adjusted)")


# SAAT MASS
# ad.lnm.lnsatm <- list(
#   "PFOS" = glm(LNSAT_MASS ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNSAT_MASS ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNSAT_MASS ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNSAT_MASS ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke + 
#                   parity + married + fish, family = gaussian, data = PFAS_D),
#   "MeFOSAA" = glm(LNSAT_MASS ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D),
#   "EtFOSAA" = glm(LNSAT_MASS ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.lnsatm, fmt = 4,
#              estimate = "{estimate}{stars}",
#              statistic = c("SE: {std.error}",
#                            "95% CI: [{conf.low}, {conf.high}]"),
#              coef_omit = "Interc", title = "LN-PFAS vs. LN-SAAT MASS (Adjusted)")


# TAAT MASS
# ad.lnm.lntatm <- list(
#   "PFOS" = glm(LNTAT_MASS ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNTAT_MASS ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNTAT_MASS ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNTAT_MASS ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke + 
#                   parity + married + fish, family = gaussian, data = PFAS_D),
#   "MeFOSAA" = glm(LNTAT_MASS ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D),
#   "EtFOSAA" = glm(LNTAT_MASS ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.lntatm, fmt = 4,
#              estimate = "{estimate}{stars}",
#              statistic = c("SE: {std.error}",
#                            "95% CI: [{conf.low}, {conf.high}]"),
#              coef_omit = "Interc", title = "LN-PFAS vs. LN-TAAT MASS (Adjusted)")


# VAT VOLUME
# ad.lnm.lnvatv <- list(
#   "PFOS" = glm(LNVAT_VOLUME ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNVAT_VOLUME ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNVAT_VOLUME ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNVAT_VOLUME ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke + 
#                   parity + married + fish, family = gaussian, data = PFAS_D),
#   "MeFOSAA" = glm(LNVAT_VOLUME ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D),
#   "EtFOSAA" = glm(LNVAT_VOLUME ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.lnvatv, fmt = 4,
#              estimate = "{estimate}{stars}",
#              statistic = c("SE: {std.error}",
#                            "95% CI: [{conf.low}, {conf.high}]"),
#              coef_omit = "Interc", title = "LN-PFAS vs. LN-VAT VOLUME (Adjusted)")


# SAAT VOLUME
# ad.lnm.lnsatv <- list(
#   "PFOS" = glm(LNSAT_VOLUME ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNSAT_VOLUME ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNSAT_VOLUME ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNSAT_VOLUME ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke + 
#                   parity + married + fish, family = gaussian, data = PFAS_D),
#   "MeFOSAA" = glm(LNSAT_VOLUME ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D),
#   "EtFOSAA" = glm(LNSAT_VOLUME ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.lnsatv, fmt = 4,
#              estimate = "{estimate}{stars}",
#              statistic = c("SE: {std.error}",
#                            "95% CI: [{conf.low}, {conf.high}]"),
#              coef_omit = "Interc", title = "LN-PFAS vs. LN-SAAT VOLUME (Adjusted)")


# TAAT VOLUME
# ad.lnm.lntatv <- list(
#   "PFOS" = glm(LNTAT_VOLUME ~ LNPFOS + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFOA" = glm(LNTAT_VOLUME ~ LNPFOA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFNA" = glm(LNTAT_VOLUME ~ LNPFNA + age_enroll + race + bmi_cat + income + smoke + 
#                  parity + married + fish, family = gaussian, data = PFAS_D),
#   "PFHxS" = glm(LNTAT_VOLUME ~ LNPFHxS + age_enroll + race + bmi_cat + income + smoke + 
#                   parity + married + fish, family = gaussian, data = PFAS_D),
#   "MeFOSAA" = glm(LNTAT_VOLUME ~ LNMeFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D),
#   "EtFOSAA" = glm(LNTAT_VOLUME ~ LNEtFOSAA + age_enroll + race + bmi_cat + income + smoke + 
#                     parity + married + fish, family = gaussian, data = PFAS_D))
# 
# modelsummary(ad.lnm.lntatv, fmt = 4,
#              estimate = "{estimate}{stars}",
#              statistic = c("SE: {std.error}",
#                            "95% CI: [{conf.low}, {conf.high}]"),
#              coef_omit = "Interc", title = "LN-PFAS vs. LN-TAAT VOLUME (Adjusted)")

```

```{r}
##### EMPLOY FDR CORRECTION
PFAS_A <- PFAS_A %>% relocate(aid, L2PFOS, L2PFOA, L2PFNA, L2PFHxS, L2MeFOSAA, L2EtFOSAA, everything()) 
PFAS_D <- PFAS_D %>% relocate(aid, L2PFOS, L2PFOA, L2PFNA, L2PFHxS, L2MeFOSAA, L2EtFOSAA, everything()) 

# BMI
pval_BMI <- NULL
for (i in 2:7){
m_BMI <- glm(PFAS_A$LNBMI ~ PFAS_A[[i]] + PFAS_A$age_enroll + PFAS_A$race + 
                PFAS_A$income + PFAS_A$menar + PFAS_A$smoke +  PFAS_A$parity + 
                PFAS_A$married, family = gaussian)
p_BMI <- summary(m_BMI)$coefficients[2,]
pval_BMI <- rbind(pval_BMI, p_BMI)
rownames(pval_BMI)[i-1] <- paste("X", i-1, sep="")
}

pval_BMI_set <- pval_BMI[,4]
BH_BMI <- p.adjust(pval_BMI_set, method="BH")
BY_BMI <- p.adjust(pval_BMI_set, method="BY")
FDR_BMI <- p.adjust(pval_BMI_set, method="fdr")
FWER_BMI <- as.data.frame(cbind(pval_BMI_set, BH_BMI, BY_BMI, FDR_BMI))
FWER_BMI


# Waist
pval_Waist <- NULL
for (i in 2:7){
m_Waist <- glm(PFAS_A$Waist ~ PFAS_A[[i]] + PFAS_A$age_enroll + PFAS_A$race + 
                PFAS_A$income + PFAS_A$menar + PFAS_A$smoke +  PFAS_A$parity + 
                PFAS_A$married, family = gaussian)
p_Waist <- summary(m_Waist)$coefficients[2,]
pval_Waist <- rbind(pval_Waist, p_Waist)
rownames(pval_Waist)[i-1] <- paste("X", i-1, sep="")
}

pval_Waist_set <- pval_Waist[,4]
BH_Waist <- p.adjust(pval_Waist_set, method="BH")
BY_Waist <- p.adjust(pval_Waist_set, method="BY")
FDR_Waist <- p.adjust(pval_Waist_set, method="fdr")
FWER_Waist <- as.data.frame(cbind(pval_Waist_set, BH_Waist, BY_Waist, FDR_Waist))
FWER_Waist


# WHR
pval_WHR <- NULL
for (i in 2:7){
m_WHR <- glm(PFAS_A$WHR ~ PFAS_A[[i]] + PFAS_A$age_enroll + PFAS_A$race + 
                PFAS_A$income + PFAS_A$menar + PFAS_A$smoke +  PFAS_A$parity + 
                PFAS_A$married, family = gaussian)
p_WHR <- summary(m_WHR)$coefficients[2,]
pval_WHR <- rbind(pval_WHR, p_WHR)
rownames(pval_WHR)[i-1] <- paste("X", i-1, sep="")
}

pval_WHR_set <- pval_WHR[,4]
BH_WHR <- p.adjust(pval_WHR_set, method="BH")
BY_WHR <- p.adjust(pval_WHR_set, method="BY")
FDR_WHR <- p.adjust(pval_WHR_set, method="fdr")
FWER_WHR <- as.data.frame(cbind(pval_WHR_set, BH_WHR, BY_WHR, FDR_WHR))
FWER_WHR


# WHtR
pval_WHtR <- NULL
for (i in 2:7){
m_WHtR <- glm(PFAS_A$WHtR ~ PFAS_A[[i]] + PFAS_A$age_enroll + PFAS_A$race + 
                PFAS_A$income + PFAS_A$menar + PFAS_A$smoke +  PFAS_A$parity + 
                PFAS_A$married, family = gaussian)
p_WHtR <- summary(m_WHtR)$coefficients[2,]
pval_WHtR <- rbind(pval_WHtR, p_WHtR)
rownames(pval_WHtR)[i-1] <- paste("X", i-1, sep="")
}

pval_WHtR_set <- pval_WHtR[,4]
BH_WHtR <- p.adjust(pval_WHtR_set, method="BH")
BY_WHtR <- p.adjust(pval_WHtR_set, method="BY")
FDR_WHtR <- p.adjust(pval_WHtR_set, method="fdr")
FWER_WHtR <- as.data.frame(cbind(pval_WHtR_set, BH_WHtR, BY_WHtR, FDR_WHtR))
FWER_WHtR


# MUAC
pval_MUAC <- NULL
for (i in 2:7){
m_MUAC <- glm(PFAS_A$MUAC ~ PFAS_A[[i]] + PFAS_A$age_enroll + PFAS_A$race + 
                PFAS_A$income + PFAS_A$menar + PFAS_A$smoke +  PFAS_A$parity + 
                PFAS_A$married, family = gaussian)
p_MUAC <- summary(m_MUAC)$coefficients[2,]
pval_MUAC <- rbind(pval_MUAC, p_MUAC)
rownames(pval_MUAC)[i-1] <- paste("X", i-1, sep="")
}

pval_MUAC_set <- pval_MUAC[,4]
BH_MUAC <- p.adjust(pval_MUAC_set, method="BH")
BY_MUAC <- p.adjust(pval_MUAC_set, method="BY")
FDR_MUAC <- p.adjust(pval_MUAC_set, method="fdr")
FWER_MUAC <- as.data.frame(cbind(pval_MUAC_set, BH_MUAC, BY_MUAC, FDR_MUAC))
FWER_MUAC


# TRNK
pval_TRNK <- NULL
for (i in 2:7){
m_TRNK <- glm(PFAS_D$LNTKNFAT ~ PFAS_D[[i]] + PFAS_D$age_enroll + PFAS_D$race + 
                PFAS_D$income + PFAS_D$menar + PFAS_D$smoke +  PFAS_D$parity + 
                PFAS_D$married, family = gaussian)
p_TRNK <- summary(m_TRNK)$coefficients[2,]
pval_TRNK <- rbind(pval_TRNK, p_TRNK)
rownames(pval_TRNK)[i-1] <- paste("X", i-1, sep="")
}

pval_TRNK_set <- pval_TRNK[,4]
BH_TRNK <- p.adjust(pval_TRNK_set, method="BH")
BY_TRNK <- p.adjust(pval_TRNK_set, method="BY")
FDR_TRNK <- p.adjust(pval_TRNK_set, method="fdr")
FWER_TRNK <- as.data.frame(cbind(pval_TRNK_set, BH_TRNK, BY_TRNK, FDR_TRNK))
FWER_TRNK


# FAT
pval_FAT <- NULL
for (i in 2:7){
m_FAT <- glm(PFAS_D$LNTOTFAT ~ PFAS_D[[i]] + PFAS_D$age_enroll + PFAS_D$race + 
                PFAS_D$income + PFAS_D$menar + PFAS_D$smoke +  PFAS_D$parity + 
                PFAS_D$married, family = gaussian)
p_FAT <- summary(m_FAT)$coefficients[2,]
pval_FAT <- rbind(pval_FAT, p_FAT)
rownames(pval_FAT)[i-1] <- paste("X", i-1, sep="")
}

pval_FAT_set <- pval_FAT[,4]
BH_FAT <- p.adjust(pval_FAT_set, method="BH")
BY_FAT <- p.adjust(pval_FAT_set, method="BY")
FDR_FAT <- p.adjust(pval_FAT_set, method="fdr")
FWER_FAT <- as.data.frame(cbind(pval_FAT_set, BH_FAT, BY_FAT, FDR_FAT))
FWER_FAT


# TRUNK FAT INDEX
pval_TFIN <- NULL
for (i in 2:7){
m_TFIN <- glm(PFAS_D$LNTFIN ~ PFAS_D[[i]] + PFAS_D$age_enroll + PFAS_D$race + 
                PFAS_D$income + PFAS_D$menar + PFAS_D$smoke +  PFAS_D$parity + 
                PFAS_D$married, family = gaussian)
p_TFIN <- summary(m_TFIN)$coefficients[2,]
pval_TFIN <- rbind(pval_TFIN, p_TFIN)
rownames(pval_TFIN)[i-1] <- paste("X", i-1, sep="")
}

pval_TFIN_set <- pval_TFIN[,4]
BH_TFIN <- p.adjust(pval_TFIN_set, method="BH")
BY_TFIN <- p.adjust(pval_TFIN_set, method="BY")
FDR_TFIN <- p.adjust(pval_TFIN_set, method="fdr")
FWER_TFIN <- as.data.frame(cbind(pval_TFIN_set, BH_TFIN, BY_TFIN, FDR_TFIN))
FWER_TFIN


# BODY FAT INDEX
pval_BFIN <- NULL
for (i in 2:7){
m_BFIN <- glm(PFAS_D$LNBFIN ~ PFAS_D[[i]] + PFAS_D$age_enroll + PFAS_D$race + 
                PFAS_D$income + PFAS_D$menar + PFAS_D$smoke +  PFAS_D$parity + 
                PFAS_D$married, family = gaussian)
p_BFIN <- summary(m_BFIN)$coefficients[2,]
pval_BFIN <- rbind(pval_BFIN, p_BFIN)
rownames(pval_BFIN)[i-1] <- paste("X", i-1, sep="")
}

pval_BFIN_set <- pval_BFIN[,4]
BH_BFIN <- p.adjust(pval_BFIN_set, method="BH")
BY_BFIN <- p.adjust(pval_BFIN_set, method="BY")
FDR_BFIN <- p.adjust(pval_BFIN_set, method="fdr")
FWER_BFIN <- as.data.frame(cbind(pval_BFIN_set, BH_BFIN, BY_BFIN, FDR_BFIN))
FWER_BFIN


# PFAT
pval_PFAT <- NULL
for (i in 2:7){
m_PFAT <- glm(PFAS_D$TotFatPct ~ PFAS_D[[i]] + PFAS_D$age_enroll + PFAS_D$race + 
                PFAS_D$income + PFAS_D$menar + PFAS_D$smoke +  PFAS_D$parity + 
                PFAS_D$married, family = gaussian)
p_PFAT <- summary(m_PFAT)$coefficients[2,]
pval_PFAT <- rbind(pval_PFAT, p_PFAT)
rownames(pval_PFAT)[i-1] <- paste("X", i-1, sep="")
}

pval_PFAT_set <- pval_PFAT[,4]
BH_PFAT <- p.adjust(pval_PFAT_set, method="BH")
BY_PFAT <- p.adjust(pval_PFAT_set, method="BY")
FDR_PFAT <- p.adjust(pval_PFAT_set, method="fdr")
FWER_PFAT <- as.data.frame(cbind(pval_PFAT_set, BH_PFAT, BY_PFAT, FDR_PFAT))
FWER_PFAT

```
