#####                                                                    #####
##### RUN MIXTURES ANALYSIS WITH QUANTILE G-COMPUTATION IN ANTHRO        #####
#####                                                                    #####

```{r}
##### LOAD PACKAGES
library('qgcomp')
library("tidyverse")
library("knitr")
library("ggplot2")

```

```{r}
##### LOAD DATASET
PFAS_A <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/P3.PFASandAdiposity/Data/PFAS_A.csv")
PFAS_D <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/P3.PFASandAdiposity/Data/PFAS_D.csv")

```

```{r}
##### TRANSFORM VARIABLES TO NUMERIC FOR BKMR COVARIATE MATRIX

# RENAME
PFAS_A$age_enroll <- PFAS_A$age_mom_enroll_d
PFAS_A$race <- PFAS_A$race2_mom_epi_epia_d
PFAS_A$edu <- PFAS_A$coll_grad
PFAS_A$income <- PFAS_A$gt70k
PFAS_A$menar <- PFAS_A$mom_firstperiod_12y
PFAS_A$smoke <- PFAS_A$smokpreg_final_d
PFAS_A$parity <- PFAS_A$parity_d
PFAS_A$married <- PFAS_A$married_cohab

# REFACTOR AND RELABEL 
PFAS_A$race <- ifelse(PFAS_A$race == "white", 0,
                     ifelse(PFAS_A$race == "black", 1,
                     ifelse(PFAS_A$race == "hispa", 2,
                     ifelse(PFAS_A$race == "asian", 3,
                     ifelse(PFAS_A$race == "other", 4, 4)))))
PFAS_A$edu <- ifelse(PFAS_A$edu == 1, 1, 0)
PFAS_A$bmi_cat <- ifelse(PFAS_A$bmi <18.5, 0,
                         ifelse(PFAS_A$bmi >=18.5 & PFAS_A$bmi < 25.0, 1, 
                         ifelse(PFAS_A$bmi >=25.0 & PFAS_A$bmi < 30.0, 2, 
                         ifelse(PFAS_A$bmi >=30.0 & PFAS_A$bmi < 35.0, 3,
                         ifelse(PFAS_A$bmi >=35.0, 4, 99)))))
PFAS_A$smoke <- ifelse(PFAS_A$smoke == "former", 0,
                         ifelse(PFAS_A$smoke == "smoke preg", 1,
                         ifelse(PFAS_A$smoke == "xnever", 2, 2)))
PFAS_A$income <- ifelse(PFAS_A$income == 1, 1, 0)
PFAS_A$parity <- ifelse(PFAS_A$parity == 0, 0,
                        ifelse(PFAS_A$parity == 1, 1,
                        ifelse(PFAS_A$parity > 1, 2, 0)))
PFAS_A$married <- ifelse(PFAS_A$married == 1, 1, 0)

# SET CATEGORICAL VARIABLES AS FACTORS
PFAS_A$edu <- as.factor(PFAS_A$edu)
PFAS_A$income <- as.factor(PFAS_A$income)
PFAS_A$bmi_cat <- as.factor(PFAS_A$bmi_cat)
PFAS_A$smoke <- as.factor(PFAS_A$smoke)
PFAS_A$parity <- as.factor(PFAS_A$parity)
PFAS_A$race <- as.factor(PFAS_A$race)
PFAS_A$married <- as.factor(PFAS_A$married)

# CENTER AND SCALE CONTINUOUS VARIABLES
# PFAS_A$age_enroll <- scale(PFAS_A$age_enroll)
# PFAS_A$menar <- scale(PFAS_A$menar)



# RENAME
PFAS_D$age_enroll <- PFAS_D$age_mom_enroll_d
PFAS_D$race <- PFAS_D$race2_mom_epi_epia_d
PFAS_D$edu <- PFAS_D$coll_grad
PFAS_D$income <- PFAS_D$gt70k
PFAS_D$menar <- PFAS_D$mom_firstperiod_12y
PFAS_D$smoke <- PFAS_D$smokpreg_final_d
PFAS_D$parity <- PFAS_D$parity_d
PFAS_D$married <- PFAS_D$married_cohab

# REFACTOR AND RELABEL 
PFAS_D$race <- ifelse(PFAS_D$race == "white", 0,
                     ifelse(PFAS_D$race == "black", 1,
                     ifelse(PFAS_D$race == "hispa", 2,
                     ifelse(PFAS_D$race == "asian", 3,
                     ifelse(PFAS_D$race == "other", 4, 4)))))
PFAS_D$edu <- ifelse(PFAS_D$edu == 1, 1, 0)
PFAS_D$bmi_cat <- ifelse(PFAS_D$bmi <18.5, 0,
                         ifelse(PFAS_D$bmi >=18.5 & PFAS_D$bmi < 25.0, 1, 
                         ifelse(PFAS_D$bmi >=25.0 & PFAS_D$bmi < 30.0, 2, 
                         ifelse(PFAS_D$bmi >=30.0 & PFAS_D$bmi < 35.0, 3,
                         ifelse(PFAS_D$bmi >=35.0, 4, 99)))))
PFAS_D$smoke <- ifelse(PFAS_D$smoke == "former", 0,
                         ifelse(PFAS_D$smoke == "smoke preg", 1,
                         ifelse(PFAS_D$smoke == "xnever", 2, 2)))
PFAS_D$income <- ifelse(PFAS_D$income == 1, 1, 0)
PFAS_D$parity <- ifelse(PFAS_D$parity == 0, 0,
                        ifelse(PFAS_D$parity == 1, 1,
                        ifelse(PFAS_D$parity > 1, 2, 0)))
PFAS_D$married <- ifelse(PFAS_D$married == 1, 1, 0)

# SET CATEGORICAL VARIABLES AS FACTORS
PFAS_D$edu <- as.factor(PFAS_D$edu)
PFAS_D$income <- as.factor(PFAS_D$income)
PFAS_D$bmi_cat <- as.factor(PFAS_D$bmi_cat)
PFAS_D$smoke <- as.factor(PFAS_D$smoke)
PFAS_D$parity <- as.factor(PFAS_D$parity)
PFAS_D$race <- as.factor(PFAS_D$race)
PFAS_D$married <- as.factor(PFAS_D$married)

# CENTER AND SCALE CONTINUOUS VARIABLES
# PFAS_D$age_enroll <- scale(PFAS_D$age_enroll)
# PFAS_D$menar <- scale(PFAS_D$menar)

```

```{r}
##### STRATIFY THE DATA BASED ON AGE
PFAS_A$mom_period_stopped_qu17 <- ifelse(PFAS_A$mom_period_stopped_qu17 == 2, 0,
                        ifelse(PFAS_A$mom_period_stopped_qu17 == 1, 1, NA))
PFAS_D$mom_period_stopped_qu17 <- ifelse(PFAS_D$mom_period_stopped_qu17 == 2, 0,
                        ifelse(PFAS_D$mom_period_stopped_qu17 == 1, 1, NA))

table(PFAS_A$mom_period_stopped_qu17)
table(PFAS_D$mom_period_stopped_qu17)

# ANTHRO
PFAS_A_MENO0 <- subset(PFAS_A, mom_period_stopped_qu17 == 0)
PFAS_A_MENO1 <- subset(PFAS_A, mom_period_stopped_qu17 == 1)

# DXA
PFAS_D_MENO0 <- subset(PFAS_D, mom_period_stopped_qu17 == 0)
PFAS_D_MENO1 <- subset(PFAS_D, mom_period_stopped_qu17 == 1)

```

```{r}
##### PREPARE VARIABLES FOR BKMR MODELS #####
##### ANTHRO DATASET (N = 545)

# SAVE THE NAMES OF THE PFAS IN THE MIXTURE
l2mix <- c("L2PFOS", "L2PFOA", "L2PFNA", "L2PFHxS", "L2MeFOSAA", "L2EtFOSAA")

# # SAVE THE NAMES OF THE COVARIATES
# cov <- c("age_enroll", "race", "menar", "income", "smoke", "parity", "married")

# SET THE OUTCOME
BMI_0 <- PFAS_A_MENO0$LNBMI
Waist_0 <- PFAS_A_MENO0$Waist
WHR_0 <- PFAS_A_MENO0$WHR
MUAC_0 <- PFAS_A_MENO0$MUAC
BMI_1 <- PFAS_A_MENO1$LNBMI
Waist_1 <- PFAS_A_MENO1$Waist
WHR_1 <- PFAS_A_MENO1$WHR
MUAC_1 <- PFAS_A_MENO1$MUAC

TRNKFAT_0 <- PFAS_D_MENO0$LNTKNFAT
TOTFAT_0 <- PFAS_D_MENO0$LNTOTFAT
TOTFATPCT_0 <- PFAS_D_MENO0$TotFatPct
TRNKFAT_1 <- PFAS_D_MENO1$LNTKNFAT
TOTFAT_1 <- PFAS_D_MENO1$LNTOTFAT
TOTFATPCT_1 <- PFAS_D_MENO1$TotFatPct

```

```{r}
##### BUILD QGC MODELS #####
### BMI
# MENO = 0
qc1_bmi0 <- qgcomp.noboot(BMI_0 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_A_MENO0, family=gaussian(), q=4)
qc1_bmi0

qc2_bmi0 <- qgcomp.boot(BMI_0 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_A_MENO0, family=gaussian(), q=4, B = 500, seed = 125)
qc2_bmi0

# MENO = 1
qc1_bmi1 <- qgcomp.noboot(BMI_1 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_A_MENO1, family=gaussian(), q=4)
qc1_bmi1

qc2_bmi1 <- qgcomp.boot(BMI_1 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_A_MENO1, family=gaussian(), q=4, B = 500, seed = 125)
qc2_bmi1


### WAIST CIRCUMFERENCE
# MENO = 0
qc1_wc0 <- qgcomp.noboot(Waist_0 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_A_MENO0, family=gaussian(), q=4)
qc1_wc0

qc2_wc0 <- qgcomp.boot(Waist_0 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_A_MENO0, family=gaussian(), q=4, B = 500, seed = 125)
qc2_wc0

# MENO = 1
qc1_wc1 <- qgcomp.noboot(Waist_1 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_A_MENO1, family=gaussian(), q=4)
qc1_wc1

qc2_wc1 <- qgcomp.boot(Waist_1 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_A_MENO1, family=gaussian(), q=4, B = 500, seed = 125)
qc2_wc1


### WAIST-TO-HIP-RATIO
# MENO = 0
qc1_whr0 <- qgcomp.noboot(WHR_0 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_A_MENO0, family=gaussian(), q=4)
qc1_whr0

qc2_whr0 <- qgcomp.boot(WHR_0 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_A_MENO0, family=gaussian(), q=4, B = 500, seed = 125)
qc2_whr0

# MENO = 1
qc1_whr1 <- qgcomp.noboot(WHR_1 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_A_MENO1, family=gaussian(), q=4)
qc1_whr1

qc2_whr1 <- qgcomp.boot(WHR_1 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_A_MENO1, family=gaussian(), q=4, B = 500, seed = 125)
qc2_whr1


### MUAC
# MENO = 0
qc1_muac0 <- qgcomp.noboot(MUAC_0 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_A_MENO0, family=gaussian(), q=4)
qc1_muac0

qc2_muac0 <- qgcomp.boot(MUAC_0 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_A_MENO0, family=gaussian(), q=4, B = 500, seed = 125)
qc2_muac0

# MENO = 1
qc1_muac1 <- qgcomp.noboot(MUAC_1 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_A_MENO1, family=gaussian(), q=4)
qc1_muac1

qc2_muac1 <- qgcomp.boot(MUAC_1 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_A_MENO1, family=gaussian(), q=4, B = 500, seed = 125)
qc2_muac1

```

```{r}
# ##### VIEW HOW EACH PFAS IS SCORED. THESE ARE QUANTIED EXPOSURES #####
# head(l2qc_bmi1$qx)
# head(l2qc_wc1$qx)
# head(l2qc_whr1$qx)
# head(l2qc_muac1$qx)

```

```{r}
##### PLOT WEIGHTS FOR EACH OUTCOME
# BMI
plot(qc1_bmi0)
plot(qc1_bmi1)

# WAIST CIRCUMFERENCE
plot(qc1_wc0)
plot(qc1_wc1)

# WAIST-TO-HIP RATIO
plot(qc1_whr0)
plot(qc1_whr1)

# MUAC
plot(qc1_muac0)
plot(qc1_muac1)

```

```{r}
##### PLOT...
# BMI
plot(qc2_bmi0) 
plot(qc2_bmi0, pointwiseref = 3, xlab = "PFAS quantile", ylab = "BMI (kg/m^2)")
pointwisebound.boot(qc2_bmi0, pointwiseref=3)

plot(qc2_bmi0) 
plot(qc2_bmi0, pointwiseref = 3, xlab = "PFAS quantile", ylab = "BMI (kg/m^2)")
pointwisebound.boot(qc2_bmi0, pointwiseref=3)


# WAIST CIRCUMFERENCE
plot(qc2_wc0) 
plot(qc2_wc0, pointwiseref = 3)
pointwisebound.boot(qc2_wc0, pointwiseref=3)

plot(qc2_wc1) 
plot(qc2_wc1, pointwiseref = 3)
pointwisebound.boot(qc2_wc1, pointwiseref=3)


# WAIST-TO-HIP RATIO
plot(qc2_whr0) 
plot(qc2_whr0, pointwiseref = 3)
pointwisebound.boot(qc2_whr0, pointwiseref=3)

plot(qc2_whr1) 
plot(qc2_whr1, pointwiseref = 3)
pointwisebound.boot(qc2_whr1, pointwiseref=3)


# MUAC
plot(qc2_muac0) 
plot(qc2_muac0, pointwiseref = 3)
pointwisebound.boot(qc2_muac1, pointwiseref=3)

plot(qc2_muac1) 
plot(qc2_muac1, pointwiseref = 3)
pointwisebound.boot(qc2_muac1, pointwiseref=3)

```


```{r}
##### BUILD QGC MODELS #####
### TRUNK FAT MASS
# MENO = 0
qc1_trnkfat0 <- qgcomp.noboot(TRNKFAT_0 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_D_MENO0, family=gaussian(), q=4)
qc1_trnkfat0

qc2_trnkfat0 <- qgcomp.boot(TRNKFAT_0 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_D_MENO0, family=gaussian(), q=4, B = 500, seed = 125)
qc2_trnkfat0

# MENO = 1
qc1_trnkfat1 <- qgcomp.noboot(TRNKFAT_1 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_D_MENO1, family=gaussian(), q=4)
qc1_trnkfat1

qc2_trnkfat1 <- qgcomp.boot(TRNKFAT_1 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_D_MENO1, family=gaussian(), q=4, B = 500, seed = 125)
qc2_trnkfat1


### TOTAL BODY FAT MASS
# MENO = 0
qc1_totfat0 <- qgcomp.noboot(TOTFAT_0 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_D_MENO0, family=gaussian(), q=4)
qc1_totfat0

qc2_totfat0 <- qgcomp.boot(TOTFAT_0 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_D_MENO0, family=gaussian(), q=4, B = 500, seed = 125)
qc2_totfat0

# MENO = 1
qc1_totfat1 <- qgcomp.noboot(TOTFAT_1 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_D_MENO1, family=gaussian(), q=4)
qc1_totfat1

qc2_totfat1 <- qgcomp.boot(TOTFAT_1 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_D_MENO1, family=gaussian(), q=4, B = 500, seed = 125)
qc2_totfat1


### TOTAL BODY FAT PERCENT
# MENO = 0
qc1_totfatpct0 <- qgcomp.noboot(TOTFATPCT_0 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_D_MENO0, family=gaussian(), q=4)
qc1_totfatpct0

qc2_totfatpct0 <- qgcomp.boot(TOTFATPCT_0 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_D_MENO0, family=gaussian(), q=4, B = 500, seed = 125)
qc2_totfatpct0

# MENO = 1
qc1_totfatpct1 <- qgcomp.noboot(TOTFATPCT_1 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_D_MENO1, family=gaussian(), q=4)
qc1_totfatpct1

qc2_totfatpct1 <- qgcomp.boot(TOTFATPCT_1 ~ age_enroll + race + menar + income + smoke + parity + married +
                          L2PFOS + L2PFOA + L2PFNA + L2PFHxS + L2MeFOSAA + L2EtFOSAA,
                        expnms = l2mix, data = PFAS_D_MENO1, family=gaussian(), q=4, B = 500, seed = 125)
qc2_totfatpct1

```

```{r}
# ##### VIEW HOW EACH PFAS IS SCORED. THESE ARE QUANTIED EXPOSURES #####
# head(l2qc_trnkfat1$qx)
# head(l2qc_totfat1$qx)
# head(l2qc_totfatpct1$qx)

```

```{r}
##### PLOT WEIGHTS FOR EACH OUTCOME
# TRUNK FAT MASS
plot(qc1_trnkfat0)
plot(qc1_trnkfat1)

# TOTAL BODY FAT MASS
plot(qc1_totfat0)
plot(qc1_totfat1)

# TOTAL BODY FAT PERCENT
plot(qc1_totfatpct0)
plot(qc1_totfatpct1)

```

```{r}

##### PLOT...
# TRUNK FAT MASS
plot(qc2_trnkfat0)
plot(qc2_trnkfat0, pointwiseref = 3)
pointwisebound.boot(qc2_trnkfat0, pointwiseref=3)

plot(qc2_trnkfat1)
plot(qc2_trnkfat1, pointwiseref = 3)
pointwisebound.boot(qc2_trnkfat1, pointwiseref=3)

# TOTAL BODY FAT MASS
plot(qc2_totfat0)
plot(qc2_totfat0, pointwiseref = 3)
pointwisebound.boot(qc2_totfat0, pointwiseref=3)

plot(qc2_totfat1)
plot(qc2_totfat1, pointwiseref = 3)
pointwisebound.boot(qc2_totfat1, pointwiseref=3)

# TOTAL BODY FAT PERCENT
plot(qc2_totfatpct0)
plot(qc2_totfatpct0, pointwiseref = 3)
pointwisebound.boot(qc2_totfatpct0, pointwiseref=3)

plot(qc2_totfatpct1)
plot(qc2_totfatpct1, pointwiseref = 3)
pointwisebound.boot(qc2_totfatpct1, pointwiseref=3)

```
