#####                                                  #####
##### RUN MIXTURES ANALYSIS WITH BKMR IN ANTHRO        #####
#####                                                  #####

```{r message=FALSE, warning=FALSE}
##### LOAD PACKAGES
library("bkmr")
library("ggplot2")
library("beepr")
library("tidyverse")

```

```{r message=FALSE, warning=FALSE}
##### LOAD DATASET
PFAS_D <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/P3.PFASandAdiposity/Data/PFAS_D.csv")

##### LOAD WORKSPACE
load("C:/Users/jarva/Desktop/James-Todd Lab/P3.PFASandAdiposity/Data/P3_BKMR_D_STRAT.Rdata")

```

```{r}
##### TRANSFORM VARIABLES TO NUMERIC FOR BKMR COVARIATE MATRIX

# RENAME
PFAS_D$age <- PFAS_D$age_mom_enroll_d
PFAS_D$menar <- PFAS_D$mom_firstperiod_12y
PFAS_D$bmi <- PFAS_D$bmi_mom_prepreg_d
PFAS_D$race <- PFAS_D$race2_mom_epi_epia_d
PFAS_D$income <- PFAS_D$gt70k
PFAS_D$parity <- PFAS_D$parity_d
PFAS_D$smoke <- PFAS_D$smokpreg_final_d
PFAS_D$married <- PFAS_D$married_cohab
PFAS_D$edu <- PFAS_D$coll_grad
PFAS_D$fish <- PFAS_D$fish_d_f1
PFAS_D$darkmeat <- PFAS_D$dark_meat_f1

# REFACTOR AND RELABEL 
PFAS_D$bmi_cat <- ifelse(PFAS_D$bmi <18.5, 0,
                         ifelse(PFAS_D$bmi >=18.5 & PFAS_D$bmi < 25.0, 1, 
                                ifelse(PFAS_D$bmi >=25.0 & PFAS_D$bmi < 30.0, 2, 
                                       ifelse(PFAS_D$bmi >=30.0 & PFAS_D$bmi < 35.0, 3,
                                              ifelse(PFAS_D$bmi >=35.0, 4, 99)))))
PFAS_D$race <- ifelse(PFAS_D$race == "white", 0,
                      ifelse(PFAS_D$race == "black", 1,
                             ifelse(PFAS_D$race == "hispa", 2,
                                    ifelse(PFAS_D$race == "asian", 3,
                                           ifelse(PFAS_D$race == "other", 4, 4)))))
PFAS_D$income <- ifelse(PFAS_D$income == 1, 1, 0)
PFAS_D$parity <- ifelse(PFAS_D$parity == 0, 0,
                        ifelse(PFAS_D$parity == 1, 1,
                               ifelse(PFAS_D$parity > 1, 2, 0)))
PFAS_D$smoke <- ifelse(PFAS_D$smoke == "former", 0,
                       ifelse(PFAS_D$smoke == "smoke preg", 1,
                              ifelse(PFAS_D$smoke == "xnever", 2, 2)))
PFAS_D$married <- ifelse(PFAS_D$married == 1, 1, 0)
PFAS_D$edu <- ifelse(PFAS_D$edu == 1, 1, 0)

# SET CATEGORICAL VARIABLES AS FACTORS
PFAS_D$bmi_cat <- as.factor(PFAS_D$bmi_cat)
PFAS_D$race <- as.factor(PFAS_D$race)
PFAS_D$income <- as.factor(PFAS_D$income)
PFAS_D$parity <- as.factor(PFAS_D$parity)
PFAS_D$smoke <- as.factor(PFAS_D$smoke)
PFAS_D$married <- as.factor(PFAS_D$married)
PFAS_D$edu <- as.factor(PFAS_D$edu)

# CENTER AND SCALE CONTINUOUS VARIABLES
PFAS_D$height_s <- scale(PFAS_D$height)
PFAS_D$age_s <- scale(PFAS_D$age)
PFAS_D$menar_s <- scale(PFAS_D$menar)
PFAS_D$fish_s <- scale(PFAS_D$fish)
PFAS_D$darkmeat_s <- scale(PFAS_D$darkmeat)

```

```{r}
##### STRATIFY ANTHRO DATASET BY PRE-PREGNANCY BMI
table(PFAS_D$bmi_cat)
PFAS_D_B0 <- subset(PFAS_D, bmi_cat == 0 | bmi_cat == 1)
PFAS_D_B1 <- subset(PFAS_D, bmi_cat == 2 | bmi_cat == 3 | bmi_cat == 4)


##### STRATIFY ANTHRO DATASET BY MENOPAUSAL STATUS
table(PFAS_D$meno_cat)
PFAS_D_M0 <- subset(PFAS_D, meno_cat == "Pre-menopause")
PFAS_D_M1 <- subset(PFAS_D, meno_cat == "Post-menopause")

```

```{r}
##### PREPARE VARIABLES FOR BKMR MODELS #####
##### ANTHRO DATASET (N = 549)

# CREATE MIXTURE OF PFAS
mixture_d_b0 <- as.matrix(cbind(PFAS_D_B0$PFOS, PFAS_D_B0$PFOA, PFAS_D_B0$PFNA, PFAS_D_B0$PFHxS, 
                             PFAS_D_B0$MeFOSAA, PFAS_D_B0$EtFOSAA))
mixture_d_b1 <- as.matrix(cbind(PFAS_D_B1$PFOS, PFAS_D_B1$PFOA, PFAS_D_B1$PFNA, PFAS_D_B1$PFHxS, 
                             PFAS_D_B1$MeFOSAA, PFAS_D_B1$EtFOSAA))
mixture_d_m0 <- as.matrix(cbind(PFAS_D_M0$PFOS, PFAS_D_M0$PFOA, PFAS_D_M0$PFNA, PFAS_D_M0$PFHxS, 
                             PFAS_D_M0$MeFOSAA, PFAS_D_M0$EtFOSAA))
mixture_d_m1 <- as.matrix(cbind(PFAS_D_M1$PFOS, PFAS_D_M1$PFOA, PFAS_D_M1$PFNA, PFAS_D_M1$PFHxS, 
                             PFAS_D_M1$MeFOSAA, PFAS_D_M1$EtFOSAA))

# RENAME VARIABLES IN MIXTURE
colnames(mixture_d_b0) <- c("PFOS", "PFOA", "PFNA", "PFHxS", "MeFOSAA", "EtFOSAA")
colnames(mixture_d_b1) <- c("PFOS", "PFOA", "PFNA", "PFHxS", "MeFOSAA", "EtFOSAA")
colnames(mixture_d_m0) <- c("PFOS", "PFOA", "PFNA", "PFHxS", "MeFOSAA", "EtFOSAA")
colnames(mixture_d_m1) <- c("PFOS", "PFOA", "PFNA", "PFHxS", "MeFOSAA", "EtFOSAA")

# LOG2-TRANSFORM MIXTURE
l2mixture_d_b0 <- apply(mixture_d_b0, 2, log2)
l2mixture_d_b1 <- apply(mixture_d_b1, 2, log2)
l2mixture_d_m0 <- apply(mixture_d_m0, 2, log2)
l2mixture_d_m1 <- apply(mixture_d_m1, 2, log2)

# SCALE MIXTURE VARIABLES TO THE MEAN
l2mixture_d_b0_z <- scale(l2mixture_d_b0)
l2mixture_d_b1_z <- scale(l2mixture_d_b1)
l2mixture_d_m0_z <- scale(l2mixture_d_m0)
l2mixture_d_m1_z <- scale(l2mixture_d_m1)

# SET THE OUTCOME
TFM_B0 <- PFAS_D_B0$TrnkFat
TBFM_B0 <- PFAS_D_B0$TotFat
TFM_B1 <- PFAS_D_B1$TrnkFat
TBFM_B1 <- PFAS_D_B1$TotFat
TFM_M0 <- PFAS_D_M0$TrnkFat
TBFM_M0 <- PFAS_D_M0$TotFat
TFM_M1 <- PFAS_D_M1$TrnkFat
TBFM_M1 <- PFAS_D_M1$TotFat

# CREAT THE COVARIATE MATRIX
cov_d_b0 <- as.matrix(cbind(PFAS_D_B0$age_s, PFAS_D_B0$race, PFAS_D_B0$bmi_cat, PFAS_D_B0$smoke, 
                         PFAS_D_B0$parity, PFAS_D_B0$married, PFAS_D_B0$fish_s, PFAS_D_B0$height_s))
cov_d_b1 <- as.matrix(cbind(PFAS_D_B1$age_s, PFAS_D_B1$race, PFAS_D_B1$bmi_cat, PFAS_D_B1$smoke, 
                         PFAS_D_B1$parity, PFAS_D_B1$married, PFAS_D_B1$fish_s, PFAS_D_B1$height_s))
cov_d_m0 <- as.matrix(cbind(PFAS_D_M0$age_s, PFAS_D_M0$race, PFAS_D_M0$bmi_cat, PFAS_D_M0$smoke, 
                         PFAS_D_M0$parity, PFAS_D_M0$married, PFAS_D_M0$fish_s, PFAS_D_M0$height_s))
cov_d_m1 <- as.matrix(cbind(PFAS_D_M1$age_s, PFAS_D_M1$race, PFAS_D_M1$bmi_cat, PFAS_D_M1$smoke, 
                         PFAS_D_M1$parity, PFAS_D_M1$married, PFAS_D_M1$fish_s, PFAS_D_M1$height_s))

# SET THE SEED
set.seed(1234)

# CREATE KNOTS
knots_d_b0 <- fields::cover.design(l2mixture_d_b0_z, nd = 30)$design
knots_d_b1 <- fields::cover.design(l2mixture_d_b1_z, nd = 20)$design
knots_d_m0 <- fields::cover.design(l2mixture_d_m0_z, nd = 30)$design
knots_d_m1 <- fields::cover.design(l2mixture_d_m1_z, nd = 20)$design

```

```{r}
# ##### BUILD BKMR MODELS 
# # TRUNK FAT MASS
# m_tfm_b0 <- kmbayes(y = TFM_B0, Z = l2mixture_d_b0_z, X = cov_d_b0, iter = 20000, family = "gaussian",
#                       verbose = FALSE, varsel = TRUE, knots = knots_d_b0)
# beep(sound=5, expr=NULL)
# 
# m_tfm_b1 <- kmbayes(y = TFM_B1, Z = l2mixture_d_b1_z, X = cov_d_b1, iter = 20000, family = "gaussian",
#                       verbose = FALSE, varsel = TRUE, knots = knots_d_b1)
# beep(sound=5, expr=NULL)
# 
# m_tfm_m0 <- kmbayes(y = TFM_M0, Z = l2mixture_d_m0_z, X = cov_d_m0, iter = 20000, family = "gaussian",
#                       verbose = FALSE, varsel = TRUE, knots = knots_d_m0)
# beep(sound=5, expr=NULL)
# 
# m_tfm_m1 <- kmbayes(y = TFM_M1, Z = l2mixture_d_m1_z, X = cov_d_m1, iter = 20000, family = "gaussian",
#                       verbose = FALSE, varsel = TRUE, knots = knots_d_m1)
# beep(sound=5, expr=NULL)
# 
# # TOTAL BODY FAT MASS
# m_tbfm_b0 <- kmbayes(y = TBFM_B0, Z = l2mixture_d_b0_z, X = cov_d_b0, iter = 20000, family = "gaussian",
#                       verbose = FALSE, varsel = TRUE, knots = knots_d_b0)
# beep(sound=5, expr=NULL)
# 
# m_tbfm_b1 <- kmbayes(y = TBFM_B1, Z = l2mixture_d_b1_z, X = cov_d_b1, iter = 20000, family = "gaussian",
#                       verbose = FALSE, varsel = TRUE, knots = knots_d_b1)
# beep(sound=5, expr=NULL)
# 
# m_tbfm_m0 <- kmbayes(y = TBFM_M0, Z = l2mixture_d_m0_z, X = cov_d_m0, iter = 20000, family = "gaussian",
#                       verbose = FALSE, varsel = TRUE, knots = knots_d_m0)
# beep(sound=5, expr=NULL)
# 
# m_tbfm_m1 <- kmbayes(y = TBFM_M1, Z = l2mixture_d_m1_z, X = cov_d_m1, iter = 20000, family = "gaussian",
#                       verbose = FALSE, varsel = TRUE, knots = knots_d_m1)
# beep(sound=5, expr=NULL)

```

```{r}
# # ##### SAVE WORKSPACE FOR SBP BKMR FUNCTIONS
# save(m_tfm_b0, m_tfm_b1, m_tfm_m0, m_tfm_m1, m_tbfm_b0, m_tbfm_b1, m_tbfm_m0, m_tbfm_m1,
#     file="C:/Users/jarva/Desktop/James-Todd Lab/P3.PFASandAdiposity/Data/P3_BKMR_D_STRAT.Rdata")

```

```{r}
##### VALUES TO KEEP AFTER BURIN/THIN
sel <- seq(0,20000,by = 50)

##### ACCESS CONVERGENCE WITH TRACEPLOTS
# TracePlot(fit = l2m_wt, par = "beta", sel = sel)
# TracePlot(fit = l2m_waist, par = "beta", sel = sel)

##### VALUES TO KEEP AFTER BURNING/THIN (ACCORDING TO THE TRACEPLOT FUNCTION ABOVE)
sel_final <- seq(1200, 20000, by = 1)

```

```{r}
##### ESIMATE POSTERIOR INCLUSION PROBABILITIES
# TOTAL BODY FAT MASS
#summary(l2m_wt)
ExtractPIPs(m_tfm_b0, sel = sel_final)
ExtractPIPs(m_tfm_b1, sel = sel_final)
ExtractPIPs(m_tfm_m0, sel = sel_final)
ExtractPIPs(m_tfm_m1, sel = sel_final)

# TOTAL BODY FAT MASS
#summary(l2m_wt)
ExtractPIPs(m_tbfm_b0, sel = sel_final)
ExtractPIPs(m_tbfm_b1, sel = sel_final)
ExtractPIPs(m_tbfm_m0, sel = sel_final)
ExtractPIPs(m_tbfm_m1, sel = sel_final)

```

```{r}
##### PREDICT UNIVARIATE EXPOSURE-RESPONSE FUNCTION
# TRUNK FAT MASS
univar_tfm_b0 <- PredictorResponseUnivar(fit = m_tfm_b0, sel = sel_final, method = "approx")
univar_tfm_b1 <- PredictorResponseUnivar(fit = m_tfm_b1, sel = sel_final, method = "approx")
univar_tfm_m0 <- PredictorResponseUnivar(fit = m_tfm_m0, sel = sel_final, method = "approx")
univar_tfm_m1 <- PredictorResponseUnivar(fit = m_tfm_m1, sel = sel_final, method = "approx")

# TOTAL BODY FAT MASS
univar_tbfm_b0 <- PredictorResponseUnivar(fit = m_tbfm_b0, sel = sel_final, method = "approx")
univar_tbfm_b1 <- PredictorResponseUnivar(fit = m_tbfm_b1, sel = sel_final, method = "approx")
univar_tbfm_m0 <- PredictorResponseUnivar(fit = m_tbfm_m0, sel = sel_final, method = "approx")
univar_tbfm_m1 <- PredictorResponseUnivar(fit = m_tbfm_m1, sel = sel_final, method = "approx")



##### PLOT UNIVARIATE EXPOSURE-RESPONSE FUNCTION
# TRUNK FAT MASS
uni_tfm_b0 <- ggplot(univar_tfm_b0, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity", colour='black') + xlab("Plasma PFAS, log2(ng/mL)") + ylab("Trunk fat mass (kg)") +
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 25))  

uni1_tfm_b0 <- ggplot(univar_tfm_b0[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOS, log2(ng/mL)") + ylab("Trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni2_tfm_b0 <- ggplot(univar_tfm_b0[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOA, log2(ng/mL)") + ylab("Trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni3_tfm_b0 <- ggplot(univar_tfm_b0[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFNA, log2(ng/mL)") + ylab("Trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni4_tfm_b0 <- ggplot(univar_tfm_b0[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFHxS, log2(ng/mL)") + ylab("Trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni5_tfm_b0 <- ggplot(univar_tfm_b0[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma MeFOSAA, log2(ng/mL)") + ylab("Trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni6_tfm_b0 <- ggplot(univar_tfm_b0[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma EtFOSAA, log2(ng/mL)") + ylab("Trunk fat mass (kg)") +
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni_tfm_b0
uni1_tfm_b0
uni2_tfm_b0
uni3_tfm_b0
uni4_tfm_b0
uni5_tfm_b0
uni6_tfm_b0


uni_tfm_b1 <- ggplot(univar_tfm_b1, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity", colour='black') + xlab("Plasma PFAS, log2(ng/mL)") + ylab("Trunk fat mass (kg)") +
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 25))  

uni1_tfm_b1 <- ggplot(univar_tfm_b1[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOS, log2(ng/mL)") + ylab("Trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni2_tfm_b1 <- ggplot(univar_tfm_b1[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOA, log2(ng/mL)") + ylab("Trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni3_tfm_b1 <- ggplot(univar_tfm_b1[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFNA, log2(ng/mL)") + ylab("Trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni4_tfm_b1 <- ggplot(univar_tfm_b1[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFHxS, log2(ng/mL)") + ylab("Trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni5_tfm_b1 <- ggplot(univar_tfm_b1[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma MeFOSAA, log2(ng/mL)") + ylab("Trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni6_tfm_b1 <- ggplot(univar_tfm_b1[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma EtFOSAA, log2(ng/mL)") + ylab("Trunk fat mass (kg)") +
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni_tfm_b1
uni1_tfm_b1
uni2_tfm_b1
uni3_tfm_b1
uni4_tfm_b1
uni5_tfm_b1
uni6_tfm_b1



uni_tfm_m0 <- ggplot(univar_tfm_m0, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity", colour='black') + xlab("Plasma PFAS, log2(ng/mL)") + ylab("Trunk fat mass (kg)") +
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 25))  

uni1_tfm_m0 <- ggplot(univar_tfm_m0[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOS, log2(ng/mL)") + ylab("Trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni2_tfm_m0 <- ggplot(univar_tfm_m0[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOA, log2(ng/mL)") + ylab("Trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni3_tfm_m0 <- ggplot(univar_tfm_m0[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFNA, log2(ng/mL)") + ylab("Trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni4_tfm_m0 <- ggplot(univar_tfm_m0[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFHxS, log2(ng/mL)") + ylab("Trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni5_tfm_m0 <- ggplot(univar_tfm_m0[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma MeFOSAA, log2(ng/mL)") + ylab("Trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni6_tfm_m0 <- ggplot(univar_tfm_m0[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma EtFOSAA, log2(ng/mL)") + ylab("Trunk fat mass (kg)") +
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni_tfm_m0
uni1_tfm_m0
uni2_tfm_m0
uni3_tfm_m0
uni4_tfm_m0
uni5_tfm_m0
uni6_tfm_m0



uni_tfm_m1 <- ggplot(univar_tfm_m1, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity", colour='black') + xlab("Plasma PFAS, log2(ng/mL)") + ylab("Trunk fat mass (kg)") +
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 25))  

uni1_tfm_m1 <- ggplot(univar_tfm_m1[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOS, log2(ng/mL)") + ylab("Trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni2_tfm_m1 <- ggplot(univar_tfm_m1[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOA, log2(ng/mL)") + ylab("Trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni3_tfm_m1 <- ggplot(univar_tfm_m1[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFNA, log2(ng/mL)") + ylab("Trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni4_tfm_m1 <- ggplot(univar_tfm_m1[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFHxS, log2(ng/mL)") + ylab("Trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni5_tfm_m1 <- ggplot(univar_tfm_m1[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma MeFOSAA, log2(ng/mL)") + ylab("Trunk fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni6_tfm_m1 <- ggplot(univar_tfm_m1[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma EtFOSAA, log2(ng/mL)") + ylab("Trunk fat mass (kg)") +
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni_tfm_m1
uni1_tfm_m1
uni2_tfm_m1
uni3_tfm_m1
uni4_tfm_m1
uni5_tfm_m1
uni6_tfm_m1



# TOTAL BODY FAT MASS
uni_tbfm_b0 <- ggplot(univar_tbfm_b0, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity", colour='black') + xlab("Plasma PFAS, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 25))  

uni1_tbfm_b0 <- ggplot(univar_tbfm_b0[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOS, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni2_tbfm_b0 <- ggplot(univar_tbfm_b0[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOA, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni3_tbfm_b0 <- ggplot(univar_tbfm_b0[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFNA, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni4_tbfm_b0 <- ggplot(univar_tbfm_b0[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFHxS, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni5_tbfm_b0 <- ggplot(univar_tbfm_b0[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma MeFOSAA, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni6_tbfm_b0 <- ggplot(univar_tbfm_b0[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma EtFOSAA, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni_tbfm_b0
uni1_tbfm_b0
uni2_tbfm_b0
uni3_tbfm_b0
uni4_tbfm_b0
uni5_tbfm_b0
uni6_tbfm_b0


uni_tbfm_b1 <- ggplot(univar_tbfm_b1, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity", colour='black') + xlab("Plasma PFAS, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 25))  

uni1_tbfm_b1 <- ggplot(univar_tbfm_b1[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOS, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni2_tbfm_b1 <- ggplot(univar_tbfm_b1[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOA, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni3_tbfm_b1 <- ggplot(univar_tbfm_b1[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFNA, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni4_tbfm_b1 <- ggplot(univar_tbfm_b1[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFHxS, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni5_tbfm_b1 <- ggplot(univar_tbfm_b1[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma MeFOSAA, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni6_tbfm_b1 <- ggplot(univar_tbfm_b1[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma EtFOSAA, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni_tbfm_b1
uni1_tbfm_b1
uni2_tbfm_b1
uni3_tbfm_b1
uni4_tbfm_b1
uni5_tbfm_b1
uni6_tbfm_b1



uni_tbfm_m0 <- ggplot(univar_tbfm_m0, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity", colour='black') + xlab("Plasma PFAS, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 25))  

uni1_tbfm_m0 <- ggplot(univar_tbfm_m0[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOS, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni2_tbfm_m0 <- ggplot(univar_tbfm_m0[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOA, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni3_tbfm_m0 <- ggplot(univar_tbfm_m0[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFNA, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni4_tbfm_m0 <- ggplot(univar_tbfm_m0[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFHxS, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni5_tbfm_m0 <- ggplot(univar_tbfm_m0[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma MeFOSAA, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni6_tbfm_m0 <- ggplot(univar_tbfm_m0[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma EtFOSAA, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni_tbfm_m0
uni1_tbfm_m0
uni2_tbfm_m0
uni3_tbfm_m0
uni4_tbfm_m0
uni5_tbfm_m0
uni6_tbfm_m0



uni_tbfm_m1 <- ggplot(univar_tbfm_m1, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity", colour='black') + xlab("Plasma PFAS, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 25))  

uni1_tbfm_m1 <- ggplot(univar_tbfm_m1[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOS, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni2_tbfm_m1 <- ggplot(univar_tbfm_m1[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOA, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni3_tbfm_m1 <- ggplot(univar_tbfm_m1[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFNA, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni4_tbfm_m1 <- ggplot(univar_tbfm_m1[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFHxS, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni5_tbfm_m1 <- ggplot(univar_tbfm_m1[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma MeFOSAA, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni6_tbfm_m1 <- ggplot(univar_tbfm_m1[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma EtFOSAA, log2(ng/mL)") + ylab("Total body fat mass (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni_tbfm_m1
uni1_tbfm_m1
uni2_tbfm_m1
uni3_tbfm_m1
uni4_tbfm_m1
uni5_tbfm_m1
uni6_tbfm_m1

```

```{r}
##### PREDICT BIVARIATE EXPOSURE-RESPONSE CURVE TO ASSESS POTENTIAL INTERACTIONS
##### SUBESQUENTLY, PREDICT INTERACTIONS AMONG PFAS
# TRUNK FAT MASS
bivar_wt <- PredictorResponseBivar(fit = l2m_wt, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_wt <- PredictorResponseBivarLevels(pred.resp.df = bivar_wt, Z = l2mixture_d_z,
                                            both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_tfm_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_wt, Z = l2mixture_d_z,
                                                 both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))

# TOTAL BODY FAT MASS
bivar_waist <- PredictorResponseBivar(fit = l2m_waist, min.plot.dist = 1, sel = sel_final, method = "approx")
interact_waist <- PredictorResponseBivarLevels(pred.resp.df = bivar_waist, Z = l2mixture_d_z,
                                               both_pairs = T, qs = c(0.25, 0.50, 0.75))
interact_waist_1090 <- PredictorResponseBivarLevels(pred.resp.df = bivar_waist, Z = l2mixture_d_z,
                                                    both_pairs = TRUE, qs = c(0.10, 0.5, 0.90))



##### PLOT BIVARIATE INTERACTIONS
##### NON-PARALLEL LINES WOULD INDICATE POTENTIAL INTERACTIONS
# TRUNK FAT MASS
p_interact_wt <- ggplot(interact_wt, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) + theme(
    axis.title.x=element_text(angle=0, color='black', size = 20),
    axis.title.y=element_text(angle=90, color='black', size = 20)) +
  xlab ("PFAS 1") +
  ylab ("Trunk fat mass (kg)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_wt

# TOTAL BODY FAT MASS
p_interact_waist <- ggplot(interact_waist, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) + theme(
    axis.title.x=element_text(angle=0, color='black', size = 20),
    axis.title.y=element_text(angle=90, color='black', size = 20)) +
  xlab ("PFAS 1") +
  ylab ("Total body fat mass (kg)") +
  ggtitle("h(PFAS 1 | Quantiles of PFAS 2)") 
p_interact_waist 

```

```{r}
##### DETERMINE RISK ASSOCIATED WITH THE OVERALL MIXTURE
# TRUNK FAT MASS
overall_tfm_b0 <- OverallRiskSummaries(fit = m_tfm_b0, q.fixed = 0.50, sel = sel_final,
                                   method = "approx", qs = seq(0.25, 0.75, by = 0.05))
overall_tfm_b1 <- OverallRiskSummaries(fit = m_tfm_b1, q.fixed = 0.50, sel = sel_final,
                                   method = "approx", qs = seq(0.25, 0.75, by = 0.05))
overall_tfm_m0 <- OverallRiskSummaries(fit = m_tfm_m0, q.fixed = 0.50, sel = sel_final,
                                   method = "approx", qs = seq(0.25, 0.75, by = 0.05))
overall_tfm_m1 <- OverallRiskSummaries(fit = m_tfm_m1, q.fixed = 0.50, sel = sel_final,
                                   method = "approx", qs = seq(0.25, 0.75, by = 0.05))

# TOTAL BODY FAT MASS
overall_tbfm_b0 <- OverallRiskSummaries(fit = m_tbfm_b0, q.fixed = 0.50, sel = sel_final,
                                      method = "approx", qs = seq(0.25, 0.75, by = 0.05))
overall_tbfm_b1 <- OverallRiskSummaries(fit = m_tbfm_b1, q.fixed = 0.50, sel = sel_final,
                                      method = "approx", qs = seq(0.25, 0.75, by = 0.05))
overall_tbfm_m0 <- OverallRiskSummaries(fit = m_tbfm_m0, q.fixed = 0.50, sel = sel_final,
                                      method = "approx", qs = seq(0.25, 0.75, by = 0.05))
overall_tbfm_m1 <- OverallRiskSummaries(fit = m_tbfm_m1, q.fixed = 0.50, sel = sel_final,
                                      method = "approx", qs = seq(0.25, 0.75, by = 0.05))



##### PLOT RISK ASSOCIATED WITH THE OVERALL MIXTURE
# TRUNK FAT MASS
p_overall_tfm_b0 <- ggplot(overall_tfm_b0, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange() +
  scale_y_continuous(name = "Trunk fat mass (kg)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 25),
    axis.text.y = element_text(size = 24),
    axis.title.x = element_text(angle = 0, color = 'black', size = 25),
    axis.title.y = element_text(angle = 90, color = 'black', size = 24))
p_overall_tfm_b0

p_overall_tfm_b1 <- ggplot(overall_tfm_b1, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange() +
  scale_y_continuous(name = "Trunk fat mass (kg)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 25),
    axis.text.y = element_text(size = 24),
    axis.title.x = element_text(angle = 0, color = 'black', size = 25),
    axis.title.y = element_text(angle = 90, color = 'black', size = 24))
p_overall_tfm_b1

p_overall_tfm_m0 <- ggplot(overall_tfm_m0, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange() +
  scale_y_continuous(name = "Trunk fat mass (kg)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 25),
    axis.text.y = element_text(size = 24),
    axis.title.x = element_text(angle = 0, color = 'black', size = 25),
    axis.title.y = element_text(angle = 90, color = 'black', size = 24))
p_overall_tfm_m0

p_overall_tfm_m1 <- ggplot(overall_tfm_m1, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange() +
  scale_y_continuous(name = "Trunk fat mass (kg)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 25),
    axis.text.y = element_text(size = 24),
    axis.title.x = element_text(angle = 0, color = 'black', size = 25),
    axis.title.y = element_text(angle = 90, color = 'black', size = 24))
p_overall_tfm_m1


# TOTAL BODY FAT MASS
p_overall_tbfm_b0 <- ggplot(overall_tbfm_b0, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange() +
  scale_y_continuous(name = "Total body fat mass (kg)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 25),
    axis.text.y = element_text(size = 24),
    axis.title.x = element_text(angle = 0, color = 'black', size = 25),
    axis.title.y = element_text(angle = 90, color = 'black', size = 24))
p_overall_tbfm_b0

p_overall_tbfm_b1 <- ggplot(overall_tbfm_b1, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange() +
  scale_y_continuous(name = "Total body fat mass (kg)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 25),
    axis.text.y = element_text(size = 24),
    axis.title.x = element_text(angle = 0, color = 'black', size = 25),
    axis.title.y = element_text(angle = 90, color = 'black', size = 24))
p_overall_tbfm_b1

p_overall_tbfm_m0 <- ggplot(overall_tbfm_m0, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange() +
  scale_y_continuous(name = "Total body fat mass (kg)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 25),
    axis.text.y = element_text(size = 24),
    axis.title.x = element_text(angle = 0, color = 'black', size = 25),
    axis.title.y = element_text(angle = 90, color = 'black', size = 24))
p_overall_tbfm_m0

p_overall_tbfm_m1 <- ggplot(overall_tbfm_m1, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange() +
  scale_y_continuous(name = "Total body fat mass (kg)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 25),
    axis.text.y = element_text(size = 24),
    axis.title.x = element_text(angle = 0, color = 'black', size = 25),
    axis.title.y = element_text(angle = 90, color = 'black', size = 24))
p_overall_tbfm_m1

```

```{r}
##### ESTIMATE SINGLE PFAS EFFECT
# TRUNK FAT MASS
singvar_wt <- SingVarRiskSummaries(fit = l2m_wt, qs.diff = c(0.25, 0.75),
                                   q.fixed = c(0.25, 0.50, 0.75), sel = sel_final, method = "approx")
singvar_wt2 <- SingVarRiskSummaries(fit = l2m_wt, qs.diff = c(0.25, 0.75),
                                    q.fixed = c(0.50), sel = sel_final, method = "approx")


# TOTAL BODY FAT MASS
singvar_waist <- SingVarRiskSummaries(fit = l2m_waist, qs.diff = c(0.25, 0.75),
                                      q.fixed = c(0.25, 0.50, 0.75), sel = sel_final, method = "approx")
singvar_waist2 <- SingVarRiskSummaries(fit = l2m_waist, qs.diff = c(0.25, 0.75),
                                       q.fixed = c(0.50), sel = sel_final, method = "approx")



##### PLOT SINGLE PFAS EFFECT
##### HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
# TRUNK FAT MASS
p_singvar_wt <- ggplot(singvar_wt, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                       col = q.fixed)) + 
  theme_bw() + theme(text = element_text(size = 23)) + theme(axis.title.y = element_blank()) +
  scale_x_discrete(limits = c("EtFOSAA", "MeFOSAA", "PFHxS", "PFNA", "PFOA", "PFOS")) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "black", linewidth = 1) +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_y_continuous(name = "Trunk fat mass (kg)")
p_singvar_wt


# TOTAL BODY FAT MASS
p_singvar_waist <- ggplot(singvar_waist, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd,
                                             col = q.fixed)) + 
  theme_bw() + theme(text = element_text(size = 23)) + theme(axis.title.y = element_blank()) +
  scale_x_discrete(limits = c("EtFOSAA", "MeFOSAA", "PFHxS", "PFNA", "PFOA", "PFOS")) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "black", linewidth = 1) +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_y_continuous(name = "Total body fat mass (kg)")
p_singvar_waist





# TRUNK FAT MASS
p_singvar_wt2 <- ggplot(singvar_wt2, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
  theme_bw() + theme(text = element_text(size = 23, color = "black")) + theme(axis.title.y = element_blank()) +
  scale_x_discrete(limits = c("EtFOSAA", "MeFOSAA", "PFHxS", "PFNA", "PFOA", "PFOS")) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_y_continuous(name = "Trunk fat mass (kg)")
p_singvar_wt2


# TOTAL BODY FAT MASS
p_singvar_waist2 <- ggplot(singvar_waist2, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
  theme_bw() + theme(text = element_text(size = 23, color = "black")) + theme(axis.title.y = element_blank()) +
  scale_x_discrete(limits = c("EtFOSAA", "MeFOSAA", "PFHxS", "PFNA", "PFOA", "PFOS")) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_y_continuous(name = "Total body fat mass (kg)")
p_singvar_waist2



```

```{r}
##### UNIVARIATE INTERACTIONS AMONG PFAS
# TRUNK FAT MASS
overall_interact_wt <- SingVarIntSummaries(fit = l2m_wt, qs.diff = c(0.25, 0.75),
                                           qs.fixed = c(0.25, 0.75),sel=sel_final)

# TOTAL BODY FAT MASS
overall_interact_waist <- SingVarIntSummaries(fit = l2m_waist, qs.diff = c(0.25, 0.75),
                                              qs.fixed = c(0.25, 0.75),sel=sel_final)




##### PLOT UNIVARIATE INTERACTIONS
# TRUNK FAT MASS
p_overall_interact_wt <- ggplot(overall_interact_wt, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) +theme(text = element_text(size = 25)) +
  geom_hline(yintercept = 0, lty = 2, color = "red", linewidth = 1) + coord_flip() +
  ylab("Trunk fat mass (kg)") +
  xlab("Plasma PFAS")
p_overall_interact_wt


# TOTAL BODY FAT MASS
p_overall_interact_waist <- ggplot(overall_interact_waist, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_pointrange(position = position_dodge(width = 0.75)) + theme(text = element_text(size = 25)) +
  geom_hline(yintercept = 0, lty = 2, color = "red", linewidth = 1) + coord_flip() +
  ylab("Total body fat mass (kg)") +
  xlab("Plasma PFAS")
p_overall_interact_waist


```
