#####                                                  #####
##### RUN MIXTURES ANALYSIS WITH BKMR IN ANTHRO        #####
#####                                                  #####

```{r message=FALSE, warning=FALSE}
##### LOAD PACKAGES
library("bkmr")
library("ggplot2")
library("beepr")
library("tidyverse")

```

```{r message=FALSE, warning=FALSE}
##### LOAD DATASET
PFAS_A <-read_csv("C:/Users/jarva/Desktop/James-Todd Lab/P3.PFASandAdiposity/Data/PFAS_AF.csv")

##### LOAD WORKSPACE
load("C:/Users/jarva/Desktop/James-Todd Lab/P3.PFASandAdiposity/Data/P3_BKMR_AF_STRAT.Rdata")

```

```{r}
##### TRANSFORM VARIABLES TO NUMERIC FOR BKMR COVARIATE MATRIX

# RENAME
PFAS_A$age_enroll <- PFAS_A$age_mom_enroll_d
PFAS_A$menar <- PFAS_A$mom_firstperiod_12y
PFAS_A$bmi <- PFAS_A$bmi_mom_prepreg_d
PFAS_A$race <- PFAS_A$race2_mom_epi_epia_d
PFAS_A$income <- PFAS_A$gt70k
PFAS_A$parity <- PFAS_A$parity_d
PFAS_A$smoke <- PFAS_A$smokpreg_final_d
PFAS_A$married <- PFAS_A$married_cohab
PFAS_A$edu <- PFAS_A$coll_grad
PFAS_A$fish <- PFAS_A$fish_d_f1
PFAS_A$darkmeat <- PFAS_A$dark_meat_f1

# REFACTOR AND RELABEL 
PFAS_A$bmi_cat <- ifelse(PFAS_A$bmi <18.5, 0,
                         ifelse(PFAS_A$bmi >=18.5 & PFAS_A$bmi < 25.0, 1, 
                                ifelse(PFAS_A$bmi >=25.0 & PFAS_A$bmi < 30.0, 2, 
                                       ifelse(PFAS_A$bmi >=30.0 & PFAS_A$bmi < 35.0, 3,
                                              ifelse(PFAS_A$bmi >=35.0, 4, 99)))))
PFAS_A$race <- ifelse(PFAS_A$race == "white", 0,
                      ifelse(PFAS_A$race == "black", 1,
                             ifelse(PFAS_A$race == "hispa", 2,
                                    ifelse(PFAS_A$race == "asian", 3,
                                           ifelse(PFAS_A$race == "other", 4, 4)))))
PFAS_A$income <- ifelse(PFAS_A$income == 1, 1, 0)
PFAS_A$parity <- ifelse(PFAS_A$parity == 0, 0,
                        ifelse(PFAS_A$parity == 1, 1,
                               ifelse(PFAS_A$parity > 1, 2, 0)))
PFAS_A$smoke <- ifelse(PFAS_A$smoke == "former", 0,
                       ifelse(PFAS_A$smoke == "smoke preg", 1,
                              ifelse(PFAS_A$smoke == "xnever", 2, 2)))
PFAS_A$married <- ifelse(PFAS_A$married == 1, 1, 0)
PFAS_A$edu <- ifelse(PFAS_A$edu == 1, 1, 0)

# SET CATEGORICAL VARIABLES AS FACTORS
PFAS_A$bmi_cat <- as.factor(PFAS_A$bmi_cat)
PFAS_A$race <- as.factor(PFAS_A$race)
PFAS_A$income <- as.factor(PFAS_A$income)
PFAS_A$parity <- as.factor(PFAS_A$parity)
PFAS_A$smoke <- as.factor(PFAS_A$smoke)
PFAS_A$married <- as.factor(PFAS_A$married)
PFAS_A$edu <- as.factor(PFAS_A$edu)

# CENTER AND SCALE CONTINUOUS VARIABLES
PFAS_A$height_s <- scale(PFAS_A$height)
PFAS_A$age_s <- scale(PFAS_A$age_enroll)
PFAS_A$menar_s <- scale(PFAS_A$menar)
PFAS_A$fish_s <- scale(PFAS_A$fish)
PFAS_A$darkmeat_s <- scale(PFAS_A$darkmeat)

```

```{r}
##### STRATIFY ANTHRO DATASET BY PRE-PREGNANCY BMI
table(PFAS_A$bmi_cat)
PFAS_A_B0 <- subset(PFAS_A, bmi_cat == 0 | bmi_cat == 1)
PFAS_A_B1 <- subset(PFAS_A, bmi_cat == 2 | bmi_cat == 3 | bmi_cat == 4)


##### STRATIFY ANTHRO DATASET BY MENOPAUSAL STATUS
table(PFAS_A$meno_cat)
PFAS_A_M0 <- subset(PFAS_A, meno_cat == "Pre-menopause")
PFAS_A_M1 <- subset(PFAS_A, meno_cat == "Post-menopause")

```

```{r}
##### PREPARE VARIABLES FOR BKMR MODELS #####
##### ANTHRO DATASET (N = 549)

# CREATE MIXTURE OF PFAS
mixture_a_b0 <- as.matrix(cbind(PFAS_A_B0$PFOS, PFAS_A_B0$PFOA, PFAS_A_B0$PFNA, PFAS_A_B0$PFHxS, 
                             PFAS_A_B0$MeFOSAA, PFAS_A_B0$EtFOSAA))
mixture_a_b1 <- as.matrix(cbind(PFAS_A_B1$PFOS, PFAS_A_B1$PFOA, PFAS_A_B1$PFNA, PFAS_A_B1$PFHxS, 
                             PFAS_A_B1$MeFOSAA, PFAS_A_B1$EtFOSAA))
mixture_a_m0 <- as.matrix(cbind(PFAS_A_M0$PFOS, PFAS_A_M0$PFOA, PFAS_A_M0$PFNA, PFAS_A_M0$PFHxS, 
                             PFAS_A_M0$MeFOSAA, PFAS_A_M0$EtFOSAA))
mixture_a_m1 <- as.matrix(cbind(PFAS_A_M1$PFOS, PFAS_A_M1$PFOA, PFAS_A_M1$PFNA, PFAS_A_M1$PFHxS, 
                             PFAS_A_M1$MeFOSAA, PFAS_A_M1$EtFOSAA))

# RENAME VARIABLES IN MIXTURE
colnames(mixture_a_b0) <- c("PFOS", "PFOA", "PFNA", "PFHxS", "MeFOSAA", "EtFOSAA")
colnames(mixture_a_b1) <- c("PFOS", "PFOA", "PFNA", "PFHxS", "MeFOSAA", "EtFOSAA")
colnames(mixture_a_m0) <- c("PFOS", "PFOA", "PFNA", "PFHxS", "MeFOSAA", "EtFOSAA")
colnames(mixture_a_m1) <- c("PFOS", "PFOA", "PFNA", "PFHxS", "MeFOSAA", "EtFOSAA")

# LOG2-TRANSFORM MIXTURE
l2mixture_a_b0 <- apply(mixture_a_b0, 2, log2)
l2mixture_a_b1 <- apply(mixture_a_b1, 2, log2)
l2mixture_a_m0 <- apply(mixture_a_m0, 2, log2)
l2mixture_a_m1 <- apply(mixture_a_m1, 2, log2)

# SCALE MIXTURE VARIABLES TO THE MEAN
l2mixture_a_b0_z <- scale(l2mixture_a_b0)
l2mixture_a_b1_z <- scale(l2mixture_a_b1)
l2mixture_a_m0_z <- scale(l2mixture_a_m0)
l2mixture_a_m1_z <- scale(l2mixture_a_m1)

# SET THE OUTCOME
WT_B0 <- PFAS_A_B0$Weight
WC_B0 <- PFAS_A_B0$Waist
WT_B1 <- PFAS_A_B1$Weight
WC_B1 <- PFAS_A_B1$Waist
WT_M0 <- PFAS_A_M0$Weight
WC_M0 <- PFAS_A_M0$Waist
WT_M1 <- PFAS_A_M1$Weight
WC_M1 <- PFAS_A_M1$Waist

# CREAT THE COVARIATE MATRIX
cov_a_b0_nw <- as.matrix(cbind(PFAS_A_B0$age_s, PFAS_A_B0$race, PFAS_A_B0$smoke, 
                         PFAS_A_B0$parity, PFAS_A_B0$married, PFAS_A_B0$fish_s, PFAS_A_B0$height_s))
cov_a_b1_nw <- as.matrix(cbind(PFAS_A_B1$age_s, PFAS_A_B1$race, PFAS_A_B1$smoke, 
                         PFAS_A_B1$parity, PFAS_A_B1$married, PFAS_A_B1$fish_s, PFAS_A_B1$height_s))
cov_a_m0_nw <- as.matrix(cbind(PFAS_A_M0$age_s, PFAS_A_M0$race, PFAS_A_M0$smoke, 
                         PFAS_A_M0$parity, PFAS_A_M0$married, PFAS_A_M0$fish_s, PFAS_A_M0$height_s))
cov_a_m1_nw <- as.matrix(cbind(PFAS_A_M1$age_s, PFAS_A_M1$race, PFAS_A_M1$smoke, 
                         PFAS_A_M1$parity, PFAS_A_M1$married, PFAS_A_M1$fish_s, PFAS_A_M1$height_s))

cov_a_b0 <- as.matrix(cbind(PFAS_A_B0$age_s, PFAS_A_B0$race, PFAS_A_B0$bmi_cat, PFAS_A_B0$smoke, 
                         PFAS_A_B0$parity, PFAS_A_B0$married, PFAS_A_B0$fish_s, PFAS_A_B0$height_s))
cov_a_b1 <- as.matrix(cbind(PFAS_A_B1$age_s, PFAS_A_B1$race, PFAS_A_B1$bmi_cat, PFAS_A_B1$smoke, 
                         PFAS_A_B1$parity, PFAS_A_B1$married, PFAS_A_B1$fish_s, PFAS_A_B1$height_s))
cov_a_m0 <- as.matrix(cbind(PFAS_A_M0$age_s, PFAS_A_M0$race, PFAS_A_M0$bmi_cat, PFAS_A_M0$smoke, 
                         PFAS_A_M0$parity, PFAS_A_M0$married, PFAS_A_M0$fish_s, PFAS_A_M0$height_s))
cov_a_m1 <- as.matrix(cbind(PFAS_A_M1$age_s, PFAS_A_M1$race, PFAS_A_M1$bmi_cat, PFAS_A_M1$smoke, 
                         PFAS_A_M1$parity, PFAS_A_M1$married, PFAS_A_M1$fish_s, PFAS_A_M1$height_s))

# SET THE SEED
set.seed(1234)

# CREATE KNOTS
knots_a_b0 <- fields::cover.design(l2mixture_a_b0_z, nd = 30)$design
knots_a_b1 <- fields::cover.design(l2mixture_a_b1_z, nd = 20)$design
knots_a_m0 <- fields::cover.design(l2mixture_a_m0_z, nd = 30)$design
knots_a_m1 <- fields::cover.design(l2mixture_a_m1_z, nd = 20)$design

```

```{r}
# ##### BUILD BKMR MODELS
# # WEIGHT
# m_wt_b0 <- kmbayes(y = WT_B0, Z = l2mixture_a_b0_z, X = cov_a_b0, iter = 20000, family = "gaussian",
#                       verbose = FALSE, varsel = TRUE, knots = knots_a_b0)
# beep(sound=5, expr=NULL)
# 
# m_wt_b1 <- kmbayes(y = WT_B1, Z = l2mixture_a_b1_z, X = cov_a_b1, iter = 20000, family = "gaussian",
#                       verbose = FALSE, varsel = TRUE, knots = knots_a_b1)
# beep(sound=5, expr=NULL)
# 
# m_wt_m0 <- kmbayes(y = WT_M0, Z = l2mixture_a_m0_z, X = cov_a_m0, iter = 20000, family = "gaussian",
#                       verbose = FALSE, varsel = TRUE, knots = knots_a_m0)
# beep(sound=5, expr=NULL)
# 
# m_wt_m1 <- kmbayes(y = WT_M1, Z = l2mixture_a_m1_z, X = cov_a_m1, iter = 20000, family = "gaussian",
#                       verbose = FALSE, varsel = TRUE, knots = knots_a_m1)
# beep(sound=5, expr=NULL)
# 
# # WAIST CIRCUMFERENCE
# m_wc_b0 <- kmbayes(y = WC_B0, Z = l2mixture_a_b0_z, X = cov_a_b0, iter = 20000, family = "gaussian",
#                       verbose = FALSE, varsel = TRUE, knots = knots_a_b0)
# beep(sound=5, expr=NULL)
# 
# m_wc_b1 <- kmbayes(y = WC_B1, Z = l2mixture_a_b1_z, X = cov_a_b1, iter = 20000, family = "gaussian",
#                       verbose = FALSE, varsel = TRUE, knots = knots_a_b1)
# beep(sound=5, expr=NULL)
# 
# m_wc_m0 <- kmbayes(y = WC_M0, Z = l2mixture_a_m0_z, X = cov_a_m0, iter = 20000, family = "gaussian",
#                       verbose = FALSE, varsel = TRUE, knots = knots_a_m0)
# beep(sound=5, expr=NULL)
# 
# m_wc_m1 <- kmbayes(y = WC_M1, Z = l2mixture_a_m1_z, X = cov_a_m1, iter = 20000, family = "gaussian",
#                       verbose = FALSE, varsel = TRUE, knots = knots_a_m1)
# beep(sound=5, expr=NULL)

```

```{r}
# ##### SAVE WORKSPACE FOR SBP BKMR FUNCTIONS
# save(m_wt_b0, m_wt_b1, m_wt_m0, m_wt_m1, m_wc_b0, m_wc_b1, m_wc_m0, m_wc_m1,
#     file="C:/Users/jarva/Desktop/James-Todd Lab/P3.PFASandAdiposity/Data/P3_BKMR_AF_STRAT.Rdata")

```

```{r}
##### VALUES TO KEEP AFTER BURIN/THIN
sel <- seq(0,20000,by = 50)

##### ACCESS CONVERGENCE WITH TRACEPLOTS
# TracePlot(fit = l2m_wt, par = "beta", sel = sel)
# TracePlot(fit = l2m_waist, par = "beta", sel = sel)

##### VALUES TO KEEP AFTER BURNING/THIN (ACCORDING TO THE TRACEPLOT FUNCTION ABOVE)
sel_final <- seq(1200, 20000, by = 1)

```

```{r}
##### ESIMATE POSTERIOR INCLUSION PROBABILITIES
# WAIST CIRCUMFERENCE
#summary(l2m_wt)
ExtractPIPs(m_wt_b0, sel = sel_final)
ExtractPIPs(m_wt_b1, sel = sel_final)
ExtractPIPs(m_wt_m0, sel = sel_final)
ExtractPIPs(m_wt_m1, sel = sel_final)

# WAIST CIRCUMFERENCE
#summary(l2m_wt)
ExtractPIPs(m_wc_b0, sel = sel_final)
ExtractPIPs(m_wc_b1, sel = sel_final)
ExtractPIPs(m_wc_m0, sel = sel_final)
ExtractPIPs(m_wc_m1, sel = sel_final)

```

```{r}
##### PREDICT UNIVARIATE EXPOSURE-RESPONSE FUNCTION
# WEIGHT
univar_wt_b0 <- PredictorResponseUnivar(fit = m_wt_b0, sel = sel_final, method = "approx")
univar_wt_b1 <- PredictorResponseUnivar(fit = m_wt_b1, sel = sel_final, method = "approx")
univar_wt_m0 <- PredictorResponseUnivar(fit = m_wt_m0, sel = sel_final, method = "approx")
univar_wt_m1 <- PredictorResponseUnivar(fit = m_wt_m1, sel = sel_final, method = "approx")

# WAIST CIRCUMFERENCE
univar_wc_b0 <- PredictorResponseUnivar(fit = m_wc_b0, sel = sel_final, method = "approx")
univar_wc_b1 <- PredictorResponseUnivar(fit = m_wc_b1, sel = sel_final, method = "approx")
univar_wc_m0 <- PredictorResponseUnivar(fit = m_wc_m0, sel = sel_final, method = "approx")
univar_wc_m1 <- PredictorResponseUnivar(fit = m_wc_m1, sel = sel_final, method = "approx")



##### PLOT UNIVARIATE EXPOSURE-RESPONSE FUNCTION
# BMI
uni_wt_b0 <- ggplot(univar_wt_b0, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity", colour='black') + xlab("Plasma PFAS, log2(ng/mL)") + ylab("Weight (kg)") +
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 25))  

uni1_wt_b0 <- ggplot(univar_wt_b0[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOS, log2(ng/mL)") + ylab("Weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni2_wt_b0 <- ggplot(univar_wt_b0[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOA, log2(ng/mL)") + ylab("Weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni3_wt_b0 <- ggplot(univar_wt_b0[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFNA, log2(ng/mL)") + ylab("Weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni4_wt_b0 <- ggplot(univar_wt_b0[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFHxS, log2(ng/mL)") + ylab("Weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni5_wt_b0 <- ggplot(univar_wt_b0[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma MeFOSAA, log2(ng/mL)") + ylab("Weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni6_wt_b0 <- ggplot(univar_wt_b0[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma EtFOSAA, log2(ng/mL)") + ylab("Weight (kg)") +
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni_wt_b0
uni1_wt_b0
uni2_wt_b0
uni3_wt_b0
uni4_wt_b0
uni5_wt_b0
uni6_wt_b0


uni_wt_b1 <- ggplot(univar_wt_b1, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity", colour='black') + xlab("Plasma PFAS, log2(ng/mL)") + ylab("Weight (kg)") +
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 25))  

uni1_wt_b1 <- ggplot(univar_wt_b1[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOS, log2(ng/mL)") + ylab("Weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni2_wt_b1 <- ggplot(univar_wt_b1[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOA, log2(ng/mL)") + ylab("Weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni3_wt_b1 <- ggplot(univar_wt_b1[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFNA, log2(ng/mL)") + ylab("Weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni4_wt_b1 <- ggplot(univar_wt_b1[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFHxS, log2(ng/mL)") + ylab("Weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni5_wt_b1 <- ggplot(univar_wt_b1[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma MeFOSAA, log2(ng/mL)") + ylab("Weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni6_wt_b1 <- ggplot(univar_wt_b1[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma EtFOSAA, log2(ng/mL)") + ylab("Weight (kg)") +
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni_wt_b1
uni1_wt_b1
uni2_wt_b1
uni3_wt_b1
uni4_wt_b1
uni5_wt_b1
uni6_wt_b1



uni_wt_m0 <- ggplot(univar_wt_m0, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity", colour='black') + xlab("Plasma PFAS, log2(ng/mL)") + ylab("Weight (kg)") +
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 25))  

uni1_wt_m0 <- ggplot(univar_wt_m0[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOS, log2(ng/mL)") + ylab("Weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni2_wt_m0 <- ggplot(univar_wt_m0[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOA, log2(ng/mL)") + ylab("Weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni3_wt_m0 <- ggplot(univar_wt_m0[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFNA, log2(ng/mL)") + ylab("Weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni4_wt_m0 <- ggplot(univar_wt_m0[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFHxS, log2(ng/mL)") + ylab("Weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni5_wt_m0 <- ggplot(univar_wt_m0[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma MeFOSAA, log2(ng/mL)") + ylab("Weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni6_wt_m0 <- ggplot(univar_wt_m0[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma EtFOSAA, log2(ng/mL)") + ylab("Weight (kg)") +
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni_wt_m0
uni1_wt_m0
uni2_wt_m0
uni3_wt_m0
uni4_wt_m0
uni5_wt_m0
uni6_wt_m0



uni_wt_m1 <- ggplot(univar_wt_m1, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity", colour='black') + xlab("Plasma PFAS, log2(ng/mL)") + ylab("Weight (kg)") +
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 25))  

uni1_wt_m1 <- ggplot(univar_wt_m1[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOS, log2(ng/mL)") + ylab("Weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni2_wt_m1 <- ggplot(univar_wt_m1[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOA, log2(ng/mL)") + ylab("Weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni3_wt_m1 <- ggplot(univar_wt_m1[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFNA, log2(ng/mL)") + ylab("Weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni4_wt_m1 <- ggplot(univar_wt_m1[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFHxS, log2(ng/mL)") + ylab("Weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni5_wt_m1 <- ggplot(univar_wt_m1[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma MeFOSAA, log2(ng/mL)") + ylab("Weight (kg)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni6_wt_m1 <- ggplot(univar_wt_m1[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma EtFOSAA, log2(ng/mL)") + ylab("Weight (kg)") +
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni_wt_m1
uni1_wt_m1
uni2_wt_m1
uni3_wt_m1
uni4_wt_m1
uni5_wt_m1
uni6_wt_m1



# WAIST CIRCUMFERENCE
uni_wc_b0 <- ggplot(univar_wc_b0, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity", colour='black') + xlab("Plasma PFAS, log2(ng/mL)") + ylab("Waist circumference (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 25))  

uni1_wc_b0 <- ggplot(univar_wc_b0[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOS, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni2_wc_b0 <- ggplot(univar_wc_b0[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOA, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni3_wc_b0 <- ggplot(univar_wc_b0[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFNA, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni4_wc_b0 <- ggplot(univar_wc_b0[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFHxS, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni5_wc_b0 <- ggplot(univar_wc_b0[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma MeFOSAA, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni6_wc_b0 <- ggplot(univar_wc_b0[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma EtFOSAA, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni_wc_b0
uni1_wc_b0
uni2_wc_b0
uni3_wc_b0
uni4_wc_b0
uni5_wc_b0
uni6_wc_b0


uni_wc_b1 <- ggplot(univar_wc_b1, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity", colour='black') + xlab("Plasma PFAS, log2(ng/mL)") + ylab("Waist circumference (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 25))  

uni1_wc_b1 <- ggplot(univar_wc_b1[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOS, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni2_wc_b1 <- ggplot(univar_wc_b1[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOA, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni3_wc_b1 <- ggplot(univar_wc_b1[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFNA, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni4_wc_b1 <- ggplot(univar_wc_b1[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFHxS, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni5_wc_b1 <- ggplot(univar_wc_b1[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma MeFOSAA, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni6_wc_b1 <- ggplot(univar_wc_b1[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma EtFOSAA, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni_wc_b1
uni1_wc_b1
uni2_wc_b1
uni3_wc_b1
uni4_wc_b1
uni5_wc_b1
uni6_wc_b1



uni_wc_m0 <- ggplot(univar_wc_m0, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity", colour='black') + xlab("Plasma PFAS, log2(ng/mL)") + ylab("Waist circumference (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 25))  

uni1_wc_m0 <- ggplot(univar_wc_m0[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOS, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni2_wc_m0 <- ggplot(univar_wc_m0[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOA, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni3_wc_m0 <- ggplot(univar_wc_m0[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFNA, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni4_wc_m0 <- ggplot(univar_wc_m0[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFHxS, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni5_wc_m0 <- ggplot(univar_wc_m0[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma MeFOSAA, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni6_wc_m0 <- ggplot(univar_wc_m0[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma EtFOSAA, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni_wc_m0
uni1_wc_m0
uni2_wc_m0
uni3_wc_m0
uni4_wc_m0
uni5_wc_m0
uni6_wc_m0



uni_wc_m1 <- ggplot(univar_wc_m1, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + facet_wrap(~ variable) + 
  geom_smooth(stat = "identity", colour='black') + xlab("Plasma PFAS, log2(ng/mL)") + ylab("Waist circumference (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1) + theme(text = element_text(size = 25))  

uni1_wc_m1 <- ggplot(univar_wc_m1[1:50,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOS, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni2_wc_m1 <- ggplot(univar_wc_m1[51:100,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFOA, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni3_wc_m1 <- ggplot(univar_wc_m1[101:150,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFNA, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni4_wc_m1 <- ggplot(univar_wc_m1[151:200,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma PFHxS, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni5_wc_m1 <- ggplot(univar_wc_m1[201:250,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma MeFOSAA, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni6_wc_m1 <- ggplot(univar_wc_m1[251:300,], aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity", colour='black') + theme_classic() +
  xlab("Plasma EtFOSAA, log2(ng/mL)") + ylab("Waist circ. (cm)")+
  geom_hline(yintercept = 0, colour = 'red', linetype = 'dashed', linewidth = 1.5) + theme(text = element_text(size = 28))  

uni_wc_m1
uni1_wc_m1
uni2_wc_m1
uni3_wc_m1
uni4_wc_m1
uni5_wc_m1
uni6_wc_m1

```

```{r}
##### DETERMINE RISK ASSOCIATED WITH THE OVERALL MIXTURE
# WEIGHT
overall_wt_b0 <- OverallRiskSummaries(fit = m_wt_b0, q.fixed = 0.50, sel = sel_final,
                                   method = "approx", qs = seq(0.25, 0.75, by = 0.05))
overall_wt_b1 <- OverallRiskSummaries(fit = m_wt_b1, q.fixed = 0.50, sel = sel_final,
                                   method = "approx", qs = seq(0.25, 0.75, by = 0.05))
overall_wt_m0 <- OverallRiskSummaries(fit = m_wt_m0, q.fixed = 0.50, sel = sel_final,
                                   method = "approx", qs = seq(0.25, 0.75, by = 0.05))
overall_wt_m1 <- OverallRiskSummaries(fit = m_wt_m1, q.fixed = 0.50, sel = sel_final,
                                   method = "approx", qs = seq(0.25, 0.75, by = 0.05))

# WAIST CIRCUMFERENCE
overall_wc_b0 <- OverallRiskSummaries(fit = m_wc_b0, q.fixed = 0.50, sel = sel_final,
                                      method = "approx", qs = seq(0.25, 0.75, by = 0.05))
overall_wc_b1 <- OverallRiskSummaries(fit = m_wc_b1, q.fixed = 0.50, sel = sel_final,
                                      method = "approx", qs = seq(0.25, 0.75, by = 0.05))
overall_wc_m0 <- OverallRiskSummaries(fit = m_wc_m0, q.fixed = 0.50, sel = sel_final,
                                      method = "approx", qs = seq(0.25, 0.75, by = 0.05))
overall_wc_m1 <- OverallRiskSummaries(fit = m_wc_m1, q.fixed = 0.50, sel = sel_final,
                                      method = "approx", qs = seq(0.25, 0.75, by = 0.05))



##### PLOT RISK ASSOCIATED WITH THE OVERALL MIXTURE
# WEIGHT
p_overall_wt_b0 <- ggplot(overall_wt_b0, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange() +
  scale_y_continuous(name = "Weight (kg)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 25),
    axis.text.y = element_text(size = 24),
    axis.title.x = element_text(angle = 0, color = 'black', size = 25),
    axis.title.y = element_text(angle = 90, color = 'black', size = 24))
p_overall_wt_b0

p_overall_wt_b1 <- ggplot(overall_wt_b1, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange() +
  scale_y_continuous(name = "Weight (kg)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 25),
    axis.text.y = element_text(size = 24),
    axis.title.x = element_text(angle = 0, color = 'black', size = 25),
    axis.title.y = element_text(angle = 90, color = 'black', size = 24))
p_overall_wt_b1

p_overall_wt_m0 <- ggplot(overall_wt_m0, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange() +
  scale_y_continuous(name = "Weight (kg)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 25),
    axis.text.y = element_text(size = 24),
    axis.title.x = element_text(angle = 0, color = 'black', size = 25),
    axis.title.y = element_text(angle = 90, color = 'black', size = 24))
p_overall_wt_m0

p_overall_wt_m1 <- ggplot(overall_wt_m1, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange() +
  scale_y_continuous(name = "Weight (kg)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 25),
    axis.text.y = element_text(size = 24),
    axis.title.x = element_text(angle = 0, color = 'black', size = 25),
    axis.title.y = element_text(angle = 90, color = 'black', size = 24))
p_overall_wt_m1


# WAIST CIRCUMFERENCE
p_overall_wc_b0 <- ggplot(overall_wc_b0, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange() +
  scale_y_continuous(name = "Waist circ (cm)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 25),
    axis.text.y = element_text(size = 24),
    axis.title.x = element_text(angle = 0, color = 'black', size = 25),
    axis.title.y = element_text(angle = 90, color = 'black', size = 24))
p_overall_wc_b0

p_overall_wc_b1 <- ggplot(overall_wc_b1, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange() +
  scale_y_continuous(name = "Waist circ (cm)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 25),
    axis.text.y = element_text(size = 24),
    axis.title.x = element_text(angle = 0, color = 'black', size = 25),
    axis.title.y = element_text(angle = 90, color = 'black', size = 24))
p_overall_wc_b1

p_overall_wc_m0 <- ggplot(overall_wc_m0, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange() +
  scale_y_continuous(name = "Waist circ (cm)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 25),
    axis.text.y = element_text(size = 24),
    axis.title.x = element_text(angle = 0, color = 'black', size = 25),
    axis.title.y = element_text(angle = 90, color = 'black', size = 24))
p_overall_wc_m0

p_overall_wc_m1 <- ggplot(overall_wc_m1, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
  geom_hline(yintercept = 00, linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange() +
  scale_y_continuous(name = "Waist circ (cm)")+
  xlab("PFAS quantile") +
  theme_classic()+ theme(
    axis.text.x = element_text(size = 25),
    axis.text.y = element_text(size = 24),
    axis.title.x = element_text(angle = 0, color = 'black', size = 25),
    axis.title.y = element_text(angle = 90, color = 'black', size = 24))
p_overall_wc_m1

```

```{r}
##### ESTIMATE SINGLE PFAS EFFECT
# WEIGHT
singvar_wt_b0 <- SingVarRiskSummaries(fit = m_wt_b0, qs.diff = c(0.25, 0.75),
                                   q.fixed = c(0.50), sel = sel_final, method = "approx")
singvar_wt_b1 <- SingVarRiskSummaries(fit = m_wt_b1, qs.diff = c(0.25, 0.75),
                                   q.fixed = c(0.50), sel = sel_final, method = "approx")
singvar_wt_m0 <- SingVarRiskSummaries(fit = m_wt_m0, qs.diff = c(0.25, 0.75),
                                   q.fixed = c(0.50), sel = sel_final, method = "approx")
singvar_wt_m1 <- SingVarRiskSummaries(fit = m_wt_m1, qs.diff = c(0.25, 0.75),
                                   q.fixed = c(0.50), sel = sel_final, method = "approx")

# WAIST CIRCUMFERENCE
singvar_wc_b0 <- SingVarRiskSummaries(fit = m_wc_b0, qs.diff = c(0.25, 0.75),
                                      q.fixed = c(0.50), sel = sel_final, method = "approx")
singvar_wc_b1 <- SingVarRiskSummaries(fit = m_wc_b1, qs.diff = c(0.25, 0.75),
                                      q.fixed = c(0.50), sel = sel_final, method = "approx")
singvar_wc_m0 <- SingVarRiskSummaries(fit = m_wc_m0, qs.diff = c(0.25, 0.75),
                                      q.fixed = c(0.50), sel = sel_final, method = "approx")
singvar_wc_m1 <- SingVarRiskSummaries(fit = m_wc_m1, qs.diff = c(0.25, 0.75),
                                      q.fixed = c(0.50), sel = sel_final, method = "approx")



##### PLOT SINGLE PFAS EFFECT
##### HOLDING ALL OTHER PFAS AT THE 25TH, 50TH, 75TH PERCENTILES
# WEIGHT
p_singvar_wt_b0 <- ggplot(singvar_wt_b0, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
  theme_bw() + theme(text = element_text(size = 23, color = "black")) + theme(axis.title.y = element_blank()) +
  scale_x_discrete(limits = c("EtFOSAA", "MeFOSAA", "PFHxS", "PFNA", "PFOA", "PFOS")) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_y_continuous(name = "Weight (kg)")
p_singvar_wt_b0

p_singvar_wt_b1 <- ggplot(singvar_wt_b1, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
  theme_bw() + theme(text = element_text(size = 23, color = "black")) + theme(axis.title.y = element_blank()) +
  scale_x_discrete(limits = c("EtFOSAA", "MeFOSAA", "PFHxS", "PFNA", "PFOA", "PFOS")) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_y_continuous(name = "Weight (kg)")
p_singvar_wt_b1

p_singvar_wt_m0 <- ggplot(singvar_wt_m0, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
  theme_bw() + theme(text = element_text(size = 23, color = "black")) + theme(axis.title.y = element_blank()) +
  scale_x_discrete(limits = c("EtFOSAA", "MeFOSAA", "PFHxS", "PFNA", "PFOA", "PFOS")) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_y_continuous(name = "Weight (kg)")
p_singvar_wt_m0

p_singvar_wt_m1 <- ggplot(singvar_wt_m1, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
  theme_bw() + theme(text = element_text(size = 23, color = "black")) + theme(axis.title.y = element_blank()) +
  scale_x_discrete(limits = c("EtFOSAA", "MeFOSAA", "PFHxS", "PFNA", "PFOA", "PFOS")) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_y_continuous(name = "Weight (kg)")
p_singvar_wt_m1


# WAIST CIRCUMFERENCE
p_singvar_wc_b0 <- ggplot(singvar_wc_b0, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
  theme_bw() + theme(text = element_text(size = 23, color = "black")) + theme(axis.title.y = element_blank()) +
  scale_x_discrete(limits = c("EtFOSAA", "MeFOSAA", "PFHxS", "PFNA", "PFOA", "PFOS")) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_y_continuous(name = "Waist circ. (cm)")
p_singvar_wc_b0

p_singvar_wc_b1 <- ggplot(singvar_wc_b1, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
  theme_bw() + theme(text = element_text(size = 23, color = "black")) + theme(axis.title.y = element_blank()) +
  scale_x_discrete(limits = c("EtFOSAA", "MeFOSAA", "PFHxS", "PFNA", "PFOA", "PFOS")) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_y_continuous(name = "Waist circ. (cm)")
p_singvar_wc_b1

p_singvar_wc_m0 <- ggplot(singvar_wc_m0, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
  theme_bw() + theme(text = element_text(size = 23, color = "black")) + theme(axis.title.y = element_blank()) +
  scale_x_discrete(limits = c("EtFOSAA", "MeFOSAA", "PFHxS", "PFNA", "PFOA", "PFOS")) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_y_continuous(name = "Waist circ. (cm)")
p_singvar_wc_m0

p_singvar_wc_m1 <- ggplot(singvar_wc_m1, aes(variable, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
  theme_bw() + theme(text = element_text(size = 23, color = "black")) + theme(axis.title.y = element_blank()) +
  scale_x_discrete(limits = c("EtFOSAA", "MeFOSAA", "PFHxS", "PFNA", "PFOA", "PFOS")) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "red", linewidth = 1) +
  geom_pointrange(position = position_dodge(width = 0.75)) + coord_flip() +
  scale_y_continuous(name = "Waist circ. (cm)")
p_singvar_wc_m1

```
